### ISSUE TITLE
Get aliased index (ALIASGET)

### ISSUE THREAD

**Issue by mahemoff** [RediSearch/RediSearch#1012]
Is there a way to see the underlying index an alias maps to? Like a `FT.ALIASGET` functionality?

It's needed to purge a stale index after "cutting over" the alias to point to a fresh index.

**Comment by MeirShpilraien** [comment]
You can use 'ft.info <alias>' and you will get the index name there ..

**Comment by mahemoff** [comment]
Thanks!
