### ISSUE TITLE
FT.AGGREGATE performance problem

### ISSUE THREAD

**Issue by paulflo150** [RediSearch/RediSearch#1016]
I am having an issue in Redis Enterprise Cloud (redis 5.0.4/ redisearch 1.4.6) where FT.AGGREGATE takes much longer than FT.SEARCH (about 165k records take 1 second to return, 500k take 3 seconds)

`"FT.AGGREGATE" "trips_hash_index" "(@VisibleToCompanyIDs:{2}) (@TripMainTypeID:{6|4|1|3|2}) (@TripStatusID:{1|5|4|6|3})" "SORTBY" "8" "@CreatedDateTimeUTC" "DESC" "@TripStartDate" "ASC" "@TripEndDate" "ASC" "@TripID" "DESC" "LIMIT" "0" "10" MAX 10`

`"FT.SEARCH" "trips_hash_index" "(@VisibleToCompanyIDs:{2}) (@TripMainTypeID:{6|4|1|3|2}) (@TripStatusID:{1|5|4|6|3})" "SORTBY" "TripID" "DESC" "LIMIT" "0" "10"`

Thanks you

**Comment by filipecosta90** [comment]
hi there @paulflo150, following what we've discussed on the group we'll try to understand why the `MAX` argument has no effect on performance, considering that the only difference between the `FT.SEARCH` and `FT.AGGREGATE` is the group by clause. We'll investigate further and update you back ( and assess if updating for a newer RS version will solve the issue as well ). 

## ft.info output

```
ft.info trips_hash_index
 1) index_name
 2) "trips_hash_index"
 3) fields
 4)  1) 1) PrimaryKey
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
        6) SORTABLE
     2) 1) TripID
        2) type
        3) NUMERIC
        4) SORTABLE
     3) 1) UserID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
     4) 1) TripDescription
        2) type
        3) TEXT
        4) WEIGHT
        5) "1"
     5) 1) TripStartDate
        2) type
        3) NUMERIC
        4) SORTABLE
     6) 1) TripEndDate
        2) type
        3) NUMERIC
        4) SORTABLE
     7) 1) TripTypeID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
     8) 1) TripMainTypeID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
     9) 1) TripStatusID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    10) 1) CreatedDateTimeUTC
        2) type
        3) NUMERIC
        4) SORTABLE
    11) 1) VisibleToCompanyIDs
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    12) 1) ParentTripID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    13) 1) Supplier
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    14) 1) TripCarrierTypeID
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
    15) 1) ClientIDs
        2) type
        3) TAG
        4) SEPARATOR
        5) ,
 5) index_options
 6) 1) "NOOFFSETS"
 7) gc_stats
 8) 1) current_hz
    2) "3.0289804935455322"
    3) bytes_collected
    4) (integer) 68723
    5) effectiv_cycles_rate
    6) "0.036071268224674498"
 9) cursor_stats
10) 1) global_idle
    2) (integer) 0
    3) global_total
    4) (integer) 0
    5) index_capacity
    6) (integer) 128
    7) index_total
    8) (integer) 0
11) num_docs
12) (integer) 599715
13) max_doc_id
14) (integer) 600432
15) num_terms
16) (integer) 878752
17) num_records
18) (integer) 4937876
19) inverted_sz_mb
20) "4.6262814823090749e+18"
21) offset_vectors_sz_mb
22) "0"
23) doc_table_size_mb
24) "4.6329217579703337e+18"
25) key_table_size_mb
26) "4.6255695592675082e+18"
27) records_per_doc_avg
28) "8.2337043428962087"
29) bytes_per_record_avg
30) "4.2159641108849231"
31) offsets_per_term_avg
32) "0"
33) offset_bits_per_record_avg
34) "nan"
```

**Comment by paulflo150** [comment]
Hi @filipecosta90 
have you been able to reproduce this at all?

Thanks!

**Comment by filipecosta90** [comment]
> Hi @filipecosta90
> have you been able to reproduce this at all?
> 
> Thanks!

hi there @paulflo150 , can you provide an rdb so that I can reproduce with more ease?
kind regards,

**Comment by paulflo150** [comment]
@filipecosta90: will it take another month for you to respond if I do? I thought the whole point of the enterprise subscription was to receive help when needed?

**Comment by gkorland** [comment]
@paulflo150 for enterprise support please use the support official platform https://support.redislabs.com/

**Comment by filipecosta90** [comment]
Closing this issue given there was no follow-up on the issue since:

> hi there @paulflo150 , can you provide an rdb so that I can reproduce with more ease?
