### ISSUE TITLE
Max fields for aggregate

### ISSUE THREAD

**Issue by djbokkeman** [RediSearch/RediSearch#1041]
Currently we are binded with a max of 128 text fields for index. We would love more for filtering (aggregation). Right now we try to solve it with running multiple indexes but this is not ideal.

Is it possible to increase the fields for just aggregation?

Ps. Great work so far!

**Comment by mnunberg** [comment]
You can create more fields that are SORTABLE NOINDEX. You are limited to 128 max indexed text fields, though

**Comment by djbokkeman** [comment]
Hi @mnunberg, Thanks for the info. I think we will stick to multiple indexes. We need 1000+ possible filters and are expanding fast.
