### ISSUE TITLE
Can't build 1.6.5 (Makefile:3: deps/readies/mk/main: No such file or directory)

### ISSUE THREAD

**Issue by mahemoff** [RediSearch/RediSearch#1044]
I'm trying to build v1.6.5. It looks like the build process has changed recently, and it's not entirely clear if I'm doing this right, but I simply ran `make build` based on the docs, and got this error.

```
$ make build
Makefile:3: deps/readies/mk/main: No such file or directory
Makefile:75: /defs: No such file or directory
Makefile:76: /rules: No such file or directory
make: *** No rule to make target '/rules'.  Stop.
```

**Comment by mnunberg** [comment]
This is due to submodule dependencies added in the latest version. Do `git submodule init && git submodule update`

**Comment by mahemoff** [comment]
That worked, thanks. I was using the releases like before, but I see the docs mention `git clone --recursive`, so it shouldn't cause issues for others.
