### ISSUE TITLE
SORTBY on TEXT fields that have floatStrings

### ISSUE THREAD

**Issue by srmarjani** [RediSearch/RediSearch#1064]
Hi
Consider below index.

`FT.CREATE  test SCHEMA floatString TEXT SORTABLE float NUMERIC SORTABLE`

then I add 3 docs :

`FT.ADD test doc1 1.0 FIELDS floatString 1.25 float 1.25`
`FT.ADD test doc2 1.0 FIELDS floatString 11.25 float 11.25`
`FT.ADD test doc3 1.0 FIELDS floatString 8.25 float 8.25`

If I query index by sortBy on NUMERIC fields the result is as expected 

`ft.search test * SORTBY float`
`[
  3,
  "doc1",
  [
    "float",
    "1.25",
    "floatString",
    "1.25"
  ],
  "doc3",
  [
    "float",
    "8.25",
    "floatString",
    "8.25"
  ],
  "doc2",
  [
    "float",
    "11.25",
    "floatString",
    "11.25"
  ]
]`

but when I query on TEXT field answer is wrong

`ft.search test * SORTBY floatString`

`[
  3,
  "doc1",
  [
    "floatString",
    "1.25",
    "float",
    "1.25"
  ],
  "doc2",
  [
    "floatString",
    "11.25",
    "float",
    "11.25"
  ],
  "doc3",
  [
    "floatString",
    "8.25",
    "float",
    "8.25"
  ]
]`

As I know string "8.25" is smaller than "11.25".
In my project I need to deal with large float string.

I can convert string to number and vice versa but I prefer to not to do it

thanks

**Comment by mnunberg** [comment]
I think this can be done with aggregations and the `to_number` function, it would look something like..

```
FT.SEARCH test * APPLY to_number(@float) AS numFloat SORTBY 1 @numFloat
```

I'm not sure if this syntax is correct, but something to this effect.

**Comment by srmarjani** [comment]
@mnunberg thanks for your reply.
