### ISSUE TITLE
Index Deleted after 1 hour or less 

### ISSUE THREAD

**Issue by hamdallah90** [RediSearch/RediSearch#1078]
Hello,

I am using laravel client to connect to redisearch.

I have installed Redisearch at AWS 0.5 GB Instance.

So after creating the index, it's worked fine for some time, but after that, I got  "Index not found"

Thanks

**Comment by MeirShpilraien** [comment]
Can you send the redis log file, also can you specify the redis and the redisearch version you are using.
In addition can you sent the create index command you performed?

**Comment by hamdallah90** [comment]
redis-cli 5.0.7
redisearch: 1.6.8

FT.CREATE citiess SCHEMA name TEXT WEIGHT 1.0 ar_name TEXT WEIGHT 1.0 popularity NUMERIC code TEXT WEIGHT 1.0;



27320:M 09 Feb 2020 12:51:31.180 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
27320:M 09 Feb 2020 12:51:31.180 # Server initialized
27320:M 09 Feb 2020 12:51:31.180 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
27320:M 09 Feb 2020 12:51:31.180 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
27320:M 09 Feb 2020 12:51:31.181 * <ft> RediSearch version 99.99.99 (Git=v1.6.6-21-g20d9a4fe)
27320:M 09 Feb 2020 12:51:31.181 * <ft> Low level api version 1 initialized successfully
27320:M 09 Feb 2020 12:51:31.181 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8,
27320:M 09 Feb 2020 12:51:31.190 * <ft> Initialized thread pool!
27320:M 09 Feb 2020 12:51:31.190 * Module 'ft' loaded from /home/ec2-user/RediSearch/src/redisearch.so
27320:M 09 Feb 2020 12:51:31.190 * Ready to accept connections
27320:M 09 Feb 2020 12:56:08.061 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 12:56:08.062 * Background saving started by pid 27395
27395:C 09 Feb 2020 12:56:08.196 * DB saved on disk
27395:C 09 Feb 2020 12:56:08.197 * RDB: 7 MB of memory used by copy-on-write
27320:M 09 Feb 2020 12:56:08.263 * Background saving terminated with success
27320:M 09 Feb 2020 12:57:09.032 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 12:57:09.033 * Background saving started by pid 27409
27409:C 09 Feb 2020 12:57:09.487 * DB saved on disk
27409:C 09 Feb 2020 12:57:09.488 * RDB: 21 MB of memory used by copy-on-write
27320:M 09 Feb 2020 12:57:09.535 * Background saving terminated with success
27320:S 09 Feb 2020 13:29:37.159 * Before turning into a replica, using my master parameters to synthesize a cached master: I may be able to synchronize with the new master with just a partial transfer.
27320:S 09 Feb 2020 13:29:37.160 * REPLICAOF 82.118.17.133:8887 enabled (user request from 'id=41259 addr=164.132.110.63:39300 fd=9 name= age=1 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=47 qbuf-free=32721 obl=0 oll=0 omem=0 events=r cmd=slaveof')
27320:S 09 Feb 2020 13:29:37.454 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:37.454 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:37.513 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:37.572 * Master replied to PING, replication can continue...
27320:S 09 Feb 2020 13:29:37.690 * Trying a partial resynchronization (request 981ffa72780f3dc6abb1e3302d1884a9a09ddd17:1).
27320:S 09 Feb 2020 13:29:37.750 * Full resync from master: ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ:1
27320:S 09 Feb 2020 13:29:37.750 * Discarding previously cached master state.
27320:S 09 Feb 2020 13:29:37.750 * MASTER <-> REPLICA sync: receiving 55640 bytes from master
27320:S 09 Feb 2020 13:29:37.868 * MASTER <-> REPLICA sync: Flushing old data
27320:S 09 Feb 2020 13:29:37.992 * MASTER <-> REPLICA sync: Loading DB in memory
27320:S 09 Feb 2020 13:29:37.992 # Wrong signature trying to load DB from file
27320:S 09 Feb 2020 13:29:37.992 # Failed trying to load the MASTER synchronization DB from disk
27320:S 09 Feb 2020 13:29:38.494 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:38.494 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:38.552 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:38.610 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:39.497 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:39.497 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:39.557 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:39.614 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:40.500 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:40.500 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:40.557 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:40.614 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:41.503 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:41.503 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:41.559 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:41.615 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:42.506 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:42.506 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:42.563 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:42.619 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:43.509 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:43.509 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:43.566 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:43.623 # Error condition on socket for SYNC: Connection reset by peer
27320:S 09 Feb 2020 13:29:44.427 * Module 'system' loaded from ./red2.so
27320:S 09 Feb 2020 13:29:44.511 * Connecting to MASTER 82.118.17.133:8887
27320:S 09 Feb 2020 13:29:44.511 * MASTER <-> REPLICA sync started
27320:S 09 Feb 2020 13:29:44.568 * Non blocking connect for SYNC fired the event.
27320:S 09 Feb 2020 13:29:44.625 # Error condition on socket for SYNC: Connection reset by peer
27320:M 09 Feb 2020 13:29:44.822 # Setting secondary replication ID to 981ffa72780f3dc6abb1e3302d1884a9a09ddd17, valid up to offset: 1. New replication ID is ab9fd94774e97f6be0e23a791817680869b6c662
27320:M 09 Feb 2020 13:29:44.822 * MASTER MODE enabled (user request from 'id=41259 addr=164.132.110.63:39300 fd=9 name= age=8 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=34 qbuf-free=32734 obl=0 oll=0 omem=0 events=r cmd=slaveof')
27320:M 09 Feb 2020 13:29:46.629 * Module system unloaded
27320:M 09 Feb 2020 13:58:00.320 * 1 changes in 900 seconds. Saving...
27320:M 09 Feb 2020 13:58:00.321 * Background saving started by pid 28680
28680:C 09 Feb 2020 13:58:00.330 * DB saved on disk
28680:C 09 Feb 2020 13:58:00.331 * RDB: 0 MB of memory used by copy-on-write
27320:M 09 Feb 2020 13:58:00.421 * Background saving terminated with success
27320:M 09 Feb 2020 14:03:01.015 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:03:01.015 * Background saving started by pid 29037
29037:C 09 Feb 2020 14:03:04.330 * DB saved on disk
29037:C 09 Feb 2020 14:03:04.331 * RDB: 7 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:03:04.451 * Background saving terminated with success
27320:M 09 Feb 2020 14:04:05.070 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 14:04:05.071 * Background saving started by pid 29108
29108:C 09 Feb 2020 14:04:07.610 * DB saved on disk
29108:C 09 Feb 2020 14:04:07.611 * RDB: 6 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:04:07.690 * Background saving terminated with success
27320:M 09 Feb 2020 14:05:21.179 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 14:05:21.180 * Background saving started by pid 29182
29182:C 09 Feb 2020 14:05:21.898 * DB saved on disk
29182:C 09 Feb 2020 14:05:21.899 * RDB: 13 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:05:21.987 * Background saving terminated with success
27320:M 09 Feb 2020 14:06:24.381 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 14:06:24.382 * Background saving started by pid 29247
29247:C 09 Feb 2020 14:06:33.014 * DB saved on disk
29247:C 09 Feb 2020 14:06:33.016 * RDB: 18 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:06:33.134 * Background saving terminated with success
27320:M 09 Feb 2020 14:07:47.956 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 14:07:47.957 * Background saving started by pid 29328
29328:C 09 Feb 2020 14:07:58.648 * DB saved on disk
29328:C 09 Feb 2020 14:07:58.767 * RDB: 22 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:07:58.811 * Background saving terminated with success
27320:M 09 Feb 2020 14:12:59.043 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:12:59.045 * Background saving started by pid 32334
32334:C 09 Feb 2020 14:13:09.454 * DB saved on disk
32334:C 09 Feb 2020 14:13:09.456 * RDB: 21 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:13:09.580 * Background saving terminated with success
27320:M 09 Feb 2020 14:16:41.935 * 10000 changes in 60 seconds. Saving...
27320:M 09 Feb 2020 14:16:41.936 * Background saving started by pid 32552
32552:C 09 Feb 2020 14:16:49.493 * DB saved on disk
32552:C 09 Feb 2020 14:16:49.496 * RDB: 19 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:16:49.614 * Background saving terminated with success
27320:M 09 Feb 2020 14:21:50.119 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:21:50.121 * Background saving started by pid 1749
1749:C 09 Feb 2020 14:22:00.083 * DB saved on disk
1749:C 09 Feb 2020 14:22:00.085 * RDB: 21 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:22:00.205 * Background saving terminated with success
27320:M 09 Feb 2020 14:27:01.025 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:27:01.027 * Background saving started by pid 2071
2071:C 09 Feb 2020 14:27:11.809 * DB saved on disk
2071:C 09 Feb 2020 14:27:11.811 * RDB: 23 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:27:11.930 * Background saving terminated with success
27320:M 09 Feb 2020 14:32:12.090 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:32:12.092 * Background saving started by pid 2448
2448:C 09 Feb 2020 14:32:23.233 * DB saved on disk
2448:C 09 Feb 2020 14:32:23.235 * RDB: 22 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:32:23.399 * Background saving terminated with success
27320:M 09 Feb 2020 14:37:24.096 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:37:24.097 * Background saving started by pid 2790
2790:C 09 Feb 2020 14:37:35.331 * DB saved on disk
2790:C 09 Feb 2020 14:37:35.410 * RDB: 22 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:37:35.531 * Background saving terminated with success
27320:M 09 Feb 2020 14:50:39.909 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:50:39.910 * Background saving started by pid 3635
3635:C 09 Feb 2020 14:50:50.335 * DB saved on disk
3635:C 09 Feb 2020 14:50:50.336 * RDB: 25 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:50:50.541 * Background saving terminated with success
27320:M 09 Feb 2020 14:55:51.023 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 14:55:51.024 * Background saving started by pid 4006
4006:C 09 Feb 2020 14:56:01.869 * DB saved on disk
4006:C 09 Feb 2020 14:56:01.908 * RDB: 22 MB of memory used by copy-on-write
27320:M 09 Feb 2020 14:56:01.989 * Background saving terminated with success
27320:M 09 Feb 2020 15:01:02.118 * 10 changes in 300 seconds. Saving...
27320:M 09 Feb 2020 15:01:02.120 * Background saving started by pid 4368
4368:C 09 Feb 2020 15:01:14.075 * DB saved on disk
4368:C 09 Feb 2020 15:01:14.077 * RDB: 23 MB of memory used by copy-on-write
27320:M 09 Feb 2020 15:01:14.237 * Background saving terminated with success

**Comment by MeirShpilraien** [comment]
I see that at some point this redis was demoted to slave which means that it flush the data and tried to sync from master unsuccessfully and after it was promoted back to master. Do you use sentinel?

**Comment by hamdallah90** [comment]
> I see that at some point this redis was demoted to slave which means that it flush the data and tried to sync from master unsuccessfully and after it was promoted back to master. Do you use sentinel?

What is the "sentinel"?

And how to fix this problem?

Thanks again for your replay.

**Comment by MeirShpilraien** [comment]
Are you using a maste slave deployment or is it just a single redis?

**Comment by hamdallah90** [comment]
> Are you using a maste slave deployment or is it just a single redis?
single redis

**Comment by MeirShpilraien** [comment]
So it looks like someone is messing with you...
You probably run with default port and not password and its probably open to the internet.
Please try change the default port and set up a password then let me know if its still happened.

**Comment by hamdallah90** [comment]
Ok thanks,

I will do that :), thanks for your help

**Comment by hamdallah90** [comment]
Fixed, The solution just secures the Redis server with a password.
