### ISSUE TITLE
coredump in v1.6.8

### ISSUE THREAD

**Issue by bailiyang** [RediSearch/RediSearch#1081]
hello
I got a coredump with RediSearch v1.6.8
try command

"FT.CREATE" "abc" "TEMPORARY" "36000" "STOPWORDS" "0" "SCHEMA" "name" "TEXT" "WEIGHT" "5.0" "uid" "NUMERIC" "NOINDEX"
"FT.ADD" "abc" "123" "1.0" "NOSAVE" "FIELDS" "name" "{\~LiZA\~}" "uid" "123"
FT.SEARCH abc "_\~rsna025\~_*" INFIELDS 1 name LIMIT 0 3

you will get a coredump

i think '~' make RediSearch crash

**Comment by bailiyang** [comment]
and same command in v1.4.24
no crash at all

**Comment by bailiyang** [comment]
sorry，I read doc and think '~' is not a right query syntax

**Comment by mnunberg** [comment]
Reopened, even if you're using the wrong syntax, a well behaved library should not core dump

**Comment by mnunberg** [comment]
I was not able to reproduce it. I did see a trace in msan (but only _once_) where it complained about something in `NewTokenNode`, so I am going to assume some freak ambiguity in the parser?

**Comment by MeirShpilraien** [comment]
@mnunberg did you solve this crash eventually?

**Comment by mnunberg** [comment]
no, let's keep this open for another few months, as I was not able to reproduce.

**Comment by bailiyang** [comment]
@mnunberg sorry, I haven't developed rediSearch for a while, this coredump is happend when i try to make rediSearch running in codis (with my own redis 5.0.5),
and i'm not sure this coredump is running my redis or the redis from github
i try to reproduce this error  NOW

**Comment by bailiyang** [comment]
i try:
rediSearch v1.6.8 (checkout from github)
with redis 5.0.5
--- no core at all
with redis 5.0.8
--- no core at all
with redis 5.0.5 (with my change)
--- no core at all

just got "(error) Syntax error at offset 9 near rsna025"

so, seem like this error not happen

by the way, rediSearch v1.4.24 is now running in my codis, beacause v1.6.8 may use more memory than v1.4.24, so we choice v1.4.24
