### ISSUE TITLE
Fuzzy search multi words.

### ISSUE THREAD

**Issue by hamdallah90** [RediSearch/RediSearch#1087]
Hello my friend,

Thank you for your help,

Please what is the best way to search for a fuzzy match on a string more than 2 words?

Thanks

**Comment by mnunberg** [comment]
Is there a reason why you can't just use the fuzzy syntax on each word?

**Comment by hamdallah90** [comment]
So this is the best way to do that
%word% %word% %word%  ?

**Comment by mnunberg** [comment]
that's what i would use.

**Comment by hamdallah90** [comment]
Thanks
