### ISSUE TITLE
Support for hindi snowball tokenizer

### ISSUE THREAD

**Issue by joeirimpan** [RediSearch/RediSearch#1096]
Can we add https://snowballstem.org/algorithms/hindi/stemmer.html which is available here https://snowballstem.org/dist/libstemmer_c.tgz?
Let me know if [this](https://github.com/joeirimpan/RediSearch/commit/eac3594ce76fe86584ae5805be825f9e81650828) can be a PR?

**Comment by mnunberg** [comment]
It certainly seems like it could!
