### ISSUE TITLE
Data conflicts between indexes 

### ISSUE THREAD

**Issue by hamdallah90** [RediSearch/RediSearch#1118]
Hello,

I am using laravel Scout to import models data.

and after import, the first index 100000 records its working fine,

But after load the second model I found there is a conflict when the document has the same id.

Thanks

**Comment by gkorland** [comment]
@hamdallah90 can you please add more extended recreation?

**Comment by miroslavp** [comment]
According to documentation [here](https://oss.redislabs.com/redisearch/Commands.html)

Warning!!!¶

FT.ADD will actually create a hash in Redis with the given fields and value. This means that if the hash already exists, it will override with the new values. Moreover, if you try to add a document with the same id to two different indexes one of them will override the other and you will get wrong responses from one of the indexes. For this reason, it is recommended to create global unique documents ids (this can e.g. be achieved by adding the index name to the document id as prefix).

**Comment by hamdallah90** [comment]
> According to documentation [here](https://oss.redislabs.com/redisearch/Commands.html)
> 
> Warning!!!¶
> 
> FT.ADD will actually create a hash in Redis with the given fields and value. This means that if the hash already exists, it will override with the new values. Moreover, if you try to add a document with the same id to two different indexes one of them will override the other and you will get wrong responses from one of the indexes. For this reason, it is recommended to create global unique documents ids (this can e.g. be achieved by adding the index name to the document id as prefix).

working :) thanks
