### ISSUE TITLE
1 Million limit on lettuceRediSearchClient.findall 

### ISSUE THREAD

**Issue by jphaugla** [RediSearch/RediSearch#1125]
this works at 1000000 but fails at 10000001
 Set<ProductEntity> products = lettuceRediSearchClient.findAll(1000001).resultStream()

com.rnbwarden.redisearch.LettuceTest > testFindAll FAILED
    io.lettuce.core.RedisCommandExecutionException at LettuceTest.java:184
        Caused by: io.lettuce.core.RedisCommandExecutionException at ExceptionFactory.java:135

this is the code link:
https://github.com/rnbWarden/jredisearch-spring-boot-starter/blob/master/src/test/java/com/rnbwarden/redisearch/LettuceTest.java

**Comment by ashtul** [comment]
Hi @jphaugla,
Can you please share the `message` and `cause` in the exception?

**Comment by jphaugla** [comment]
Additional Information on this limit.  I turned on monitor and determined this is the command being executed but the lettuceRediSearchClient.findAll.
"FT.AGGREGATE" "product" "*" "LOAD" "1" "@sdoc" "LIMIT" "0" "1000001" "WITHCURSOR" "COUNT" "1000"
I also ran this test against multiple versions of redisearch.  Running this with a value of 1000001 works in versions:  10410, 10417, 10419, and 10420.  It breaks using 10424, 10425, 10600, 10605, and 10610.

**Comment by jphaugla** [comment]
I accidentally closed this-sorry for the hassle...  Additional comment from customer:
I'm working on my spring boot starter. A complaint from my developers has been that client-side paging hits the hard 1M limit. But server-side paging has no option to pull only keys. So any (client) operation that wants to operate off keys alone (and still be certain we're working outside the 1M limit) pays the cost of pulling the gzip-compressed serialized document from Redis, sending it to the client, decompressing, deserializing, and then discards 99% of the payload. <barf>
I'm digging into the details and not seeing how I can entice FT.AGGREGATE to return the keys. It appears you have to use the LOAD param but in such a scenario you can only pull individual fields… which I think means fields explicitly added to the index. However, the key isn't one of those fields. I'm hoping there's some hook to pull the key.
The goal is to return the keys and save the pain described above.
