### ISSUE TITLE
Feature request: enable filtering by the exact value of whole text field

### ISSUE THREAD

**Issue by yurymann** [RediSearch/RediSearch#1130]
It appears that it's not currently possible to search for documents where a text field exactly equals a certain value. The search will always include documents where the searched value is one of the tokenised terms. 

Example:
```
> FT.CREATE idx1 NOHL NOFREQS SCHEMA f1 TEXT NOSTEM
> FT.ADD idx1 doc1 1 FIELDS f1 aa.bb
> FT.ADD idx1 doc2 1 FIELDS f1 aa
> FT.ADD idx1 doc3 1 FIELDS f1 cc.aa
```
This search returns all 3 documents because "aa" is recognised as a term in all of them. 
`> FT.SEARCH idx1 @f1:aa`

But in my case I may have thousands of "aa.bb" and a few "aa" mixed in between them. How can I query only those where f1=="aa"?

Note that some of SQL mappings in the [documentation](https://oss.redislabs.com/redisearch/Query_Syntax.html#mapping_common_sql_predicates_to_redisearch) are incorrect in this sense. E.g. @x:foo and WHERE x='foo' have different semantics. 

@gkorland suggested using tag fields for this purpose. Unfortunately, it does not solve our more generic use case unless we build an extra indexing layer on top of Redisearch - with special fields or indices for "exact match" search. 

Related discussion: https://groups.google.com/forum/#!topic/redisearch/W-25Nl7_I_A

Thanks

**Comment by lumina7** [comment]
Should work if you add "exact match"

f1="\"aa\"" in your case

**Comment by yurymann** [comment]
> Should work if you add "exact match"
> 
> > FT.SEARCH idx1 @F1:"aa"
> 
> in your case

@lumina7, does it work for you with my example? Which version of redis and RediSearch?
I've just tried (again) and it returns all 3 documents. 

I use Redis 5.0.7 and RediSearch 1.6.10.

**Comment by lumina7** [comment]
You are right does not work either for me. You still can use tag field for exact match. 
But having this feature would be a no-brainer on others fields...

**Comment by yurymann** [comment]
I'm not convinced that tag fields are what  need. My plan so far (if I don't move to a different technology by that time): create proxy fields alongside the functional fields specifically for exact search, with all tokeniser separators escaped. E.g. in the example above I'll also have field i_f1 with "." in values replaced by "\.".

**Comment by Sceat** [comment]
While i have another usecase i got the same issue, i was trying to index users and couldn't add/search their mails

```sh
	> FT.CREATE User SCHEMA mail TEXT NOSTEM
OK
	> FT.ADD User user:1 0 FIELDS mail "foo@bar.baz"
OK
	> keys *
1) idx:User
2) user:1
3) ft:User/baz
4) ft:User/foo
5) ft:User/bar
	> FT.SEARCH User "@mail:foo@bar.baz"
(error) Syntax error at offset 14 near baz
	> FT.SEARCH User "@mail:foo\@bar\.baz"
1) 0
```

We also can't search for hashtags inside a text i guess

**Comment by emmanuelkeller** [comment]
@yurymann  To solve this issue, we are currently implementing an alias feature, where you can have different indexing strategy for the same field.

The PR is here: https://github.com/RediSearch/RediSearch/pull/1909
That will be production ready in the next major version (2.2).

Here is how it works.

Creating the index:

```
FT.CREATE idx1 NOHL NOFREQS SCHEMA f1 AS f1_text TEXT NOSTEM f1 AS f1_tag TAG
```

Notice the new syntax: "f1 AS f1_text"

In the index, we have created two representation of the same field "f1":
- **f1_text** can now be used for full text search,
- **f1_tag** can be used for tag search.

Indexing some data:

```
FT.ADD idx1 doc1 1 FIELDS f1 aa.bb
FT.ADD idx1 doc2 1 FIELDS f1 aa
FT.ADD idx1 doc3 1 FIELDS f1 cc.aa
```

Now you have two search options (without duplicating the data in the hash):

Finding the exact text by using the f1_tag field:

```
FT.SEARCH idx1 @f1_tag:{aa}
1) (integer) 1
2) "doc2"
3) 1) "f1"
   2) "aa"
```

Or do a normal full-text search query:

```FT.SEARCH idx1 @f1_text:aa
1) (integer) 3
2) "doc1"
3) 1) "f1"
   2) "aa.bb"
4) "doc2"
5) 1) "f1"
   2) "aa"
6) "doc3"
7) 1) "f1"
   2) "cc.aa"
```

**Comment by emmanuelkeller** [comment]
@Sceat Here is how to handle that with RediSearch v2.0

The @ character has to be escaped because this character is used to identify a field in the query syntax (see how to do it below).

### Solution:

Creating the index with the TAG field:

``` 
FT.CREATE User SCHEMA mail TAG
``` 

Indexing your data:

``` 
HSET user:1 mail "foo@bar.baz"
``` 

Searching for the email by escaping @ and . 

``` 
FT.SEARCH User "@mail:{foo\\@bar\\.baz}"
1) (integer) 1
2) "user:1"
3) 1) "mail"
   2) "foo@bar.baz"
``` 

When you have parsing issues, feel free to use FT.EXPLAINCLI to see what is going on.

Example without escaping the dot. Notice that the parser is splitting the query into "foo@bar" and "baz".

```
FT.EXPLAINCLI User "@mail:{foo\\@bar.baz}"
1) TAG:@mail {
2)   INTERSECT {
3)     foo@bar
4)     baz
5)   }
6) } 
``` 

Example without escaping the dot. Notice that the parser is splitting the query into "foo@bar" and "baz".

```
FT.EXPLAINCLI User "@mail:{foo\\@bar\\.baz}"
1) TAG:@mail {
2)   foo@bar.baz
3) }
```

**Comment by ashtul** [comment]
A TAG field should be used.
On TEXT fields, `.` is considered a separator so `aa` and `bb` are tokenized as two distinguished words.

**Comment by Li-Khan** [comment]
@emmanuelkeller can you please show how to implement the same query in golang language?
FT.CREATE idx1 NOHL NOFREQS SCHEMA f1 AS f1_text TEXT NOSTEM f1 AS f1_tag TAG
using the package github.com/RediSearch/redisearch-go/redisearch
