### ISSUE TITLE
Cursor API not documented for FT.SEARCH

### ISSUE THREAD

**Issue by sheinbergon** [RediSearch/RediSearch#1153]
Hi.

While WITHCURSOR statements seem to work for FT.SEARCH, they're only documented as part of the aggregations functionality. It's a powerful feature, and IMO you should update the documentation to reflect on it.

**Comment by K-Jo** [comment]
@sheinbergon Currently, this feature is not supported (as it's not documented).  I have written down an explanation here: https://groups.google.com/forum/#!msg/redisearch/W_V-8IqMfPk/ID9WANoPAgAJ
This is related to #689 and will be tackled in 3.0 since it's a breaking change/

**Comment by sheinbergon** [comment]
@K-Jo well, it's working for me with 1.6.10. What do you mean by 'not supported'?

**Comment by mnunberg** [comment]
It means we haven't integrated it into our tests, so it doesn't have our formal Stamp Of Approval (TM). Off the record, it should work just fine in this particular scenario.

If you want to get into the nitty gritty, WITHCURSOR on FT.SEARCH does not work on our enterprise offering currently.

**Comment by sheinbergon** [comment]
@mnunberg OK got it. though it brings major performance boosts ( 50x faster on 1M items index) for pagination queries. Thanks anyway, closing this.

**Comment by sheinbergon** [comment]
@mnunberg seeing your edits on your recent comment, FWIW, are there any plans to remove that feature from FT.SEARCH until it's officially supported? we are relying on the performance boost it gives for pagination queries, so please don't make it eat my data :-(
