### ISSUE TITLE
MAXDOCTABLESIZE not registered into redis-server log

### ISSUE THREAD

**Issue by lumina7** [RediSearch/RediSearch#1161]
`redis-server --loadmodule ./redisearch.so MAXDOCTABLESIZE 2000000`

And when the server start...
```
cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8,
```
Is MAXDOCTABLESIZE properly registered?

**Comment by mnunberg** [comment]
what version of search are you using?

**Comment by lumina7** [comment]
RediSearch version 99.99.99 (Git=v1.6.6-45-gc13f342f)

**Comment by mnunberg** [comment]
You're right, it's not actually setting it.

**Comment by mnunberg** [comment]
@ashtul It's simply not setting it in the function, though it's validating them. I'm wondering if there aren't other options that we're missing
