### ISSUE TITLE
Equal MySQL query

### ISSUE THREAD

**Issue by lipoiq** [RediSearch/RediSearch#1206]
How I can do query equal MySQL `WHERE column <> 3`

**Comment by MeirShpilraien** [comment]
https://oss.redislabs.com/redisearch/Query_Syntax.html#mapping_common_sql_predicates_to_redisearch
```
@num:[-inf (3] | @num:[(3 +inf]
```

**Comment by lipoiq** [comment]
> https://oss.redislabs.com/redisearch/Query_Syntax.html#mapping_common_sql_predicates_to_redisearch
> 
> ```
> @num:[-inf (3] | @num:[(3 +inf]
> ```

thnx
