### ISSUE TITLE
Documentation has been rebuilt incorrectly and URLs have changed.

### ISSUE THREAD

**Issue by simonprickett** [RediSearch/RediSearch#1233]
It appears that the documentation has been rebuilt and a lot of URLs no longer resolve, for example:

https://oss.redislabs.com/redisearch/Scoring/

https://oss.redislabs.com/redisearch/Commands/#ftsearch

https://oss.redislabs.com/redisearch/Commands/#ftexplain

Looks like .html has been introduced into the URLs with no 301 redirects for the old URLs.  I assume this is an error in building the site and that we don’t want .html in the URLs.

https://oss.redislabs.com/redisearch/Commands.html#ftcreate

**Comment by gkorland** [comment]
The documentation is now versioned,
https://oss.redislabs.com/redisearch/1.6/Scoring.html
https://oss.redislabs.com/redisearch/1.6/Commands.html

**Comment by itamarhaber** [comment]
This is another issue, unrelated to versioned docs.

This https://github.com/RediSearch/RediSearch/blob/master/mkdocs.yml#L16 should be set to `true` like all other modules' docs I believe

**Comment by simonprickett** [comment]
@itamarhaber the URLs are still different than before, breaking things that link to the docs. e.g. https://oss.redislabs.com/redisearch/Commands.html#ftadd used to be https://oss.redislabs.com/redisearch/Commands/#ftsearch

If this is intentional (extra .html) I'll update the Redis University course that has many links to this documentation.  I assume this is still a mistake though?

**Comment by simonprickett** [comment]
This is working well now, thanks.

**Comment by itamarhaber** [comment]
Woot!!!
