### ISSUE TITLE
ERR unknown command `FT.CREATE`

### ISSUE THREAD

**Issue by gyana12** [RediSearch/RediSearch#1236]
while creating an index getting error

> ERR unknown command FT.CREATE

`redis-cli --cluster call 127.0.0.1:30001 FT.CREATE myIdx SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT value NUMERIC`

i tried to install the redis search module using below command, but no success.
`redis-cli --cluster call 127.0.0.1:30001 MODULE load redisearch.so OPT1 OPT2`

could someone guide me how to install these modules on redis cluster.

**Comment by MeirShpilraien** [comment]
Can you share the output of module list command on each shard? I suspect the module was not loaded on all the shards..

**Comment by gyana12** [comment]
Yes you are correct module hasn't loaded.
`create-cluster znrind-a0053$ ~/Downloads/redis-5.0.5/src/redis-cli --cluster call 127.0.0.1:30001 MODULE LIST`

```
>>> Calling MODULE LIST
127.0.0.1:30001: 
127.0.0.1:30006: 
127.0.0.1:30005: 
127.0.0.1:30002: 
127.0.0.1:30004: 
127.0.0.1:30003:
```

**Comment by MeirShpilraien** [comment]
@gyana12 Sorry for the late reply, you should send the module load command to all the shards with the path to the module .so file and make sure the .so file is located on this path on all the nodes.
