### ISSUE TITLE
Won't filter the letter "a" ?

### ISSUE THREAD

**Issue by Jonarod** [RediSearch/RediSearch#1237]
When I create a simple schema like this:
```
FT.CREATE test SCHEMA category TEXT SORTABLE subcategory TEXT SORTABLE
```

Then add entries:
```
FT.ADD test id_1 0.5 FIELDS category "a" subcategory "b"
FT.ADD test id_2 0.5 FIELDS category "b" subcategory "a"
```

Search works for "b":
```
FT.SEARCH test "@category:b" RETURN 0
1) (integer) 1
2) "id_2"

FT.SEARCH test "@subcategory:b" RETURN 0
1) (integer) 1
2) "id_1"
```

Search completely misses for "a":
```
FT.SEARCH test "@category:a" RETURN 0
1) (integer) 0  // SHOULD RETURN id_1

FT.SEARCH test "@subcategory:a" RETURN 0
1) (integer) 0  // SHOULD RETURN id_2
```

I have made several tests changing fields names, etc... it always comes down to the letter "a" being ignored by search: is there something I missed ?

**Comment by gkorland** [comment]
"a" is considered a stop word for tokenization 
See: https://oss.redislabs.com/redisearch/Stopwords.html

**Comment by Jonarod** [comment]
Thanks for your lightening fast reply.

My bad... I thought stop words would have been considered only on fields labeled as `PHONETIC` :sweat: 

I tried to use `NOSTOPWORDS` in my search, it throws the same result ignoring the letter "a"...

Is there a way to avoid re-indexing all my data set now?

**Comment by Jonarod** [comment]
I used `STOPWORDS 0` at schema creation.
