### ISSUE TITLE
No command to list all indexes

### ISSUE THREAD

**Issue by humblewolf** [RediSearch/RediSearch#1240]
Please add a command to list all indexes in redisearch currently. I guess there is none at present, or is there any ?

Thanks

**Comment by gkorland** [comment]
@humblewolf there is no such command, but we plan to add in RediSearch 2.0

**Comment by humblewolf** [comment]
Thank you.

**Comment by lumina7** [comment]
A simple `keys idx:*` works on vanilla redis.

**Comment by ashtul** [comment]
fixed by #1337
