### ISSUE TITLE
SORTBY GEO

### ISSUE THREAD

**Issue by chameleonbr** [RediSearch/RediSearch#125]
Hi, my project use a large data set with more than 10 million of points in 360 miles of range. We use elasticsearch as search engine and we starting to test redisearch seeing your great evolution. The only thing that we not found is sort by geo.
You have plans to implement this feature?
I've tried to understand and help to make this feature, but I have not programmed in C for a long time.
Thanks for your great lib.

**Comment by dvirsky** [comment]
It's not hard to implement it, it's in the TODO but not on the near term road map. 
If you want I can guide you, and it's something I'll definitely add if contributed.

**Comment by atris** [comment]
Is this a good newbie thing to pick?

**Comment by dvirsky** [comment]
@atris I would start with something lighter. And this will require an API change as you would have to sort by radius given a point.

**Comment by atris** [comment]
@dvirsky Sure, please suggest

**Comment by mnunberg** [comment]
@dvirsky @atris https://github.com/RedisLabsModules/RediSearch/issues/184 - this should be a simple enough task to perform. Please ping me if you need more details.

**Comment by mattboban** [comment]
@dvirsky @atris has there been any progress on this?

**Comment by chameleonbr** [comment]
Hello, any progress?

**Comment by yghaile** [comment]
Another user here wondering about this.  If I had any time, I'd complete it for you.  I have a simple hack to to work around this, but I'm not sure if I we should expect this issue to be completed at some point soon (or make the hack more permanent).  Please advise.  Also, thanks for the great work so far...

**Comment by mstaack** [comment]
check this post:
https://groups.google.com/forum/#!topic/redisearch/R4fz5cip1n8

**Comment by ashtul** [comment]
related #1246

**Comment by ashtul** [comment]
@chameleonbr @mstaack @yghaile @matijaboban @atris 
#1246
