### ISSUE TITLE
FT.AGGREGATE on Tag field with multiple values

### ISSUE THREAD

**Issue by lumina7** [RediSearch/RediSearch#1258]
```
 FT.AGGREGATE index 'red' GROUPBY 1 @category REDUCE count 0 AS 'hits'

1) (integer) 1
2)1) "category"
   2) "212,215,221"
   3) "hits"
   4) "1"
```
I was expecting 3 results.

It seems FT.aggregate does not really work on tags field with multiple entries? 
It is not splitting them in multiple fields.

As there is no other way to have multiple entries, having this working correctly would be great for people using facets... like me :)

**Comment by guykorlandredis** [comment]
@lumina7 can you please add a full example including some example docs?

**Comment by lumina7** [comment]
ok, here is the whole step to reproduce.

Basically create an index with a text field and a tag field.

```
redis-cli
FT.CREATE myidx SCHEMA productnameTEXT category TAG SORTABLE
```

Now add some documents to the index with a multiple tags (to add multiple tags, the default separator is the comma)
```

FT.ADD myidx p1 1.0 NOSAVE FIELDS productname 'red flower' category 200,201,202 
FT.ADD myidx p2 1.0 NOSAVE FIELDS productname 'red lily' category 200
FT.ADD myidx p3 1.0 NOSAVE FIELDS productname 'red rose' category 201
```

Now lets do the aggregate to get the facets for the search 'red'

Expected results:
3 results for category 200
2 results for category 201
1 results for category 202

```
redis >  FT.AGGREGATE myidx 'red' GROUPBY 1 @category REDUCE count 0 AS 'hits'
1) (integer) 3
2) 1) "category"
   2) "201"
   3) "hits"
   4) "1"
3) 1) "category"
   2) "200,201,202"
   3) "hits"
   4) "1"
4) 1) "category"
   2) "200"
   3) "hits"
   4) "1"
 
```
FT.AGGREGATE do not work with TAGS field. It consider a tag fields with multiple tags as a whole only, not as different 'value', which is a problem for faceted search on multiples entries.

**Comment by MeirShpilraien** [comment]
You need to apply a split function before the Groupby https://oss.redislabs.com/redisearch/Aggregations/#list_of_string_apply_functions

**Comment by lumina7** [comment]
Ok, I see it now in the doc but it is really not well documented.
Can someone show me how to do that???

**Comment by MeirShpilraien** [comment]
```
127.0.0.1:6379> FT.CREATE idx SCHEMA t TAG
OK
127.0.0.1:6379> FT.ADD idx doc1 1.0 FIELDS t foo,bar
OK
127.0.0.1:6379> FT.ADD idx doc2 1.0 FIELDS t foo,bar,koo
OK
127.0.0.1:6379> FT.ADD idx doc 1.0 FIELDS t foo
OK
127.0.0.1:6379> FT.AGGREGATE idx * LOAD 1 @t APPLY "split(@t)" as t1 GROUPBY 1 @t1 REDUCE count 0 AS 'hits'
1) (integer) 3
2) 1) "t1"
   2) "foo"
   3) "hits"
   4) "3"
3) 1) "t1"
   2) "bar"
   3) "hits"
   4) "2"
4) 1) "t1"
   2) "koo"
   3) "hits"
   4) "1"
```

**Comment by lumina7** [comment]
I found it by myself by trail and error, thank you for the help!!!!
