### ISSUE TITLE
Key events are not triggered

### ISSUE THREAD

**Issue by Sceat** [RediSearch/RediSearch#1287]
I have an usecase where i need be notified whenever a hash is created, updated or deleted. It seems `FT.ADD` doesn't trigger any key notification

## Reproduce

```sh
CONFIG SET notify-keyspace-events KEA
PSUBSCRIBE __key*__:*
```

```sh
FT.CREATE users SCHEMA name TEXT
FT.ADD users user:1 1.0 FIELDS name "Paul"
```

**Comment by K-Jo** [comment]
Hi @Sceat, we're working on the next major version of RediSearch where at creation time of the index, you'll be able to define which hashes RediSearch should follow/index.  So you'll just write into redis hashes to update the index.  This will also resolve the above issue.

**Comment by Sceat** [comment]
Sounds nice! in the mean time i actually `PUBLISH __keyevent__:FT_ADD <id>` manually
