### ISSUE TITLE
FT.SEARCH vs FT.GET

### ISSUE THREAD

**Issue by Sceat** [RediSearch/RediSearch#1288]
Asking for usage advice, is there an **important** difference performance wise doing 

```sh
FT.SEARCH idx "*" INKEYS doc1
```

instead of

```sh
FT.GET idx doc1 
```

I wrote a [js lib](https://github.com/HydreIO/disk) and for convenience i only use SEARCH but maybe i should use GET whenever possible ?

**Comment by MeirShpilraien** [comment]
@Sceat yes, FT.GET is doing directly to the document and returns the values while FT.SEARCH will perform the query and then return doc1 if doc1 appears in the results. To summaries, for this specific example, FT.GET should be much much faster.
