### ISSUE TITLE
using dot in field name

### ISSUE THREAD

**Issue by srmarjani** [RediSearch/RediSearch#1289]
Hi

I have problem when I search a specific field that have dot in its name.

consider below scenario :

`FT.CREATE test SCHEMA a.a TEXT`

`FT.ADD test doc1 1.0 FIELDS a.a "hello world"`

Searching without specifying field return result
```
FT.SEARCH test "hello world"
1) (integer) 1
2) "doc1"
3) 1) "title.a"
   1) "a.a"
   2) "hello world"
```

BUT with field I get error
```
FT.SEARCH test "a.a:hello world"
(error) Syntax error at offset 3 near 'a'
```

In this issue 
https://github.com/RediSearch/RediSearch/issues/225

It seemed that problem has been solved.

I use redisearch version 1.6

thanks.

**Comment by tomazz75** [comment]
In commit for #225 you have some examples, it looks like you have to escape the dot

FT.SEARCH test "@a\\.a:hello world"
1) (integer) 1
2) "doc1"
3) 1) "a.a"
   2) "hello world"

**Comment by srmarjani** [comment]
thanks.
