### ISSUE TITLE
Stopwords(?) cause problems with prefix search

### ISSUE THREAD

**Issue by Nomafin** [RediSearch/RediSearch#1297]
Using RediSearch version 1.6.13.

Searching with query `how to behave` or `video at recess` brings wanted results with these phrases present in the document. However, with `how* to* behave*` or `video* at* recess*` do not work, while `how* behave*` and `video* recess*` still do. So I guess this has something to do with RediSearch's default stopwords list including English prepositions?

**Comment by ashtul** [comment]
@Nomafin 
Indeed this is related to stopwords. Since `to`, as a stopword,  was not indexed, your search for it does not yield any result and you receive an empty list. This is the expected behavior.

**Comment by ashtul** [comment]
@Nomafin, is there further assistance you need for this issue?
