### ISSUE TITLE
can't create index using redislab/redissearch:edge docker image

### ISSUE THREAD

**Issue by listaction** [RediSearch/RediSearch#1320]
```
127.0.0.1:6379> FT.CREATE myIdx SCHEMA title TAG
(error) No rule type given
```
I am using:
```
redislabs/redisearch                                               edge                bc3bebf37dde
```
This was working a few days ago.

**Comment by MeirShpilraien** [comment]
You are probably using the edge docker image which we recently update with the new follow hashes feature. This introduce a small change to the api that require rule definition. We will post a message about it in the RediSearch forum with explanation and also we will update the documentation. 
Until then if you want to use the api as it is on the latest version please use the latest tag

**Comment by MeirShpilraien** [comment]
On the other hand if you want to checkout the new follow hash feature just add 'ON hash' to the ft.create command after the index name

Ft.create myidx ON hash SCHEMA .. 

Then each hash added using hset command will outomatically be indexed.

**Comment by listaction** [comment]
thanks - please do share the link to the forum / docs. When you say each hash added during the hset command - does it mean that when I add a document I have to use a different command as well (i have fields which get indexed currently as fulltext).

 Additionally, I am waiting for this as well : https://github.com/RediSearch/RediSearch/pull/1246  🙇‍♂️

**Comment by MeirShpilraien** [comment]
You can still use the ft.add command but simple Redis hset will also work. Will update you when we post the message.
Regarding the geo distance we still did not agreed on the final API. Will try to push it.

**Comment by listaction** [comment]
I tried this with the cli it works, however in java using https://github.com/RediSearch/JRediSearch, it does not expose option to pass this in. should I pr or should i expect it  on the way?

**Comment by MeirShpilraien** [comment]
Its on the way

**Comment by slavaGanzin** [comment]
My redis crashed with memory errors (and not an error describing incompatible dump.rdb changes in redisearch) after I updated redisearch. I needed to flushall databases just to understand what's happening. And problem is that you push breaking changes in master. And don't say I should use latest or any other tag. I do as it's written in docs: https://oss.redislabs.com/redisearch/Quick_Start/#building_and_running_from_source

So I'll remind you: redisearch is used in production. So push breaking changes in separate branch until everything is ready: docs, code, examples. 

p.s. I now it's an open source, you owe me nothing.

**Comment by MeirShpilraien** [comment]
You should not use master branch in production, you should use only officials versions (vx.x.x github tags)

**Comment by slavaGanzin** [comment]
If this is official recommendation it should be stated in docs and not be buried in issues that will be closed. Please add this.

And you shouldn't recommend in README.md to use docker image that is updated from master if it doesnt' support api that is described in docs.

**Comment by MeirShpilraien** [comment]
Agree, will be fixed.
Thanks

**Comment by gkorland** [comment]
@slavaGanzin thanks for the feedback! 
But, the docs do say explicitly to use `$ docker run -p 6379:6379 redislabs/redisearch:latest` which is the default tag even if no tag was used.
The `redislabs/redisearch:edge` is never mentioned in the docs how did you come about it?

**Comment by gkorland** [comment]
@listaction as for the JRediSearch you can use this PR for now https://github.com/RediSearch/JRediSearch/pull/108
Or the 2.0.0-snapshot

```
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>

  <dependencies>
    <dependency>
      <groupId>com.redislabs</groupId>
      <artifactId>jredisearch</artifactId>
      <version>2.0.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
```

**Comment by slavaGanzin** [comment]
@gkorland I draw a wrong conclusion based on docker hub and not README. My fault

**Comment by gkorland** [comment]
@slavaGanzin thanks anyway for the feedback, it's a good point if someone is coming directly to docker hub there is no comment indicating edge is the unstable "master"
