### ISSUE TITLE
Large numbers rounded and returned with e notation using FT.AGGREGATE

### ISSUE THREAD

**Issue by lpellegr** [RediSearch/RediSearch#1332]
Using RediSearch 1.6.13, let's say you have a `post` schema with an indexed field of type Numeric that is called "expirationTime".

You create a document with value  `9223372036854775807` for field `expirationTime`.

Now if you make a query with FT.SEARCH, you get the value that you inputted for field `expirationTime`:

> FT.SEARCH post *
> ...
> 41) "expirationTime"
> 42) "9223372036854775807"

However, if you make an FT.AGGREGATE a different value using the e notation is returned:

> FT.AGGREGATE post * LOAD 1 expirationTime
> 1) (integer) 1
> 2) 1) "expirationTime"
>    2) "9.22337203685e+18"

Is it an expected behavior? any solutions to get the same output as as FT.SEARCH, namely "9223372036854775807"?

**Comment by ashtul** [comment]
@lpellegr
`FT.SEARCH` retrieves the original string as inserted and therefore isn't modified.
`FT.AGGREGATE` parse the number into a double in order to allow transformations on the results and therefore is limited to numbers up to `2^52`.

**Comment by lpellegr** [comment]
Thanks for the information.
