### ISSUE TITLE
make build error

### ISSUE THREAD

**Issue by h1100e** [RediSearch/RediSearch#1351]
redis: Redis server v=6.0.5 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64 build=814f88e9606f720e
OS: ubuntu
error info:
Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" failed.
Compiler: CMAKE_CXX_COMPILER-NOTFOUND
Build flags:
Id flags: -c

The output was:
No such file or directory

What happend?

**Comment by ashtul** [comment]
Try calling `which c++` and see what you get.
The module sets it as `/usr/bin/c++`.

**Comment by h1100e** [comment]
> Try calling `which c++` and see what you get.
> The module sets it as `/usr/bin/c++`.
I find the way. Thank you.
sudo apt update
sudo apt install -y build-essential
