### ISSUE TITLE
FT.SEARCH return result in array. How can we get it as object

### ISSUE THREAD

**Issue by waleedarshad-vf** [RediSearch/RediSearch#1352]
Currently if i run this command 

`FT.SEARCH userIndex "Saud*"  LIMIT 0 10 HIGHLIGHT `

Or nodeRediSearch command

```
  let users
client.ft_search(['userIndex','(saud*)|(saud)'], async (err, data) => {
    if (err) {
        console.log("err",err)
    } else {

      console.log("params",data);
      users = data
    }
  });
```

I get result as

```
[ 1,
  '5ecf54d2343c90783cffb06e',
  [ 'firstName',
    'Saud',
    'lastName',
    'Butt',
    'username',
    'saud',
    'type',
    'user',
    'profilePicture',
    '[object Object]',
    'verified',
    'true',
    'url',
    '/users/portfolio?id=5ecf54d2343c90783cffb06e' ] ]
```
this array consits of array. how can i loop on it efficiently. right now i have no way except to run 
result[1]
results[2][1] and checking if it is value. 

can't it be like
results.firstName etc.

Can anybody guide me

**Comment by gkorland** [comment]
@waleedarshad-vf which client are you using?

**Comment by waleedarshad-vf** [comment]
@gkorland https://github.com/stockholmux/node_redis-redisearch

**Comment by stockholmux** [comment]
@waleedarshad-vf The client library doesn't provide what you're requesting (for many reasons) but the way to accomplish this is by chunking document then converting pairs to entries. 

You can do this with lodash/underscore or without.

First you take the array and convert it into 2-entry sub pairs using [chunk or other methods](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_chunk). It turns the document into something like this:
```
 [ ['firstName', 'Saud'],
    ['lastName','Butt'],
    ['username','saud'],...
 ]
```

You then you use [fromPairs or other methods](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore#_frompairs) to convert the array from the previous step into an object.
```
{
  'firstName' : 'Saud',
  'lastName' : 'Butt',
  'username' : 'saud',....
}
```

There are lots of ways to do this, but effectively it looks something like `let fooAsObj = fromPairs(chunk(foo))`

You will still need to parse out doc count and doc name for your specific query - take a look at the RediSearch documentation - the output varies based on the arguments you are passing into the query.

Also, double check your original snippet where you run the command - it doesn't look quite right.

**Comment by waleedarshad-vf** [comment]
ah Great. Thanks. Long Live @stockholmux.  I will implement it and let you know. Thanks again
