### ISSUE TITLE
Understanding Keys Created by FT.ADD

### ISSUE THREAD

**Issue by TropicalPenguin** [RediSearch/RediSearch#1388]
Hello, I notice that with this series of simple commands:
```
FT.CREATE N SCHEMA name TEXT
FT.ADD N 0 1 NOSAVE FIELDS name Hello
FT.DEL N 0 DD
```

One key each are created by FT.CREATE & FT.ADD, respectively:
```
> KEYS *
1) "idx:N"
2) "ft:N/hello"
```

What I'm confused by is why FT.DEL does not effectively 'undo' FT,ADD and remove `ft:N/hello`, and am wondering if there's any mechanism by which such keys are removed (besides `FT.DROP`ping the index itself).

RediSearch version used: 1.8.1

**Comment by gkorland** [comment]
The keys you're seeing is the "empty" inverted index of `hello` and the key for the empty Index `N`.
Notice in the upcoming RediSearch 2.0 the index and the inverted index keys are not saved in the keyspace.

**Comment by TropicalPenguin** [comment]
Thanks @gkorland; I'm asking more out of curiosity than practical requirement, but, are there any plans to garbage collect such 'empty' inverted indexes?

**Comment by gkorland** [comment]
@TropicalPenguin we didn't see great benefit in cleaning these since we don't see too many empty inverted indexes in long running systems and will yield any real benefit

**Comment by ashtul** [comment]
Duplicate #1263
