### ISSUE TITLE
FT.SPELLCHECK confidence scores extremely low for unknown reasons

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#1390]
I have been using redisearch for various datasets (& also seen a few examples of ft.spellcheck in github issues) and the confidence scores for the spellcheck suggestions are always ridiculously low, in fact that they don't make any sense whatsoever, even though the suggestions are really good.

```
redis-cli "FT.SPELLCHECK" "idx1" "Islad" "DISTANCE" "2" 
1) 1) "TERM"
   2) "islad"
   3)   1) 1) "0.0066979382934979018"
           2) "island"
        2) 1) "0.0031479132246004962"
           2) "+island"
        3) 1) "0.0030284574047466021"
           2) "islands"
        4) 1) "0.00087488769470457401"
           2) "+islam"
        5) 1) "0.00064270596034066781"
           2) "isaac"
        6) 1) "0.00062924614965290517"
           2) "isle"
        7) 1) "0.00049801299544721905"
           2) "island."
        8) 1) "0.00049464804277527831"
           2) "islam"
        9) 1) "0.00022713430535599517"
           2) "inland"
       10) 1) "0.0002187219236761435"
           2) "isles"
```

(via https://github.com/RediSearch/RediSearch/issues/969)

This is approx what I get for 99.9% of cases.
However https://redislabs.com/blog/redisearch-1-4-phonetics-spell-check/ shows scores of 5 and 7, never had that happen.

Additionally, I think it would be nice (more intuitive) if the scores were some normalized value between 0-1, where 0.6 means 60% confidence.

Could you check why this happens or update the docs explaining that these extremely low values are normal and how they can be interpreted?

**Comment by ashtul** [comment]
@kkmuffme 
We are investigating this issue.
About the score in the blog post you mentioned, please note those are scientific float with an exponent of `-5`.

**Comment by kkmuffme** [comment]
Ah thank you, I somehow missed the -e when going through the docs, as I wasn't expecting to have such a low confidence score for the first 2 suggestions.
Makes much more sense with the suggested change you created

**Comment by ashtul** [comment]
@kkmuffme 
The score for the spelling suggestions is `Number of documents where the term appears` / `Number of documents in the index`. So for large indexes, the score can be very low. 

If you want a normalized value, you can divide all scores by the first suggestion score as the suggestions are returned in descending order of the score, 

We'll update the documentation to reflect this.
