### ISSUE TITLE
Maybe faster way to implement UI_ReadSorted

### ISSUE THREAD

**Issue by lych4o** [RediSearch/RediSearch#1392]
For now, redisearch will scan all active `IndexIterator` in `UnionIterator` for every call of `UI_ReadSorted()` to find the minimum Iterator, which is `O(n*m)` in time to read the whole `UnionIterator` where n is total number of item in `UnionIterator` and `m` is the number of `IndexIterator` in `UnionIterator`.

In my opinion, the better way to implement this function is to use a heap like `std::priority_queue` or write by hand to maintain the minimun `docId` which is `O(n*log(m))` in time to read the whole iterator.

When the number of `m` is too large, it is very slow to read. I've encountered this problem with a large `TagLexRange` query. One unique `tag` in result will lead to one `TrieMapNode` and then one `IndexIterator`. So the number of `IndexIterator` is large enough to effect the execute time.

**Comment by MeirShpilraien** [comment]
@lych4o thanks for sharing, this is a very good idea. We also encounter a slow read when `m` becomes very large and we know this is our weakness on the searching part. We also already have a heap implementation so it should be really easy to do. We will prioritize it.
