### ISSUE TITLE
Search: provide distance and sort on distance in the Search

### ISSUE THREAD

**Issue by tgrall** [RediSearch/RediSearch#1442]
* Use case:
   * "Find all restaurants around me sorted from the the closest to the farest, and opposite order"

* A possible syntax that is close the the `georadius` core command would be:

```
FT.SEARCH idx:poi 
  "@location:[-73.9798156 40.7614367 1 km] @type:{restaurant} "
  WITHDIST   ========================> New parameter to return/print the distance 
  SORTBY $$distance$$ ASC.  ===========> To Control the sort based on distance
  RETURN 2 name location

1) (integer) 2
2) "poi:65"
3) 1) "calculated.distance".   ==============> new structure return when WITHDIST is set
     2) 0.544
     3) unit
     4) km
4) 1) "name"
   2) "Minskoff Bar"
   3) "location"
   4) "-73.98605419441054,40.7579233360297"
5) "poi:31"
6) 1) "calculated.distance"
     2) 0.856
     3) unit
     4) km
7) 1) "name"
   2) "Ethel Barrymore Restaurant"
   3) "location"
   4) "-73.98615677726568,40.76010047723625"

``` 

May be find a way to return the distance from [here](https://github.com/RediSearch/RediSearch/blob/d1eca8d79523af213127260699bfa9331f77309e/src/dep/geo/rs_geo.c#L95-L96) to the result document list. (I quickly tried but the distance pointer does not seem to be available in the return list)

**Comment by ashtul** [comment]
fixed by #1246
