### ISSUE TITLE
Building and Running from Source with WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by CrimsonTide0** [RediSearch/RediSearch#1508]
Hi so I have Ubuntu 18.04 through WSL and was attempting to run from source. It properly cloned the git repository but when I run the command "make build" I get the error: make error *** no rule to make target 'build'

As a windows user, I really don't know what that means or how I can fix this issue. Help would be appreciated, thank you!

**Comment by rafie** [comment]
If `make` is installed, simply invoke `sudo make setup` before doing `make build`.
Otherwise, run:
```
./deps/readies/bin/getpy2
./system-setup.py
make build
```
PS
To install Redis, run: `sudo python2 ./deps/readies/bin/getredis`

**Comment by CrimsonTide0** [comment]
Hi it says that there is no such directory called ./deps/readies/bin/getpy2 or ./deps/readies/bin/getredis. Would this be because I'm using WSL? Where can I find the RediSearch Directory after I download it through git?

**Comment by rafie** [comment]
Did you run `git submodule update --init --recursive` after cloning?

**Comment by CrimsonTide0** [comment]
I did not, I just tried running it and it responds with fatal: not a git repository (or any of the parent directories): .git
On the other hand, I found the RediSearch directory and ran the sudo make setup command and the make build command. I had to update my Redis but now everything seems to be working fine.

When I run the server I do seem to be getting two warnings however unlike when I used to run redis straight from windows rather than WSL Ubuntu:
Warning: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.

What does this warning mean and how can I resolve this? I believe I can resolve the second warning myself.

**Comment by rafie** [comment]
Once a git repo was cloned, subsequent git commands should run from within the repo directory, that is:
```
git clone https://github.com/RediSearch/RediSearch.git
cd RediSearch
git submodule update --init --recursive
```
Alternatively, you can just run: `git clone --recursive https://github.com/RediSearch/RediSearch.git`

The TCP backlog warning is a formality and can be ignored.

A recommendation: it's better to start discussing usability problems in the [RediSearch forum](https://forum.redislabs.com/c/modules/redisearch), and only open an issue once it's clear that something is indeed broken.
We'll review the documentation to make sure the build process is accurate.

**Comment by CrimsonTide0** [comment]
Thank you for all your help!
