### ISSUE TITLE
SORTBY should raise an error if a field is not SORTABLE

### ISSUE THREAD

**Issue by tgrall** [RediSearch/RediSearch#1540]
When using SORTBY in a FT.SEARCH query the search does not happen if the field is not SORTABLE. 

It will be better for the user to raise an error indicating that SORTBY cannot be done on this not SORTABLE field(ideally) or do the sort (like in AGGREGATE, but not the best from a resource point of view).

The current behaviour could generate hard to debug behavior in in the application.

**Comment by ashtul** [comment]
This issue exist in RS 1.6.x as well so we should cherry-pick once fixed.
