### ISSUE TITLE
Getting a None (null) Value when trying to retrieve data with FT.SUGGET with Server

### ISSUE THREAD

**Issue by CrimsonTide0** [RediSearch/RediSearch#1548]
Hi I'm trying to use RediSearch to employ an autocomplete system on my searches. I use the programming language Rust as my server and currently have the following code which sends a command to the database:
```
pub fn ft_sugadd(index: String, field: String) -> redis::RedisResult<()>
{
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;
    redis::cmd("FT.SUGADD").arg(index).arg(field).arg("1".to_string()).query(&mut con)?;
    Ok(())
}

pub fn ft_sugget(index: String, field: String) -> redis::RedisResult<String>
{
    let client = redis::Client::open("redis://127.0.0.1/")?;
    let mut con = client.get_connection()?;
    let data_value = redis::cmd("FT.SUGGET").arg(index).arg(field).arg("fuzzy".to_string()).query(&mut con)?;
    Ok(data_value)
}

fn main()
{
    ft_sugadd("dictionary".to_string(), "Bob".to_string()).ok();
    let remember = ft_sugget("dictionary".to_string(), "Bo".to_string()).ok();
    println!("Hello {:?}", remember);
}
```
This format of code works perfectly well with sets and gets on Redis so I thought that I wouldn't have any issues if I just modifed the format a little bit. So I properly add a string to the key and then ask for suggestions in that key given the string Bo but this ends up returning None (null) when I print it. When I run ft.sugget dictionary Bo fuzzy manually through the command prompt it properly returns 1) "Bob but when I do it through the server it returns None (null).

How do I properly access the strings in the key and also how do I store multiple outputs serverside when the database outputs multiple times like 1) Bob 2) Boy?

**Comment by ashtul** [comment]
@CrimsonTide0 - `FT.SUGGET` reply with an array which is empty if no results have been returned. This is different than `SET` and `GET` which return a `(nil)` if the key was not found.

If this does not answer your question, can you try and give a specific example for what value you expected back. Maybe you can run it using `redis-cli`.

**Comment by CrimsonTide0** [comment]
Hi, what would be the code to store the array in a variable? I tried
```
let remember: Vec<String> = ft_sugget("dictionary".to_string(), "Y".to_string()).ok().unwrap();
```
but this seems to pop up an error saying expected std::vec::Vec found std::string::String

**Comment by CrimsonTide0** [comment]
Problem solved, I should've been expecting an array rather than a String, thanks!
