### ISSUE TITLE
Internal links are broken on Commands page

### ISSUE THREAD

**Issue by bmansheim** [RediSearch/RediSearch#1552]
The commands page has links to aggregation, stemming, etc. but the links do not include the version number so they go to "page not found".

**Comment by gkorland** [comment]
Where do you see such link? Do you mean this link? it seems to work
![image](https://user-images.githubusercontent.com/753206/93468731-18362180-f8f8-11ea-81b9-a5750f6cd299.png)

**Comment by bmansheim** [comment]
Confirmed.
