### ISSUE TITLE
FT.SYNDUMP silently ignores multiple arguments

### ISSUE THREAD

**Issue by banker** [RediSearch/RediSearch#1565]
According to the docs, SYNDUMP takes only one argument (a single index name). However, you can provide SYNDUMP with as many arguments as you like, and it will ignore these later arguments. It should return an error is the wrong number of arguments is provided.

**Comment by banker** [comment]
It should be useful for arguments after the <index name> to be the names of any synonym group IDs you want to inspect.

**Comment by ashtul** [comment]
> It would be useful for arguments after the to be the names of any synonym group IDs you want to inspect.

@K-Jo What do you think about the idea to allow specifying the `synonym group id` rather than dumping all of them?
