### ISSUE TITLE
Getting different results after rdb load on restart 

### ISSUE THREAD

**Issue by raybog** [RediSearch/RediSearch#1578]
I have followed this info: https://oss.redislabs.com/redisearch/Configuring/#maxexpansions
and set the MAXEXPANSIONS to 20 instead of default 200 in order to test the speed of my prefix query.

My index has 14.2M docs with one text field indexed. This indexed field holds up to 7 english terms on which I run full text search. 

I am getting different results (in terms of Total Documents Matched) for prefix queries.

For example:

- for MAXEXPANSIONS set to 20 and query -> "@Field(a*)" - getting  1,260,917 documents matched and response time 1826.21 ms

- for MAXEXPANSIONS set to 200 (default) and query -> "@Field(a*)" - getting  229,052 documents matched and response time 578.88 ms

Does it mean that setting MAXEXPANSIONS to higher value lowers the number of matched documents therefore response time is shorter? 

Also for some reason I am getting opposite results for different queries, for example:

- for MAXEXPANSIONS set to 20 and query -> "@Field(m*)" - getting  2776 documents matched and fast response time (not recorded by slowlog)

- for MAXEXPANSIONS set to 200 (default) and query -> "@Field(m*)" - getting 73,150 documents matched and response time 224.66 ms

**Comment by MeirShpilraien** [comment]
@raybog can you give us full reproduction steps (with the Redis and RediSearch versions you are using). I could not reproduce it with a simple test.

**Comment by raybog** [comment]
Sure here are redis/redisearch details:
```
1:C 23 Sep 2020 22:07:45.685 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 23 Sep 2020 22:07:45.685 # Redis version=6.0.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 23 Sep 2020 22:07:45.685 # Configuration loaded
1:M 23 Sep 2020 22:07:45.686 * Running mode=standalone, port=6379.
1:M 23 Sep 2020 22:07:45.686 # Server initialized
1:M 23 Sep 2020 22:07:45.727 * <search> Redis version found by RedisSearch : 6.0.5 - oss
1:M 23 Sep 2020 22:07:45.727 * <search> RediSearch version 2.0.0 (Git=v1.99.5-17-gd421035)
1:M 23 Sep 2020 22:07:45.727 * <search> Low level api version 1 initialized successfully
1:M 23 Sep 2020 22:07:45.727 * <search> concurrent writes: OFF, gc: ON, prefix min length: 1, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8, 
1:M 23 Sep 2020 22:07:45.727 * <search> Initialized thread pool!
1:M 23 Sep 2020 22:07:45.728 * Module 'search' loaded from /usr/lib/redis/modules/redisearch.so
1:M 23 Sep 2020 22:07:45.732 * Loading RDB produced by version 6.0.5
1:M 23 Sep 2020 22:07:45.732 * RDB age 229024 seconds
1:M 23 Sep 2020 22:07:45.732 * RDB memory usage when created 9758.48 Mb
1:M 23 Sep 2020 22:08:54.724 * <module> Scanning all indexes
1:M 23 Sep 2020 22:08:54.724 * DB loaded from disk: 68.996 seconds
1:M 23 Sep 2020 22:08:54.724 * Ready to accept connections
1:M 23 Sep 2020 22:08:54.725 * <module> Scanning indexes in background
1:M 23 Sep 2020 22:22:14.257 * <module> Scanning indexes in background: done (scanned=14159443)
```

I have run some more tests and it looks like the issue (or my misunderstanding how prefix query works?) is not related to changing value `MAXEXPANSIONS` but to due simple restart of redis. 

For example before restart I have run following queries:
```
echo a
"(a=>{$phonetic:false;})" limit 0 0
"(a=>{$phonetic:true;})" limit 0 0
"(a*)" limit 0 0
echo b
"(b=>{$phonetic:false;})" limit 0 0
"(b=>{$phonetic:true;})" limit 0 0
"(b*)" limit 0 0
echo c
"(c=>{$phonetic:false;})" limit 0 0
"(c=>{$phonetic:true;})" limit 0 0
"(c*)" limit 0 0
echo e
"(e=>{$phonetic:false;})" limit 0 0
"(e=>{$phonetic:true;})" limit 0 0
"(e*)" limit 0 0
echo t
"(t=>{$phonetic:false;})" limit 0 0
"(t=>{$phonetic:true;})" limit 0 0
"(t*)" limit 0 0
echo o
"(o=>{$phonetic:false;})" limit 0 0
"(o=>{$phonetic:true;})" limit 0 0
"(o*)" limit 0 0
echo r
"(r=>{$phonetic:false;})" limit 0 0
"(r=>{$phonetic:true;})" limit 0 0
"(r*)" limit 0 0
```
and got following response from redis-cli (number of documents):

```
a
3708
341919
1353287
b
2642
370038
106020
c
1314
90606
368921
e
1176
339526
135449
t
668
53220
221763
o
25303
363352
113122
r
564
32366
3243118
```

Then I just restarted Redis, waited for:  `Scanning indexes in background: done (scanned=14159443)` and run the same script again, and got following:

```
a
3708
341919
1343264
b
2642
370038
108399
c
1314
90606
636494
e
1176
339526
404275
t
668
53220
393718
o
25303
363352
170982
r
564
32366
3280554
```

What is the reason prefix queries are different ?

I am happy to share the RDB directly.

**Comment by ashtul** [comment]
@raybog 
In RediSearch 2.0 we index the hashes as they are loaded into the database which means querying prior to the completion of rdb reload will result in partial results.
You can test to check whether the reload has finished by running `ft.info` and checking if `indexing` value is `0`.

**Comment by raybog** [comment]
@ashtul thanks for the update. I just have checked the `ft.ino` and got following (without the fields bit):
```
 9) "num_docs"
10) "14159443"
11) "max_doc_id"
12) "14159443"
13) "num_terms"
14) "177930"
15) "num_records"
16) "207213574"
17) "inverted_sz_mb"
18) "1380.45654296875"
19) "total_inverted_index_blocks"
20) "2210643"
21) "offset_vectors_sz_mb"
22) "177.93394470214844"
23) "doc_table_size_mb"
24) "1620.4195556640625"
25) "sortable_values_size_mb"
26) "0"
27) "key_table_size_mb"
28) "812.50537109375"
29) "records_per_doc_avg"
30) "14.634302139282227"
31) "bytes_per_record_avg"
32) "6.9856119155883789"
33) "offsets_per_term_avg"
34) "0.90041047334671021"
35) "offset_bits_per_record_avg"
36) "8"
37) "hash_indexing_failures"
38) "0"
39) "indexing"
40) "0"
41) "percent_indexed"
42) "1"
43) "gc_stats"
44)  1) "bytes_collected"
     2) "0"
     3) "total_ms_run"
     4) "0"
     5) "total_cycles"
     6) "0"
     7) "avarage_cycle_time_ms"
     8) "-nan"
     9) "last_run_time_ms"
    10) "0"
    11) "gc_numeric_trees_missed"
    12) "0"
    13) "gc_blocks_denied"
    14) "0"
45) "cursor_stats"
46) 1) "global_idle"
    2) (integer) 0
    3) "global_total"
    4) (integer) 0
    5) "index_capacity"
    6) (integer) 128
    7) "index_total"
    8) (integer) 0
47) "stopwords_list"
48) (empty list or set)
```
and run my script again, and the same results (so I must have run the previous test already when  `indexing` value was `0`).

```
a
3708
341919
1343264
b
2642
370038
108399
c
1314
90606
636494
e
1176
339526
404275
t
668
53220
393718
o
25303
363352
170982
r
564
32366
3280554
```

**Comment by ashtul** [comment]
@raybog can this issue be closed?

**Comment by raybog** [comment]
@ashtul - as per my previous message I am getting different results (prefix queries) each time I restart redisearch and wait for  `indexing` value to be `0`. Sorry perhaps I do not understand something but why you are suggesting this should be closed?

**Comment by ashtul** [comment]
@raybog, can you please share the rdb file?

**Comment by raybog** [comment]
@ashtul - i just have sent you an email with the rdb file information.

**Comment by MeirShpilraien** [comment]
@raybog after investigation with Ariel we notice that we have a bug on updating the max expansions and the new value is not applied until after a restart. Could it be that you change the max expansions, it had no effect, then after a restart, you suddenly see more results on prefix search because the new max expansions value took effect?

**Comment by raybog** [comment]
@MeirShpilraien - I see different results (prefix search) each time I do restart without changing any settings. Initially I have thought the same (problem around max expansion) however more testing proved that it is just restart. As I was testing a lot prefix queries I have a feeling that this issue may be related to #1575?

**Comment by ashtul** [comment]
@raybog The issue you are seeing is a combination of two facts - 
1. In Redis 6.0.5, the scanning/indexing is happening after the rdb was reloaded and the keys might be indexed in a different order.
2. With prefix, the max expansion option makes return partial results as it trims the tree.
This combination gives you a different count of results.

In version 6.0.7, the keys are indexed as they are loaded into Redis from the rdb file and therefore, their order is consistent between reloads.

Extending the maxexpansion to a high number that will trim no nodes should return the same count for all versions. I will confirm and post the results.

**Comment by raybog** [comment]
@ashtul - thanks for the explanation. I still do not understand how `trimming` works. Is it a random operation? I would think that even with low number of maxexpansion the count should be the same (assuming only restart and no maxexpansion settings change)?

**Comment by MeirShpilraien** [comment]
@raybog its not the same because the trie gives the expended terms in different order and those terms has different number of documents which they match to.

**Comment by raybog** [comment]
@MeirShpilraien - how the order of the expanded terms is calculated then?

**Comment by MeirShpilraien** [comment]
It based on the insertion order which might be different on versions less then 6.0.7

**Comment by raybog** [comment]
Oh ok then if using 6.0.7 and above then the count should be always the same?

**Comment by MeirShpilraien** [comment]
Yes

**Comment by raybog** [comment]
Thanks 👍

**Comment by ashtul** [comment]
@MeirShpilraien 
So results in 6.0.7 will be the same if loaded from the same but if we save to RDB twice, we might get different results since redis may save to RDB in a different order?
