### ISSUE TITLE
Redisearch2 installation fails on mac os x with error

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#1581]
Copied from https://forum.redislabs.com/t/redisearch2-installation-fails-on-mac-os-x-with-error/917 

Has anybody managed to install RS2 on mac os x?

I am following the instructions here to install on Mac OS X 10.14.6 which were linked from here:

git clone --recursive https://github.com/RediSearch/RediSearch.git RediSearch2
git checkout tags/v2.0.0

~/src/RediSearch2$ sudo make setup
Password:
Setting up system…
brew update || true
Error: Running Homebrew as root is extremely dangerous and no longer supported.
…
make: *** [Makefile:128: setup] Error 1

~/src/RediSearch2$ make setup
…
make[4]: *** No rule to make target ‘strbuf.o’, needed by ‘liblua.a’. Stop.
make[3]: *** [Makefile:75: lua] Error 2
make[3]: *** Waiting for unfinished jobs…
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o sockcompat.o
ar rcs libhiredis_ssl.a ssl.o
ar: net.o: No such file or directory
ar: hiredis.o: No such file or directory
ar: sds.o: No such file or directory
ar: async.o: No such file or directory
ar: ar: read.o: No such file or directory
ssl.o: No such file or directory
ar: sockcompat.o: No such file or directory
make[4]: *** [Makefile:118: libhiredis_ssl.a] Error 1
make[4]: *** Waiting for unfinished jobs…
make[4]: *** [Makefile:112: libhiredis.a] Error 1
make[3]: *** [Makefile:50: hiredis] Error 2
make[2]: [Makefile:266: persist-settings] Error 2 (ignored)
…
clang: error: no such file or directory: ‘…/deps/lua/src/liblua.a’
make[2]: *** [Makefile:285: redis-server] Error 1
make[2]: *** Waiting for unfinished jobs…
make[1]: *** [Makefile:6: all] Error 2
command failed: { make -j /Users/michaelmasouras/src/RediSearch2/deps/readies/bin/nproc BUILD_TLS=yes; } >/var/folders/qm/m56dtbfd3_v1m274_wxgd4x40000gn/T/tmpY8ckn5 2>&1
command failed: python2 /Users/michaelmasouras/src/RediSearch2/deps/readies/bin/getredis -v 6 --force
make: *** [setup] Error 1

**Comment by rafie** [comment]
On macOS, `make setup` should run without `sudo`.

**Comment by mmasouras** [comment]
Unfortunately, that produces a different error as you see in my report.

Are there Mac-specific installation instructions that I can give a try - maybe I missed a Mac-only required step.

These are the instructions I follow:
https://oss.redislabs.com/redisearch/Quick_Start/#building_and_running_from_source?_ga=2.31237948.2066207977.1600801791-2025933075.1600203115

**Comment by sefai** [comment]
I am having the same problem. Any updates on the issue?

**Comment by Dmitry-N-Medvedev** [comment]
same here. any updates?

**Comment by mmasouras** [comment]
I just tried this again, and it's still failing. 

**sudo make install**

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
command failed: { brew list git &>/dev/null || brew install git; } >/tmp/tmpuPMy8I 2>&1
make: *** [Makefile:128: setup] Error 1


**make install**
....

MAKE lua
cd lua/src && make all CFLAGS="-O2 -Wall -DLUA_ANSI -DENABLE_CJSON_GLOBAL -DREDIS_STATIC='' " MYLDFLAGS="" AR="ar rcu"
make[4]: Nothing to be done for 'linenoise.o'.
make[4]: *** No rule to make target 'strbuf.o', needed by 'liblua.a'.  Stop.
make[3]: *** [Makefile:75: lua] Error 2
make[3]: *** Waiting for unfinished jobs....
ar rcs libhiredis.a net.o hiredis.o sds.o async.o read.o sockcompat.o
ar rcs libhiredis_ssl.a ssl.o
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
make[4]: *** [Makefile:112: libhiredis.a] Error 1
make[4]: *** Waiting for unfinished jobs....
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
make[4]: *** [Makefile:118: libhiredis_ssl.a] Error 1
make[3]: *** [Makefile:50: hiredis] Error 2
make[2]: [Makefile:283: persist-settings] Error 2 (ignored)
    CC adlist.o
    CC quicklist.o
    CC ae.o
    CC anet.o
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
make[2]: *** [Makefile:334: adlist.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Makefile:334: quicklist.o] Error 1
make[2]: *** [Makefile:334: anet.o] Error 1
make[2]: *** [Makefile:334: ae.o] Error 1
make[1]: *** [Makefile:6: all] Error 2
command failed: { make -j `/Users/michaelmasouras/src/RediSearch2/deps/readies/bin/nproc`  BUILD_TLS=yes; } >/var/folders/qm/m56dtbfd3_v1m274_wxgd4x40000gn/T/tmpJWTTR8 2>&1
command failed: python2 /Users/michaelmasouras/src/RediSearch2/deps/readies/bin/getredis -v 6 --force
make: *** [Makefile:128: setup] Error 1

**Comment by dyanakiev** [comment]
Did anyone got it to work? Or i should just install it in linux vm?

**Comment by rafie** [comment]
The symptom described here was fixed long time ago. See #1878 for more recent macOS build trouble (we never run out of them).
