### ISSUE TITLE
How to add PHONETIC Attribute on Create Schema

### ISSUE THREAD

**Issue by hualoqueros** [RediSearch/RediSearch#1607]
I've been looking how to add PHONETIC attribute on creating schema. 

this is my code :
```
sc := redisearch.NewSchema(redisearch.DefaultOptions).
		AddField(redisearch.Field{
		 	Name:     "text",
		 	Type:     redisearch.TextField,
		 	Sortable: true,
		 	Options:  "PHONETIC dm:en",
	       }).
...
```

But im facing this error: 
`Error on TextField serialization`

after found this line code:

```
func serializeField(f Field, args redis.Args) (argsOut redis.Args, err error) {
	argsOut = args
	switch f.Type {
	case TextField:
		argsOut = append(argsOut, f.Name, "TEXT")
		if f.Options != nil {
			opts, ok := f.Options.(TextFieldOptions)
			if !ok {
				err = fmt.Errorf("Error on TextField serialization")
				return
			}
...
```
i know the root cause is `Options:  "PHONETIC dm:en"`

and, Option for TextField attribute is only `Weight` `Sortable` `NoStem` and `NoIndex`. there's no PHONETIC here
```
type TextFieldOptions struct {
	Weight   float32
	Sortable bool
	NoStem   bool
	NoIndex  bool
}
```

so is it possible to add phonetic attribute on creating schema?

Many Thanks.

**Comment by ashtul** [comment]
@hualoqueros 
Please post the issue on the [redisearch-go](https://github.com/RediSearch/redisearch-go) client repo.

**Comment by ashtul** [comment]
Opened issue RediSearch/redisearch-go#87
