### ISSUE TITLE
Allow querying for exact matches on numeric fields without a range

### ISSUE THREAD

**Issue by abrookins** [RediSearch/RediSearch#1620]
Developer experience would be better if we could search for exact matches on a numeric field without using a range. In other words, this query should work -- `registered_on` being a NUMERIC field:

```
127.0.0.1:6379> ft.search user-idx "@registered_on:1601510400"
```

But it doesn't, currently. It requires a range:

```
127.0.0.1:6379> ft.search user-idx "@registered_on:[1601510400 1601510400]"
1) (integer) 2
2) "users:user:1"
3) 1) "first_name"
   2) "Andrew"
   3) "last_name"
   4) "B."
   5) "registered_on"
   6) "1601510400"
4) "users:user:2"
5) 1) "first_name"
   2) "Justin"
   3) "last_name"
   4) "C."
   5) "registered_on"
   6) "1601510400"
```

**Comment by kkmuffme** [comment]
+1 from me, as this is unintuitive/unexpected, which means there will be questions/issues popping up for it

**Comment by ashtul** [comment]
There a PR already that adds this feature. 
Cheers

**Comment by ashtul** [comment]
This sugarcoating syntax will not be implemented for the moment.

**Comment by ashtul** [comment]
Similar to #181
