### ISSUE TITLE
static host problems

### ISSUE THREAD

**Issue by subrat00000** [RediSearch/RediSearch#1645]
in client.py and auto_comple.py there is a function `def __init__(self, key, host='localhost', port=6379, conn = None, password=None):`.
In localhost there should be the value that is given by the user

**Comment by gkorland** [comment]
@subrat00000 such question probably fits https://github.com/RediSearch/RediSearch-py better 
But, I'm not sure I get the issue, `host` is a named optional argument, `localhost` is the default value in case you don't pass your own value.

**Comment by subrat00000** [comment]
i am currently working on dockerized redisearch from docker hub. there i have to use my host address that the docker-compose decided.`localhost` will not work their. Python redisearch client is giving error -`redis.exceptions.ConnectionError: Error 99 connecting to localhost:6379. Cannot assign requested address
`

**Comment by subrat00000** [comment]
I have not see the code properly
