### ISSUE TITLE
SUGGET MAX is unstable

### ISSUE THREAD

**Issue by TobyHFerguson** [RediSearch/RediSearch#1650]
When I use`SUGGET` with MAX then, depending on the size of MAX, different items < MAX might be returned. In other words, `SUGGET` is unstable with respect to MAX.

In the examples below I've truncated the output to focus on the earliest part of the output where the anomaly is demonstrated.

Look at the fourth item here, with a MAX 10:
`
>> ft.sugget ms:search:suggest:movies 'the ' max 10 withscores
 1) "The Gift"
 2) "2.2360680103302002"
 3) "The Guest"
 4) "2.0412414073944092"
 5) "The Giver"
 6) "2.0412414073944092"
 7) "The Gambler"
 8) "1.7677669525146484"
`
So the fourth item is 'The Gambler', with a score of 1.7677 ...

But if I change MAX to 15 then suddenly 'The Gambler' is replaced by 'The Intern', with a higher score. Why wasn't 'The Intern' returned in the first call? MAX should only change the number returned, not the universe of things to be returned!

`
>> ft.sugget ms:search:suggest:movies 'the ' max 15 withscores
 1) "The Gift"
 2) "2.2360680103302002"
 3) "The Guest"
 4) "2.0412414073944092"
 5) "The Giver"
 6) "2.0412414073944092"
 7) "The Intern"
 8) "1.8898223638534546"
`

**Comment by ashtul** [comment]
@TobyHFerguson , I have created a test for `SUGGET` with different 'MAX' values, and I get persistent results.
Can you please add details about your server settings and data?
Redis version and RediSearch version.

**Comment by TobyHFerguson** [comment]
@ashtul I'm using the Docker image redislabs/redisearch:2.0.3 in a larger, docker-compose, java based application. 

The issue has changed slightly (given that I didn't record exactly how to build the previous system I'm afraid I can't reproduce the exact original issue). What I see now is that although there's more stability the 'max' command is unstable in the sense that, for a given score, a max of 10 is not a prefix to a max 15:

```
>> ft.sugget ms:search:suggest:movies 'the ' max 10 withscores

 1) "The Boy"
 2) "1"
 3) "The Fly"
 4) "1"
 5) "The BFG"
 6) "1"
 7) "The Loft"
 8) "0.89442718029022217"
 9) "The DUFF"
10) "0.89442718029022217"
11) "The Mask"
12) "0.89442718029022217"
13) "The Gift"
14) "0.89442718029022217"
15) "The Boat"
16) "0.89442718029022217"
17) "The Drop"
18) "0.89442718029022217"
19) "The Rock"
20) "0.89442718029022217"
>> ft.sugget ms:search:suggest:movies 'the ' max 15 withscores

 1) "The Boy"
 2) "1"
 3) "The Fly"
 4) "1"
 5) "The BFG"
 6) "1"
 7) "The Boat"
 8) "0.89442718029022217"
 9) "The Rock"
10) "0.89442718029022217"
11) "The Gift"
12) "0.89442718029022217"
```
I think it'd be reasonable to expect the entries with a score of 0.89442718029022217 to be stable even if they weren't in some specific order (of course it'd be preferable if they were in alphabetical order!). So there's still a problem, but its a lesser one than the original issue was about. 

The way to reproduce this with the exact build I'm using is:

```
git clone https://github.com/TobyHFerguson/redis-microservices-demo.git
cd redis-microservices-demo
git checkout dfa1776
mvn clean package
docker-compose up --build -d
```

- Connect to the application at http://localhost/services and start the services
- Go to RedisInsight at http://localhost:8001 and configure the database:
  - Name: redis-service
  - Host: redis-service
  - Port: 6379

Then you 
I'd be happy to jump on a call and show you if need be.
