### ISSUE TITLE
Numeric field queries  bug

### ISSUE THREAD

**Issue by tongpipi** [RediSearch/RediSearch#1665]
![image](https://user-images.githubusercontent.com/49895714/99367637-2c48d000-28f5-11eb-91ed-65d3000530b4.png)

**Comment by tongpipi** [comment]
![image](https://user-images.githubusercontent.com/49895714/99367705-45518100-28f5-11eb-9507-945e79e6de1d.png)

**Comment by tongpipi** [comment]
same search condistion . just change execution_price:[38.299, 38.3]  to  execution_price:[38.3, 38.3]

**Comment by ashtul** [comment]
Related #1657

**Comment by new-commer** [comment]
@Related Thanks. We run into this issue in redis5( redisearch 1.6.14). It will works in redis5 too?

**Comment by ashtul** [comment]
Fixed by #1657
