### ISSUE TITLE
If text fields is chinese mixed english or text fields is english mixed number , search result is wrong?

### ISSUE THREAD

**Issue by 23233** [RediSearch/RediSearch#1670]
### Create index:
```
ft.create tt on hash prefix 1 tst: language chinese schema title text sortable desc text sortable
```

### Add row:
```
hset tst:001 title "中文包含英文的句子 chinese mixed english" desc "tt1800" 
hset tst:002 title "如果你是一只火鸟,我一定是那火苗 fire flame" desc "testnumber1800"
hset tst:003 title "感谢 thanks" desc  "857857nnn"
```
### Run search:
![image](https://user-images.githubusercontent.com/12870070/99902436-cc896500-2cf8-11eb-91b9-9607c7797a04.png)
![image](https://user-images.githubusercontent.com/12870070/99902457-f3e03200-2cf8-11eb-945c-fd860ac474f9.png)

### Question:
* why search match result is 0? 
* if search tt why not match tst:001 ?
* if search nnn why not match tst:003?
* if search 火鸟 why not match tst:002?

### Want:
* search 火鸟 match tst:002
* search tt match tst:001
* search nnn match tst:003

**Comment by gkorland** [comment]
@23233 it seems like there might be a little confusion here `%` in RediSearch query syntax is used for Fuzzy matching see: https://oss.redislabs.com/redisearch/Query_Syntax/#fuzzy_matching

**Comment by 23233** [comment]
I see it , but i don't know user search word , i don't know sometime add LD{1,2,3} , how to get normal search behavior match result ? 
just like : 
user maybe search "火鸟" or search "tt" if i'm fixed use LD1 just "%火鸟%" , search match result is tst:002 , but if user search "tt" , use LD1 match result is not as expected! if fixed use LD2 or LD3 , result match is blurry and not accurate! 
@gkorland  I'm so confused , what should I do ? very thanks ~

**Comment by gkorland** [comment]
What do you mean by LD{1,2,3}? Can you add "fixed" examples with the right syntaxt?

**Comment by 23233** [comment]
### Core just one question , look ↓

![image](https://user-images.githubusercontent.com/12870070/99903726-2d1ca000-2d01-11eb-8756-763e7540e1f9.png)

### How to search nnn , Success match tst:003 ? 

### thanks ~

**Comment by gkorland** [comment]
Are you trying to run `get all dos that containes('nnn')`? 
Notice RediSearch doesn't support contains queries but but only prefix queries.

**Comment by gkorland** [comment]
ref https://github.com/RediSearch/RediSearch/issues/348

**Comment by 23233** [comment]
@gkorland  Thanks ~ Hope add this feature !!
