### ISSUE TITLE
How can break an string camelized?

### ISSUE THREAD

**Issue by catchex** [RediSearch/RediSearch#1773]
Such as, 'RediSearch' can be breaked into 'Redi' and 'Search', I cannot inject an English dictionary into RediSearch.
Too many projects in github, their name are spliced, the RediSearch breaks words by standard English grammar and escaping separators now. For words spliced, RediSearch can't work well.

**Comment by ashtul** [comment]
@catchex Currently, RediSearch does not provide this capability.
Is it possible for you to do it on the client-side?

**Comment by catchex** [comment]
Ok, I have solved it, there is another question now, the text field in a index definition, it may contain two languages, chinese and english, at this time, how can I set language of index definition value.

**Comment by ashtul** [comment]
@catchex May I ask how did you solve it?

As for your next question, RediSearch allows you to define a language per document but not per field in a document.

**Comment by catchex** [comment]
@ashtul It's too simple, I break the camelized string in client-side, and save into RediSearch.

For NO 2, I know that RediSearch is capable, which means I have to detect the language type of the document?

**Comment by ashtul** [comment]
@catchex Yes. If you provide the language before adding the document, you can query for that specific language. By default, RediSearchh assumes your language is English.
