### ISSUE TITLE
Alternative to FT.MGET?

### ISSUE THREAD

**Issue by Nic0S** [RediSearch/RediSearch#1791]
Reading the [documentation](https://oss.redislabs.com/redisearch/Commands/#ftmget), I see that FT.MGET is deprecated, and the recommended replacement is HGETALL.

HGETALL seems fundamentally different, though, in that you can only fetch a single hash. Is the recommendation to just make multiple HGETALL requests (one per hash), or is there something I'm missing?

**Comment by gkorland** [comment]
You should use multi HGETALL, notice using pipeline should yell pretty similar results to FT.MGET with multiple IDs

**Comment by Nic0S** [comment]
Oh right, makes sense. Thank you!

**Comment by timmixell** [comment]
Is this still the preferred/performant way to go? Is a set of pipelined commands faster than `load`'ing fields via `ft.aggregate`?
