### ISSUE TITLE
Load all keys of hash in FT.AGGREGATE query.

### ISSUE THREAD

**Issue by vyj7** [RediSearch/RediSearch#1816]
Currently FT.SEARCH only supports one SORT BY statement. As a workaround, we can use FT.AGGREGATE query but the caveat is I have to add each and every key whose data I wanted.
As a suggestion/enhancement, 
Can we have FT.SEARCH to support multiple sortBy (Fields which are indexed as SORTABLE)?
or Can we load all the keys in FT.AGGREGATE query by using let's say ```LOAD -1```

**Comment by emmanuelkeller** [comment]
in FT.AGGREGATE, we currently have @__key to return the key of the document.
We could add @__all to return every fields/values.

https://oss.redislabs.com/redisearch/Aggregations/#aggregate_request_format

**Comment by emmanuelkeller** [comment]
@vyj7 Please find the link to the issue related to the multiple SORTBY  #1615
(Easier to handle one feature per issue)

**Comment by vyj7** [comment]
@emmanuelkeller  Agreed :-) My view of looking it was to make it a bit closer to SQL query

**Comment by ashtul** [comment]
@vyj7 @emmanuelkeller 
The `-1` approach is good but how about `LOADALL` instead of 'LOAD'?

**Comment by vyj7** [comment]
I am fine with `LOADALL`. 
This will introduce a new KEYWORD which can be avoided if we can do something in `LOAD` which will tell the system to populate all keys and value. 
So the format of `LOAD  number_of_args  keys` can be used something like `LOAD 1 @__allKeys`.

**Comment by ashtul** [comment]
fixed by #2243
