### ISSUE TITLE
Search low-level API Geo support

### ISSUE THREAD

**Issue by swilly22** [RediSearch/RediSearch#1818]
@MeirShpilraien please confirm these two additions

Index a geo point
```
MODULE_API_FUNC(void, RediSearch_DocumentAddFieldGeo)
(RSDoc* d, const char* fieldName, float lat, float lon)
```

Build geo query node
```
MODULE_API_FUNC(RSQNode*, RediSearch_CreateGeoNode)
(RSIndex* sp, const char* field, float origin_lat, float origin_lon, float radius, enum {meter, km, mil, ft});
```

**Comment by ashtul** [comment]
@swilly22 @MeirShpilraien
A float has 23 bits for the value vs. 52 bits in a double. This means we will lose precision (from under a meter to 2-3 meters). Does it worth saving on the doubles?

**Comment by MeirShpilraien** [comment]
@ashtul good point, I agree.
