### ISSUE TITLE
Received SIGUSR1 in child, exiting now

### ISSUE THREAD

**Issue by yukinarit** [RediSearch/RediSearch#1823]
We run `redislabs/redisearch:1.6.14` docker container in Hashicorp Nomad cluster. 

The container keeps printing `17110:signal-handler (1612480421) Received SIGUSR1 in child, exiting now.` almost every second. Is this an expected behaviour or our container setup has something wrong? 🤔 

I also referred: https://github.com/redis/redis/pull/7359

Thank you!

**Comment by gkorland** [comment]
@yukinarit you can ignore these logs, it just indicates that the Search GC fork was running and finished. 
This version of RediSearch docker is based on Redis 6.0.1 on 6.0.9 is was "fixed". 

If it bothers you, you can do one of the followings:
1. Run RediSearch 2.0.x
2. Upgrade the Redis to 6.0.9+

**Comment by yukinarit** [comment]
Thank you! @gkorland  👍
