### ISSUE TITLE
extreme performance degradation for a TAG field vs TEXT NOSTEM field 

### ISSUE THREAD

**Issue by jrots** [RediSearch/RediSearch#1867]
Hi, 

I created 2 indexes: 
first one with a field: themeId tag => idxSearch1
other one with field : themeId text nostem => idxSearch2
both contain +/- 400K entries, 
the query I run matches +/- 4000 entries

I am still running 71167:M 23 Feb 2021 20:03:21.023 * <search> RediSearch version 99.99.99 (Git=v1.99.5-111-g17487693)
but from what I see in the changelogs it were mainly minor fixes since that version. 

Thought from what I read here "TAG" was the way to go for "fast" nostem single word queries,
https://oss.redislabs.com/redisearch/Tags/
but def. not the case in my benchmark. 

`redis-benchmark -n 10000 ft.search idxSearch1 @themeId:{1} limit 0 1 filter dateAdd 1613377546 +inf verbatim nocontent 
`
=> 120.00 requests per second
(used a lower -n total amount here as it would run too long otherwise)

`redis-benchmark -n 1000000 ft.search idxSearch2 "@themeId:{1}" limit 0 1 filter dateAdd 1613377546 +inf verbatim nocontent
`
=> 17059.03 requests per second

the TEXT field query being 150 times faster.. 
Is this expected behaviour?

**Comment by filipecosta90** [comment]
@jrots, a couple of questions so we can further investigate this:
- is it possible to share an rdb with the data so we can analysis this further?
- have you checked that both queries return valid / with data outputs?
- can you also run the benchmark with the `-e` flag so it outputs errors in case of wrong formatted queries?

**Comment by jrots** [comment]
You were right, my second example had to be the id/ text without the curly braces `{` `}`
in order to get results.. 

```
 redis-benchmark -n 10000 ft.search idxSearch2 "@themeId:1" limit 0 1 filter dateAdd 1613377546 +inf verbatim nocontent
```
slower then tag field now : 
84.02 requests per second

nonetheless still weird that performance is that slow even I strip the query down to the most "bare" representation without filtering etc

`redis-benchmark -n 10000 ft.search idxWikio2 "@themeId:1" verbatim nocontent`
 compared to this initial redisearch post  
https://forum.redislabs.com/t/ann-redisearch-1-0-2/94

where : 14542.37 requests/sec. were easily get.  .

**Comment by ashtul** [comment]
@jrots The error you received meant the query was not fully parsed. Therefore, the command returns very quickly w/o creating the iterators, pulling the inverted indexing, and iterating them.
