### ISSUE TITLE
Offical Website Translation

### ISSUE THREAD

**Issue by jlcoding** [RediSearch/RediSearch#1901]
If you guys need someone to translate your offical website to Chinese. Please contact me.

**Comment by gkorland** [comment]
Thanks for the offer, but we didn't consider it.
Obviously a pull request will be welcomed.

**Comment by jlcoding** [comment]
> Thanks for the offer, but we didn't consider it.
> Obviously a pull request will be welcomed.

cool。 thanks for your response
