### ISSUE TITLE
How to get index data from redis

### ISSUE THREAD

**Issue by rogan0** [RediSearch/RediSearch#1915]
How to get index data from redis

**Comment by MeirShpilraien** [comment]
Do you mean FT.INFO ?
https://oss.redislabs.com/redisearch/Commands/#ftinfo

**Comment by rogan0** [comment]
thanks, it works, I can get the index structrue,
 and I want to produce my own index data,  and put into redis. can you give me some advice?

**Comment by MeirShpilraien** [comment]
I am not sure what you want to acheive, can you share some more information?

**Comment by rogan0** [comment]
at indexer.c, I find this function to create document index, index stuctrue  at DocumentIndexer is a queue, and I want to insert an DocumentIndexer item by myself, an it can be used by  FT.search, what I need to do ?,  below is the code I found in the source.
////////////////////////////////////////////////////////////////////////////////
504  ////////////////////////////////////////////////////////////////////////////////
505  /// Multiple Indexers                                                        ///
506  ////////////////////////////////////////////////////////////////////////////////
507  ////////////////////////////////////////////////////////////////////////////////
508  
509  /**
510   * Each index (i.e. IndexSpec) will have its own dedicated indexing thread.
511   * This is because documents only need to be indexed in order with respect
512   * to their document IDs, and the ID namespace is only unique among a given
513   * index.
514   *
515   * Separating background threads also greatly simplifies the work of merging
516   * or folding indexing and document ID assignment, as it can be assumed that
517   * every item within the document ID belongs to the same index.
518   */
519  
520  // Creates a new DocumentIndexer. This initializes the structure and starts the
521  // thread. This does not insert it into the list of threads, though
522  // todo: remove the withIndexThread var once we switch to threadpool
523  DocumentIndexer *NewIndexer(IndexSpec *spec) {
524    DocumentIndexer *indexer = rm_calloc(1, sizeof(*indexer));
525    indexer->refcount = 1;
526    if ((spec->flags & Index_Temporary) || RSGlobalConfig.concurrentMode == 0) {
527      indexer->options |= INDEXER_THREADLESS;
528    }
529    indexer->head = indexer->tail = NULL;
530  
531    BlkAlloc_Init(&indexer->alloc);
532    static const KHTableProcs procs = {
533        .Alloc = mergedAlloc, .Compare = mergedCompare, .Hash = mergedHash};
534    KHTable_Init(&indexer->mergeHt, &procs, &indexer->alloc, 4096);
535  
536    if (!(indexer->options & INDEXER_THREADLESS)) {
537      pthread_cond_init(&indexer->cond, NULL);
538      pthread_mutex_init(&indexer->lock, NULL);
539      pthread_create(&indexer->thr, NULL, Indexer_Run, indexer);
540      pthread_detach(indexer->thr);
541    }
542  
543    indexer->next = NULL;
544    indexer->redisCtx = RedisModule_GetThreadSafeContext(NULL);
545    indexer->specId = spec->uniqueId;
546    indexer->specKeyName =
547        RedisModule_CreateStringPrintf(indexer->redisCtx, INDEX_SPEC_KEY_FMT, spec->name);
548  
549    ConcurrentSearchCtx_InitSingle(&indexer->concCtx, indexer->redisCtx, reopenCb);
550    return indexer;
551  }



indexer.h
===================================
typedef struct DocumentIndexer {
18    RSAddDocumentCtx *head;          // first item in the queue
19    RSAddDocumentCtx *tail;          // last item in the queue
20    pthread_mutex_t lock;            // lock - only used when adding or removing items from the queue
21    pthread_cond_t cond;             // condition - used to wait on items added to the queue
22    size_t size;                     // number of items in the queue
23    ConcurrentSearchCtx concCtx;     // GIL locking. This is repopulated with the relevant key data
24    RedisModuleCtx *redisCtx;        // Context for keeping the spec key
25    RedisModuleString *specKeyName;  // Cached, used for opening/closing the spec key.
26    uint64_t specId;                 // Unique spec ID. Used to verify we haven't been replaced
27    int isDbSelected;
28    struct DocumentIndexer *next;  // Next structure in the indexer list
29    KHTable mergeHt;               // Hashtable and block allocator for merging
30    BlkAlloc alloc;
31    int options;
32    pthread_t thr;
33    size_t refcount;
34  } DocumentIndexer;

**Comment by MeirShpilraien** [comment]
So you want to index other datatypes and not hashes? what datatypes do you want to index?

**Comment by rogan0** [comment]
I want to add a command to import  InvertedIndex  data, I find two function , invoke this can add invertedIndex from outside?

inverted_index.c
=====
```c
/** Write a forward-index entry to the index */
461  size_t InvertedIndex_WriteForwardIndexEntry(InvertedIndex *idx, IndexEncoder encoder,
462                                              ForwardIndexEntry *ent) {
463    RSIndexResult rec = {.type = RSResultType_Term,
464                         .docId = ent->docId,
465                         .offsetsSz = VVW_GetByteLength(ent->vw),
466                         .freq = ent->freq,
467                         .fieldMask = ent->fieldMask};
468  
469    rec.term.term = NULL;
470    if (ent->vw) {
471      rec.term.offsets.data = VVW_GetByteData(ent->vw);
472      rec.term.offsets.len = VVW_GetByteLength(ent->vw);
473    }
474    return InvertedIndex_WriteEntryGeneric(idx, encoder, ent->docId, &rec);
475  }
```

```c
InvertedIndex *NewInvertedIndex(IndexFlags flags, int initBlock) {
57    InvertedIndex *idx = rm_malloc(sizeof(InvertedIndex));
58    idx->blocks = NULL;
59    idx->size = 0;
60    idx->lastId = 0;
61    idx->gcMarker = 0;
62    idx->flags = flags;
63    idx->numDocs = 0;
64    if (initBlock) {
65      InvertedIndex_AddBlock(idx, 0);
66    }
67    return idx;
68  }
```
```c
typedef struct InvertedIndex {
30    IndexBlock *blocks;
31    uint32_t size;
32    IndexFlags flags;
33    t_docId lastId;
34    uint32_t numDocs;
35    uint32_t gcMarker;
36  } InvertedIndex;
```

**Comment by MeirShpilraien** [comment]
Why not add the data as hashes to Redis and let RediSearch index them?

**Comment by rogan0** [comment]
because index logic is our company`s protected code , it  Always change，and we must keep it in secret
