### ISSUE TITLE
Death by limit

### ISSUE THREAD

**Issue by rafie** [RediSearch/RediSearch#1932]
```
127.0.0.1:20000> FT.CREATE idx SCHEMA t TEXT
OK
127.0.0.1:20000> FT.AGGREGATE idx * LIMIT 100000000000000000 100000000000 SORTBY 1 @t
Error: Connection reset by peer
```
a.k.a MOD-1063

**Comment by ashtul** [comment]
We can check if offset

**Comment by ashtul** [comment]
Failure is due to result in heap allocation of a huge chunk of memory.
We can check if the offset is larger than the number of docs in the index and, in this case, return `0 results`.

**Comment by MeirShpilraien** [comment]
Why not limit it with MAXAGGREGATERESULTS?

**Comment by rafie** [comment]
@MeirShpilraien `RPSorter_NewByFields` is naturally linked to aggregation (via `getArrangeRP`), so `MAXAGGREGATERESULTS` is the natural choice. However, it is set by default to no limit, so it won't solve the death problem unless configured to a real limit.
