### ISSUE TITLE
Prefix queries not working for just 1 character 

### ISSUE THREAD

**Issue by Taymindis** [RediSearch/RediSearch#1950]
When i key this search, but not found
```bash

127.0.0.1:6379> FT.SEARCH myIdx "@firstname:A*"
1) (integer) 0

```

if I start with 2 character ahead, it show

```bash
127.0.0.1:6379> FT.SEARCH myIdx "@firstname:As*"
1) (integer) 2
2) "cust:1001"
3) 1) "lastname"
   2) "Asdasd"
   3) "firstname"
   4) "asdasdsa"
   5) "date_start"
   6) "1618451733467"
   7) "date_end"
   8) "1618451833467"
4) "cust:1002"
5) 1) "lastname"
   2) "12312312312"
   3) "firstname"
   4) "asdasdsa"
   5) "date_start"
   6) "1618451733467"
   7) "date_end"
   8) "1618451833467"
```

**Comment by MeirShpilraien** [comment]
Notice that that we have MINPREFIX configuration value (https://oss.redislabs.com/redisearch/Configuring/) which is 2 by default. You can set it to 1 if you want but as the documentation state it might hurt the performance.

**Comment by emmanuelkeller** [comment]
By default, the minimum size of a prefix is 2 characters.

But you can change this value to 1:

    FT.CONFIG SET MINPREFIX 1

https://oss.redislabs.com/redisearch/Query_Syntax/#prefix_matching

I invite you to have a look at MAXEXPANSIONS, as it can also restrict the results

**Comment by Taymindis** [comment]
@emmanuelkeller  @MeirShpilraien  verified and thanks!
