### ISSUE TITLE
FT search result is confusion

### ISSUE THREAD

**Issue by h1100e** [RediSearch/RediSearch#1961]
I want to search something in index1,but it will give me all indexes result.Is something wrong?

**Comment by gkorland** [comment]
@h1100e can you please share how did you define the index or better a short recreation of the issue?

**Comment by h1100e** [comment]
ok,
create:
FT.CREATE article ON hash SCHEMA title TEXT WEIGHT 5 SORTABLE content TEXT art_id NUMERIC keywords TEXT is_hot NUMERIC is_new NUMERIC create_time NUMERIC source TEXT abstract TEXT
search:
FT.SEARCH atricle "hello" limit 10

**Comment by emmanuelkeller** [comment]
@h1100e It works on my side. I see there is a type in the index name: ```atricle``` vs ```article```

Notice the limit takes 2 parameters

```
HMSET doc title "hello"
FT.SEARCH article "hello" limit 0 10
1) (integer) 1
2) "doc"
3) 1) "title"
   2) "hello"
```

**Comment by h1100e** [comment]
Hello .Sorry atricle is my spelling mistake,but it's not the emphasis. And the limit statement is also like this.
If I create two indexes ，for example atricle1,atricle2.They all have two docs with "hello x",  then FT.SEARCH article1 "hello" limit 0 10,I get 4 docs , not 2.This confuses me.My redisearch version is 1.9. There was a problem with 2.0 at the time, so I downgraded it.

**Comment by emmanuelkeller** [comment]
When you create an index, unless you are using the PREFIX parameters, all the hashes are indexed.

```
HMSET doc1 title "hello"
HMSET doc2 title "hello"
HMSET doc3 title "hello"
HMSET doc4 title "hello"
FT.CREATE articles1 ON hash SCHEMA title TEXT
FT.CREATE articles2 ON hash SCHEMA title TEXT
```

In this case, both indexes (article1 and article2) are indexing the 4 documents. 

```
FT.SEARCH articles1 *
1) (integer) 4
2) "doc4"
3) 1) "title"
   2) "hello"
4) "doc1"
5) 1) "title"
   2) "hello"
6) "doc2"
7) 1) "title"
   2) "hello"
8) "doc3"
9) 1) "title"
   2) "hello"
```

```
FT.SEARCH articles2 *
1) (integer) 4
2) "doc4"
3) 1) "title"
   2) "hello"
4) "doc1"
5) 1) "title"
   2) "hello"
6) "doc2"
7) 1) "title"
   2) "hello"
8) "doc3"
9) 1) "title"
   2) "hello"
```

In this case, both indexes (article1 and article2) are indexing the 4 documents. 

If you want distribute your document into several indexes, you have to use the PREFIX parameter. A good practice with REDIS is to use the colon pattern for your keys. Example:

```
HMSET "art1:doc1" title "hello"
HMSET "art1:doc2" title "hello"
HMSET "art2:doc3" title "hello"
HMSET "art2:doc4" title "hello"
```

Now we can filter the indexing by using the prefixes ```art1:``` and ```art2:```:
```
FT.CREATE articles1 ON hash PREFIX 1 "art1:" SCHEMA title TEXT
FT.CREATE articles2 ON hash PREFIX 1 "art2:"  SCHEMA title TEXT
```

And each index contains only two documents:

```
FT.SEARCH articles1 *
1) (integer) 2
2) "art1:doc2"
3) 1) "title"
   2) "hello"
4) "art1:doc1"
5) 1) "title"
   2) "hello"
```

```
FT.SEARCH articles2 *
1) (integer) 2
2) "art2:doc3"
3) 1) "title"
   2) "hello"
4) "art2:doc4"
5) 1) "title"
   2) "hello"
```

**Comment by h1100e** [comment]
Oh thank you very much.It fix my problem.You are so greate.I hope it can be updated to the document.
