### ISSUE TITLE
inconsistent result using sortby

### ISSUE THREAD

**Issue by trimbilrepo** [RediSearch/RediSearch#1966]
Hi,
I found there is inconsistent total records found on search the index with and without sortby.

`127.0.0.1:6379> ft.search myIndex "@unix:[1618938000000 1619024399000]" limit 0 1`
`1) (integer) 1496299`
`2) (empty array)`
`(0.50s)`

`127.0.0.1:6379> ft.search myIndex "@unix:[1618938000000 1619024399000]" sortby unix desc limit 0 1`
`1) (integer) 852199`
`2) (empty array)`
`(0.50s)`

additionally, I can't understand why redis return empty array when there is record that have unix timestamp between 1618938000000 1619024399000
`127.0.0.1:6379> ft.search myIndex "@unix:[1618992120000 1618992128174]" limit 0 1`
`1) (integer) 3`
`2) "userid:1384779469626363907"`
`3)  1) "user_id"`
    `2) "1384779469626363907"`
    `3) "unix"`
   ` 4) "1618992128174"`
   ` 5) "device"`
    `6) "Android"`

**Comment by emmanuelkeller** [comment]
@trimbilrepo Currently investigating this issue. Which version of RediSearch are you using ?

**Comment by trimbilrepo** [comment]
@emmanuelkeller I don't know how get redissearch version;
however I clone and build from master in the beginning of this month.
I used redis version 6.2.2

**Comment by ashtul** [comment]
@trimbilrepo I believe you ran into timeout and therefore you got the number of results so far but no results.
You can try enlarge the timeout limit or change the [ON_TIMEOUT policy](https://oss.redis.com/redisearch/Configuring/#on_timeout_policy) to `fail`.
