### ISSUE TITLE
Wrong result on slop query 

### ISSUE THREAD

**Issue by gkorland** [RediSearch/RediSearch#1986]
With a slop set to 0, this query shouldn't return any document

```
127.0.0.1:6379> FT.CREATE idx ON HASH SCHEMA label TEXT
OK
127.0.0.1:6379> HSET doc:1 label "Hello the world"
(integer) 1
127.0.0.1:6379> FT.SEARCH idx '(Hello world) => {$slop: 0}'
1) (integer) 1
``` 

```
======================================================================
FAIL: testClient (__main__.RedisSearchTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/circleci/repo/test/test.py", line 169, in testClient
    self.assertEqual(3,client.search(Query('henry king').slop(0).in_order()).total)
AssertionError: 3 != 52
```
https://app.circleci.com/pipelines/github/RediSearch/redisearch-py/654/workflows/7dcd6c25-6c3e-44ec-8eb5-cef51f72eda0/jobs/1325

**Comment by MeirShpilraien** [comment]
Introduced with this optimization: https://github.com/RediSearch/RediSearch/pull/1881
We are sorting the intersect iterator so we basically changing the order by which the query was performed.
I tried with one commit before this optimization and the tests pass.
@ashtul FYI

**Comment by ashtul** [comment]
@gkorland #1994 would fix the failure on redisearch-py.
The upper example should return a result since `the` is a stopword.
