### ISSUE TITLE
Feature - min score / loss of score on sort

### ISSUE THREAD

**Issue by ficus** [RediSearch/RediSearch#1988]
Hi,

I'm trying to come up with the best way to handle site search. I was starting to lean towards something like this `"((quick brown fox) => {$weight: 3.0}|(quick|brown|fox) => {$weight: 1.0})"`.

This is trying to strike a balance between returning good matches and avoiding returning too few results. This lead me to look at how I could set a min score threshold for the query. Looking at the code it seems this concept might exist but there is no way to pass that value. I am hoping the idea is to eventually be able to pass that with the `SCORER` argument of a query?

This would also make a search like `"~guitar ~electric"` much more useful as you could avoid it returning all indexed documents as it does now.

I am also trying to understand why all scores have a value of zero when a `SORTBY` is added to the query.

Thanks!

**Comment by MeirShpilraien** [comment]
@ficus I am not sure if this is a question or a feature request, Today we can not specify to return values that greater a given score. I guess this is what you are asking right?

**Comment by ficus** [comment]
Hi @MeirShpilraien, Yes. I'd say the `minscore` behavior is a feature request. Again, looking at the `RegisterScorerFunciton` it seems like maybe that is in the works. And then I did just throw a question in there also about why score is not returned when using `SORTBY`.

**Comment by MeirShpilraien** [comment]
@ficus you are right, seems like a regression on 1.6 and 2.0, when using sortby + withscores the score is not calculated even though it should:
```
not connected> FT.CREATE idx SCHEMA t TEXT
OK
127.0.0.1:6379> ft.add idx doc1 1.0 FIELDS  t foo1
OK
127.0.0.1:6379> FT.SEARCH idx foo* WITHSCORES
1) (integer) 1
2) "doc1"
3) "1"
4) 1) "t"
   2) "foo1"
127.0.0.1:6379> FT.SEARCH idx foo* WITHSCORES SORTBY t
1) (integer) 1
2) "doc1"
3) "0"
4) 1) "t"
   2) "foo1"
```

@rafie @emmanuelkeller FYI
