### ISSUE TITLE
Recent release 2.0.7?

### ISSUE THREAD

**Issue by osokin** [RediSearch/RediSearch#1992]
The https://github.com/RediSearch/RediSearch/ shows the recent release is 2.0.7, what's weird.

Also, it seems like 18 hours ago recent releases 2.0.7 and 2.0.8 have been touched somehow and that's probably a reason why the order of releases has changed.

Could you take a look on that.

Thanks.

**Comment by rafie** [comment]
@osokin Hello Sergey, thank you for you diligence. Version 2.0.7 was skipped at the time and we eventually decided to make it available for the good order of things. Version 2.0.8 is the latest release (contrary to how Github precieves it), and it's the one RediSearch 2.0 users should be using. Docker images were correspondingly updated.
всего доброго! :-)

**Comment by osokin** [comment]
> @osokin Hello Sergey, thank you for you diligence. Version 2.0.7 was skipped at the time and we eventually decided to make it available for the good order of things. Version 2.0.8 is the latest release (contrary to how Github preceives it), and it's the one RediSearch 2.0 users should be using. Docker images were correspondingly updated.
> всего доброго! :-)

Thanks for your reply @rafie but it's still unclear why GH shows 2.0.7 as the latest one.

**Comment by rafie** [comment]
It's a known issue in GH, that it is sometimes impossible to control how released versions are presented, and GH will not allow one to explicitly set which version is latest. We're about to release v2.0.9, which will fix this inconvenience.
