### ISSUE TITLE
query with two wildcards gives no result

### ISSUE THREAD

**Issue by sergey-mm** [RediSearch/RediSearch#2008]
Create an index with two TEXT fields
Add document
Try to use wildcard search on both fields

**Expected:** wildcard works for both fields

**Actual:** wildcard works only for first field

```
FT.CREATE myIdx ON HASH PREFIX 1 doc: SCHEMA foo TEXT bar TEXT

hset doc:1 foo "foo" bar "abcd"

FT.SEARCH myIdx (@foo:foo*|@bar:bar*)
1) (integer) 1
2) "doc:1"
3) 1) "foo"
   2) "foo"
   3) "bar"
   4) "abcd"

FT.SEARCH myIdx (@bar:bar*|@foo:foo*)
1) (integer) 0
```

**Comment by gkorland** [comment]
Thanks for reporting, it seems like a bug in the parser.
```
127.0.0.1:6379> FT.EXPLAIN myIdx (@bar:bar*|@foo:foo*)
"@bar:UNION {\n  @bar:PREFIX{bar*}\n  @NULL:PREFIX{foo*}\n}\n"
```

**Comment by emmanuelkeller** [comment]
As a workaround, and to avoid any ambiguity, you can enclose each sub query into parenthesis:

``` 
FT.EXPLAIN idx "(@bar:bar*)|(@foo:foo*)"
"UNION {\n  @bar:PREFIX{bar*}\n  @foo:PREFIX{foo*}\n}\n"
127.0.0.1:6379> FT.SEARCH idx "(@bar:bar*)|(@foo:foo*)"
1) (integer) 1
2) "doc:1"
3) 1) "foo"
   2) "foo"
   3) "bar"
   4) "abcd"
```

We keep this issue open, it is still a parser bug

**Comment by ashtul** [comment]
@sergey-mm 
The bug in the parser is when it tries to parse a token as a modifier (field). The correct way is, as @emmanuelkeller wrote above, to use parenthesis so the query should look like `(@bar:bar*)|(@foo:foo*)
We have a bug in the error handling mechanism, but for now, you can use RediSearch after you fix your query..`
