### ISSUE TITLE
Can we remove all the documents from a particular index in Redisearch?

### ISSUE THREAD

**Issue by chaitradalawai** [RediSearch/RediSearch#2023]

**Comment by K-Jo** [comment]
@chaitradalawai we can, but it would also delete the index itself.  
https://oss.redislabs.com/redisearch/Commands/#ftdropindex with the `DD` option (Delete Documents)

**Comment by chaitradalawai** [comment]
@K-Jo I want to keep the index and remove the documents only, is it possible?

**Comment by ashtul** [comment]
@chaitradalawai, currently we do not plan to add this functionality.
Similar #1640.
