### ISSUE TITLE
Upgrading from 1.99.3 to 2.0.9 resulting in empty index

### ISSUE THREAD

**Issue by deresatom** [RediSearch/RediSearch#2046]
Hello,

I am trying to upgrade my older (RediSearch version _1.99.3 (Git=v1.99.2-11-g525eda2c)_ index to the latest _2.0.9_ version

Build steps I followed:

1.  git clone --recursive https://github.com/RediSearch/RediSearch.git
2.  cd RediSearch
3.  sudo make setup
4.  make build

I followed the upgrade process from [Upgrade to 2.0](https://oss.redislabs.com/redisearch/Upgrade_to_2.0/)

The interesting thing is that when I start _Redis 6.2.4_ I get the following log:

My loadmodule line is: 

`loadmodule /etc/redis/redisearch.so MINPREFIX 1 UPGRADE_INDEX myIndex PREFIX 1 id:`

```
3220:M 06 Jun 2021 16:11:27.881 * <search> RediSearch version 99.99.99 (Git=v1.99.5-202-gf67e29cb)
3220:M 06 Jun 2021 16:11:27.884 # <search> Index myIndex was defined for upgrade but was not found
```

Redis starts perfectly, but unfortunately I can not query my records.
`ft.info myIndex` tells me that `num_records` is 0. _(According to RedisInsight, the saved records are there though)_

I tried `FT.DROPINDEX myIndex`, then recreate my index with

```
FT.CREATE myIndex ON HASH STOPWORDS 0 PAYLOAD_FIELD payload_field PREFIX 1 id: SCHEMA a TEXT b TEXT c TEXT d NUMERIC
```

but it is a temporarily solution, because when I restart redis-server _myIndex_ _num_records_ are empty again.

Am I doing something wrong? Is version _99.99.99_ is the same as the latest _2.0.9_ version?

Thanks in advance!

**Comment by deresatom** [comment]
git clone somehow cached an older RediSearch version and that seems to have caused the issue!

**Comment by gkorland** [comment]
```
    git clone --recursive https://github.com/RediSearch/RediSearch.git
    cd RediSearch
    sudo make setup
    make build
```

Is not getting you 2.0.9 but the code from the master branch.
You need to call `git checkout 2.0.9` after you close the repo.

```
    git clone --recursive https://github.com/RediSearch/RediSearch.git
    cd RediSearch
    git checkout 2.0.9
    sudo make setup
    make build
```

**Comment by MeirShpilraien** [comment]
@deresatom 1.99.3 is not any GA version so we do not guaranty any upgrade from it. That said, I do believe it should work but you do not have to use the instruction of upgrading from 1.0.x version. A normal upgrade should work, this version already contains the index out of the keyspace, and 2.0.9 should just be able to read it without any additional configuration.
Regarding the problem of the empty index after a restart, can you share the full Redis logs?

**Comment by deresatom** [comment]
Hey @gkorland Ohh thank you very much. I followed the [Quick Start](https://oss.redislabs.com/redisearch/Quick_Start/) blindly and it seems I managed to compile the master branch without selecting  v2.0.9 🤣 

Thanks for looking into it @MeirShpilraien. After compiling v2.0.9 the empty index is resolved and I can successfully query my records even after restart!

**Comment by MeirShpilraien** [comment]
Reopen because it might indicate we have an issue with the current master.
@emmanuelkeller @rafie FYI

**Comment by MeirShpilraien** [comment]
@deresatom if you can still share the full log of the run with the master branch it can really help.

**Comment by deresatom** [comment]
Hey, oh alrighty!

Here is my redis-server startup log. Is there any other log I could provide that would be helpful?

I just re-compiled master to reproduce it _(same empty index issue, num_records 0, dropindex, recreate works temporarily as described in my first comment)_:

[redis-server.log](https://github.com/RediSearch/RediSearch/files/6607297/redis-server.log)
