### ISSUE TITLE
Serbian language support

### ISSUE THREAD

**Issue by interlark** [RediSearch/RediSearch#2049]
I see you're using libstemmer for stemming support. But looks like somehow you're missing Serbian language. I found that there were a PR #1727 with Serbian support. Could you add this language too?

**Comment by emmanuelkeller** [comment]
@interlark  Thanks for the issue !

We can take the opportunity upgrade to snowball 2.1 (released in January) https://snowballstem.org

And add the missing languages:
- Armenian
- Serbian    
- Yiddish
