### ISSUE TITLE
Having trouble with a GEO filter. 

### ISSUE THREAD

**Issue by tombatron** [RediSearch/RediSearch#2066]
Hey there everyone, I'm trying to follow along with the documentation at: [Geofilters in query](https://oss.redislabs.com/redisearch/Query_Syntax/#geo_filters_in_query)

The following query:

```
FT.SEARCH zips * @Coordinates:[-87.320330 30.423090 10 mi]
```

Results in:

```
(error) Unknown argument `@Coordinates:[-87.320330` at position 1 for <main>
```

Whereas this query:

```
FT.SEARCH zips * GEOFILTER Coordinates -87.320330 30.423090 10 mi
```

Results in:

![image](https://user-images.githubusercontent.com/119369/121883049-4a39b000-ccdf-11eb-892a-48965e56c7bb.png)

My RediSearch module version is: 20009

The index is defined as:

```
 6)  1) "key_type"
     2) "HASH"
     3) "prefixes"
     4) 1) "zip::"
     5) "language_field"
     6) "__language"
     7) "default_score"
     8) "1"
     9) "score_field"
    10) "__score"
    11) "payload_field"
    12) "__payload"
 7) "fields"
 8) 1) 1) "ZipCode"
       2) "type"
       3) "TEXT"
       4) "WEIGHT"
       5) "1"
    2) 1) "City"
       2) "type"
       3) "TEXT"
       4) "WEIGHT"
       5) "1"
    3) 1) "State"
       2) "type"
       3) "TEXT"
       4) "WEIGHT"
       5) "1"
    4) 1) "Coordinates"
       2) "type"
       3) "GEO"
    5) 1) "TimeZoneOffset"
       2) "type"
       3) "NUMERIC"
    6) 1) "DaylightSavingsFlag"
       2) "type"
       3) "NUMERIC"
```

**Comment by MeirShpilraien** [comment]
@tombatron notice that query should come as one argument inside `""`:
`FT.SEARCH zips * "@Coordinates:[-87.320330 30.423090 10 mi]"`

**Comment by tombatron** [comment]
So would this:

![image](https://user-images.githubusercontent.com/119369/121884970-9259d200-cce1-11eb-9c9b-6c4dc6464f53.png)

Actually be more like?

```
chinese restaurant "@location:[-122.41 37.77 5 km]"
```

**Comment by MeirShpilraien** [comment]
No, this entire string is one query so:
`FT.SEARCH zips "chinese restaurant @location:[-122.41 37.77 5 km]"`

**Comment by emmanuelkeller** [comment]
@tombatron The wildcard query is a special case.

Mixing the wildcard subquery with another subquery it is not allowed:

``` 
 FT.SEARCH zips "@State:{FL} @Coordinates:[-87.320330 30.423090 10 mi]"
1) (integer) 1
2) "doc1"
3) 1) "Coordinates"
   2) "-87.320330 30.423090"
   3) "State"
   4) "FL"
```

```
127.0.0.1:6379> FT.SEARCH zips "* @State:{FL}"
(error) Syntax error at offset 2 near State
127.0.0.1:6379> 
```

``` 
127.0.0.1:6379> FT.SEARCH zips "* @Coordinates:[-87.320330 30.423090 10 mi]"
(error) Syntax error at offset 2 near Coordinates
```

**Comment by tombatron** [comment]
OK cool!

This makes perfect sense. 

Thank you both for your time!
