### ISSUE TITLE
Remove opening and closing quotes when storing TAGS for JSON 

### ISSUE THREAD

**Issue by Mon0Man** [RediSearch/RediSearch#2072]
Hello, currently when creating an index for Tag fields on JSON, the tags are stored with the string quotes: 

![Screenshot (17)](https://user-images.githubusercontent.com/86112502/122925673-11c85080-d335-11eb-970f-7a668c32a227.png)
`ran FT.TAGVALS`

And to query it, that works looks like this: `FT.SEARCH "idx" "@category: {\\\"florane\\-russell\\\"}"`

maybe there is a better way to do this ?

Thanks

edit: 
Steps to reproduce:
```
JSON.SET test:1 '{"category":"sports"}' .
FT.CREATE idx ON JSON PREFIX 1 test: SCHEMA $.category AS category TAG
FT.TAGVALS idx category

FT.SEARCH idx "@category: {sports}"  returns nil
FT.SEARCH "idx" "@category: {\\\"sports\\\"}" returns match
```
I am using docker image: redislabs/redismod:edge

**Comment by ashtul** [comment]
Fixed by #2093
