### ISSUE TITLE
FT.INFO should specify attributes and identifiers for JSON index (instead of fields)

### ISSUE THREAD

**Issue by oshadmi** [RediSearch/RediSearch#2097]
For index `ON JSON`, instead of fields, identifiers and optionally attributes are used (`{identifier} [AS {attribute}]`)
FT.INFO should list them.
Currently only the `AS` attributes are listed (and are shown under category fields).
Need to list the identifiers and also the attributes if they exist.
For example, for such as index:
`ft.create idx ON JSON prefix 1 doc: schema $.f1 AS f1 TEXT $.f2 AS f2 TEXT`
`FT.INFO` includes only `f1` and `f2` and does not include `$.f1` and `$.f2`.

**Comment by oshadmi** [comment]
Suggested info:
```
...
7) identifiers
 8) 1) 1) $.f1
       2) attribute
       3) f1
       4) type
       5) TEXT
       6) WEIGHT
       7) "1"
...
```

**Comment by ashtul** [comment]
@oshadmi I like your suggestion and think we should add `path` as `1)` so we follow `key/value` structure.
@emmanuelkeller WDYT?

**Comment by emmanuelkeller** [comment]
@ashtul  Agree with both, with the following modification:
- `fields` replaced by `attributes` 
- `path` replaced by `identifier` (as it is not a path when using hash)

That should look like this:

```
...
7) attributes
 8)  1)  1) identifier
           2) $.f1
           3) attribute
           4) f1
           5) type
           6) TEXT
           7) WEIGHT
           8) "1"
...
```

**Comment by oshadmi** [comment]
1. `attribute` may be missing (if there is no `AS`)
So there would be `7) attributes` but no `attribute` under it?

2. In previous format, there was no repetition, so if we use 
```
7) identifiers
 8) 1) 1) identifier
       2) $.f1
       3) attribute
       4) f1
```
` 8) 1) 1) identifier` is redundant,
The same way it is not here in 2.0 (first element is already a **field**)
```
...
7) fields
 8) 1) 1) field1
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
    2) 1) field2
       2) type
       3) TEXT
       4) WEIGHT
       5) "1"
...

```

**Comment by ashtul** [comment]
How about...
```
...
 7) fields
 8)   1)   1) identifier
           2) $.f1
           3) attribute
           4) f1
           5) type
           6) TEXT
           7) WEIGHT
           8) "1"
...
```
We can eliminate `attribute` if not used or just repeat it to keep things simple. We can also use `path` and `alias`.
