### ISSUE TITLE
Question: Cluster Support in 1.0

### ISSUE THREAD

**Issue by salt4pommes** [RediSearch/RediSearch#211]
Hi!

Will the final release of 1.0 contain cluster support in opensource-edition?

Thanks you :)

**Comment by dvirsky** [comment]
No, it will remain in the enterprise version only for the foreseeable future. If you'd like to try the enterprise version, let me know. When the version is officially released you could try it for free with up to 4 shards.

**Comment by victorstewart** [comment]
has anything changed on this front, or planned to change?

**Comment by itamarhaber** [comment]
Things stand as they have. Change may come, but I have no pertinent information to share at the moment.

**Comment by victorstewart** [comment]
I'll say a prayer to my open source fairy tonight
