### ISSUE TITLE
Question on stopwords/highlighting

### ISSUE THREAD

**Issue by ghdi** [RediSearch/RediSearch#2122]
Hi,

When using the highlight functionality, shouldn't the stop words that are present in the search query also be highlighted in the results or is there any other way to achieve this?

In the example below, I believe 'Foo' should also be highlighted, because it is part of the search query and part of the result. 

Regards,

Edwin

```
127.0.0.1:6379> ft.create test on hash prefix 1 test: stopwords 1 foo schema name TEXT
OK
127.0.0.1:6379> hset test:1 name 'My Foo Bar'
(integer) 1
127.0.0.1:6379> ft.search test 'my foo bar' highlight 
1) (integer) 1
2) "test:1"
3) 1) "name"
   2) "<b>My</b> Foo <b>Bar</b>"
```

**Comment by ashtul** [comment]
@ghdi, thank you for the question.
A stopword is not indexed and therefore RediSearch does not keep the offset for it. At query, highlighting is based on these offsets. There is no way to achieve this except for removing a word from the stopword list.

**Comment by ghdi** [comment]
Ariel,

Much appreciated and no worries, easily enough achieved on the client side.

Regards,

Edwin

**Comment by ashtul** [comment]
Hallelujah :+1:
