### ISSUE TITLE
Search using index on JSON is failing to find keys with partial content

### ISSUE THREAD

**Issue by oshadmi** [RediSearch/RediSearch#2141]
Compared to index on HASH, which is able to find keys having only a subset of the fields in the schema,
When searching using a JSON index, keys are found only when all schema identifiers exist in the key.
For example, similar to the following HASH key `key1` and to JSON key `key3`, the JSON key `key2` should be retrieved as well by the search on the JSON index:

```
127.0.0.1:6379> ft.create ndxHash ON HASH SCHEMA field1 TEXT field2 TEXT
OK
127.0.0.1:6379> ft.create ndxJson ON JSON SCHEMA $.field1 TEXT $.field2 TEXT
OK
127.0.0.1:6379> hset key1 field1 basta
(integer) 1
127.0.0.1:6379> json.set key2 $ '{"field1":"piu"}'
OK
127.0.0.1:6379> ft.search ndxHash *
1) (integer) 1
2) "key1"
3) 1) "field1"
   2) "basta"
127.0.0.1:6379> ft.search ndxJson *
1) (integer) 0
127.0.0.1:6379> json.set key3 $ '{"field1":"piu", "field2":"sopra"}'
OK
127.0.0.1:6379> ft.search ndxJson *
1) (integer) 1
2) "key3"
3) 1) "$"
   2) "{\"field1\":\"piu\",\"field2\":\"sopra\"}"
127.0.0.1:6379> 
```

**Comment by MR4online** [comment]
realy solved?
I'm still having this issue with redisSearch version 2.2.0 and redisJson 2.2.0 (as well as with the edge versions).

Reversal tested with removing none existing properties from the index -> then I do have the correct amount of results.

**Comment by ashtul** [comment]
@MR4online 2.2.0 does not contain this fix but edge should.
Can you give steps to reproduce this issue?
