### ISSUE TITLE
Add NOSTORE option for SCHEMA fields

### ISSUE THREAD

**Issue by Sembiance** [RediSearch/RediSearch#2173]
I have a DB where each item has several meta fields and 1 'content' field. The content field doesn't need to be stored/retrieved, just indexed. With the removal of NOSAVE support (#1640), it would be great if we could mark particular fields that don't get stored.

I'm thinking something like: `FT.CREATE test SCHEMA content TEXT NOSTORE`
Then you would create a document: `HMSET doc:1 content "Some very long content"`
RediSearch would index `doc:1` but directly after indexing would do `HDEL doc:1 content` to save space.

One question though, when redis persists to disk, do the indexes get saved in the RDB? Or do the indexes get re-created upon reloading an RDB?

If the latter, this wouldn't work because there would no longer be a 'content' field.

If this is doable, I'd be willing to take a stab at implementing it myself, but would love some brief pointers as to which files/methods I would need to modify to support such a feature, especially any 'gotchas' I should be aware of.

**Comment by ashtul** [comment]
@Sembiance 
You hit the nail on its head! The main change from RediSearch 1.6 to 2.0 was, stop persisting the index to the RDB but instead, indexing all hashes as we load them. This is why the `NOSAVE` option was removed and why the `NOSTORE` option cannot be supported.

**Comment by Sembiance** [comment]
Thanks so much for the info ashtul!
