### ISSUE TITLE
NRediSearch Does not support Sortable Tags in Index Definition Schema Object

### ISSUE THREAD

**Issue by dcoopertd** [RediSearch/RediSearch#2187]
When creating a new schema like this:

`var schema = new Schema().AddTagField("TagField", "|") ;`

There is no option to make it sortable.  For example there is no `AddSortableTagField()` method like there is for text fields.  According to https://oss.redis.com/redisearch/1.6/Commands/#ftcreate , tag fields can clearly be sortable.

**Comment by tombatron** [comment]
NRediSearch is a splinter project of StackExchange.Redis. You should open these features here: https://github.com/StackExchange/StackExchange.Redis

**Comment by dcoopertd** [comment]
Thanks
