### ISSUE TITLE
How to ft.search only in a particular index?

### ISSUE THREAD

**Issue by Getsumi3** [RediSearch/RediSearch#2197]
Using latest version from dockerhub (guess it's 2.0.11).

Hello. I'm new to Redis and Redisearch.

**Question**: If I have multiple indexes how do I search data only from selected index?

**Detailed description** of the problem:
I have two indexes: 
- idx:users
- idx:test:small

Both of this indexes have one common field "id_str"
When I perform a search query it returns matches from both indexes:

_Example_:
Query:
`FT.SEARCH idx:test:small 901514466`

_Expected result_:
![image](https://user-images.githubusercontent.com/20124129/130196869-cd83dfb3-34e2-4ddd-85ef-b076bc5ba70b.png)

_Actual result_:
![image](https://user-images.githubusercontent.com/20124129/130198574-1387627a-927d-4beb-802a-3b527aa8b582.png)

Thanks

**Comment by emmanuelkeller** [comment]
How did you create the index ? Are you using the [PREFIX](idx:users) option to filter which hashes are indexed ?

    FT.CREATE idx:users ON HASH PREFIX 1 idx:users: SCHEMA ...

**Comment by Getsumi3** [comment]
> How did you create the index ? Are you using the PREFIX option to filter which hashes are indexed ?
> 
> ```
> FT.CREATE idx:users ON HASH PREFIX 1 idx:users: SCHEMA ...
> ```

No. Looks like I missed PREFIX option when was looking into docs.
`FT.CREATE idx:users SCHEMA ...`

I'll try it with PREFIX option

**Comment by Getsumi3** [comment]
I've changed my code a bit
`FT.CREATE users ON hash PREFIX 1 users: SCHEMA id_str TEXT`

Now FT.SEARCH works as I expected.
Thanks!
