### ISSUE TITLE
redeSearch returns empty result

### ISSUE THREAD

**Issue by lielie976** [RediSearch/RediSearch#2198]
I have a problem that it returns empty when query on the index。why? 
Does someone knows what's the problem?
127.0.0.1:6379> ft.create products:index prefix 1 p: schema pinyin text
OK
127.0.0.1:6379> hset p:1 code 02623HK pinyin "A I D E X I N N E N G Y U A N"
2
127.0.0.1:6379> ft.search products:index @pingyin:"X I N N E N G Y U A N"
0

**Comment by oshadmi** [comment]
Please see this [comment](https://github.com/RediSearch/RediSearch/issues/1950#issuecomment-820275838) in #1950

**Comment by lielie976** [comment]
I think it's not the prefix problem. I want to find the documents that have all the characters——the relationship between characters is and

**Comment by lielie976** [comment]
Is it related to stop words?

**Comment by ashtul** [comment]
The field names in `HSET` and `FT.SEARCH` commands do not match.

**Comment by MeirShpilraien** [comment]
The data is also contains spaces which are tokenized, you need to define the field as tag and not as text...
