### ISSUE TITLE
Searching for blank values

### ISSUE THREAD

**Issue by anderslangballe** [RediSearch/RediSearch#2241]
I have a use case where I would like to filter out documents when a specific field contains blank values. As far as I can tell, this seems to be unsupported by RediSearch, throwing a syntax error with a select string like `"@author:"`. What is the recommended way/best practice to perform these sorts of queries with RediSearch?

**Comment by ashtul** [comment]
@anderslangballe you can use APPLY with the function exists().
https://oss.redis.com/redisearch/Aggregations/#list_of_field_apply_functions

**Comment by ashtul** [comment]
@emmanuelkeller WDYT?

**Comment by anderslangballe** [comment]
Thanks @ashtul, that seems to fit our use case. Closing.
