### ISSUE TITLE
Adding Prefix when creating an Index using Jredisearch

### ISSUE THREAD

**Issue by chaitradalawai** [RediSearch/RediSearch#2249]
I am not sure if this is the right place to ask help regarding Jredisearch, please do guide me if I need to ask in different platform.

I use Jredisearch(com.redislabs:jredisearch:2.0.0) for querying using Redisearch. I want to add a prefix while creating the Index. I am able to add prefix using the below Redisearch command,
FT.CREATE MyIndex ON HASH PREFIX 1 doc: SCHEMA name TEXT

But not able to find options for the same when writing in Java. I use the following code in Java, 
client.createIndex(schema, Client.IndexOptions.defaultOptions());

Could you help me on how do we add Prefix when using Jredisearch?

**Comment by gkorland** [comment]
moved to https://github.com/RediSearch/JRediSearch/issues/166
