### ISSUE TITLE
[v2.2] How to index a JSON list as TAG

### ISSUE THREAD

**Issue by clmno** [RediSearch/RediSearch#2254]
I have a `list of category IDs` in a JSON and I would like to index them as tags.
```
JSON.SET test:dfeb0140-19e6-11ec-b844-8f0ebb85e6b4 . "{\"id\":\"dfeb0140-19e6-11ec-b844-8f0ebb85e6b4\",\"name\":\"Product Name\",\"company_id\":\"dd36b1ba-19e6-11ec-b844-f3ab916d7e05\",\"category_id\":[\"df8b2284-19e6-11ec-b844-5b3f89776eaf\",\"df8bd63e-19e6-11ec-b844-1f15173494d2\"]}"
FT.CREATE idx:test ON JSON PREFIX 1 test: SCHEMA $.name AS name TEXT $.category_id[:] AS category TAG $.company_id AS company TAG

# this works
FT.SEARCH idx:test product

# single element tag works
FT.SEARCH idx:test @company:{dd36b1ba\-19e6\-11ec\-b844\-f3ab916d7e05}

# the first category can be searched
FT.SEARCH idx:test @category:{df8b2284\-19e6\-11ec\-b844\-5b3f89776eaf}

# but not the second
FT.SEARCH idx:test @category:{df8bd63e\-19e6\-11ec\-b844\-1f15173494d2}
```

## Question
1. How to index a JSON list as TAGs

**Comment by ashtul** [comment]
@clmno The category field should get `*` instead of `:`.
Can you try
```
T.CREATE idx ON JSON PREFIX 1 test: SCHEMA $.name AS name TEXT $.category_id[*] AS category TAG $.company_id AS company TAG
```

**Comment by clmno** [comment]
@ashtul No this does not work.

I tried
```
FT.SEARCH idx:test @category:{df8bd63e\-19e6\-11ec\-b844\-1f15173494d2}
```
after updating the index, to get no response
```
1) (integer) 0
```

I even tried listing the tags, **which only gave one**
```
FT.TAGVALS idx:test category
1) "df8b2284-19e6-11ec-b844-5b3f89776eaf"
```

**Comment by ashtul** [comment]
@clmno which version of RediSearch are you using?
Please more I have changed the index name to `idx`.

**Comment by clmno** [comment]
1. Version: Redis:2.2.0 (I believe this is the version with rejson bundled together)
2. Yes I did notice that you used `idx`. I just chaged `:` to `*` in my FT.CREATE command (which creates idx:test)

**Comment by ashtul** [comment]
@clmno The multivalue feature was not introduced in 2.2.0.
Can you please test on the master/edge version?

**Comment by clmno** [comment]
Yes, will test it on `edge` and get back to you

**Comment by clmno** [comment]
It works. I was using a redisearch verison that did not have the mutivalue feature implemented.

Here's a recap

**Question**
1. How to index multiple tags from a JSON list

**Answer**
1. Use the latest version of redisearch
2. Use the `*` operator to get all values in a JSON list when creating an index
```
JSON.SET test:dfeb0140-19e6-11ec-b844-8f0ebb85e6b4 . "{\"id\":\"dfeb0140-19e6-11ec-b844-8f0ebb85e6b4\",\"name\":\"Product Name\",\"company_id\":\"dd36b1ba-19e6-11ec-b844-f3ab916d7e05\",\"category_id\":[\"df8b2284-19e6-11ec-b844-5b3f89776eaf\",\"df8bd63e-19e6-11ec-b844-1f15173494d2\"]}"
FT.CREATE idx:test ON JSON PREFIX 1 test: SCHEMA $.name AS name TEXT $.category_id[*] AS category TAG $.company_id AS company TAG
```
Note that I used `$.category_id[*]` to get all the values in the JSON list and add them to the column `category` which is a TAG.

**Comment by clmno** [comment]
@ashtul 
Do you know when RediSearch + ReJSON will be production ready / or have a release version?

**Comment by emmanuelkeller** [comment]
@clmno The plan (for both RediSearch & RedisJSON is to have a production ready release by the end of October. A release candidate (on both) will be pushed before the end of September.
