### ISSUE TITLE
When using the limit parameter in FT.search, if the offset exceeds the total documents, it will block until it time out.

### ISSUE THREAD

**Issue by uimeet** [RediSearch/RediSearch#2370]
For example:

I have 2 docs in my index, my code below:

`FT.search myindex * LIMIT 10 10`

It's block forever, so what can i do to fix it.

Thanks.

**Comment by emmanuelkeller** [comment]
@uimeet Which version are you using ? This has currently be fixed in v2.2.5

**Comment by uimeet** [comment]
> @uimeet Which version are you using ? This was fixed in [v2.2.5](https://github.com/RediSearch/RediSearch/releases/tag/v2.2.5)

It's clone Master branch code, maybe a week ago.
Glad it was fixed.

Thanks
