### ISSUE TITLE
Is Aggregate TOLIST guarantee at same index of each column? 

### ISSUE THREAD

**Issue by Taymindis** [RediSearch/RediSearch#2396]
![image](https://user-images.githubusercontent.com/14217761/143974302-2289d9a3-180c-43ac-a7fa-bd6f48325955.png)

For the image given above,  
The `orderId` and `comments` fields, I found that they are actually the same indexed for each other which is what i am looking for. I'm just wondering will it be possible to different index poining? 

For example `orderID=>1332` actually should same index with `comments=>hello Drag` , will it be pointing to `comments=>hello Sej` if next query or if data too big?

**Comment by ashtul** [comment]
@Taymindis In your case, you see the values at the same index since we create the list in the order in which the document is processed. But please note, if a value appears several times, the list will return it only once, and then the list will get out of sync.
Cheers
