### ISSUE TITLE
The best way to perform IN query

### ISSUE THREAD

**Issue by Taymindis** [RediSearch/RediSearch#2398]
If the ids contain 1000 data,  The query will be.

```
@fieldId:(1|2|4|........|1000)
```

Is it the best way to do or I missed out some magic part?

**Comment by oshadmi** [comment]
@Taymindis If relevant `fieldId` values are sequential, consider using a range, e.g.,
`@fieldId:[1 1000]`.
In addition, if no text search is required on `fieldId` (no need for stemming etc.), using a TAG for such a field is recommended, e.g.,
`@fieldId:{1|2|...|1000}`

**Comment by Taymindis** [comment]
@gkorland @oshadmi ,

For example I have customer who had ordered more than 1000 items, so let's assumed I able to get the OrderId (It's not sequential) .

So I will need to get the order details by using orderId. So I will use

```
FT.SEARCH "idx/order_details" "@orderId:(ORD_131|ORD_156|.....)" RETURN .....

```

Is it the only way to use it? Or I should alter `orderId` field to TAG as per @oshadmi said?

**Comment by oshadmi** [comment]
@Taymindis Yes, OR-ing the terms is the only way, whether field is `TEXT` or `TAG`, and a recommendation is to use [`TAG`](https://oss.redis.com/redisearch/Tags/) when possible.
