### ISSUE TITLE
RediSearch on arm64 via docker

### ISSUE THREAD

**Issue by amansubhan** [RediSearch/RediSearch#2406]
Is there any docker image or repo for arm64 architecture? If no then what will be the steps to compile and create an image for arm64 servers?

**Comment by rafie** [comment]
Yes, there is: `redisfab/redisearch:master-arm64v8-bionic`

**Comment by amansubhan** [comment]
> Yes, there is: `redisfab/redisearch:master-arm64v8-bionic`

Okay thanks
