### ISSUE TITLE
Aggregate fail with APPLY command

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2450]
using the redislabs/redisearch:latest docker image,
127.0.0.1:6379> FT.CREATE idx SCHEMA title TEXT WEIGHT 5.0 body TEXT price NUMERIC
OK
127.0.0.1:6379> hset item title "hello world" body "lorem ipsum" price 1337
3
127.0.0.1:6379> FT.AGGREGATE idx "hello" APPLY "@price" as k GROUPBY 1 @title REDUCE AVG 1 @k as avgprice
 1
 (error) Value was not found in result (not a hard error)

but when I don't use APPLY , it is ok as below: 
127.0.0.1:6379> FT.AGGREGATE idx "hello" GROUPBY 1 @title REDUCE AVG 1 @price as avgprice
1
title
hello world
avgprice
1337

**Comment by ashtul** [comment]
@chenlizhao FT.AGGREGATE adds a LOADER before a GROUPER therefore, the value is accessible for the grouper but not for the APPLY transformation.
You can check it using `FT.PROFILE`.

```
FT.PROFILE idx AGGREGATE QUERY "hello" APPLY "@price" as k GROUPBY 1 @title REDUCE AVG 1 @k as avgprice
FT.PROFILE idx AGGREGATE QUERY "hello" GROUPBY 1 @title REDUCE AVG 1 @price as avgprice
```

**Comment by chenlizhao** [comment]
@ashtul  so what is the correct way that I can use APPLY?

**Comment by ashtul** [comment]
@chenlizhao You should either make the field `SORTABLE` or 'LOAD` the field value before using `APPLY`.

**Comment by chenlizhao** [comment]
@ashtul load is ok, but sort the field failed as:

127.0.0.1:6379> FT.AGGREGATE idx "hello world" APPLY "@price" as k GROUPBY 1 @title REDUCE AVG 1 @k as avgprice SORTBY 2 @k ASC MAX 10
Property `k` not loaded nor in schema
