### ISSUE TITLE
Unable to search for data with the letter 'a' as a condition

### ISSUE THREAD

**Issue by moniang** [RediSearch/RediSearch#2455]
I don't know how I should describe my problem.
```shell
FT.CREATE testIdx ON JSON SCHEMA $.user.name AS name TEXT
JSON.SET test $ '{"user":{"name":"a"}}'
FT.SEARCH testIdx @name:(a)
JSON.SET test $ '{"user":{"name":"b"}}'
FT.SEARCH testIdx @name:(b)
```
![1](https://user-images.githubusercontent.com/61287199/147648310-ae928e96-5da4-4451-9277-59166d31958c.png)

**Comment by gkorland** [comment]
Please see `Stop words` - https://oss.redis.com/redisearch/Stopwords/

**Comment by moniang** [comment]
> Please see `Stop words` - https://oss.redis.com/redisearch/Stopwords/

Sorry, I didn't bother to read the document.
