### ISSUE TITLE
Not able to provide Alias Name to Schema Identifier in Redis Search

### ISSUE THREAD

**Issue by Kailash-Ramco** [RediSearch/RediSearch#2477]
Hi Team,

I have spinned up a docker container with redislabs/redisearch:latest image, and tried executing the below command

**FT.CREATE idx ON HASH PREFIX 1 blog:post: SCHEMA sku AS sku_text TEXT sku AS sku_tag TAG SORTABLE**

available in the official RediSearch documentation (https://oss.redis.com/redisearch/Commands)

I get the below error

![image](https://user-images.githubusercontent.com/97166966/148212042-cd39c855-b92a-4bf2-a5f7-ffc3091d31a3.png)

Could you please help me out on the same.

Regards,

Kailash

**Comment by gkorland** [comment]
Please try the edge docker: `sudo docker run -p 6379:6379 redislabs/redisearch:edge`

**Comment by Kailash-Ramco** [comment]
Hi @gkorland 

Using the edge docker image resolved the issue, Thanks for your support.
