### ISSUE TITLE
How to index JSON Array

### ISSUE THREAD

**Issue by Tarun-sngh** [RediSearch/RediSearch#2478]
Am trying to create my index on a array of json but it dosen't seem to work any way.
this is my index => 

```javascript
await redisClient.ft.create(`${indexName}:tt`, {
            '$.attributes[*].value': {
                type: SchemaFieldTypes.TEXT,
                AS: 'attributes'
            },
        }, {
            ON: 'JSON',
            PREFIX: 'mobiles:'
        });
```

I also tried => 

```javascript
await redisClient.ft.create(`${indexName}:tt`, {
            '$.attributes[0:].value': {
                type: SchemaFieldTypes.TEXT,
                AS: 'attributes'
            },
        }, {
            ON: 'JSON',
            PREFIX: 'mobiles:'
        });
```

but this also didn't work.

my array of json => 

```javascript
  attributes: [
    { name: 'Brand', value: 'Vivo' },
    { name: 'Color', value: 'Mirror Black' },
    { name: 'Sim Type', value: 'Dual Sim' }
]
```

**Comment by gkorland** [comment]
@Tarun-sngh can you please share the error you get? Which version of the server do you run?

**Comment by Tarun-sngh** [comment]
Am not getting any error, it just dosen't find the document. it gives empty document.

this is how am inserting data => 
await redisClient.json.set(`mobiles:${toInsert.name}`, '.', toInsert );

this is how am searching => 
await redisClient.ft.search(`${indexName}:tt`, `@attributes:${toSearch}`);

the result => 
{ total: 0, documents: [] }

**Comment by Tarun-sngh** [comment]
This is how am connecting to redis server.

let connectToRedis = async () => {

    const client = createClient({
        url: //connnection_url here
    });

    client.on('error', (err) => console.log('Redis Client Error', err));
    await client.connect();
    return client;
}

**Comment by Tarun-sngh** [comment]
Redis_version: 6.2.5

**Comment by Tarun-sngh** [comment]
Can you please look into it a little fast, it's a part of ongoing project so i need to get it done soon.

**Comment by JYeop** [comment]
Redis: v6.2.3
RedisJSON: v2.0.6
RediSearch: v2.2.6
Running at Redis Cloud.

Facing same issue.

**Comment by JYeop** [comment]
```ts
    await redisClient.ft.create(
      'idx:test:case',
      {
        '$.aaa[*].uuid': {
          type: SchemaFieldTypes.TEXT,
          AS: 'uuid'
        },
      }, {
        ON: 'JSON',
        PREFIX: 'test:case'
      }
    ).catch(error => {
      console.log(error)
    });
    const ddd = 'vvnpM5OAWa0yocqEnxC3'
    const ddd2 = '2141242141242141fewf'
 await redisClient.json.set(
      `test:case:${ ddd2 }`,
      '$',
      {
        // test: null,
        testNum: 0,
        aaa: [
          {
            uuid: 'aassdd',
            createdAt: Date.now()
          },
          {
            uuid: 'gas112233',
            createdAt: Date.now() + 10
          }
        ],
      }
    );
    const res3 = await redisClient.ft.search('idx:test:case', '@uuid:aassdd*')
    console.log(res3)
    const res4 = await redisClient.ft.search('idx:test:case', '@uuid:aassdd')
    console.log(res4)

```
Result:
>{ total: 0, documents: [] }
>{ total: 0, documents: [] }

Same result in CLI.
> ft.search idx:test:case @uuid:aassdd
>>1) 0

**Comment by Tarun-sngh** [comment]
Doesn't work with SchemaFieldTypes.TAG as well. Still giving the same output.

**Comment by ashtul** [comment]
@Tarun-sngh the fix was not merged yet into the master branch. Until merged and tagged, you can try branch https://github.com/RediSearch/RediSearch/tree/ariel_issue2478.

**Comment by Tarun-sngh** [comment]
@JYeop is it working for you now?
