### ISSUE TITLE
Can I use custom word via configuration options of FRISOINI 

### ISSUE THREAD

**Issue by ricoisme** [RediSearch/RediSearch#2493]
Hi 

I would like to use custom word via configuration options of FRISOINI   in RediSearch when start docker.

But It seems not work when query custom word.

 Does RediSearch container not support for that ?

If I miss anything please tell me.

thanks

**Comment by ashtul** [comment]
We support a custom dictionary only for Chinese.
Please see documentation at https://oss.redis.com/redisearch/Configuring/#frisoini_file_name.

**Comment by ricoisme** [comment]
Got it .
Thanks for reply.
