### ISSUE TITLE
what does the totalResults of AggregateResult stand for?

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2497]
when I use AggregationBuilder r = new AggregationBuilder(q).apply(xxx).filter(yyy).limit(0,10), the totalResults is 9, but the results array is empty, why they are inconsistent?

**Comment by ashtul** [comment]
It might have been the number of results from the query and before you have filtered out additional results.

**Comment by ashtul** [comment]
In FT.SEARCH is stands for the total number of results. 
In FT.AGGREGATE, it cannot be used. It is a known issue (#436). The issue is the internal structure of RediSearch.

A fix would be to break the API and return an accurate count at the end of the reply.

**Comment by chenlizhao** [comment]
> 老铁，你用上RSCoordinator了没？我编译RSCoordinator失败

what client will you use for RSCoordinator?
