### ISSUE TITLE
Cluster returns double results

### ISSUE THREAD

**Issue by xiaohei31** [RediSearch/RediSearch#2511]
the same as this issue: https://github.com/RediSearch/RSCoordinator/issues/326

**Comment by ashtul** [comment]
Fixed by #2404

**Comment by xiaohei31** [comment]
I build the latest codes, it returns "(error) could not parse redisearch results" when ft.search.
Maybe the returned struct is not correct?

**Comment by xiaohei31** [comment]
"(error) could not parse redisearch results" because of TIMEOUT. 
This issue has been fixed.
