### ISSUE TITLE
FT.SEARCH fail when dbsize > 2 millions

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2518]
I create a simple JSON shcema as:
FT.CREATE userIdx ON JSON SCHEMA $.source as source NUMERIC $.sourceId as sourceId NUMERIC $.id AS id NUMERIC

then I dump data into redis, when dbsize is not big, the FT.SEARCH command succeed as:
172.16.3.43:6379> FT.SEARCH userIdx "*" LIMIT 0 1
1696245
user:153698:165889:1
$
{"source":1,"sourceId":165889,"id":153698}

but when dbsize is larger than 2 millions or so, the FT.SEARCH command fail as:
172.16.3.43:6379> dbsize
2032959
172.16.3.43:6379> FT.SEARCH userIdx "*" LIMIT 0 1
2043999

you can see the result array is empty.

urgent help is needed!

lizhao

**Comment by MeirShpilraien** [comment]
Please specify RediSearch and Redis versions.

**Comment by chenlizhao** [comment]
> Please specify RediSearch and Redis versions.

redis 6.2.5, redisearch 2.2.0, rejson 1.5.0

**Comment by MeirShpilraien** [comment]
Can you try to increase the timeout and see if it makes any changes: https://oss.redis.com/redisearch/Configuring/

**Comment by chenlizhao** [comment]
> 
it seems work now, thanks a lot!
