### ISSUE TITLE
what's the fast way to search by date range?

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2522]
I have an user JSON schema which includes registrationTime text field, and I want to get the count of users which registered yesterday, now I use aggregation builder like:

```
AggregationBuilder r = new AggregationBuilder(query)
            		.apply("parsetime(@registrationTime, \"%Y-%m-%d %H:%M:%S\")", "time")
                        .filter(@time < parsetime(today, "%Y-%m-%d") && @time >= parsetime(yesterday, "%Y-%m-%d"))
                        .groupby("id");
```

but it will cost much time when the keys size grows fast, is there an efficient way to do this?

**Comment by gkorland** [comment]
@chenlizhao what does the `query` look like? 
Notice, `filter` is doing post filtering and not using the index, the index is being only being utilized as part of the query.

**Comment by chenlizhao** [comment]
> @chenlizhao what does the `query` look like? Notice, `filter` is doing post filtering and not using the index, the index is being only being utilized as part of the query.

how can I filter registrationTime in query?

**Comment by chenlizhao** [comment]
@gkorland could you give me some comments?

**Comment by ashtul** [comment]
@chenlizhao If you can serialize your date as a number, you could use the NUMERIC field type.

**Comment by chenlizhao** [comment]
> @chenlizhao If you can serialize your date as a number, you could use the NUMERIC field type.

OK, thanks a lot!
