### ISSUE TITLE
Is there a way to sort by the geo calculated distance?

### ISSUE THREAD

**Issue by tariqalardah** [RediSearch/RediSearch#2525]
I have been using geo filters in queries like 
`@field:[{lon} {lat} {radius} {m|km|mi|ft}]`

I spent a long time trying to find references in documentation and examples to be able to sort the results from shortest to longest distance but couldn't, is there anyway?

**Comment by gkorland** [comment]
You can use one of the geo function and then sort by the results.
For more details see: https://oss.redis.com/redisearch/Aggregations/#list_of_geo_apply_functions
