### ISSUE TITLE
Building from Source - Error

### ISSUE THREAD

**Issue by shannonantony** [RediSearch/RediSearch#2529]
Hi, 

I am trying to build the Redisearch.io from source

I am following the steps outlined at https://oss.redis.com/redisearch/Quick_Start/#building_and_running_from_source

I get following error

[root@machine1 RediSearch]# make build
# search root: /apps/redis/RediSearch
# search binroot: /apps/redis/RediSearch/bin/linux-x64-release
# VectorSimilarity root: /apps/redis/RediSearch/deps/VectorSimilarity
# VectorSimilarity binroot: /apps/redis/RediSearch/bin/linux-x64-release/search/deps/VectorSimilarity/src
# VectorSimilarity static build: ON
# OS=linux
# OSNICK=centos7
# ARCH=x64
# VECSIM_MARCH: skylake-avx512
gmake[1]: Entering directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[2]: Entering directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[3]: Entering directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[3]: Leaving directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[3]: Entering directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
[ 11%] Performing download step (git clone) for 'cpu_features-populate'
Cloning into 'cpu_features-src'...
error: pathspec 'master' did not match any file(s) known to git.
CMake Error at cpu_features-subbuild/cpu_features-populate-prefix/tmp/cpu_features-populate-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'

gmake[3]: *** [cpu_features-populate-prefix/src/cpu_features-populate-stamp/cpu_features-populate-download] Error 1
gmake[3]: Leaving directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[2]: *** [CMakeFiles/cpu_features-populate.dir/all] Error 2
gmake[2]: Leaving directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'
gmake[1]: *** [all] Error 2
gmake[1]: Leaving directory `/apps/redis/RediSearch/bin/linux-x64-release/search/_deps/cpu_features-subbuild'

CMake Error at /usr/share/cmake-3.21/Modules/FetchContent.cmake:1017 (message):
  Build step for cpu_features failed: 2
Call Stack (most recent call first):
  /usr/share/cmake-3.21/Modules/FetchContent.cmake:1146:EVAL:2 (__FetchContent_directPopulate)
  /usr/share/cmake-3.21/Modules/FetchContent.cmake:1146 (cmake_language)
  /usr/share/cmake-3.21/Modules/FetchContent.cmake:1189 (FetchContent_Populate)
  deps/VectorSimilarity/cmake/cpu_features.cmake:8 (FetchContent_MakeAvailable)
  deps/VectorSimilarity/src/VecSim/spaces/CMakeLists.txt:34 (include)

-- Configuring incomplete, errors occurred!
See also "/apps/redis/RediSearch/bin/linux-x64-release/search/CMakeFiles/CMakeOutput.log".
See also "/apps/redis/RediSearch/bin/linux-x64-release/search/CMakeFiles/CMakeError.log".
Makefile:381: recipe for target '/apps/redis/RediSearch/bin/linux-x64-release/search/Makefile' failed
make: *** [/apps/redis/RediSearch/bin/linux-x64-release/search/Makefile] Error 1

Please help

thanks

Jay

**Comment by gkorland** [comment]
@shannonantony we're working on fixing the build on the `master` branch.
Meanwhile, please use the stable branches 2.2 - https://github.com/RediSearch/RediSearch/tree/2.2 .

**Comment by shannonantony** [comment]
Hi, since the master branch is fixed, I tried it again

make setup succeeded.

make build created following errors

[root@gaproxy01 RediSearch]# make build
# search root: /apps/redis/RediSearch
# search binroot: /apps/redis/RediSearch/bin/linux-x64-release
# VectorSimilarity root: /apps/redis/RediSearch/deps/VectorSimilarity
# VectorSimilarity binroot: /apps/redis/RediSearch/bin/linux-x64-release/search/deps/VectorSimilarity/src
# VectorSimilarity static build: ON
# OS=linux
# OSNICK=centos7
# ARCH=x64
# VECSIM_MARCH: skylake-avx512
-- Configuring done
-- Generating done
-- Build files have been written to: /apps/redis/RediSearch/bin/linux-x64-release/search
Building /apps/redis/RediSearch/bin/linux-x64-release/search/redisearch.so ...
Consolidate compiler generated dependencies of target rmutil
Consolidate compiler generated dependencies of target friso
[  0%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o
Consolidate compiler generated dependencies of target rscore
[  3%] Built target rmutil
cc1: error: bad value (‘x86-64-v2’) for ‘-march=’ switch
cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake cooperlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native; did you mean ‘x86-64’?
make[3]: *** [_deps/cpu_features-build/CMakeFiles/utils.dir/build.make:76: _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:909: _deps/cpu_features-build/CMakeFiles/utils.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[  6%] Built target friso
[ 49%] Built target rscore
make[1]: *** [Makefile:146: all] Error 2
make: *** [Makefile:387: /apps/redis/RediSearch/bin/linux-x64-release/search/redisearch.so] Error 2

**Comment by shannonantony** [comment]
Also, can you please let me know the steps to build redisearch.so from a specific version like https://github.com/RediSearch/RediSearch/tree/2.2

thanks again

Jay

**Comment by zxgjava** [comment]
> Hi, since the master branch is fixed, I tried it again
> 
> make setup succeeded.
> 
> make build created following errors
> 
> [root@gaproxy01 RediSearch]# make build
> 
> # search root: /apps/redis/RediSearch
> # search binroot: /apps/redis/RediSearch/bin/linux-x64-release
> # VectorSimilarity root: /apps/redis/RediSearch/deps/VectorSimilarity
> # VectorSimilarity binroot: /apps/redis/RediSearch/bin/linux-x64-release/search/deps/VectorSimilarity/src
> # VectorSimilarity static build: ON
> # OS=linux
> # OSNICK=centos7
> # ARCH=x64
> # VECSIM_MARCH: skylake-avx512
> -- Configuring done -- Generating done -- Build files have been written to: /apps/redis/RediSearch/bin/linux-x64-release/search Building /apps/redis/RediSearch/bin/linux-x64-release/search/redisearch.so ... Consolidate compiler generated dependencies of target rmutil Consolidate compiler generated dependencies of target friso [ 0%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o Consolidate compiler generated dependencies of target rscore [ 3%] Built target rmutil cc1: error: bad value (‘x86-64-v2’) for ‘-march=’ switch cc1: note: valid arguments to ‘-march=’ switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake cooperlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native; did you mean ‘x86-64’? make[3]: *** [_deps/cpu_features-build/CMakeFiles/utils.dir/build.make:76: _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o] Error 1 make[2]: *** [CMakeFiles/Makefile2:909: _deps/cpu_features-build/CMakeFiles/utils.dir/all] Error 2 make[2]: *** Waiting for unfinished jobs.... [ 6%] Built target friso [ 49%] Built target rscore make[1]: *** [Makefile:146: all] Error 2 make: *** [Makefile:387: /apps/redis/RediSearch/bin/linux-x64-release/search/redisearch.so] Error 2

Hi, I have the same problem, do you have a solution?
