### ISSUE TITLE
Invalid rule type: JSON

### ISSUE THREAD

**Issue by shannonantony** [RediSearch/RediSearch#2532]
Environment

Redis: ver 6.2.4
RediSearch: ver 2.2.5

When I run the below command
>> FT.CREATE userIdx ON JSON SCHEMA $.user.name AS name TEXT $.user.tag AS country TAG

I get following error

(error) Invalid rule type: JSON

Please help

thanks

Jay

**Comment by oshadmi** [comment]
@shannonantony Please make sure ReJSON module is loaded
You should see it listed when you run `INFO Modules`

**Comment by gkorland** [comment]
@shannonantony how are you running the server?
Please see the docs about how to index/query JSONs - https://oss.redis.com/redisearch/Indexing_JSON/

It seems like RedisJSON is not loaded.
The easiest way to start is to just run the docker container that is loaded with both modules RediSearch and RedisJSON.
```
docker run -p 6379:6379 redislabs/redisearch:latest
```

**Comment by shannonantony** [comment]
My mistake, I resolved the issue. 

Much appreciated your quick response.

thanks

Jay

**Comment by shannonantony** [comment]
environmental issue. closing the issue
