### ISSUE TITLE
problem at indexing JSON documents to the right index

### ISSUE THREAD

**Issue by monitorspot** [RediSearch/RediSearch#2535]
Hi there,
I am trying to understand how Redis knows to index documents to the right index without success.

1. FT.CREATE indexA ON JSON SCHEMA $.id AS id NUMERIC $.name AS name TEXT $.aField AS aField TEXT
2. FT.CREATE indexB ON JSON SCHEMA $.id AS id NUMERIC $.name AS name TEXT $.bField AS bField TEXT

now, I added a few JSON documents to Redis, and the problem is FT.SEARCH is finding docs of type indexA in indexB index. (and searching docs of type indexA in indexA index have no results)

SO - how can I make sure that Redis indexing the right JSON documents to the right index?
how does it work? thanks.

edit:
And I have one more question please:
It is possible to search for NUMERIC field by exact number? I saw only search by ranges, but not by exact number.

**Comment by gkorland** [comment]
Please see the `FT.CREATE` docs - https://oss.redis.com/redisearch/Commands/#ftcreate
`FT.CREATE` has `PREFIX` argument that lets you mark which documetns should be indexed.
e.g.

```
> FT.CREATE indexA ON JSON PREFIX 1 post: SCHEMA $.id AS id NUMERIC $.name AS name TEXT $.aField AS aField TEXT
> FT.CREATE indexA ON JSON PREFIX 1 user: SCHEMA $.id AS id NUMERIC $.name AS name TEXT $.aField AS aField TEXT
```

**Comment by gkorland** [comment]
As for the exact match you can use the range such that `min`==`max`.
e.g.
```
@price:[200 200]
```

**Comment by monitorspot** [comment]
@gkorland thanks Guy, the PREFIX solved my problem.
