### ISSUE TITLE
Queries for the string 'a' fail to return results

### ISSUE THREAD

**Issue by StephenGrider** [RediSearch/RediSearch#2536]
Steps are reproducible on a Redis Cloud free tier instance running RedisJSON 2.0.6 and RediSearch 2.2.6

**Steps to Reproduce**

1. Create an index: `ft.create idx ON JSON SCHEMA $ AS name TEXT`
2. Insert docs:
```
json.set doc:1 $ '"b"'
json.set doc:2 $ '"c"'
json.set doc:3 $ '"a"'
```
3. Verify all docs are in the index:
```
redis> ft.search idx *
1) (integer) 3
2) "doc:3"
3) 1) "$"
   2) "\"a\""
4) "doc:1"
5) 1) "$"
   2) "\"b\""
6) "doc:2"
7) 1) "$"
   2) "\"c\""
```
4. Query for `c` or `b` and documents are found:
```ruby
ft.search idx '@name:(b)' # Good
ft.search idx 'b' # Good
ft.search idx '@name:(c)' # Good
ft.search idx 'c' # Good
```
5. Query for `a` and documents aren't found:
```ruby
ft.search idx 'a' # no results
# or 
ft.search idx '@name:(a)' # no results
```

**Result**

1. Queries for 'a' return zero results

**Expected**
1. Queries for `a` return the value at key `doc:3`

**Additional Notes**

Bug is reproducible for nested json, such as `{ "name": "a" }` (after updating the index as well).

`ft.explaincli` seems to return the appropriate values when entering a query for `b` or `c`:
```
redis> ft.explaincli idx 'b'
1) UNION {
2)   b
3)   +b(expanded)
4) }
5)
```

Query plans for `a` are empty:
```
redis> ft.explaincli idx 'a'
1) <empty>}
2)
```

**Comment by gkorland** [comment]
`a` is considered a `stop word` escaping if you want you can change it. 
see: https://oss.redis.com/redisearch/Stopwords/

**Comment by StephenGrider** [comment]
Ah, perfect!
