### ISSUE TITLE
make buil：cc1: error: bad value ('x86-64-v2') for '-march=' switch

### ISSUE THREAD

**Issue by zxgjava** [RediSearch/RediSearch#2539]
`[root@centos-vm RediSearch]# make build
# search root: /root/git/RediSearch
# search binroot: /root/git/RediSearch/bin/linux-x64-release
-- The C compiler identification is GNU 10.2.1
-- The CXX compiler identification is GNU 10.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/rh/devtoolset-10/root/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/rh/devtoolset-10/root/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
# VectorSimilarity root: /root/git/RediSearch/deps/VectorSimilarity
# VectorSimilarity binroot: /root/git/RediSearch/bin/linux-x64-release/search/deps/VectorSimilarity/src
# VectorSimilarity static build: ON
# OS=linux
# OSNICK=centos7
# ARCH=x64
# VECSIM_MARCH: skylake-avx512
-- Configuring done
-- Generating done
-- Build files have been written to: /root/git/RediSearch/bin/linux-x64-release/search
Building /root/git/RediSearch/bin/linux-x64-release/search/redisearch.so ...
[  0%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o
cc1: error: bad value ('x86-64-v2') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server cascadelake tigerlake cooperlake bonnell atom silvermont slm goldmont goldmont-plus tremont knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 znver2 btver1 btver2 native; did you mean 'x86-64'?
make[3]: *** [_deps/cpu_features-build/CMakeFiles/utils.dir/build.make:76: _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:920: _deps/cpu_features-build/CMakeFiles/utils.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
Consolidate compiler generated dependencies of target rscore
[  0%] Building C object CMakeFiles/rscore.dir/deps/base64/base64.o
[  0%] Building C object CMakeFiles/rscore.dir/deps/base64/base64_check.o
[  1%] Building C object CMakeFiles/rscore.dir/deps/cndict/cndict_data.o
[  1%] Building C object CMakeFiles/rscore.dir/deps/geohash/geohash.o
[  1%] Building C object CMakeFiles/rscore.dir/deps/geohash/geohash_helper.o
[  2%] Building C object CMakeFiles/rscore.dir/deps/libnu/cesu8.o
[  2%] Building C object CMakeFiles/rscore.dir/deps/libnu/ducet.o
[  2%] Building C object CMakeFiles/rscore.dir/deps/libnu/extra.o
[  3%] Building C object CMakeFiles/rscore.dir/deps/libnu/strcoll.o
[  3%] Building C object CMakeFiles/rscore.dir/deps/libnu/strings.o
[  3%] Building C object CMakeFiles/rscore.dir/deps/libnu/tofold.o
[  4%] Building C object CMakeFiles/rscore.dir/deps/libnu/tolower.o
[  4%] Building C object CMakeFiles/rscore.dir/deps/libnu/toupper.o
[  4%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16.o
[  4%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16be.o
[  5%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16he.o
[  5%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16le.o
[  5%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32.o
[  6%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32be.o
[  6%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32he.o
[  6%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32le.o
[  7%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf8.o
[  7%] Building C object CMakeFiles/rscore.dir/deps/libnu/validate.o
[  7%] Building C object CMakeFiles/rscore.dir/deps/libnu/version.o
[  8%] Building C object CMakeFiles/rscore.dir/deps/miniz/miniz.o
[  8%] Building C object CMakeFiles/rscore.dir/deps/thpool/thpool.o
[  8%] Building C object CMakeFiles/rscore.dir/deps/triemap/triemap.o
[  9%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_exec.o
[  9%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_plan.o
[  9%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_request.o
In file included from /usr/include/string.h:633,
                 from /root/git/RediSearch/src/value.h:4,
                 from /root/git/RediSearch/src/aggregate/aggregate.h:3,
                 from /root/git/RediSearch/src/aggregate/aggregate_request.c:1:
/root/git/RediSearch/src/aggregate/aggregate_request.c: In function 'getArrangeRP':
/root/git/RediSearch/src/aggregate/aggregate_request.c:974:13: warning: '__builtin_strncpy' specified bound depends on the length of the source argument [-Wstringop-overflow=]
  974 |             strncpy(buf, keystr, keystrlen);
      |             ^~~~~~~
/root/git/RediSearch/src/aggregate/aggregate_request.c:971:27: note: length computed here
  971 |           int keystrlen = strlen(keystr) - _SCORE_LEN;
      |                           ^~~~~~~~~~~~~~
[  9%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/exprast.o
[ 10%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/expression.o
[ 10%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/lexer.o
[ 10%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/parser.o
[ 11%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/date.o
[ 11%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/function.o
[ 11%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/geo.o
[ 12%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/math.o
[ 12%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/string.o
[ 12%] Building C object CMakeFiles/rscore.dir/src/aggregate/group_by.o
[ 13%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducer.o
[ 13%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count.o
[ 13%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count_distinct.o
[ 14%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/deviation.o
[ 14%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/first_value.o
[ 14%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/minmax.o
[ 14%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/quantile.o
[ 15%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/random_sample.o
[ 15%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/sum.o
[ 15%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/to_list.o
[ 16%] Building C object CMakeFiles/rscore.dir/src/alias.o
[ 16%] Building C object CMakeFiles/rscore.dir/src/buffer.o
[ 16%] Building C object CMakeFiles/rscore.dir/src/byte_offsets.o
[ 17%] Building C object CMakeFiles/rscore.dir/src/cndict_loader.o
[ 17%] Building C object CMakeFiles/rscore.dir/src/concurrent_ctx.o
[ 17%] Building C object CMakeFiles/rscore.dir/src/config.o
[ 18%] Building C object CMakeFiles/rscore.dir/src/cursor.o
[ 18%] Building C object CMakeFiles/rscore.dir/src/debug_commads.o
[ 18%] Building C object CMakeFiles/rscore.dir/src/dictionary.o
[ 19%] Building C object CMakeFiles/rscore.dir/src/doc_table.o
[ 19%] Building C object CMakeFiles/rscore.dir/src/doc_types.o
[ 19%] Building C object CMakeFiles/rscore.dir/src/document.o
[ 20%] Building C object CMakeFiles/rscore.dir/src/document_add.o
[ 20%] Building C object CMakeFiles/rscore.dir/src/document_basic.o
[ 20%] Building C object CMakeFiles/rscore.dir/src/ext/default.o
[ 20%] Building C object CMakeFiles/rscore.dir/src/extension.o
[ 21%] Building C object CMakeFiles/rscore.dir/src/field_spec.o
[ 21%] Building C object CMakeFiles/rscore.dir/src/fork_gc.o
[ 21%] Building C object CMakeFiles/rscore.dir/src/forward_index.o
[ 22%] Building C object CMakeFiles/rscore.dir/src/fragmenter.o
[ 22%] Building C object CMakeFiles/rscore.dir/src/gc.o
[ 22%] Building C object CMakeFiles/rscore.dir/src/geo_index.o
[ 23%] Building C object CMakeFiles/rscore.dir/src/highlight_processor.o
[ 23%] Building C object CMakeFiles/rscore.dir/src/hll/hll.o
[ 23%] Building C object CMakeFiles/rscore.dir/src/id_list.o
[ 24%] Building C object CMakeFiles/rscore.dir/src/index.o
[ 24%] Building C object CMakeFiles/rscore.dir/src/index_result.o
[ 24%] Building C object CMakeFiles/rscore.dir/src/indexer.o
[ 25%] Building C object CMakeFiles/rscore.dir/src/info_command.o
[ 25%] Building C object CMakeFiles/rscore.dir/src/inverted_index.o
[ 25%] Building C object CMakeFiles/rscore.dir/src/json.o
[ 25%] Building C object CMakeFiles/rscore.dir/src/language.o
[ 26%] Building C object CMakeFiles/rscore.dir/src/legacy_gc.o
[ 26%] Building C object CMakeFiles/rscore.dir/src/list_reader.o
[ 26%] Building C object CMakeFiles/rscore.dir/src/module.o
[ 27%] Building C object CMakeFiles/rscore.dir/src/notifications.o
[ 27%] Building C object CMakeFiles/rscore.dir/src/numeric_filter.o
[ 27%] Building C object CMakeFiles/rscore.dir/src/numeric_index.o
[ 28%] Building C object CMakeFiles/rscore.dir/src/offset_vector.o
[ 28%] Building C object CMakeFiles/rscore.dir/src/param.o
[ 28%] Building C object CMakeFiles/rscore.dir/src/phonetic_manager.o
[ 29%] Building C object CMakeFiles/rscore.dir/src/print_version.o
[ 29%] Building C object CMakeFiles/rscore.dir/src/profile.o
[ 29%] Building C object CMakeFiles/rscore.dir/src/qint.o
[ 30%] Building C object CMakeFiles/rscore.dir/src/query.o
[ 30%] Building C object CMakeFiles/rscore.dir/src/query_error.o
[ 30%] Building C object CMakeFiles/rscore.dir/src/query_param.o
[ 30%] Building C object CMakeFiles/rscore.dir/src/query_parser/lexer.o
[ 31%] Building C object CMakeFiles/rscore.dir/src/query_parser/parser.o
[ 31%] Building C object CMakeFiles/rscore.dir/src/rdb.o
[ 31%] Building C object CMakeFiles/rscore.dir/src/redis_index.o
[ 32%] Building C object CMakeFiles/rscore.dir/src/redisearch_api.o
[ 32%] Building C object CMakeFiles/rscore.dir/src/result_processor.o
[ 32%] Building C object CMakeFiles/rscore.dir/src/rlookup.o
[ 33%] Building C object CMakeFiles/rscore.dir/src/rs_geo.o
[ 33%] Building C object CMakeFiles/rscore.dir/src/rules.o
[ 33%] Building C object CMakeFiles/rscore.dir/src/rwlock.o
[ 34%] Building C object CMakeFiles/rscore.dir/src/score_explain.o
[ 34%] Building C object CMakeFiles/rscore.dir/src/sortable.o
[ 34%] Building C object CMakeFiles/rscore.dir/src/spec.o
[ 35%] Building C object CMakeFiles/rscore.dir/src/spell_check.o
[ 35%] Building C object CMakeFiles/rscore.dir/src/stemmer.o
[ 35%] Building C object CMakeFiles/rscore.dir/src/stopwords.o
[ 35%] Building C object CMakeFiles/rscore.dir/src/suggest.o
[ 36%] Building C object CMakeFiles/rscore.dir/src/summarize_spec.o
[ 36%] Building C object CMakeFiles/rscore.dir/src/synonym_map.o
[ 36%] Building C object CMakeFiles/rscore.dir/src/tag_index.o
[ 37%] Building C object CMakeFiles/rscore.dir/src/tokenize.o
[ 37%] Building C object CMakeFiles/rscore.dir/src/tokenize_cn.o
[ 37%] Building C object CMakeFiles/rscore.dir/src/trie/levenshtein.o
[ 38%] Building C object CMakeFiles/rscore.dir/src/trie/rune_util.o
[ 38%] Building C object CMakeFiles/rscore.dir/src/trie/sparse_vector.o
[ 38%] Building C object CMakeFiles/rscore.dir/src/trie/trie.o
[ 39%] Building C object CMakeFiles/rscore.dir/src/trie/trie_type.o
[ 39%] Building C object CMakeFiles/rscore.dir/src/util/arr.o
[ 39%] Building C object CMakeFiles/rscore.dir/src/util/array.o
[ 40%] Building C object CMakeFiles/rscore.dir/src/util/block_alloc.o
[ 40%] Building C object CMakeFiles/rscore.dir/src/util/dict.o
[ 40%] Building C object CMakeFiles/rscore.dir/src/util/fnv.o
[ 41%] Building C object CMakeFiles/rscore.dir/src/util/heap.o
[ 41%] Building C object CMakeFiles/rscore.dir/src/util/khtable.o
[ 41%] Building C object CMakeFiles/rscore.dir/src/util/logging.o
[ 41%] Building C object CMakeFiles/rscore.dir/src/util/mempool.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/util/minmax_heap.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/util/misc.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/util/quantile.o
[ 43%] Building C object CMakeFiles/rscore.dir/src/value.o
[ 43%] Building C object CMakeFiles/rscore.dir/src/varint.o
[ 43%] Building C object CMakeFiles/rscore.dir/src/vector_index.o
[ 43%] Built target rscore
make[1]: *** [Makefile:146: all] Error 2
make: *** [Makefile:387: /root/git/RediSearch/bin/linux-x64-release/search/redisearch.so] Error 2`

hi, I have a problem with the source code compilation

**Comment by 18373712565** [comment]
hi, I have the same problem with build logs as follows:

[main] 正在生成文件夹: e:/work/2025/NXP/Project/hello_world/build 
[build] 正在启动生成
[proc] 执行命令: D:\embedded_dev_tools\CMake\bin\cmake.EXE --build e:/work/2025/NXP/Project/hello_world/build --config Debug --target all -j 14 --
[build] [  4%] Building C object CMakeFiles/hello_world.elf.dir/board/pin_mux.c.obj
[build] [  9%] Building C object CMakeFiles/hello_world.elf.dir/board/src/board.c.obj
[build] [ 13%] Building C object CMakeFiles/hello_world.elf.dir/board/src/clock_config.c.obj
[build] [ 18%] Building C object CMakeFiles/hello_world.elf.dir/CMSIS/system_MKL46Z4.c.obj
[build] [ 22%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_clock.c.obj
[build] [ 27%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_common.c.obj
[build] [ 31%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_cache.c.obj
[build] [ 36%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_controller.c.obj
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] [ 40%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_flash.c.obj
[build] [ 50%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_flexnvm.c.obj
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] [ 50%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_uart.c.obj
[build] [ 59%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_lpsci.c.obj
[build] [ 63%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_gpio.c.obj
[build] [ 63%] Building C object CMakeFiles/hello_world.elf.dir/drivers/fsl_smc.c.obj
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:76: CMakeFiles/hello_world.elf.dir/board/pin_mux.c.obj] Error 1
[build] mingw32-make.exe[2]: *** Waiting for unfinished jobs....
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:91: CMakeFiles/hello_world.elf.dir/board/src/board.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:106: CMakeFiles/hello_world.elf.dir/board/src/clock_config.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:121: CMakeFiles/hello_world.elf.dir/CMSIS/system_MKL46Z4.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:136: CMakeFiles/hello_world.elf.dir/drivers/fsl_clock.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:151: CMakeFiles/hello_world.elf.dir/drivers/fsl_common.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:166: CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_cache.c.obj] Error 1
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:211: CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_flexnvm.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:181: CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_controller.c.obj] Error 1
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:256: CMakeFiles/hello_world.elf.dir/drivers/fsl_smc.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:196: CMakeFiles/hello_world.elf.dir/drivers/fsl_ftfx_flash.c.obj] Error 1
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:226: CMakeFiles/hello_world.elf.dir/drivers/fsl_gpio.c.obj] Error 1
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:241: CMakeFiles/hello_world.elf.dir/drivers/fsl_lpsci.c.obj] Error 1
[build] cc1.exe: error: bad value ('cortex-m0plus') for '-march=' switch
[build] cc1.exe: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native
[build] mingw32-make.exe[2]: *** [CMakeFiles\hello_world.elf.dir\build.make:271: CMakeFiles/hello_world.elf.dir/drivers/fsl_uart.c.obj] Error 1
[build] mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:82: CMakeFiles/hello_world.elf.dir/all] Error 2
[build] mingw32-make.exe: *** [Makefile:90: all] Error 2
[proc] 命令“D:\embedded_dev_tools\CMake\bin\cmake.EXE --build e:/work/2025/NXP/Project/hello_world/build --config Debug --target all -j 14 --”已退出，代码为 2
[driver] 生成完毕: 00:00:00.295
[build] 生成已完成，退出代码为 2
