### ISSUE TITLE
sudo make setup throws error after cloning the repository

### ISSUE THREAD

**Issue by Kailash-Ramco** [RediSearch/RediSearch#2546]
Hi Team,

I cloned the RediSearch repository using the below command

sudo git clone --recursive https://github.com/RediSearch/RediSearch.git

Once completed, i tried to setup the RediSearch using (**sudo make setup**) command, but faced the following error

![image](https://user-images.githubusercontent.com/97166966/152148483-ed7449c3-2051-404a-9b91-cc759854cb5f.png)

Could you please help on how to proceed further.

Additional Info: I am trying to install redis open-source with RediSearch module via ubuntu 20.04 using wsl 
on a windows server 2019

**Comment by gkorland** [comment]
Please try to update the submodules and rerun.

```
git submodule update --init --recursive
```

**Comment by Kailash-Ramco** [comment]
Hi @gkorland,

Thanks for the response, this helped.
