### ISSUE TITLE
ft.search error 'noauth authentication required'

### ISSUE THREAD

**Issue by xiaohei31** [RediSearch/RediSearch#2555]
My cluster's configure needs password.
When I ft.search, it occurs 'noauth authentication required'.
Then I input 'auth xxxx',  it still occurs 'noauth authentication required' to ft.search.

Did I miss any configure? Should I config like 'loadmodule reidearch.so password xxxx'?

**Comment by gkorland** [comment]
You should configure the password to be used by the coordinator, for cross shards communication. 

```
redis-server --loadmodule ./redisearch.so OSS_GLOBAL_PASSWORD password
```

**Comment by xiaohei31** [comment]
thanks!
