### ISSUE TITLE
module-oss.so loading failed

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2559]
I used make build COORD=1, and loaded module-oss.so, but it failed as:

31730:M 07 Feb 2022 13:22:46.255 # Module /opt/git/RediSearch/module-oss.so initialization failed. Module not loaded
31730:M 07 Feb 2022 13:22:46.255 # Can't load module from /opt/git/RediSearch/module-oss.so: server aborting

I  loaded RSCoordinator module together with redisearch module.

**Comment by gkorland** [comment]
@chenlizhao can you please share the way you start the server?
Please notice you don't need to load both module the RSCoordinator includes the RediSearch in it.
