### ISSUE TITLE
ft.search with cluster return duplicate keys

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#2562]
I create a cluster of 6 nodes(3 msaters and 3 slaves) which load redisearch module with COORD enabled,  then create a testSearch hash schema, and add document with key doc1 and doc2, but the search result is like:

127.0.0.1:7003> FT.SEARCH testSearch *
1) (integer) 3
2) "doc1"
3) 1) "title"
   2) "Hi"
   3) "content"
   4) "OOOO"
4) "doc2"
5) 1) "title"
   2) "test"
   3) "content"
   4) "OOOO"
6) "doc2"
7) 1) "title"
   2) "test"
   3) "content"
   4) "OOOO"

there are two doc2 in result, it seems return doc2 for both master and slave nodes.

**Comment by xiaohei31** [comment]
Did you build Redisearch with the latest codes? I built Redisearch yesterday with the latest codes, and didn't find this issue in my application today.
Maybe I should have a try and be careful of this issue tomorrow.
I adviced you to build your cluster again.
