### ISSUE TITLE
When Docker restarted,can't query anything using language chinese.

### ISSUE THREAD

**Issue by xiaogui340** [RediSearch/RediSearch#2600]
i run redisearch like this:
docker run --name=redisearch  -p 7000:6379 -v /var/docker/redis/etc/redis.conf:/etc/redis/redis.conf -v /var/docker/redis/data:/data -d 332d5a356937 redis-server /etc/redis/redis.conf  --loadmodule /usr/lib/redis/modules/redisearch.so --save 3600 1 300 100 60 10000 --appendonly yes

and test ok using language chinese!

when i restart docker,then query from redisearch,it alwarys return empty,  but the key still exist in redis.

**Comment by ashtul** [comment]
@xiaogui340 
Can you please share -
* RediSearch version
* FT.INFO of your index
* samples of data and search queries.

**Comment by xiaogui340** [comment]
Thanks for reply!1. my docker redisearch version is the latest one.2. I compared the FT.INFO,and find two messages missed (language_field,__language) after restarating the docker.发自我的荣耀手机-------- 原始邮件 --------发件人： Ariel Shtul ***@***.***>日期： 2022年2月24日周四 15:17收件人： RediSearch/RediSearch ***@***.***>抄送： gt1987 ***@***.***>, Mention ***@***.***>主    题： Re: [RediSearch/RediSearch] When Docker restarted,can't query anything using language chinese. (Issue #2600)
@xiaogui340
Can you please share -
RediSearch versionFT.INFO of your indexsamples of data and search queries.

**Comment by xiaogui340** [comment]
well, i set the defualt language option when creating index. and problem fix~~

if you only set the language option when adding the documents, when the docker restart, you will lose the language option.
