### ISSUE TITLE
ft.search TIMEOUT argument not working

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#2610]
TIMEOUT argument was added here https://github.com/RediSearch/RediSearch/issues/479 but it's not in the docs https://oss.redis.com/redisearch/Commands/#ftsearch

and it also doesn't work for me: (I'm on redisearch 2.0.10)
>Unknown argument `TIMEOUT` at position 10 for <main>

Seems to work for others though? https://github.com/RediSearch/RediSearch/issues/2579#issuecomment-1042513460

**Comment by gkorland** [comment]
@kkmuffme can you please share the command you try to send?

**Comment by kkmuffme** [comment]
This:

```
redis-cli -h 127.0.0.1 -a my-pass ft.search rs_2749073106_hello_world_com_4 @post_type:product LANGUAGE english NOCONTENT LIMIT 0 29999 SORTBY post_id ASC TIMEOUT 1000 ON_TIMEOUT fail
```

**Comment by kkmuffme** [comment]
@gkorland ?

**Comment by gkorland** [comment]
`ON_TIMEOUT` is a configuration argument.
See: https://oss.redis.com/redisearch/Configuring/#on_timeout_policy

**Comment by kkmuffme** [comment]
wasn't it added as a ft.search argument here https://github.com/RediSearch/RediSearch/issues/479 ?
