### ISSUE TITLE
Does Redisearch support join queries on multiple indices?

### ISSUE THREAD

**Issue by chaitradalawai** [RediSearch/RediSearch#2614]
I have multiple indices in Redis and need to query two or more of them together like joining tables in a DB. Is it possible to the same way on Indices in Redisearch?
Please suggest.

**Comment by gkorland** [comment]
Can you please give a sketch example of you're trying to achieve? 

RediSearch doesn't support join of two indexes out of the box, Redis has some server side scripting that might be able to provide you a solution to what you're looking for.

Please check [EVAL](https://redis.io/commands/eval) & [RedisGears](https://oss.redis.com/redisgears/)
