### ISSUE TITLE
Error: No matching repo to modify: powertools

### ISSUE THREAD

**Issue by yydsleo** [RediSearch/RediSearch#2616]
env:
```
CentOS Linux release 8.5.2111
```
step:
```
make setup
```
message:
```
Setting up system...
# readies version: 742d646
dnf install -q -y ca-certificates
dnf install -q -y curl wget unzip
/root/RediSearch/sbin/../deps/readies/bin/enable-utf8
dnf install -q -y git gawk jq openssl rsync unzip
dnf install -q -y patch
dnf install -q -y redhat-lsb-core
/root/RediSearch/sbin/../deps/readies/bin/getepel
Error: No matching repo to modify: powertools.

In /root/RediSearch/deps/readies/bin/getepel:
39       		# runn dnf install -q -y --allowerasing https://dl.fedoraproject.org/pub/epel/epel-release-latest-${EPEL}.noarch.rpm
40       		runn dnf install -q -y http://rpms.remirepo.net/enterprise/remi-release-${EPEL}.rpm
41       	fi
42   >>> 	runn dnf config-manager -qy --set-enabled remi powertools
43       
44       	# enable raven repo (i.e. pkgs.org)
45       	if [[ $EPEL == 8 && `uname -m` == x86_64 && NO_RAVEN != 1 ]]; then

command failed: /root/RediSearch/sbin/../deps/readies/bin/getepel
make: *** [Makefile:425: setup] Error 1

```

**Comment by rafie** [comment]
Hello @yydsleo,
Please note that CentOS 8 is EOL.
The natural candidates to replace it (in the same functional manner) are RockyLinux and AlmaLinux. OracleLinux also can help, but more as a runtime platform (we experienced some build problems with it).
So currently please use Oracle Linux 8 (e.g. `make docker OSNICK=ol8`).
We'll be moving into RockyLinux as our RHEL8-compatible build platform pretty soon.
As for CentOS 8, it can still be made functional by using repos from CloudFlare (you can use `deps/readies/bin/getupdates` to enable that on a CentOS 8 machine), or by using Docker images from `quay.io/centos/centos:stream8` (the latter, however, is a stream-based CentOS 8, which is not the same as the traditional model, therefore not exactly binary compatible with RHEL8).
