### ISSUE TITLE
New 2.4 grouping also for fields?

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#2650]
https://github.com/RediSearch/RediSearch/releases/tag/v2.4.2

As of 2.4 RediSearch requires to use `@name:(James Brown)` instead of `@name:James Brown`

This should also apply for fields though to keep things consistent?
e.g.
`@first_name|surname:(James Brown)`

Should also be changed to:
`(@first_name|surname):(James Brown)`

But this doesn't work? It's illogical that grouping is required on the "right" side, but not on the left.

**Comment by oshadmi** [comment]
@kkmuffme Indeed the modifier, on the "left" side, is not a full complex expression, rather it is just OR'ing of a few modifiers to a group, so parentheses are not used for grouping modifiers and this is the way to do it `@first_name|surname:(James Brown)`
