### ISSUE TITLE
Redis methods callback not working.

### ISSUE THREAD

**Issue by Tarun-sngh** [RediSearch/RediSearch#2652]
It seems like my callback is not hitting, am not getting any output on my console.
can you please look into it and let me know if there is any issue in my code or what .

Node version am using : 4.0.4
My code:

```javascript
function getUserProfile(userId, cb) {
    let redis = redisConnect();
    redis.hGetAll( userId, cb);
}

getUserProfile("teams:91, (err, results) => {
    if(err){
        console.log(err);
    }
    console.log(results);
})
```

**Comment by gkorland** [comment]
Moved to: https://github.com/redis/node-redis/issues/2034
