### ISSUE TITLE
Module Disabled in Open Source Redis

### ISSUE THREAD

**Issue by starkaqi** [RediSearch/RediSearch#2672]
An exception occurs when redis 6.0.6 uses redissearch. The prompt message is: module disabled in open source redis

**Comment by gkorland** [comment]
How did you run the server?

**Comment by starkaqi** [comment]
The service has been started, which may be due to the installation of redis module. When the command is executed, it can be created successfully, but an exception is prompted when querying: "module disabled in open source redis"

**Comment by gkorland** [comment]
how did you install the module/redis?

**Comment by ashtul** [comment]
The module gives this error when it is compiled to run with Redis Enterprise cluster but is run in OSS mode.

**Comment by starkaqi** [comment]
![image](https://user-images.githubusercontent.com/92778050/159206125-4c1a6bf8-ef27-4173-abee-3f800b58afe3.png)

**Comment by ashtul** [comment]
@starkaqi did you build the binary yourself or downloaded it?
You Can build the OSS version `make clean build COORD=oss`.

**Comment by starkaqi** [comment]
Thank you. It's settled.
