### ISSUE TITLE
Search on JSON index where field has hypens

### ISSUE THREAD

**Issue by mike-niemand** [RediSearch/RediSearch#2681]
Hi All,

I've indexed my JSON content (Wordpress) successfully using:

` FT.CREATE slugsIdx ON JSON SCHEMA $.slug AS slug TEXT`

where slug is a url slug e.g. 'hello-world-how-are-you'

I have added many documents including 'hello-world-how-are-you'

`FT.SEARCH slugsIdx *` confirms the index contains documents.

 BUT
 
 `FT.SEARCH slugsIdx "@slug:(hello-world-how-are-you)" RETURN 1 slug`
 
 Returns several results but none match 'hello-world-how-are-you'?
 
 I am aware of escaping hypens but that doesn't seem to help. 

Any of you more knowledgeable folk have any ideas?

**Comment by gkorland** [comment]
@mike-niemand you might want to read about the query syntax here:
https://oss.redis.com/redisearch/Query_Syntax/

You should also notice that the original text in the document is tokenized and `-` is consider for tokenization, see: https://oss.redis.com/redisearch/Escaping/

So there are two options you can take here:
1. Use `slop` as part of your query 
2. Mark RediSearch to not tokenize by `-`

**Comment by mike-niemand** [comment]
Thank you so much @gkorland :

`FT.SEARCH slugsIdx "@slug:('hello world how are you')" SLOP 1 RETURN 1 slug
`

Works a treat!
