### ISSUE TITLE
Redis coordinator binary keep crashing in cluster mode

### ISSUE THREAD

**Issue by rajkaura** [RediSearch/RediSearch#2689]
We are trying to RedisCoordinator with RedisCLuster. But we observe the following crash on slaves as soon as the cluster is started
Could you please suggest what could be wrong here

1:M 14 Feb 2022 13:24:54.431 # Server initialized
RSValue size: 16
1:M 14 Feb 2022 13:24:54.433 * <search> redis version observed by redisearch : 6.2.6
1:M 14 Feb 2022 13:24:54.433 * <search> Redis version found by RedisSearch : 6.2.6 - oss
1:M 14 Feb 2022 13:24:54.433 * <search> RediSearch version 2.2.7 (Git=2.2-dd90694e)
1:M 14 Feb 2022 13:24:54.433 * <search> Low level api version 1 initialized successfully
1:M 14 Feb 2022 13:24:54.433 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8,
1:M 14 Feb 2022 13:24:54.433 * <search> Initialized thread pool!
1:M 14 Feb 2022 13:24:54.433 * <search> Enabled diskless replication
1:M 14 Feb 2022 13:24:54.433 * <search> Cluster configuration: 0 partitions, type: 0, coordinator timeout: 0ms
Creating thread...
Thread created
1:M 14 Feb 2022 13:24:54.434 * <search> Register write commands
1:M 14 Feb 2022 13:24:54.434 * Module 'search' loaded from /usr/lib/redis/modules/module-oss.so
1:M 14 Feb 2022 13:24:54.434 * Ready to accept connections

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 14 Feb 2022 13:24:55.434 # Redis 6.2.6 crashed by signal: 11, si_code: 1
1:M 14 Feb 2022 13:24:55.434 # Accessing address: 0xe0000000e
1:M 14 Feb 2022 13:24:55.434 # Crashed running the instruction at: 0x7f4f4bbe29fb
------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/module-oss.so(+0xd39fb)[0x7f4f4bbe29fb]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140)[0x7f4f4cf03140]
/usr/lib/redis/modules/module-oss.so(+0xd39fb)[0x7f4f4bbe29fb]
/usr/lib/redis/modules/module-oss.so(+0xe028b)[0x7f4f4bbef28b]
/usr/lib/redis/modules/module-oss.so(+0xe0d32)[0x7f4f4bbefd32]
/usr/lib/redis/modules/module-oss.so(+0x18a80d)[0x7f4f4bc9980d]
/usr/lib/redis/modules/module-oss.so(+0x199395)[0x7f4f4bca8395]
/usr/lib/redis/modules/module-oss.so(uv_run+0x11c)[0x7f4f4bc9a0fc]
/usr/lib/redis/modules/module-oss.so(+0xdfefe)[0x7f4f4bbeeefe]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8ea7)[0x7f4f4cef7ea7]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f4f4ce27def]
------ REGISTERS ------
1:M 14 Feb 2022 13:24:55.434 #
RAX:0000000000001554 RBX:0000000000000000
RCX:0000000000004000 RDX:0000000000001554
RDI:00007f4f4be7bfb0 RSI:0000000000000001
RBP:0000000e0000000e RSP:00007f4f4a93a070
R8 :0000000000000218 R9 :00007f4f4ca00900
R10:00007f4f4a93df28 R11:0000000000000005
R12:00007f4f4be7bfb0 R13:00007f4f4be7eef0
R14:0000555e940ee9c0 R15:00007f4f4be7ed40
RIP:00007f4f4bbe29fb EFL:0000000000010202
CSGSFS:002b000000000033
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07f) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07e) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07d) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07c) -> 0000000000000001
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07b) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a07a) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a079) -> 00007f4f4bc9980d
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a078) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a077) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a076) -> 0000555e940ee9d0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a075) -> 00007f4f4bbefd32
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a074) -> 00007f4f30000e30
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a073) -> 00007f4f4bbef28b
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a072) -> 0000555e940ee930
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a071) -> 00007f4f30000e00
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a070) -> 0000555e940ee910

------ INFO OUTPUT ------
# Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ad7e0714ac70a86d
redis_mode:cluster
os:Linux 5.4.0-1067-azure x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:1
process_supervised:no
run_id:72cfb2d9bb61d4228cbdd9aba16b070814da5344
tcp_port:6379
server_time_usec:1644845095433692
uptime_in_seconds:1
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:677927
executable:/data/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:0
cluster_connections:10
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1610376
used_memory_human:1.54M
used_memory_rss:19304448
used_memory_rss_human:18.41M
used_memory_peak:1666616
used_memory_peak_human:1.59M
used_memory_peak_perc:96.63%
used_memory_overhead:1561824
used_memory_startup:1561816
used_memory_dataset:48552
used_memory_dataset_perc:99.98%
allocator_allocated:2065496
allocator_active:2359296
allocator_resident:4751360
total_system_memory:7287152640
total_system_memory_human:6.79G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.14
allocator_frag_bytes:293800
allocator_rss_ratio:2.01
allocator_rss_bytes:2392064
rss_overhead_ratio:4.06
rss_overhead_bytes:14553088
mem_fragmentation_ratio:12.04
mem_fragmentation_bytes:17700944
mem_not_counted_for_evict:4
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:8
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1644845094
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
of_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:0
total_commands_processed:7
instantaneous_ops_per_sec:50
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:0
total_writes_processed:0
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:5bdbeaf8db52edab67683d6ead38bec887e7baaa
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.019662
used_cpu_user:0.010721
used_cpu_sys_children:0.000000
used_cpu_user_children:0.001352
used_cpu_sys_main_thread:0.000000
used_cpu_user_main_thread:0.000884

# Modules
module:name=search,ver=20207,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]

# Commandstats
cmdstat_cluster:calls=2,usec=57,usec_per_call=28.50,rejected_calls=0,failed_calls=0
cmdstat_search.CLUSTERREFRESH:calls=1,usec=154,usec_per_call=154.00,rejected_calls=0,failed_calls=0
cmdstat_config:calls=1,usec=10,usec_per_call=10.00,rejected_calls=0,failed_calls=0
cmdstat_info:calls=3,usec=24,usec_per_call=8.00,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:1
# Keyspace

------ CLIENT LIST OUTPUT ------

------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
1:M 14 Feb 2022 13:24:55.435 # main thread terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #0 terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #1 terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: /usr/lib/redis/modules/module-oss.so (base 0x7f4f4bb0f000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== REDIS BUG REPORT END. Make sure to include from START to END. ===
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           [http://github.com/redis/redis/issues](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgithub.com%2Fredis%2Fredis%2Fissues&data=04%7C01%7Crakaura%40microsoft.com%7C909f82e451444156c86a08da11a24290%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637841685854213337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DyrbyVDwifP05vrLa99Jq%2BKijMYkzetsxWVdiJKORkI%3D&reserved=0)

  Suspect RAM error? Use redis-server --test-memory to verify it.1:M 14 Feb 2022 13:24:54.431 # Server initialized
RSValue size: 16
1:M 14 Feb 2022 13:24:54.433 * <search> redis version observed by redisearch : 6.2.6
1:M 14 Feb 2022 13:24:54.433 * <search> Redis version found by RedisSearch : 6.2.6 - oss
1:M 14 Feb 2022 13:24:54.433 * <search> RediSearch version 2.2.7 (Git=2.2-dd90694e)
1:M 14 Feb 2022 13:24:54.433 * <search> Low level api version 1 initialized successfully
1:M 14 Feb 2022 13:24:54.433 * <search> concurrent writes: OFF, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000, search pool size: 20, index pool size: 8,
1:M 14 Feb 2022 13:24:54.433 * <search> Initialized thread pool!
1:M 14 Feb 2022 13:24:54.433 * <search> Enabled diskless replication
1:M 14 Feb 2022 13:24:54.433 * <search> Cluster configuration: 0 partitions, type: 0, coordinator timeout: 0ms
Creating thread...
Thread created
1:M 14 Feb 2022 13:24:54.434 * <search> Register write commands
1:M 14 Feb 2022 13:24:54.434 * Module 'search' loaded from /usr/lib/redis/modules/module-oss.so
1:M 14 Feb 2022 13:24:54.434 * Ready to accept connections

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 14 Feb 2022 13:24:55.434 # Redis 6.2.6 crashed by signal: 11, si_code: 1
1:M 14 Feb 2022 13:24:55.434 # Accessing address: 0xe0000000e
1:M 14 Feb 2022 13:24:55.434 # Crashed running the instruction at: 0x7f4f4bbe29fb
------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/module-oss.so(+0xd39fb)[0x7f4f4bbe29fb]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140)[0x7f4f4cf03140]
/usr/lib/redis/modules/module-oss.so(+0xd39fb)[0x7f4f4bbe29fb]
/usr/lib/redis/modules/module-oss.so(+0xe028b)[0x7f4f4bbef28b]
/usr/lib/redis/modules/module-oss.so(+0xe0d32)[0x7f4f4bbefd32]
/usr/lib/redis/modules/module-oss.so(+0x18a80d)[0x7f4f4bc9980d]
/usr/lib/redis/modules/module-oss.so(+0x199395)[0x7f4f4bca8395]
/usr/lib/redis/modules/module-oss.so(uv_run+0x11c)[0x7f4f4bc9a0fc]
/usr/lib/redis/modules/module-oss.so(+0xdfefe)[0x7f4f4bbeeefe]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8ea7)[0x7f4f4cef7ea7]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f4f4ce27def]
------ REGISTERS ------
1:M 14 Feb 2022 13:24:55.434 #
RAX:0000000000001554 RBX:0000000000000000
RCX:0000000000004000 RDX:0000000000001554
RDI:00007f4f4be7bfb0 RSI:0000000000000001
RBP:0000000e0000000e RSP:00007f4f4a93a070
R8 :0000000000000218 R9 :00007f4f4ca00900
R10:00007f4f4a93df28 R11:0000000000000005
R12:00007f4f4be7bfb0 R13:00007f4f4be7eef0
R14:0000555e940ee9c0 R15:00007f4f4be7ed40
RIP:00007f4f4bbe29fb EFL:0000000000010202
CSGSFS:002b000000000033
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07f) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07e) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07d) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07c) -> 0000000000000001
1:M 14 Feb 2022 13:24:55.434 # (00007f4f4a93a07b) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a07a) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a079) -> 00007f4f4bc9980d
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a078) -> 00007f4f4a93a0c0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a077) -> 0000000000000000
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a076) -> 0000555e940ee9d0
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a075) -> 00007f4f4bbefd32
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a074) -> 00007f4f30000e30
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a073) -> 00007f4f4bbef28b
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a072) -> 0000555e940ee930
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a071) -> 00007f4f30000e00
1:M 14 Feb 2022 13:24:55.435 # (00007f4f4a93a070) -> 0000555e940ee910

------ INFO OUTPUT ------
# Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:ad7e0714ac70a86d
redis_mode:cluster
os:Linux 5.4.0-1067-azure x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:1
process_supervised:no
run_id:72cfb2d9bb61d4228cbdd9aba16b070814da5344
tcp_port:6379
server_time_usec:1644845095433692
uptime_in_seconds:1
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:677927
executable:/data/redis-server
config_file:/etc/redis/redis.conf
io_threads_active:0

# Clients
connected_clients:0
cluster_connections:10
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:1610376
used_memory_human:1.54M
used_memory_rss:19304448
used_memory_rss_human:18.41M
used_memory_peak:1666616
used_memory_peak_human:1.59M
used_memory_peak_perc:96.63%
used_memory_overhead:1561824
used_memory_startup:1561816
used_memory_dataset:48552
used_memory_dataset_perc:99.98%
allocator_allocated:2065496
allocator_active:2359296
allocator_resident:4751360
total_system_memory:7287152640
total_system_memory_human:6.79G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.14
allocator_frag_bytes:293800
allocator_rss_ratio:2.01
allocator_rss_bytes:2392064
rss_overhead_ratio:4.06
rss_overhead_bytes:14553088
mem_fragmentation_ratio:12.04
mem_fragmentation_bytes:17700944
mem_not_counted_for_evict:4
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:0
mem_aof_buffer:8
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1644845094
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
of_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:0
total_commands_processed:7
instantaneous_ops_per_sec:50
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:0
total_writes_processed:0
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:5bdbeaf8db52edab67683d6ead38bec887e7baaa
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.019662
used_cpu_user:0.010721
used_cpu_sys_children:0.000000
used_cpu_user_children:0.001352
used_cpu_sys_main_thread:0.000000
used_cpu_user_main_thread:0.000884

# Modules
module:name=search,ver=20207,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]

# Commandstats
cmdstat_cluster:calls=2,usec=57,usec_per_call=28.50,rejected_calls=0,failed_calls=0
cmdstat_search.CLUSTERREFRESH:calls=1,usec=154,usec_per_call=154.00,rejected_calls=0,failed_calls=0
cmdstat_config:calls=1,usec=10,usec_per_call=10.00,rejected_calls=0,failed_calls=0
cmdstat_info:calls=3,usec=24,usec_per_call=8.00,rejected_calls=0,failed_calls=0

# Errorstats

# Cluster
cluster_enabled:1
# Keyspace

------ CLIENT LIST OUTPUT ------

------ MODULES INFO OUTPUT ------

------ FAST MEMORY TEST ------
1:M 14 Feb 2022 13:24:55.435 # main thread terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #0 terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #1 terminated
1:M 14 Feb 2022 13:24:55.435 # Bio thread for job type #2 terminated

Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: (null) (base: (nil))
Module: /usr/lib/redis/modules/module-oss.so (base 0x7f4f4bb0f000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=(nil) -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== REDIS BUG REPORT END. Make sure to include from START to END. ===
=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           [http://github.com/redis/redis/issues](https://nam06.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgithub.com%2Fredis%2Fredis%2Fissues&data=04%7C01%7Crakaura%40microsoft.com%7C909f82e451444156c86a08da11a24290%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637841685854213337%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DyrbyVDwifP05vrLa99Jq%2BKijMYkzetsxWVdiJKORkI%3D&reserved=0)

  Suspect RAM error? Use redis-server --test-memory to verify it.

**Comment by gkorland** [comment]
How did you build the module?
How did you run the server?

**Comment by rajkaura** [comment]
Thanks for the response.
We have built with coord option in redisearch 2.2 (make build COORD=1)
We have loaded the module in rediserver and running it as part of statefulsets in kubernetes environment.

**Comment by rajkaura** [comment]
WIth latest 2.2.10 redisearch cluster is coming up. Thanks

**Comment by edbetway** [comment]
We're having the same issue and using the specificed version or even the latest version doesnt help.
Any ideas?
