### ISSUE TITLE
viewing the complete document on the site returns a 404 status

### ISSUE THREAD

**Issue by xieyy09** [RediSearch/RediSearch#2690]
In  https://oss.redis.com/redisearch/Commands/

[the full documentation on aggregations](https://redis.io/docs/stack/search/Query_Syntax/)

[query syntax](https://redis.io/docs/stack/search/Aggregations/)

This URL and other full documents return 404

Is there anything wrong with my visit?

**Comment by gkorland** [comment]
Thanks for reporting, these links were broken in the move to redis.io. 
We'll fix it.
These are the right links:
https://redis.io/docs/stack/search/reference/query_syntax/
https://redis.io/docs/stack/search/reference/aggregations/

**Comment by oshadmi** [comment]
@xieyy09 Links are now fixed
