### ISSUE TITLE
How do I know the index has been created？

### ISSUE THREAD

**Issue by wxzhou-gis** [RediSearch/RediSearch#2697]
I know the index name, but I don't know whether it has been created. What should I do to query the index at this time? If you first drop index and then create, does this affect the performance of object query when there is a large amount of data?

**Comment by ashtul** [comment]
@wxzhou-gis You will get an error message so there is no harm running FT.SEARCH.

As for dropping and recreating the index, you are not expected to see a significant change. If for example, we rescan the data into an index, it will be scanned randomly. Some datasets gain a bit from this and some lose. But overall, with GC working in the background, there shouldn't be any meaningful difference.

**Comment by wxzhou-gis** [comment]
Creating an index is time-consuming and laborious. Is it not elegant to detect whether to create an index through ft.search? Suppose there is such a method that can directly judge whether an index has been established and which indexes have been established. Would it be better? In this way, it is more convenient to create an index and then query, or query directly with an index.

**Comment by oshadmi** [comment]
@wxzhou-gis You can look at [FT._LIST](https://redis.io/commands/ft._list/) (and [FT.INFO](https://redis.io/commands/ft.info/))

**Comment by wxzhou-gis** [comment]
Thank you, [FT._LIST](https://redis.io/commands/ft._list/) can solve my problem.
