### ISSUE TITLE
Synonym not working with Chinese

### ISSUE THREAD

**Issue by zcw159357** [RediSearch/RediSearch#2698]
When I use Synonym in "language chinese", it won't return the expected docs, and if I use friso to do the synonym it also failes.
I found in src/ext/default.c expandCn  
```
ctx->ExpandTokenWithPhrase(ctx, (const char **)tokVec->data, tokVec->top, token->flags, 1, 0);
```
It does a replace and the token expanded by SynonymExpand loses. 

But in src/tokenize_cn.c cnTokenizer_Next 
```
    switch (tok->type) {
        // Skip words we know we don't care about.
      case __LEX_STOPWORDS__:
      case __LEX_ENPUN_WORDS__:
      case __LEX_CJK_UNITS__:
      case __LEX_NCSYN_WORDS__: // <-here
        continue;

      case __LEX_PUNC_WORDS__:
```
the synonyms added by friso was ignored. 

I tried change replace to 0 in expandCn, synonym in redisearch works again, and if comment out \_\_LEX_NCSYN_WORDS__ in cnTokenizer_Next synonym in friso works.
Is there any particular reason for doing the replace token?

**Comment by zcw159357** [comment]
test case
```
ft.create myidx schema title text weight 5.0 desc text
ft.synupdate myidx group1 pokemon 宝可梦
ft.add myidx doc1 1.0 language "chinese" fields title "我就是要测试宝可梦" desc "真的吗 我也是哦"
ft.search myidx pokemon  //this will return doc1
ft.search myidx pokemon language chinese  //this won't
```

**Comment by gkorland** [comment]
@zcw159357 it seems like the problem is that it's not considered a token on its own 
since it's part of a larger "word" - 我就是要测试宝可梦

Adding a white space like that should work:
```
ft.add myidx doc1 1.0 language "chinese" fields title "我就是要测试 宝可梦" desc "真的吗 我也是哦"
```

**Comment by zcw159357** [comment]
Hi @gkorland Sorry I tried, it won't work. 
As far as I know, Chinese stemmer was done by friso and "我就是要测试宝可梦" will become "就是 要 测试 宝可梦"  and "宝可梦" is in group1.  
src/ext/default.c line 353 when doing ExpandTokenWithPhrase, it set replace to 1, the SynonymExpandedToken in line 458 was ignored.

**Comment by ashtul** [comment]
@zcw159357 Thank you for the issue and the suggestions.
Can you please create a PR with your fix and a test?

**Comment by zcw159357** [comment]
@ashtul hi I'v created a PR, but It seems stuck on "default-flow", what should I do to trigger this step?
