### ISSUE TITLE
Is there any limit on FT.Search and FT.Aggregate

### ISSUE THREAD

**Issue by Ekotenggara** [RediSearch/RediSearch#2699]
Hi, 
I am very new to redisearch so I apologize for any noob questions in advance.
I put massive number of json key into my redis (about 14 gb in total). 
I am using docker in windows and I access it via redis-cli in command prompt.
This used to work when I had only thousand of keys, now that I hundreds thousand, it is no longer working. 
Only some of the query which returned smaller sets work.  Now it returns (empty array). How do I fix it? Thank you

FT.AGGREGATE ResultSearch "@itemID:45015" GROUPBY 1 @comparisonID REDUCE SUM 1 @impactValue as total_CalcValue SORTBY 2 @comparisonID ASC
1) (integer) 13699
2) (empty array)
(0.54s)

FT.AGGREGATE ResultSearch "@itemID:49856" GROUPBY 1 @comparisonID REDUCE SUM 1 @impactValue as total_CalcValue SORTBY 2 @comparisonID ASC
1) (integer) 7
2) 1) "comparisonID"
   2) "1"
   3) "total_CalcValue"
   4) "5167601.89931"
3) 1) "comparisonID"
   2) "11"
   3) "total_CalcValue"
   4) "114.435592275"
4) 1) "comparisonID"
   2) "18"
   3) "total_CalcValue"
   4) "4.17788052366"
5) 1) "comparisonID"
   2) "24"
   3) "total_CalcValue"
   4) "28169491.6784"
6) 1) "comparisonID"
   2) "6"
   3) "total_CalcValue"
   4) "0.0234205711401"
7) 1) "comparisonID"
   2) "7"
   3) "total_CalcValue"
   4) "2375.11493949"
8) 1) "comparisonID"
   2) "9"
   3) "total_CalcValue"
   4) "266.475673249"

**Comment by gkorland** [comment]
It might be related to a query timeout please see: https://redis.io/docs/stack/search/configuring/#timeout

**Comment by oshadmi** [comment]
`TIMEOUT` can also be overridden by the query itself (not only at module load)
See [FT.SEARCH](https://redis.io/commands/ft.search/)

**Comment by Ekotenggara** [comment]
Thank you everyone @gkorland  and @oshadmi , all fixed :) Sorry for another question, is there a way to remove the limitation of maximum 100000 row result? Thank you

**Comment by oshadmi** [comment]
See [FT.CONFIG SET](https://redis.io/commands/ft.config-set/) and [MAXSEARCHRESULTS](https://redis.io/docs/stack/search/configuring/#maxsearchresults)

**Comment by Ekotenggara** [comment]
@oshadmi  Thank you for the reply, however even after setting my maxsearchresults my limit is default to 10, I may miss something.

**Comment by oshadmi** [comment]
@Ekotenggara The default `LIMIT` is `0 10` (for offset and number)
If you specify a higher limit you will be able to get up to `MAXSEARCHRESULTS`
e.g., `LIMIT 0 2000000` (assuming `MAXSEARCHRESULTS` is `-1` or  equals to or greater than `2000000`)

**Comment by Ekotenggara** [comment]
@oshadmi Thank you so much for your reply. It is all makes sense now. Thank you again
