### ISSUE TITLE
How to get the index list in Redisearch?

### ISSUE THREAD

**Issue by wxzhou-gis** [RediSearch/RediSearch#2700]
FT._ List can obtain the existing index list in Redisearch. Which method can obtain similar functions  in jedis?

**Comment by gkorland** [comment]
First it might be better to open it a feature request in Jedis  - https://github.com/redis/jedis/issues.

`FT._ List` - is currently not exposed on Jedis.

But, you can call it explicitly using [executeCommand](https://www.javadoc.io/doc/redis.clients/jedis/latest/index.html)
