### ISSUE TITLE
[enhancement] Query for documents with no value for a text / tag field

### ISSUE THREAD

**Issue by vruizext** [RediSearch/RediSearch#272]
e.g. I want to search for items that have no value for a field named `country`.  I could imagine something like the query below, i.e. a negative query, rejecting the documents that have any value for this field. 

`FT.SEARCH index "@year:[2015 2018] -@country:*"`

**Comment by dvirsky** [comment]
You can emulate that behavior yourself by filling empty fields with some special token like __null__ or something. That's what I'd do internally to implement it - if a field is in the schema but not in the document, add the document to the index of some virtual null term.

**Comment by vruizext** [comment]
Indeed that's what I'm doing now :) 

I was wondering if there was any way to do that more efficiently at low level directly on the redis server.

**Comment by dvirsky** [comment]
I would literally do the same thing inside the server to achieve this goal, it would only look a bit more elegant and be a bit more memory efficient, but it would work exactly the same.

**Comment by mnunberg** [comment]
I'm closing this since this would be impractical to implement internally, and could result in a lot of space consumption. This should be managed at the application layer.

**Comment by btzsoft** [comment]
hi,

In my case I have **40** fields which when I add a new doc they are dynamic, in some cases there can have value in other no.
Why should I populate all docs with the same value rather that just doing some search tricks. This will save a lot of memory and storage.
In most cases only **3** fields are with values, we have millions of docs, adding the same value for any doc would cost us a lot.

Maybe there is some hacks?

**Comment by jodinathan** [comment]
couldn't find this in the docs.  

would be helpful to add that RediSearch can only search existent values

**Comment by pfyod** [comment]
Stumbled upon this unfortunate limitation too. While it's true that it's possible to handle this on application level, it can be quite challenging:
- JSON can have arbitrary nesting;
- One needs to modify the stored documents (to be able to add some sort of "__null__" value or sibling field marking that other field is null). So instead of modifying / creating an index one needs to recreate whole documents.

Would be great to have some sort of "field exists" / "field is not null" query.
