### ISSUE TITLE
Syntax error with simple vector similarity query

### ISSUE THREAD

**Issue by CalebMacdonaldBlack** [RediSearch/RediSearch#2723]
```
127.0.0.1:6381> FT.CREATE my_index SCHEMA vec VECTOR FLAT 6 TYPE FLOAT32 DIM 2 DISTANCE_METRIC L2
OK
127.0.0.1:6381> HSET x vec "aaaaaaaa"
(integer) 1
127.0.0.1:6381> FT.SEARCH my_index "*=>[KNN 2 @vec $blob]" PARAMS 2 blob "aaaaaaaa"
(error) Syntax error at offset 1 near >[
127.0.0.1:6381> 
```

Not sure what I'm doing wrong here.

Running on m1 Mac in docker with image: redisfab/redisearch:master-arm64v8-bionic
Also tried redislabs/redismod & redislabs/redisearch:edge

Honestly seems like I'm doing something obviously wrong here by I can't for the life of me figure it out.

**Comment by CalebMacdonaldBlack** [comment]
Turns out I need to set dialect:
'''
127.0.0.1:6381> FT.SEARCH my_index "*=>[KNN 2 @vec $blob]" DIALECT 2 PARAMS 2 blob "aaaaaaaa"
1) (integer) 1
2) "x"
3) 1) "__vec_score"
   2) "0"
   3) "vec"
   4) "aaaaaaaa"
127.0.0.1:6381> FT.SEARCH my_index "*=>[KNN 2 @vec $blob]" DIALECT 2 PARAMS 2 blob "aaaaaaaa" 
'''

**Comment by esandoval30** [comment]
@CalebMacdonaldBlack There is RediSearch 2.4 [documentation here.](https://docs.redis.com/latest/modules/redisearch/release-notes/redisearch-2.4-release-notes/) It includes a section on the introduction DIALECT. We didn't want to force existing RediSearch users/queries to use Dialect 2 so kept Dialect 1 as default.

Hope this helps
