### ISSUE TITLE
Cosine similarity search doesn't work.

### ISSUE THREAD

**Issue by CalebMacdonaldBlack** [RediSearch/RediSearch#2725]
```
127.0.0.1:6381> FT.CREATE my_index SCHEMA vec VECTOR FLAT 6 TYPE FLOAT32 DIM 2 DISTANCE_METRIC COSINE
OK
127.0.0.1:6381> HSET a vec "aaaaaaaa"
(integer) 1
127.0.0.1:6381> HSET b vec "bbbbbbbb"
(integer) 1
127.0.0.1:6381> FT.SEARCH my_index "*=>[KNN 10 @vec $blob]" DIALECT 2 PARAMS 2 blob "aaaaaaaa"
1) (integer) 2
2) "a"
3) 1) "__vec_score"
   2) "5.96046447754e-08"
   3) "vec"
   4) "aaaaaaaa"
4) "b"
5) 1) "__vec_score"
   2) "5.96046447754e-08"
   3) "vec"
   4) "bbbbbbbb"
127.0.0.1:6381> FT.SEARCH my_index "*=>[KNN 10 @vec $blob]" DIALECT 2 PARAMS 2 blob "bbbbbbbb"
1) (integer) 2
2) "a"
3) 1) "__vec_score"
   2) "5.96046447754e-08"
   3) "vec"
   4) "aaaaaaaa"
4) "b"
5) 1) "__vec_score"
   2) "5.96046447754e-08"
   3) "vec"
   4) "bbbbbbbb"

```

I also can't find any tests specifically for cosign similarity search queries.

**Comment by GuyAv46** [comment]
When using Cosine similarity, the distance metric relies on the angle between the vectors. Notice that `aaaaaaaa` and `bbbbbbbb` are both located on the same line between them and (0,0), so the angle between them is 0 (or close to 0 with floating point arithmetic). In other words both the vectors are equivalent.
Try testing with `aaaaaaaa` and `aaaabbbb` to have different results

**Comment by CalebMacdonaldBlack** [comment]
@GuyAv46 So running your changes in the CLI did yield useful results. However, when running a more practical example, I'm not getting the outcome I would expect.

Running this python code, I would expect my `FT.SEARCH` queries to return different results for each one, but they all come back the same.

```python
import numpy as np
import math
import redis

r = redis.Redis(host='localhost', port=6381, db=0)

print(r.execute_command('FT.CREATE', 'idx', 'SCHEMA', 'v', 'VECTOR', 'FLAT', '6', 'TYPE', 'FLOAT32', 'DIM', 4, 'DISTANCE_METRIC', 'COSINE'))

v1 = np.array([3, 45, 7, 2], dtype=np.float32)
v2 = np.array([2, 54, 13, 15], dtype=np.float32)
v3 = np.array([1, 1, 1, 1], dtype=np.float32)

print(r.execute_command('HSET', '0', 'v', v1.tobytes()))
print(r.execute_command('HSET', '1', 'v', v2.tobytes()))

print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v1.tobytes()))
print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v2.tobytes()))
print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v3.tobytes()))

def cosine_similarity(v1,v2):
    "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
    sumxx, sumxy, sumyy = 0, 0, 0
    for i in range(len(v1)):
        x = v1[i]; y = v2[i]
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y
    return sumxy/math.sqrt(sumxx*sumyy)
#
print(v1, v2, cosine_similarity(v1,v2))
```

```
b'OK'
1
1
[2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.97228425171235

```

**Comment by mariannedevriendt** [comment]
> @GuyAv46 So running your changes in the CLI did yield useful results. However, when running a more practical example, I'm not getting the outcome I would expect.
> 
> Running this python code, I would expect my `FT.SEARCH` queries to return different results for each one, but they all come back the same.
> 
> ```python
> import numpy as np
> import math
> import redis
> 
> r = redis.Redis(host='localhost', port=6381, db=0)
> 
> print(r.execute_command('FT.CREATE', 'idx', 'SCHEMA', 'v', 'VECTOR', 'FLAT', '6', 'TYPE', 'FLOAT32', 'DIM', 4, 'DISTANCE_METRIC', 'COSINE'))
> 
> v1 = np.array([3, 45, 7, 2], dtype=np.float32)
> v2 = np.array([2, 54, 13, 15], dtype=np.float32)
> v3 = np.array([1, 1, 1, 1], dtype=np.float32)
> 
> print(r.execute_command('HSET', '0', 'v', v1.tobytes()))
> print(r.execute_command('HSET', '1', 'v', v2.tobytes()))
> 
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v1.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v2.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v3.tobytes()))
> 
> def cosine_similarity(v1,v2):
>     "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
>     sumxx, sumxy, sumyy = 0, 0, 0
>     for i in range(len(v1)):
>         x = v1[i]; y = v2[i]
>         sumxx += x*x
>         sumyy += y*y
>         sumxy += x*y
>     return sumxy/math.sqrt(sumxx*sumyy)
> #
> print(v1, v2, cosine_similarity(v1,v2))
> ```
> 
> ```
> b'OK'
> 1
> 1
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.97228425171235
> ```

I experience the same issue. The cosine similarity is always 0. However, the L2 score does give correct results.

**Comment by mariannedevriendt** [comment]
> @GuyAv46 So running your changes in the CLI did yield useful results. However, when running a more practical example, I'm not getting the outcome I would expect.
> 
> Running this python code, I would expect my `FT.SEARCH` queries to return different results for each one, but they all come back the same.
> 
> ```python
> import numpy as np
> import math
> import redis
> 
> r = redis.Redis(host='localhost', port=6381, db=0)
> 
> print(r.execute_command('FT.CREATE', 'idx', 'SCHEMA', 'v', 'VECTOR', 'FLAT', '6', 'TYPE', 'FLOAT32', 'DIM', 4, 'DISTANCE_METRIC', 'COSINE'))
> 
> v1 = np.array([3, 45, 7, 2], dtype=np.float32)
> v2 = np.array([2, 54, 13, 15], dtype=np.float32)
> v3 = np.array([1, 1, 1, 1], dtype=np.float32)
> 
> print(r.execute_command('HSET', '0', 'v', v1.tobytes()))
> print(r.execute_command('HSET', '1', 'v', v2.tobytes()))
> 
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v1.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v2.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v3.tobytes()))
> 
> def cosine_similarity(v1,v2):
>     "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
>     sumxx, sumxy, sumyy = 0, 0, 0
>     for i in range(len(v1)):
>         x = v1[i]; y = v2[i]
>         sumxx += x*x
>         sumyy += y*y
>         sumxy += x*y
>     return sumxy/math.sqrt(sumxx*sumyy)
> #
> print(v1, v2, cosine_similarity(v1,v2))
> ```
> 
> ```
> b'OK'
> 1
> 1
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.97228425171235
> ```

I observe the same. Can you re-open the issue please ?

**Comment by DvirDukhan** [comment]
@CalebMacdonaldBlack @mariannedevriendt 
can you please share the platform you are running on (x86, apple-m1, arm), RediSearch version and redis-py version
I executed the example, with the change of the line `return sumxy/math.sqrt(sumxx*sumyy)` to `return 1.0 - sumxy/math.sqrt(sumxx*sumyy)`. RediSearch 2.4.5 docker on x86

code :
```python
import numpy as np
import math
import redis

r = redis.Redis()

print(r.execute_command('FT.CREATE', 'idx', 'SCHEMA', 'v', 'VECTOR', 'FLAT', '6', 'TYPE', 'FLOAT32', 'DIM', 4, 'DISTANCE_METRIC', 'COSINE'))

v1 = np.array([3, 45, 7, 2], dtype=np.float32)
v2 = np.array([2, 54, 13, 15], dtype=np.float32)
v3 = np.array([1, 1, 1, 1], dtype=np.float32)

print(r.execute_command('HSET', '0', 'v', v1.tobytes()))
print(r.execute_command('HSET', '1', 'v', v2.tobytes()))

print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v1.tobytes()))
print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v2.tobytes()))
print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v3.tobytes()))

def cosine_similarity(v1,v2):
    "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
    sumxx, sumxy, sumyy = 0, 0, 0
    for i in range(len(v1)):
        x = v1[i]; y = v2[i]
        sumxx += x*x
        sumyy += y*y
        sumxy += x*y
    return 1.0 - sumxy/math.sqrt(sumxx*sumyy)
#
print(v1, v2, cosine_similarity(v1,v2))
```

results:
```bash
b'OK'
1
1
[2, b'0', [b'__v_score', b'5.96046447754e-08', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0.376145064831', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.270419836044', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.02771574828765
```

**Comment by mariannedevriendt** [comment]
Thank you @DvirDukhan . I am running the code on apple-m1.

**Comment by CalebMacdonaldBlack** [comment]
Thanks @DvirDukhan. I'm running apple-m1 with `redislabs/redisearch:edge` on docker, redis-py version is `4.2.2`

**Comment by Lucabenj** [comment]
Maybe it is not very important, but according to Redisearch syntax the `DIALECT 2` part should be placed at the end of the query

**Comment by DvirDukhan** [comment]
@CalebMacdonaldBlack @mariannedevriendt 
I can confirm this issue reproduce on m1 mac. This is due to the fact that the docker image is x86 build.
You can now use Redis-Stack https://redis.io/docs/stack/get-started/install/mac-os/ to use with the m1 build
This is the output on m1 with Redis-Stack:
```
b'OK'
1
1
[2, b'0', [b'__v_score', b'5.96046447754e-08', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[2, b'0', [b'__v_score', b'0.376145064831', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.270419836044', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
[ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.02771574828765
```

**Comment by af913337456** [comment]
> @CalebMacdonaldBlack @mariannedevriendt can you please share the platform you are running on (x86, apple-m1, arm), RediSearch version and redis-py version I executed the example, with the change of the line `return sumxy/math.sqrt(sumxx*sumyy)` to `return 1.0 - sumxy/math.sqrt(sumxx*sumyy)`. RediSearch 2.4.5 docker on x86
> 
> code :
> 
> ```python
> import numpy as np
> import math
> import redis
> 
> r = redis.Redis()
> 
> print(r.execute_command('FT.CREATE', 'idx', 'SCHEMA', 'v', 'VECTOR', 'FLAT', '6', 'TYPE', 'FLOAT32', 'DIM', 4, 'DISTANCE_METRIC', 'COSINE'))
> 
> v1 = np.array([3, 45, 7, 2], dtype=np.float32)
> v2 = np.array([2, 54, 13, 15], dtype=np.float32)
> v3 = np.array([1, 1, 1, 1], dtype=np.float32)
> 
> print(r.execute_command('HSET', '0', 'v', v1.tobytes()))
> print(r.execute_command('HSET', '1', 'v', v2.tobytes()))
> 
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v1.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v2.tobytes()))
> print(r.execute_command('FT.SEARCH', 'idx', '*=>[KNN 10 @v $q]', 'DIALECT', '2', 'PARAMS', '2', 'q', v3.tobytes()))
> 
> def cosine_similarity(v1,v2):
>     "compute cosine similarity of v1 to v2: (v1 dot v2)/{||v1||*||v2||)"
>     sumxx, sumxy, sumyy = 0, 0, 0
>     for i in range(len(v1)):
>         x = v1[i]; y = v2[i]
>         sumxx += x*x
>         sumyy += y*y
>         sumxy += x*y
>     return 1.0 - sumxy/math.sqrt(sumxx*sumyy)
> #
> print(v1, v2, cosine_similarity(v1,v2))
> ```
> 
> results:
> 
> ```shell
> b'OK'
> 1
> 1
> [2, b'0', [b'__v_score', b'5.96046447754e-08', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0.0277158021927', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [2, b'0', [b'__v_score', b'0.376145064831', b'v', b'\x00\x00@@\x00\x004B\x00\x00\xe0@\x00\x00\x00@'], b'1', [b'__v_score', b'0.270419836044', b'v', b'\x00\x00\x00@\x00\x00XB\x00\x00PA\x00\x00pA']]
> [ 3. 45.  7.  2.] [ 2. 54. 13. 15.] 0.02771574828765
> ```

@DvirDukhan 

hey, sir, i met the same issue. the cosine_similarity is wrong, when use '1 - it', it is right, mine redis was install in centos 8, not the apple-m1, version is 2.6.1, what't problem?
