### ISSUE TITLE
Tag searching not working

### ISSUE THREAD

**Issue by redreamality** [RediSearch/RediSearch#2726]
Just running the official "Bike" example via RedisInsight. 
However, querying by tag does not work.

`FT.SEARCH idx:bikes "@type:{eBikes}"`

![RedisInsight-v2_2022-04-24_20-24-36](https://user-images.githubusercontent.com/3147776/164971995-ae5aa36b-1be0-4953-ba61-634858807df5.png)

**Comment by gkorland** [comment]
Can you please share the schema?
```
FT.INFO idx:bikes
```

**Comment by redreamality** [comment]
![RedisInsight-v2_2022-04-24_23-33-17](https://user-images.githubusercontent.com/3147776/164979012-fd1f056a-ccd1-44c4-b0c1-3a45e6f4d8f5.png)


> Can you please share the schema?
> 
> ```
> FT.INFO idx:bikes
> ```

**Comment by redreamality** [comment]
Yes the first screenshot shows that the "price" query works, and I also feel super weird about this.

**Comment by redreamality** [comment]
For more information,
I also tried the "school" example and "type" works (which is a list of tags), however the "city" failed.

![RedisInsight-v2_2022-04-25_18-42-34](https://user-images.githubusercontent.com/3147776/165053345-8a7520b1-479d-477c-b065-999adfe78cc5.png)

**Comment by ViktarStarastsenka** [comment]
@redreamality , just tested this with the database you mentioned - I still cannot reproduce.
Can you please start all the steps according to the build-in guide from the very beginning and attach here screenshots if any step fails?
Though I have found some typos in the screens you attached, e.g:
FT.SEARCH idx:bikes "@type:{'Kids bikes'}"
and
FT.SEARCH idx:bikes "@type:{eBikes}"

from the first screen should work - did you enter them manually? - seems like Tutorials include the version I mentioned above

and just to be sure - do you have any results returned from "JSON.GET school_json:1"?

**Comment by redreamality** [comment]
For `JSON.GET school_json:1`:
![RedisInsight-v2_2022-04-26_11-54-19](https://user-images.githubusercontent.com/3147776/165203682-777dd339-497c-48ca-993c-8ba003b4de3c.png)

For `FT.SEARCH idx:bikes "@type:{eBikes}"`, I tested some “wrong” cases manually, because the tutorial case is not working, for a continuous query: 
![RedisInsight-v2_2022-04-26_12-01-35](https://user-images.githubusercontent.com/3147776/165204564-6b0828dc-0777-4214-afbb-a8b47b717288.png)

And for 
> just tested this with the database you mentioned - I still cannot reproduce.
> Can you please start all the steps according to the build-in guide from the very beginning and attach here screenshots if any > step fails?
Everything is working correctly, returning "ok"



If reproducing them is difficult, could you please specify the system detailed environment so that I can make changes to mine.

**Comment by ViktarStarastsenka** [comment]
Hi @redreamality , finally managed to reproduce it with RediSearch 2.2.5.
Can you please share the version you use just to double check?

**Comment by redreamality** [comment]
yes, redisearch 2.2.5 and redisjson 2.0.4

**Comment by ViktarStarastsenka** [comment]
@redreamality , also the issue here is with case sensitivity - you can either create a JSON with lower case ("ebikes") or use CASESENSITIVE flag for the TAG field
https://redis.io/docs/stack/search/reference/tags/

**Comment by redreamality** [comment]
Thanks very much!
