### ISSUE TITLE
Parallel Access Speed.

### ISSUE THREAD

**Issue by Ekotenggara** [RediSearch/RediSearch#2768]
Hi,

I am not sure whether this is the limitation of the single instance redis running in Linux or not.

I have a usual query which normally runs for 3 seconds. 
However, if there is I run two redis-cli and I run the the two queries at the same time,
It seems like the redis server is only doing it one by one, resulting the first query to finish at 3 seconds, while the second one finish at 6 seconds (presumably because the server did the first one prior to it).

Is there any setting in .conf file that I can use to fix or enable it to gain flat 3 seconds performance for the first and second cli?

Thank you,

Eko

**Comment by gkorland** [comment]
@Ekotenggara Redis is single threaded (and so his RediSearch) if you want to handle more queries in parallel you should consider deploying multi Redis processes see: [Redis Cluster](https://redis.io/docs/manual/scaling/).

Notice with [Redis Enterprise/Cloud](https://redis.com/redis-enterprise-cloud/overview/) it's being handled for you behind the scenes.

**Comment by Ekotenggara** [comment]
@gkorland Thank you for your reply.
For Redis Cluster is it a free software? Can I set it up within my existing AWS EC2 instance? 
Thank you

**Comment by gkorland** [comment]
Yes you can set free open source only Redis Cluster or rent the from the hosted Cloud

**Comment by Ekotenggara** [comment]
@gkorland  thank you for the clarification, I will set it up. 
Please correct me if I am wrong, if I want up to 5 stable concurrent connection, does it mean I need to set up 5 clusters?
With the cluster set up, can I also improve my flat 3 seconds query? 
Thank you

**Comment by gkorland** [comment]
> if I want up to 5 stable concurrent connection, does it mean I need to set up 5 clusters?
Not 5 cluster but perhaps 5 shards

>can I also improve my flat 3 seconds query?
Yes.

Also please notice, if you'll probably need to build RediSearch with the coordinator enabled to allow distributed query across shards `make build COORD=oss`

**Comment by ashtul** [comment]
@Ekotenggara 
Can you share more details about your query? It might be possible to improve its run-time.
You can use `FT.PROFILE` to check where most time is spent.

**Comment by Ekotenggara** [comment]
Thank you @gkorland, sorry for one one more question, so cluster is the one I can set up manually.
Can I set up shards manually too? Is it still free?

@ashtul Thank you for your reply, I first learned about redisearch and redisjson from your youtube tutorial, thank you for your guidance.

This is my slowest query, took about 40 seconds to run.
FT.AGGREGATE ResultSearch "@indicatorId:1" GROUPBY 2 @designId @module REDUCE SUM 1 @impactValue as total_ImpactValue SORTBY 2 @designId ASC TIMEOUT 100000 LIMIT 0 1000000

My ft.create is like this :
FT.CREATE ResultSearch ON JSON SCHEMA $.a AS designId TAG $.b AS masterId TEXT NOSTEM $.c AS nestedId TEXT NOSTEM $.d AS processId TEXT NOSTEM $.e AS disposalId TEXT NOSTEM $.f AS elementId TEXT NOSTEM $.g AS categoryId TEXT NOSTEM $.h AS dateTimeUpdated TEXT NOSTEM $.i AS module TEXT NOSTEM $.j AS submodule TEXT NOSTEM $.k AS lifeStage TEXT NOSTEM $.l AS yearCount TEXT NOSTEM $.m AS indicatorId TEXT NOSTEM $.n AS impactValue numeric

my keys are essentially, json of abcdefgklmn.
It is grouping up to 100 million json keys. I will really appreciate if you can share a bit of wisdom how to speed it up.

Thank you

**Comment by gkorland** [comment]
Cluster and shards are the same thing. A cluster is a set of shards.

**Comment by Ekotenggara** [comment]
Thank you for the clarification @gkorland. I will give it a go.
