### ISSUE TITLE
Index sorting problem

### ISSUE THREAD

**Issue by wxzhou-gis** [RediSearch/RediSearch#2770]
In the redis cluster with three masters and three slaves,I create an index：
**FT.CREATE xxxIndex ON JSON SCHEMA $.field1 AS field TEXT  $.field2 AS field TEXT  $.field3 AS field NUMERIC SORTABLE** 
Then I query the data according to the index ：
**FT.SEARCH xxxIndex "@field1:0001 @field2:01"**
The query results are not sorted by the field3.I feel that field 3 sortable does not work when creating the index.If I sort by a field when creating an index, shouldn't the result set of the query be sorted by this field?

**Comment by gkorland** [comment]
Please see the docs about Sorting - https://redis.io/docs/stack/search/reference/sorting/

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！

**Comment by wxzhou-gis** [comment]
Thank you. Does this mean that the **SORTABLE** parameter in the index and **SORTBY**  in the query are used together?

**Comment by ashtul** [comment]
@wxzhou-gis The SORTBY parameters in the query tells the server to perform SORTBY.
Having a field as SORTABLE means we can sort faster and more efficiently.
If you plan to use a field for sorting, it is advisable you make it sortable.

Please note, you used twice `AS field`. Each field should get a separate nick.

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！

**Comment by wxzhou-gis** [comment]
您好，您的来信我已经收到了，谢谢！
