### ISSUE TITLE
Simple where IN query on numeric type

### ISSUE THREAD

**Issue by rlempa** [RediSearch/RediSearch#2778]
I'm using RediSearch and RedisJSON (newest versions).
So I have a numeric field (id). I want to do a simple query: `WHERE id IN (1, 5)` (exact match, not sequential). Based on the documentation, I can't do an exact search with `or` on the numeric index. I can't create a TAG index based on a numeric field either. How I can do this search?

I checked https://github.com/RediSearch/RediSearch/issues/2398, but in this situation that was a text field so the author of the question was able to create a tag index based on text field.

Thanks!

**Comment by gkorland** [comment]
you can use a list of `OR` exact match.

```
@id:[1,1] OR @id:[5,5] 
```

**Comment by rlempa** [comment]
@gkorland Works, thanks!
