### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by a25017012** [RediSearch/RediSearch#2834]
1 Are there any components and tools that synchronize PgSQL and MYSQL to redis search? Please give me an address
2 Redis is a memory operation. Will there be data loss in redisearch? If not, how to solve it?

**Comment by a25017012** [comment]
If you can give me a contact information, I still have some questions to ask.

**Comment by a25017012** [comment]
https://redis.io/docs/stack/search/administration/administration/
After writing, I don't know that AOF is persistent. Will the requirements for the network become higher during the master-slave backup? (especially in large quantities)

**Comment by yaronp68** [comment]
> 1 Are there any components and tools that synchronize PgSQL and MYSQL to redis search? Please give me an address
Redis has a commercial product that sync from databased (Oracle, Postgres, MySQL, MariaDB, SQL Server and more coming) into Redis Search (transforms the data to Hash / JSON)

**Comment by a25017012** [comment]
> 
Commercial product address

Are there any non-commercial open source tools?

**Comment by yaronp68** [comment]
> Commercial product address

Contact me yaron.parasol@redis.com

For OSS - see Redis Sink Connector for Debezium 
https://debezium.io/documentation/reference/stable/operations/debezium-server.html
