### ISSUE TITLE
Make setup doesn't work as it should

### ISSUE THREAD

**Issue by JianBin2017** [RediSearch/RediSearch#2869]
The version of GNU make is 4.3
When I came down from git clone redisearch and its sub modules, I used make setup to report an error: make setup
: there is no such file or directory
/Usr/bin/bash: /mnt/redisearch/deps/reads/mk/cc-have-opts: /bin/bash^m: bad interpreter: no that file or directory
/usr/bin/bash: /mnt/RediSearch/sbin/pack. Sh: /bin/bash^m: bad interpreter: no that file or directory
![image](https://user-images.githubusercontent.com/28697261/177525929-149c96af-4d08-414d-be72-1ebedfbcb93a.png)
What's the problem? How to solve it? thank you

**Comment by gkorland** [comment]
Did you clone the source with the sub modules?
```
git clone --recursive https://github.com/RediSearch/RediSearch.git
```

**Comment by JianBin2017** [comment]
您的邮件我已收到.
