### ISSUE TITLE
FT.SEARCH not showing all prefix responses

### ISSUE THREAD

**Issue by gulicheric** [RediSearch/RediSearch#2983]
I add the following hashes:

HSET "movie:1" title "Guardians of the Galaxy"
HSET "movie:2” title "The Grand Budapest Hotel"
HSET "movie:3” title "Gone Girl"
HSET "movie:4” title "The Imitation Game"

I then create the index: 
FT.CREATE idx:movie ON hash PREFIX 1 "movie:" SCHEMA title TEXT

And when I run:
FT.SEARCH idx:movie '@title:The*'

I get no output.

Is this an issue or am I doing something wrong?

**Comment by ashtul** [comment]
Hi,
"The" is a default stopword and therefore it is filtered. 
You can apply you own stopword list when you create the index.

**Comment by gulicheric** [comment]
Thank you!!!
