### ISSUE TITLE
[Documentation] Index JSON arrays as TEXT sample code not working.

### ISSUE THREAD

**Issue by jamesastound** [RediSearch/RediSearch#3025]
In the [documentation](https://redis.io/docs/stack/search/indexing_json/#index-json-arrays-as-text), there is a reference to **RediSearch v2.6.0**, but can't find any reference to it on the github page in releases or milestones.

Is this a typo or a release version not available to the public? If it is a typo, the sample code doesn't work on the latest version of redis-stack via docker. Search results are 0. 

```
> docker run -d --name redis-stack-server -p 6379:6379 redis/redis-stack-server:latest

> FT.CREATE itemIdx3 ON JSON PREFIX 1 item: SCHEMA $.colors AS colors TEXT $.name AS name TEXT $.description as description TEXT
"OK"

> JSON.SET item:3 $ '{"name":"True Wireless earbuds","description":"True Wireless Bluetooth in-ear headphones","connection":{"wireless":true,"type":"Bluetooth"},"price":74.99,"stock":20,"colors":["red","light blue"]}'
"OK"

> FT.SEARCH itemIdx3 '@colors:(white|light) (@name|description:(headphones))' RETURN 1 $.colors
1) "0"

> module list
1) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) "20009"
2) 1) "name"
   2) "search"
   3) "ver"
   4) "20409"
3) 1) "name"
   2) "timeseries"
   3) "ver"
   4) "10616"
4) 1) "name"
   2) "graph"
   3) "ver"
   4) "20815"
5) 1) "name"
   2) "bf"
   3) "ver"
   4) "20217"
```

v2.6.0 reference and sample code added in 6a8190e435f3eaba39f70df665335b9e734b4ab9

**Comment by sergey-morenets** [comment]
Hi @jamesastound 

My current RediSearch module is 20601 and the mentioned example (from documentation) works correctly.

**Comment by jamesastound** [comment]
Fixed in docker Redis-Stack-Server [7.0.2-RC4](https://hub.docker.com/layers/redis/redis-stack-server/7.0.2-RC4/images/sha256-3a3d78e3a3293a41e4303670259e10fe77d7f44b9b56cf006e29c00bbc762177?context=explore). Will self-resolve once 7.x becomes stable on Dockerhub.

**Comment by oshadmi** [comment]
@jamesastound 
Regarding
> In the [documentation](https://redis.io/docs/stack/search/indexing_json/#index-json-arrays-as-text), there is a reference to RediSearch v2.6.0, but can't find any reference to it on the github page in releases or milestones.

In https://github.com/RediSearch/RediSearch/releases
You can find [2.6-RC1 (v2.6.1)](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.1) and [2.6-M01 (v.2.6.0)](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.0)

**Comment by jamesastound** [comment]
@oshadmi Thanks. These were released after my initial post. I've closed this now.
