### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by gsnick** [RediSearch/RediSearch#3031]
Hello,
When building latest version on Rocky Linux release 8.6 (Green Obsidian) the installation fails with the below error:

[ 81%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/memory/vecsim_base.cpp.o
/tmp/RediSearch/src/vector_index.c: In function ‘NewVectorIterator’:
/tmp/RediSearch/src/vector_index.c:85:18: error: too few arguments to function ‘VecSimIndex_ResolveParams’
   85 |       if ((err = VecSimIndex_ResolveParams(vecsim, vq->params.params, array_len(vq->params.params),
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /tmp/RediSearch/src/field_spec.h:6,
                 from /tmp/RediSearch/src/spec.h:16,
                 from /tmp/RediSearch/src/search_ctx.h:7,
                 from /tmp/RediSearch/src/vector_index.h:2,
                 from /tmp/RediSearch/src/vector_index.c:1:
/tmp/RediSearch/deps/VectorSimilarity/src/VecSim/vec_sim.h:101:19: note: declared here
  101 | VecSimResolveCode VecSimIndex_ResolveParams(VecSimIndex *index, VecSimRawParam *rparams,
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [CMakeFiles/rscore.dir/build.make:2036: CMakeFiles/rscore.dir/src/vector_index.o] Error 1
make[3]: *** Waiting for unfinished jobs....
[ 81%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/algorithms/brute_force/bf_batch_iterator.cpp.o
[ 82%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/algorithms/hnsw/hnsw_batch_iterator.cpp.o
make[2]: *** [CMakeFiles/Makefile2:402: CMakeFiles/rscore.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 83%] Linking CXX static library libredismock.a
[ 83%] Built target redismock
[ 83%] Linking CXX static library libVectorSimilarity.a
[ 83%] Built target VectorSimilarity
[ 84%] Linking CXX static library ../../../lib/libgtest.a
[ 84%] Built target gtest
make[1]: *** [Makefile:146: all] Error 2
make: *** [Makefile:370: /tmp/RediSearch/bin/linux-x64-release/search/redisearch.so] Error 2

Can someone advise how this can be fixed?
Thank you,

Nicolai

**Comment by DvirDukhan** [comment]
hi @gsnick 
Can you specify which branch you are trying to build?
Also, try calling `git submodule update --init --recursive` before building

**Comment by gsnick** [comment]
Hi,
By executing git submodule update --init --recursive helped. before make build it works. 
Thanks you.

Nicolai
