### ISSUE TITLE
Synonym not working with Chinese at RediSearch version 2.4.14

### ISSUE THREAD

**Issue by wayn111** [RediSearch/RediSearch#3061]
I use chinese synonym like this
```
FT.CREATE idx ON HASH PREFIX 1 myidx:  language chinese SCHEMA title text weight 5.0 desc text
ft.synupdate idx group1 pokemon 宝可梦 数码宝贝 
hset myidx:doc1 title "我就是要测试 宝可梦 " desc "真的吗 我也是哦" _language "chinese"
ft.search idx "pokemon" language chinese 
```
it doesn't return me any result

Use environment
![image](https://user-images.githubusercontent.com/34181171/188299632-b6d212c4-4bb5-4648-9977-b65e5bd0b1ef.png)

**Comment by zcw159357** [comment]
应该是因为分词问题  我之前用了这个例子是因为我在自己的friso配置里添加过"宝可梦" "数码宝贝" 之类的分词 在能正确分词的情况下 synonym是可以正常使用的 所以我后来在那个issue里说了我当时举的例子不是太好..
建议可以根据你们自己的使用场景去添加friso配置 进行分词 然后再使用synonym

**Comment by wayn111** [comment]
好的，我试试
