### ISSUE TITLE
Incorrect  results when PREFIX on the index does not end with :

### ISSUE THREAD

**Issue by zulander1** [RediSearch/RediSearch#3079]
This will result in an incorrect results. 

```
FT.CREATE "item:idx" "ON" "Json" SCHEMA $.name AS name TEXT $.description as description TEXT
FT.CREATE "item-a:idx" "ON" "Json" SCHEMA $.name AS name TEXT $.description as description TEXT


JSON.SET item:idx $ '{"name":"testa","description":"Wireless Bluetooth headphones with noise-cancelling technology"}'
JSON.SET item-a:idx $ '{"name":"testa","description":"Wireless Bluetooth headphones with noise-cancelling technology"}'
```

 > FT.SEARCH "item:idx" '@name:(testa)'
1) "2"
2) "**item:Idx:1**"
3) 1) "$"
   2) "{\"name\":\"testa\",\"description\":\"Wireless Bluetooth headphones with noise-cancelling technology\"}"
4) "**item-a:Idx**:1"
5) 1) "$"
   2) "{\"name\":\"testa\",\"description\":\"Wireless Bluetooth headphones with noise-cancelling technology\"}"

EDIT:
After playing around i've figure it out, add PREFIX 1 "item:" works but adding PREFIX 1 "item" doesn't work

```
FT.CREATE "item:idx" "ON" "Json" PREFIX 1 "item:" SCHEMA $.name AS name TEXT $.description as description TEXT
FT.CREATE "item-a:idx" "ON" "Json" PREFIX 1 "item-a:" SCHEMA $.name AS name TEXT $.description as description TEXT
```

**Comment by gkorland** [comment]
Yes this is the expected behavior. 
'item' prefix matches both `item:idx` and  `item-a:idx`
