### ISSUE TITLE
How can I aggregate TAG types?

### ISSUE THREAD

**Issue by chao7860-java** [RediSearch/RediSearch#3115]
I'm new to this and searched all the information I could find.

_create index_

` 
 FT.CREATE idx:store ON JSON PREFIX 1 "store:" SCHEMA
 $.id AS id TEXT NOSTEM SORTABLE
 $.name AS name TEXT NOSTEM SORTABLE
 $.book[*].category AS bc TAG
 $.book[*].title AS bt TAG
`

_add data_

`
JSON.SET store:1 $ '
  {
    "id": "1",
    "name": "Main store",
    "book": [
      {
        "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      {
        "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
 '
`

`
JSON.SET store:2 $ '
  {
    "id": "2",
    "name": "No.2 store",
    "book": [
      {
        "category": "programming",
        "author": "BriAlfred V.Aho,Ravi Sethi,Jeffrey D.Ullmanef",
        "title": "Compilers: Principles,Techniques,and Tools ",
        "price": 88.95
      },
      {
        "category": "programming",
        "author": "Andrew S·Tanenbaum",
        "title": "Modern Operation Systems",
        "price": 12.99
      },
      {
        "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      {
        "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    ],
    "bicycle": {
      "color": "red",
      "price": 19.95
    }
  }
 '
`

No problem when I aggregate `name`

aggregate `name`

`
FT.AGGREGATE idx:store  * APPLY @name as name GROUPBY 1 @name REDUCE COUNT 0 AS COUNT
`

_returned result_

`  1) "2"
  2) 1) "name"
     2) "no.2 store"
     3) "COUNT"
     4) "1"
  3) 1) "name"
     2) "main store"
     3) "COUNT"
     4) "1" `

But when I aggregate `book category` there is no result

aggregate `book category`

`
FT.AGGREGATE idx:store  * APPLY @bc as bc GROUPBY 1 @bc REDUCE COUNT 0 AS COUNT
`

_returned result_

`1) "1"
2) 1) "[object Object]"`

How can I aggregate this nested structure?

Thanks in advance.

**Comment by gkorland** [comment]
First notice you don't need to use APPLY 
`FT.AGGREGATE idx:store * APPLY @name as name GROUPBY 1 @name REDUCE COUNT 0 AS COUNT`
should be the same as:
`FT.AGGREGATE idx:store * GROUPBY 1 @name REDUCE COUNT 0 AS COUNT`

As for the other query notice that since `@bc` is not SORTABLE `LOAD` must be called before the APPLY.

```
127.0.0.1:6379> FT.AGGREGATE idx:store * LOAD 1 @bc APPLY @bc as bc GROUPBY 1 @bc REDUCE COUNT 0 AS COUNT
1) (integer) 2
2) 1) "bc"
   2) "reference"
   3) "COUNT"
   4) "1"
3) 1) "bc"
   2) "programming"
   3) "COUNT"
   4) "1"
```

**Comment by chao7860-java** [comment]
@gkorland 
Thank you for your reply, he solved my problem, thank you very much
