### ISSUE TITLE
(error) elem.map is not a function When using FT.SEARCH

### ISSUE THREAD

**Issue by Ankit7991** [RediSearch/RediSearch#3126]
I am having this issue in the below example. (Error: **(error) elem.map is not a function**)

> 127.0.0.1:6379> FT.CREATE products SCHEMA name TEXT price NUMERIC
OK

> 127.0.0.1:6379> FT.ADD products prod1 1.0 FIELDS name "it just regular product 1 with some price tag" price 5000
OK

> 127.0.0.1:6379> FT.ADD products prod2 1.0 FIELDS name "name of product 2" price 75000
OK

> 127.0.0.1:6379> FT.SEARCH products "@price:[5000 75000]"
**(error) elem.map is not a function**

> 127.0.0.1:6379> FT._LIST
1 ) products

I am using docker to run Redis-stack. And using it. (https://redis.io/docs/stack/get-started/install/docker/)
- Checked with both docker instances  (1. redis/redis-stack-server, 2. redis/redis-stack). **Facing Same issue in both**

**Comment by gkorland** [comment]
It doesn't seem like an issue in the server but an issue in `redis-cli` how did you install redis-cli?

**Comment by gkorland** [comment]
It seems like you're using the redis-cli written in JS

**Comment by Ankit7991** [comment]
Yes correct, Issue is in js package, It works perfectly in redis-insight cli.

![image](https://user-images.githubusercontent.com/57867346/193547556-bcbd4936-43d6-4540-83fb-16f63ae2686a.png)
