### ISSUE TITLE
How to use Redisearch from Redis-cli to find an exact number?

### ISSUE THREAD

**Issue by hypo-thesis** [RediSearch/RediSearch#3137]
I have a set of data like this :

```
127.0.0.1:6379> json.set a:1 . '{"name":"chloe", "age":26}'
OK
127.0.0.1:6379> json.set a:2 . '{"name":"shan", "age":38}'
OK
127.0.0.1:6379> json.set a:3 . '{"name":"wala", "age":14}'
OK
127.0.0.1:6379> json.set a:4 . '{"name":"Aida", "age":18}'
```
and I wish to find the one with the age of 14 with the following command and yet I fail.

`ft.search idx "@age:(14)"`
How can I find the data with exact age of 14?

**Comment by gkorland** [comment]
Please see RediSearch docs - https://redis.io/docs/stack/search/reference/query_syntax/
Numeric fields are queried as range  
e.g. `ft.search idx "@age:[14 18]"`, and exact match is done in the same way `ft.search idx "@age:[14 14]"`
