### ISSUE TITLE
Multiple values array returns

### ISSUE THREAD

**Issue by asarnaout** [RediSearch/RediSearch#3152]
If I have this JSON:

```
{
	"Name": "Product1",
	"Sellers": [
		{
			"Name": "Seller1",
			"Locations": ["FL", "AL"]
		},
		{
			"Name": "Seller2",
			"Locations": ["MS", "GA"]
		}
	]
}
```

How can I possibly return the locations for *both* Seller1 and Seller2?
The JSON path should look like this: `$.Sellers[*].Locations[*]` and is indexed as TAG.

Doing `FT.SEARCH .... RETURN 1 $.Sellers[*].Locations` would only be able to retrieve the locations for Seller1 (FL, AL), while doing `FT.SEARCH .... RETURN 1 $.Sellers[*].Locations[*]` would only retrieve (FL).

It seems like there is no way to retrieve (MS, GA) unless I issue another query to return $.Sellers[1].Locations which isn't really maintainable.

**Comment by slorello89** [comment]
This is the same issue as #2867 

@asarnaout At the moment there's two options until a fix comes

1: You can drop the RETURN statement and pull the whole object back
2: You can script this, pull back just the ids from the search and then call `JSON.GET keyname $.Sellers[*].Locations[*]` on all the relevant ones. That way you only have to make one round trip.
