### ISSUE TITLE
Not able to install RediSearch

### ISSUE THREAD

**Issue by saalimzafar** [RediSearch/RediSearch#3155]
Command: 
$make setup

Error:
$
![Screenshot_2022-10-18-19-45-13-40_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/18111798/196455873-9aeba10a-d657-462b-89ed-72b49c9290ce.png)
![Screenshot_2022-10-18-19-45-24-33_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/18111798/196455925-95e18db4-6395-4bb1-a9aa-a71c14bc75b6.png)
make: *** [Makefile:437: setup] Error 1

**Comment by saalimzafar** [comment]
Hi @rafie, thanks for your response.
I realized that I need to have root privileges to install the RediSearch. But redis-server and cli are working fine in normal environment.

**Comment by rafie** [comment]
Hi @saalimzafar, you need root privileges for things that are to be apt-installed.
Also, the pre-build process creates `/etc/profile.d` scripts for some configuration items, and that's requires sudo as well.
It is highly recommended to first try the build in a Docker environment (you can do all git-related operations outside the container and use a volume mount to access the repo), and then try it again natively.
PS there is no need to invoke `sudo` explicitly. The setup script will do this when needed.
