### ISSUE TITLE
how to understand RSAL licese Section 1.1b 

### ISSUE THREAD

**Issue by youweol-master** [RediSearch/RediSearch#3158]
Our team is developing a WEB application，this application is not intend to be a Databse product, it using PostgreSQL database to persisience data. Now we want to use RediSearch to enhance the search ability.

Did us permitted to use RediSearch as a part of our application, even our application is now using PostgreSQL?

the RSAL said：
> use​ the Software, or your Modifications, only as part of Your Application, but not in connection with any Database Product that is distributed or otherwise made available by any third party. 

How to understand the words "in connection with any Database Product..."?
Did our situation meet "in connection with any Database Product", or NOT? It's now using PostgreSQL, a thrid party Database software.

**Comment by gkorland** [comment]
You should be good. The fact that you're also using PostgreSQL doesn't imply "in connection with any Database Product", as long as your product is not a database.

**Comment by youweol-master** [comment]
> You should be good. The fact that you're also using PostgreSQL doesn't imply "in connection with any Database Product", as long as your product is not a database.

I see, thank you very much.
