### ISSUE TITLE
Redis 6.2.6 with Redisearch crashed by signal: 11, si_code: 1

### ISSUE THREAD

**Issue by vangxitrum** [RediSearch/RediSearch#3177]
Hi, I am using redis for my project but it crashes 3 or 4 time a day. After restart the redis docker then it work fine the same data so i dont really know what happen here.

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 25 Oct 2022 06:45:53.867 # Redis 6.2.6 crashed by signal: 11, si_code: 1
1:M 25 Oct 2022 06:45:53.867 # Accessing address: 0xfffffffffffffff4
1:M 25 Oct 2022 06:45:53.867 # Crashed running the instruction at: 0x7f2b2aeb5cd0

------ STACK TRACE ------
EIP:
/usr/lib/redis/modules/redisearch.so(NumericRange_Add+0xa0)[0x7f2b2aeb5cd0]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14140)[0x7f2b2c6f3140]
/usr/lib/redis/modules/redisearch.so(NumericRange_Add+0xa0)[0x7f2b2aeb5cd0]
/usr/lib/redis/modules/redisearch.so(NumericRangeNode_Add+0x125)[0x7f2b2aeb6085]
/usr/lib/redis/modules/redisearch.so(NumericRangeTree_Add+0x20)[0x7f2b2aeb63f0]
/usr/lib/redis/modules/redisearch.so(IndexerBulkAdd+0x76)[0x7f2b2ae98026]
/usr/lib/redis/modules/redisearch.so(+0x12c3a7)[0x7f2b2aeaa3a7]
/usr/lib/redis/modules/redisearch.so(+0x12c952)[0x7f2b2aeaa952]
/usr/lib/redis/modules/redisearch.so(Indexer_Add+0x55)[0x7f2b2aeab155]
/usr/lib/redis/modules/redisearch.so(Document_AddToIndexes+0xe0)[0x7f2b2ae98390]
/usr/lib/redis/modules/redisearch.so(IndexSpec_UpdateDoc+0x135)[0x7f2b2aed5275]
/usr/lib/redis/modules/redisearch.so(Indexes_UpdateMatchingWithSchemaRules+0x94)[0x7f2b2aed5984]
/usr/lib/redis/modules/redisearch.so(HashNotificationCallback+0x137)[0x7f2b2aeb4ed7]
redis-server *:6379(moduleNotifyKeyspaceEvent+0xce)[0x56209896669e]
redis-server *:6379(notifyKeyspaceEvent+0x21)[0x562098952fa1]
redis-server *:6379(hsetCommand+0xf9)[0x56209891d559]
redis-server *:6379(call+0xa1)[0x5620988d91a1]
redis-server *:6379(processCommand+0x593)[0x5620988dad23]
redis-server *:6379(processInputBuffer+0xf8)[0x5620988edec8]
redis-server *:6379(+0xfbbb8)[0x562098985bb8]
redis-server *:6379(aeProcessEvents+0x292)[0x5620988d1e32]
redis-server *:6379(aeMain+0x1d)[0x5620988d209d]
redis-server *:6379(main+0x316)[0x5620988ce2b6]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xea)[0x7f2b2c540d0a]
redis-server *:6379(_start+0x2a)[0x5620988ce78a]

------ REGISTERS ------
1:M 25 Oct 2022 06:45:53.868 # 
RAX:000000000000000a RBX:00007f2b1b4f6548
RCX:0000000000000000 RDX:0000000000000001
RDI:00007f2b1b4f6548 RSI:0000000000000238
RBP:0000000000000238 RSP:00007ffd875af540
R8 :956c4b4ac7208150 R9 :00007f2b1b899d7b
R10:0000000000000007 R11:00007f2b2b0ca990
R12:0000000000000238 R13:0000000000000001
R14:00007f2b1b598ba0 R15:00007ffd875c76e0
RIP:00007f2b2aeb5cd0 EFL:0000000000010246
CSGSFS:002b000000000033
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54f) -> 00007f2b2aeb63f0
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54e) -> 00007f2b1b598ba0
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54d) -> 0000000000000001
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54c) -> 00007ffd875b1650
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54b) -> 00007f2b1b942250
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af54a) -> 00007f2b1b4f66d0
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af549) -> 0000000000000000
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af548) -> 0000000000000000
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af547) -> 00007f2b2aee1ac9
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af546) -> 00007ffd875c76e0
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af545) -> 00007f2b2aeb6085
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af544) -> 00007f2b2c018e40
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af543) -> 00007f2b1b4f66d0
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af542) -> 00007f2b1b78f910
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af541) -> 0000000000000002
1:M 25 Oct 2022 06:45:53.868 # (00007ffd875af540) -> 0000000000000000

------ INFO OUTPUT ------
# Server
redis_version:6.2.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:9c335ca9779faba5
redis_mode:standalone
os:Linux 5.10.104-linuxkit x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:10.2.1
process_id:1
process_supervised:no
run_id:ac577f83d2cc0301f5e91b066100755fc2a33150
tcp_port:6379
server_time_usec:1666680353867149
uptime_in_seconds:5281
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:5735969
executable:/data/redis-server
config_file:
io_threads_active:0

# Clients
connected_clients:6
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:49176
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:12485080
used_memory_human:11.91M
used_memory_rss:34627584
used_memory_rss_human:33.02M
used_memory_peak:19621072
used_memory_peak_human:18.71M
used_memory_peak_perc:63.63%
used_memory_overhead:9444880
used_memory_startup:9302472
used_memory_dataset:3040200
used_memory_dataset_perc:95.53%
allocator_allocated:13015312
allocator_active:13856768
allocator_resident:17555456
total_system_memory:2047266816
total_system_memory_human:1.91G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.06
allocator_frag_bytes:841456
allocator_rss_ratio:1.27
allocator_rss_bytes:3698688
rss_overhead_ratio:1.97
rss_overhead_bytes:17072128
mem_fragmentation_ratio:2.78
mem_fragmentation_bytes:22192880
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:123080
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:2382
rdb_bgsave_in_progress:0
rdb_last_save_time:1666680231
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:2719744
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:10
total_commands_processed:11902
instantaneous_ops_per_sec:2
total_net_input_bytes:19339042
total_net_output_bytes:39448789
instantaneous_input_kbps:41.90
instantaneous_output_kbps:42.41
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:210
evicted_keys:0
keyspace_hits:6575
keyspace_misses:1193
pubsub_channels:1
pubsub_patterns:0
latest_fork_usec:1125
total_forks:15
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:12
dump_payload_sanitizations:0
total_reads_processed:11182
total_writes_processed:20223
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:ade81dba3c774f8673be593d065ef113ebca9c76
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:96.000821
used_cpu_user:61.430741
used_cpu_sys_children:0.105533
used_cpu_user_children:0.114077
used_cpu_sys_main_thread:5.853696
used_cpu_user_main_thread:9.918895

# Modules
module:name=ai,ver=10205,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=graph,ver=20815,api=1,filters=0,usedby=[],using=[ReJSON],options=[]
module:name=rg,ver=10204,api=1,filters=1,usedby=[rg],using=[rg],options=[]
module:name=search,ver=999999,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=ReJSON,ver=20011,api=1,filters=0,usedby=[search|graph],using=[],options=[handle-io-errors]
module:name=timeseries,ver=10616,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=bf,ver=20209,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_get:calls=3,usec=11,usec_per_call=3.67,rejected_calls=0,failed_calls=0
cmdstat_select:calls=529,usec=750,usec_per_call=1.42,rejected_calls=0,failed_calls=1
cmdstat_hset:calls=140,usec=8316,usec_per_call=59.40,rejected_calls=0,failed_calls=0
cmdstat_command:calls=2,usec=1083,usec_per_call=541.50,rejected_calls=0,failed_calls=1
cmdstat_json.set:calls=94,usec=81273,usec_per_call=864.61,rejected_calls=0,failed_calls=0
cmdstat_hget:calls=4061,usec=25450,usec_per_call=6.27,rejected_calls=0,failed_calls=0
cmdstat_monitor:calls=1,usec=1,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_expire:calls=1877,usec=16348,usec_per_call=8.71,rejected_calls=0,failed_calls=0
cmdstat_exists:calls=1313,usec=3819,usec_per_call=2.91,rejected_calls=0,failed_calls=0
cmdstat_cluster:calls=3,usec=10,usec_per_call=3.33,rejected_calls=0,failed_calls=3
cmdstat_echo:calls=6,usec=6,usec_per_call=1.00,rejected_calls=0,failed_calls=0
cmdstat_auth:calls=10,usec=79,usec_per_call=7.90,rejected_calls=0,failed_calls=2
cmdstat_unlink:calls=831,usec=30285,usec_per_call=36.44,rejected_calls=0,failed_calls=0
cmdstat_subscribe:calls=3,usec=20,usec_per_call=6.67,rejected_calls=0,failed_calls=0
cmdstat_FT.DROPINDEX:calls=2,usec=40,usec_per_call=20.00,rejected_calls=0,failed_calls=2
cmdstat_ping:calls=90,usec=212,usec_per_call=2.36,rejected_calls=0,failed_calls=0
cmdstat_module:calls=1,usec=27,usec_per_call=27.00,rejected_calls=0,failed_calls=0
cmdstat_info:calls=185,usec=19725,usec_per_call=106.62,rejected_calls=0,failed_calls=0
cmdstat_FT.CREATE:calls=7,usec=2085,usec_per_call=297.86,rejected_calls=0,failed_calls=0
cmdstat_scan:calls=18,usec=3475,usec_per_call=193.06,rejected_calls=0,failed_calls=0
cmdstat_config:calls=8,usec=128,usec_per_call=16.00,rejected_calls=0,failed_calls=0
cmdstat_client:calls=6,usec=13,usec_per_call=2.17,rejected_calls=0,failed_calls=0
cmdstat_hgetall:calls=456,usec=3661,usec_per_call=8.03,rejected_calls=0,failed_calls=0
cmdstat_json.get:calls=52,usec=44630,usec_per_call=858.27,rejected_calls=0,failed_calls=0
cmdstat_hmset:calls=1848,usec=56691,usec_per_call=30.68,rejected_calls=0,failed_calls=0
cmdstat_FT.SEARCH:calls=356,usec=36890,usec_per_call=103.62,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_ERR:count=10
errorstat_Unknown:count=2

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=230,expires=166,avg_ttl=42912064

------ CLIENT LIST OUTPUT ------
id=19 addr=172.17.0.1:62790 laddr=172.17.0.3:6379 fd=22 name= age=5269 idle=0 flags=O db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=114 oll=0 omem=0 tot-mem=20496 events=r cmd=monitor user=default redir=-1
id=34 addr=172.17.0.1:62792 laddr=172.17.0.3:6379 fd=23 name= age=4738 idle=4734 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20536 events=r cmd=scan user=default redir=-1
id=37 addr=172.17.0.1:62798 laddr=172.17.0.3:6379 fd=20 name=WIN-KAQ5E6KUTS2(SE.Redis-v2.6.48.48654) age=4369 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=564 qbuf-free=40390 argv-mem=320 obl=9 oll=0 omem=0 tot-mem=61952 events=r cmd=hmset user=default redir=-1
id=38 addr=172.17.0.1:62800 laddr=172.17.0.3:6379 fd=21 name=WIN-KAQ5E6KUTS2(SE.Redis-v2.6.48.48654) age=4369 idle=27 flags=P db=0 sub=1 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=39 addr=172.17.0.1:62802 laddr=172.17.0.3:6379 fd=24 name= age=409 idle=401 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20536 events=r cmd=scan user=default redir=-1
id=40 addr=172.17.0.1:62806 laddr=172.17.0.3:6379 fd=25 name= age=399 idle=4 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20504 events=r cmd=info user=default redir=-1

------ CURRENT CLIENT INFO ------
id=37 addr=172.17.0.1:62798 laddr=172.17.0.3:6379 fd=20 name=WIN-KAQ5E6KUTS2(SE.Redis-v2.6.48.48654) age=4369 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=564 qbuf-free=40390 argv-mem=320 obl=9 oll=0 omem=0 tot-mem=61952 events=r cmd=hmset user=default redir=-1
argv[0]: 'HMSET'
argv[1]: 'RQ_Follow:RQ_Offer_35754_RQ_OfferDetail_80553_NV01338'
argv[2]: 'id'
argv[3]: '874259'
argv[4]: 'offer_detail_id'
argv[5]: '80553'
argv[6]: 'ma_nhan_vien'
argv[7]: 'NV01338'
argv[8]: 'trang_thai'
argv[9]: 'active'
argv[10]: 'nguoi_tao'
argv[11]: 'thuyenlb'
argv[12]: 'ngay_tao'
argv[13]: '10/25/2022 1:45:53 PM'
argv[14]: 'seen'
argv[15]: 'False'
argv[16]: 'seen_time'
argv[17]: 'null'
argv[18]: 'type'
argv[19]: ''
argv[20]: 'hinh_anh'
argv[21]: 'http://files-upload.pmcty.com/dev/UploadFile/Jul2022/2361/newAva2361_20220706082534114.jpg'
argv[22]: 'ten_nhan_vien'
argv[23]: 'Lê Đình Thanh'
1:M 25 Oct 2022 06:45:53.869 # key 'RQ_Follow:RQ_Offer_35754_RQ_OfferDetail_80553_NV01338' found in DB containing the following object:
1:M 25 Oct 2022 06:45:53.869 # Object type: 4
1:M 25 Oct 2022 06:45:53.869 # Object encoding: 2
1:M 25 Oct 2022 06:45:53.869 # Object refcount: 1

------ MODULES INFO OUTPUT ------
# ai_versions
ai_RedisAI_version:1.2.5
ai_low_level_API_version:1
ai_rdb_version:4

# ai_git
ai_git_sha:746b199e69f272d12aab00c26d31c8e35eb48b29

# ai_load_time_configs
ai_threads_per_queue:1
ai_inter_op_parallelism:0
ai_intra_op_parallelism:0
ai_model_execution_timeout:5000
ai_backend_memory_limit:0

# ai_backends_info

# ai_cpu
ai_self_used_cpu_sys:96.001021
ai_self_used_cpu_user:61.430869
ai_children_used_cpu_sys:0.105533
ai_children_used_cpu_user:0.114077
ai_main_thread_used_cpu_sys:5.001021
ai_main_thread_used_cpu_user:9.430869
ai_queue_CPU_bthread_n1_used_cpu_total:141.290601

# graph_executing commands

# rg
rg_nexecutions:0
rg_nregistrations:0

# rg_regisrations

# rg_plugins
rg_GearsPythonPlugin:version=10000

# rg_python_stats
rg_TotalAllocated:23732600
rg_PeakAllocated:8283512
rg_CurrAllocated:8191000

# rg_python_requirements

# rg_python_sessions

# ReJSON_trace
ReJSON_trace:   0: redis_module::base_info_func
   1: rejson::__info_func
   2: modulesCollectInfo
             at /usr/src/redis/src/module.c:7078:9
   3: logModulesInfo
             at /usr/src/redis/src/debug.c:1598:22
   4: printCrashReport
             at /usr/src/redis/src/debug.c:1849:5
      sigsegvHandler
             at /usr/src/redis/src/debug.c:1831:5
   5: <unknown>
   6: NumericRange_Add
   7: NumericRangeNode_Add.localalias
   8: NumericRangeTree_Add
   9: IndexerBulkAdd
  10: indexBulkFields
  11: Indexer_Process
  12: Indexer_Add
  13: Document_AddToIndexes
  14: IndexSpec_UpdateDoc
  15: Indexes_UpdateMatchingWithSchemaRules
  16: HashNotificationCallback
  17: moduleNotifyKeyspaceEvent
             at /usr/src/redis/src/module.c:5961:13
  18: notifyKeyspaceEvent
             at /usr/src/redis/src/notify.c:111:6
  19: hsetCommand
             at /usr/src/redis/src/t_hash.c:684:5
  20: call
             at /usr/src/redis/src/server.c:3721:5
  21: processCommand
             at /usr/src/redis/src/server.c:4241:9
  22: processCommandAndResetClient
             at /usr/src/redis/src/networking.c:2039:9
      processInputBuffer
             at /usr/src/redis/src/networking.c:2140:17
  23: callHandler
             at /usr/src/redis/src/connhelpers.h:79:18
      connSocketEventHandler
             at /usr/src/redis/src/connection.c:295:14
  24: aeProcessEvents
             at /usr/src/redis/src/ae.c:427:17
  25: aeMain
             at /usr/src/redis/src/ae.c:487:9
  26: main
             at /usr/src/redis/src/server.c:6401:5
  27: __libc_start_main
  28: _start

------ FAST MEMORY TEST ------
1:M 25 Oct 2022 06:45:53.889 # Bio thread for job type #0 terminated
1:M 25 Oct 2022 06:45:53.889 # Bio thread for job type #1 terminated
1:M 25 Oct 2022 06:45:53.889 # Bio thread for job type #2 terminated
*** Preparing to test memory region 562098a9d000 (2277376 bytes)
*** Preparing to test memory region 562099d4b000 (544768 bytes)
*** Preparing to test memory region 7f2b10000000 (135168 bytes)
*** Preparing to test memory region 7f2b144ff000 (11534336 bytes)
*** Preparing to test memory region 7f2b15000000 (8388608 bytes)
*** Preparing to test memory region 7f2b15800000 (4194304 bytes)
*** Preparing to test memory region 7f2b15dff000 (4194304 bytes)
*** Preparing to test memory region 7f2b16200000 (8388608 bytes)
*** Preparing to test memory region 7f2b16a00000 (4194304 bytes)
*** Preparing to test memory region 7f2b16ffa000 (8388608 bytes)
*** Preparing to test memory region 7f2b177fb000 (8388608 bytes)
*** Preparing to test memory region 7f2b17ffc000 (8388608 bytes)
*** Preparing to test memory region 7f2b187fd000 (8388608 bytes)
*** Preparing to test memory region 7f2b18ffe000 (8388608 bytes)
*** Preparing to test memory region 7f2b197ff000 (8388608 bytes)
*** Preparing to test memory region 7f2b1a000000 (8388608 bytes)
*** Preparing to test memory region 7f2b1a800000 (4194304 bytes)
*** Preparing to test memory region 7f2b1ac6a000 (8388608 bytes)
*** Preparing to test memory region 7f2b1b4a1000 (9437184 bytes)
*** Preparing to test memory region 7f2b1bda2000 (8388608 bytes)
*** Preparing to test memory region 7f2b1c908000 (139264 bytes)
*** Preparing to test memory region 7f2b1c92b000 (8388608 bytes)
*** Preparing to test memory region 7f2b1d12c000 (8388608 bytes)
*** Preparing to test memory region 7f2b1d92d000 (8388608 bytes)
*** Preparing to test memory region 7f2b1e12e000 (8388608 bytes)
*** Preparing to test memory region 7f2b1e92f000 (8388608 bytes)
*** Preparing to test memory region 7f2b1f4e2000 (8388608 bytes)
*** Preparing to test memory region 7f2b1fce3000 (8388608 bytes)
*** Preparing to test memory region 7f2b206ad000 (12288 bytes)
*** Preparing to test memory region 7f2b206b1000 (8388608 bytes)
*** Preparing to test memory region 7f2b20eb2000 (8388608 bytes)
*** Preparing to test memory region 7f2b216b3000 (8388608 bytes)
*** Preparing to test memory region 7f2b21eb4000 (8388608 bytes)
*** Preparing to test memory region 7f2b226b5000 (8388608 bytes)
*** Preparing to test memory region 7f2b22eb6000 (8388608 bytes)
*** Preparing to test memory region 7f2b236b7000 (8388608 bytes)
*** Preparing to test memory region 7f2b23eb8000 (8388608 bytes)
*** Preparing to test memory region 7f2b246b9000 (8388608 bytes)
*** Preparing to test memory region 7f2b24eba000 (8388608 bytes)
*** Preparing to test memory region 7f2b256bb000 (8388608 bytes)
*** Preparing to test memory region 7f2b25ebc000 (8388608 bytes)
*** Preparing to test memory region 7f2b266bd000 (8388608 bytes)
*** Preparing to test memory region 7f2b26ebe000 (8388608 bytes)
*** Preparing to test memory region 7f2b276bf000 (8388608 bytes)
*** Preparing to test memory region 7f2b297fb000 (12288 bytes)
*** Preparing to test memory region 7f2b297ff000 (8388608 bytes)
*** Preparing to test memory region 7f2b2a000000 (8388608 bytes)
*** Preparing to test memory region 7f2b2a800000 (4194304 bytes)
*** Preparing to test memory region 7f2b2ac27000 (4096 bytes)
*** Preparing to test memory region 7f2b2ad7c000 (8192 bytes)
*** Preparing to test memory region 7f2b2b1b9000 (28672 bytes)
*** Preparing to test memory region 7f2b2b1c1000 (8388608 bytes)
*** Preparing to test memory region 7f2b2bbff000 (4096 bytes)
*** Preparing to test memory region 7f2b2bc00000 (8388608 bytes)
*** Preparing to test memory region 7f2b2c4d3000 (4096 bytes)
*** Preparing to test memory region 7f2b2c514000 (24576 bytes)
*** Preparing to test memory region 7f2b2c6db000 (16384 bytes)
*** Preparing to test memory region 7f2b2c6fd000 (16384 bytes)
*** Preparing to test memory region 7f2b2c9f1000 (16384 bytes)
*** Preparing to test memory region 7f2b2cbd2000 (8192 bytes)
*** Preparing to test memory region 7f2b2cc02000 (4096 bytes)**

**Comment by ashtul** [comment]
What is the RediSearch version or SHA?

I can see you are expiring documents and dropping indexes. Can you share more about how to reproduce the crash?

**Comment by vangxitrum** [comment]
i don't know how to reproduce the crash but i think it may relate to the command server.keys i use from StackExchange library.
After i stop using it, the crash dont show up anymore.
Do you have any ideal about this?

**Comment by ashtul** [comment]
This bug was fixed in PR #3017.
