### ISSUE TITLE
Wrong version is displayed when compiled from source 

### ISSUE THREAD

**Issue by zulander1** [RediSearch/RediSearch#3236]
It would be nice to see the proper version when the module is compiled  
Currently, the _Module List_ show  99999999

**Comment by MeirShpilraien** [comment]
You are using the master branch which has 999999 version

**Comment by zulander1** [comment]
> You are using the master branch which has 999999 version

Is there a repository for the module only? I can't seem to find it

**Comment by rafie** [comment]
Works as expected. As said, master branch is reporting `999999` as module version.
