### ISSUE TITLE
How to ft.search index "@foo:(*)"

### ISSUE THREAD

**Issue by hypo-thesis** [RediSearch/RediSearch#3241]
So I am trying to find any index which has foo at any value. I can find certain values by  : 
`ft.search index "@foo:(certainValue)"` , however I cannot find away to make `certainValue ` into a wildcard. 

How can I do that?

**Comment by oshadmi** [comment]
@hypo-thesis
You can use prefix/infix/suffix, using asteriske.g., 
`FT.SEARCH index "@foo:(*Va*)"`
`FT.SEARCH index "@foo:(*Val)"`
`FT.SEARCH index "@foo:(Val*)"`
Or you can use wildcard, e.g.,
`FT.SEARCH index "@foo:(w'h*llo*')"`

Please see
https://redis.io/docs/stack/search/reference/query_syntax/#search-query-syntax
https://redis.io/docs/stack/search/reference/query_syntax/#a-few-query-examples

**Comment by hypo-thesis** [comment]
> 

I think perhaps I was not super clear on `certainValue`, by that I meant ant value. Not necessarily starting with a VA or anything like that. Thanks for the input anyway.

**Comment by oshadmi** [comment]
You can have a dedicated index for that, e.g.,
`FT.CREATE idx FILTER EXISTS(@t) SCHEMA t TEXT`
And then get results, e.g., 
`FT.SEARCH idx *`

Or you can use `FT.AGGREGATE` with an existing index to scan all documents, e.g.,
`FT.AGGREGATE index * LOAD 1 @foo FILTER EXISTS(@foo) LOAD 1 @__key`
