### ISSUE TITLE
SOS: Strange Behavior when adding a Numeric filter

### ISSUE THREAD

**Issue by VagyokC4** [RediSearch/RediSearch#3249]
[Originally posted in the Redis-OM.NET repo:](https://github.com/redis/redis-om-dotnet/issues/262)

I'm running into a weird issue where my query, when using a Sortable numeric property gives back different results.

So using the following LinqPad code:
```csharp
	var requestFrom = 0.Dump("From");
	var requestTo = DateTime.UtcNow.ToUnixTimeMs().Dump("To");
	var query = redisDb.Records.Where(q => q.Accno == "XXX");

	query = query.Where(q => q.TimeSearch < requestTo);
	query = query.Where(q => q.TimeSearch > requestFrom);
        query = query.Where(x => x.Hold == false);

	var count = query.CountAsync();
	var results = query
		.OrderByDescending(x => x.TimeSearch)
		.Skip(0)
		.Take(10)
		.ToListAsync();

	await Task.WhenAll(count, results).ConfigureAwait(false);
	count.Result.Dump("Count");
```
Produces the following redis query:
```
"FT.SEARCH" "record-idx" "((((@Accno:{XXX}) (@TimeSearch:[-inf (1669166114118])) (@TimeSearch:[(0 inf])) (@Hold:{False}))" "LIMIT" "0" "0"
"SELECT" "0"
"FT.SEARCH" "record-idx" "((((@Accno:{XXX}) (@TimeSearch:[-inf (1669166114118])) (@TimeSearch:[(0 inf])) (@Hold:{False}))" "LIMIT" "0" "10" "SORTBY" "TimeSearch" "DESC"
"INFO" "all"
```
and produces the following INCONSISTENT results: (each flash is me re-running the LinqPad query)

https://user-images.githubusercontent.com/253250/203449888-96a1fd4b-2e95-4de0-8d9c-492b1e0866b9.mp4

But as soon as I comment out the TimeSearch clauses, I get consistent results again:
```csharp
	var requestFrom = 0.Dump("From");
	var requestTo = DateTime.UtcNow.ToUnixTimeMs().Dump("To");
	var query = redisDb.Records.Where(q => q.Accno == "XXX");

	// query = query.Where(q => q.TimeSearch < requestTo);
	// query = query.Where(q => q.TimeSearch > requestFrom);
        query = query.Where(x => x.Hold == false);

	var count = query.CountAsync();
	var results = query
		.OrderByDescending(x => x.TimeSearch)
		.Skip(0)
		.Take(10)
		.ToListAsync();

	await Task.WhenAll(count, results).ConfigureAwait(false);
	count.Result.Dump("Count");
```
producing this redis query:
```
"FT.SEARCH" "record-idx" "((@Accno:{XXX}) (@Hold:{False}))" "LIMIT" "0" "0"
"SELECT" "0"
"FT.SEARCH" "record-idx" "((@Accno:{XXX}) (@Hold:{False}))" "LIMIT" "0" "10" "SORTBY" "TimeSearch" "DESC"
"INFO" "all"
```

With results like so: (each flash is me re-running the query)

https://user-images.githubusercontent.com/253250/203450551-f782ba26-fdaf-4fa9-ac13-9c03cb5e095a.mp4

I see this issue with my current production data.  I say data because I can take a backup and run it locally and get the same results with production data running locally.  However, I have been unable to create a small simple test that reproduces the behavior using sample data.

For context I'm running RediSearch version 2.4.15 (Git=HEAD-89f8340e) in PRD and RediSearch version 2.4.16 (Git=HEAD-b10e5644) locally.  I'm using a 24GB dataset that has about 10M keys in total, with the current collection displaying the issue accounting for about 1M of those keys.

Any ideas?  Has anyone else observed this strange behavior?  Any suggestions on how I can make this repeatable? Any thing else I can provide to help get to the bottom of this issue?

**Comment by MeirShpilraien** [comment]
I did not check the exact case but my guess is that your first query encounters a timeout. Try analize it using FT.PROFILE: https://redis.io/commands/ft.profile/

**Comment by VagyokC4** [comment]
> "record-idx" "((((@Accno:{XXX}) (@TimeSearch:[-inf (1669166114118])) (@TimeSearch:[(0 inf])) (@Hold:{False}))" "LIMIT" "0" "10" "SORTBY" "TimeSearch" "DESC"

I think that was it.  Once I set the TIMEOUT = 0, the query took longer (~ 4 sec) but I do get consistent results.

Question: Is the search blocking, if it takes some queries longer to execute, how does that affect other queries from other users?

**Comment by VagyokC4** [comment]
I'm going to close this issue out.  Thank-you @MeirShpilraien for your help resolving this behavior.

**Comment by MeirShpilraien** [comment]
@VagyokC4 yes the search is blocking, this is why we have the timeout so it will not block for to long. We are working on having it run on a background thread without locking but I do not have an ETA for that yet...
