### ISSUE TITLE
Redis 6.2.7 crashed by signal: 11, si_code: 1 , Accessing address: 0xfffffffffffffff4

### ISSUE THREAD

**Issue by ravidsin** [RediSearch/RediSearch#3253]
8:M 25 Nov 2022 04:53:22.193 * Partial resynchronization request from 192.168.2.105:6379 accepted. Sending 4908 bytes of backlog starting from offset 75559.

=== REDIS BUG REPORT START: Cut & paste starting from here ===
8:M 25 Nov 2022 06:18:18.999 # Redis 6.2.7 crashed by signal: 11, si_code: 1
8:M 25 Nov 2022 06:18:18.999 # Accessing address: 0xfffffffffffffff4

------ INFO OUTPUT ------
# Server
redis_version:6.2.7
redis_git_sha1:b0ced98d
redis_git_dirty:0
redis_build_id:3ab097254b76b8ad
redis_mode:standalone
os:Linux 3.10.0-1160.53.1.el7.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:c11-builtin
gcc_version:10.3.1
process_id:8
process_supervised:no
run_id:7b3965c2926b580368b1c416c265566a9b7e1d45
tcp_port:6379
server_time_usec:1669375098998901
uptime_in_seconds:13621
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:8430714
executable:/usr/bin/redis-server
config_file:/opt/cisco/hybrid/conf/redis.conf
io_threads_active:0

# Clients
connected_clients:9
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:82
client_recent_max_output_buffer:0
blocked_clients:2
tracking_clients:0
clients_in_timeout_table:2

# Memory
used_memory:2662197
used_memory_human:2.54M
used_memory_rss:6262784
used_memory_rss_human:5.97M
used_memory_peak:2692250
used_memory_peak_human:2.57M
used_memory_peak_perc:98.88%
used_memory_overhead:2078839
used_memory_startup:846815
used_memory_dataset:583358
used_memory_dataset_perc:32.13%
allocator_allocated:2651223
allocator_active:6204416
allocator_resident:6204416
total_system_memory:10315116544
total_system_memory_human:9.61G
used_memory_lua:58368
used_memory_lua_human:57.00K
used_memory_scripts:10136
used_memory_scripts_human:9.90K
number_of_cached_scripts:8
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:2.34
allocator_frag_bytes:3553193
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.01
rss_overhead_bytes:58368
mem_fragmentation_ratio:2.36
mem_fragmentation_bytes:3611561
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:17018
mem_clients_normal:153310
mem_aof_buffer:0
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:6702
rdb_bgsave_in_progress:0
rdb_last_save_time:1669361477
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:0
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:507904
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0

# Stats
total_connections_received:21246
total_commands_processed:142396
instantaneous_ops_per_sec:932
total_net_input_bytes:20028615
total_net_output_bytes:6718192
instantaneous_input_kbps:135.65
instantaneous_output_kbps:130.49
rejected_connections:0
sync_full:1
sync_partial_ok:1
sync_partial_err:0
expired_keys:118
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:89
evicted_keys:0
keyspace_hits:18204
keyspace_misses:5595
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:284
total_forks:44
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:14090
dump_payload_sanitizations:0
total_reads_processed:147195
total_writes_processed:141122
io_threaded_reads_processed:0
io_threaded_writes_processed:0

# Replication
role:master
connected_slaves:1
slave0:ip=192.168.2.105,port=6379,state=online,offset=1976092,lag=0
master_failover_state:no-failover
master_replid:4c6a0c108ccc097bf35917f8c601ac0a8957d9f1
master_replid2:6d1f5164c8787a31daeecd6afc3512558ddb935f
master_repl_offset:2098880
second_repl_offset:75559
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1050305
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:15.672546
used_cpu_user:9.690442
used_cpu_sys_children:0.010918
used_cpu_user_children:0.012983
used_cpu_sys_main_thread:15.656624
used_cpu_user_main_thread:9.686117

# Modules
module:name=search,ver=999999,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]

# Commandstats
cmdstat_scard:calls=39,usec=15,usec_per_call=0.38,rejected_calls=0,failed_calls=0
cmdstat_unsubscribe:calls=18,usec=75,usec_per_call=4.17,rejected_calls=0,failed_calls=0
cmdstat_lrange:calls=96,usec=344,usec_per_call=3.58,rejected_calls=0,failed_calls=0
cmdstat_zrem:calls=41,usec=110,usec_per_call=2.68,rejected_calls=0,failed_calls=0
cmdstat_zscore:calls=21,usec=13,usec_per_call=0.62,rejected_calls=0,failed_calls=0
cmdstat_sadd:calls=48,usec=107,usec_per_call=2.23,rejected_calls=0,failed_calls=0
cmdstat_hset:calls=5906,usec=281560,usec_per_call=47.67,rejected_calls=0,failed_calls=0
cmdstat_replicaof:calls=9,usec=1339,usec_per_call=148.78,rejected_calls=0,failed_calls=1
cmdstat_lindex:calls=133,usec=208,usec_per_call=1.56,rejected_calls=0,failed_calls=0
cmdstat_srem:calls=39,usec=166,usec_per_call=4.26,rejected_calls=0,failed_calls=0
cmdstat_incrby:calls=23,usec=106,usec_per_call=4.61,rejected_calls=0,failed_calls=0
cmdstat_expire:calls=78,usec=168,usec_per_call=2.15,rejected_calls=0,failed_calls=0
cmdstat_info:calls=306,usec=51766,usec_per_call=169.17,rejected_calls=0,failed_calls=0
cmdstat_set:calls=10,usec=171,usec_per_call=17.10,rejected_calls=0,failed_calls=0
cmdstat_rpush:calls=172,usec=1346,usec_per_call=7.83,rejected_calls=0,failed_calls=0
cmdstat_FT.CREATE:calls=2,usec=559,usec_per_call=279.50,rejected_calls=0,failed_calls=1
cmdstat_get:calls=1648,usec=2285,usec_per_call=1.39,rejected_calls=0,failed_calls=0
cmdstat_smembers:calls=4,usec=14,usec_per_call=3.50,rejected_calls=0,failed_calls=0
cmdstat_replconf:calls=20562,usec=30551,usec_per_call=1.49,rejected_calls=0,failed_calls=0
cmdstat_del:calls=38,usec=50,usec_per_call=1.32,rejected_calls=0,failed_calls=0
cmdstat_psync:calls=7658,usec=17620,usec_per_call=2.30,rejected_calls=0,failed_calls=7656
cmdstat_subscribe:calls=18,usec=72,usec_per_call=4.00,rejected_calls=0,failed_calls=0
cmdstat_zadd:calls=19,usec=141,usec_per_call=7.42,rejected_calls=0,failed_calls=0
cmdstat_client:calls=13585,usec=31536,usec_per_call=2.32,rejected_calls=0,failed_calls=0
cmdstat_eval:calls=6680,usec=342365,usec_per_call=51.25,rejected_calls=0,failed_calls=6432
cmdstat_publish:calls=10,usec=7,usec_per_call=0.70,rejected_calls=0,failed_calls=0
cmdstat_exists:calls=7351,usec=13409,usec_per_call=1.82,rejected_calls=0,failed_calls=0
cmdstat_blpop:calls=13130,usec=98043,usec_per_call=7.47,rejected_calls=0,failed_calls=0
cmdstat_hget:calls=3272,usec=5421,usec_per_call=1.66,rejected_calls=0,failed_calls=0
cmdstat_llen:calls=5127,usec=15916,usec_per_call=3.10,rejected_calls=0,failed_calls=0
cmdstat_ping:calls=56026,usec=36190,usec_per_call=0.65,rejected_calls=0,failed_calls=0
cmdstat_hgetall:calls=5,usec=16,usec_per_call=3.20,rejected_calls=0,failed_calls=0
cmdstat_hdel:calls=68,usec=1242,usec_per_call=18.26,rejected_calls=0,failed_calls=0
cmdstat_pexpire:calls=40,usec=120,usec_per_call=3.00,rejected_calls=0,failed_calls=0
cmdstat_setnx:calls=68,usec=865,usec_per_call=12.72,rejected_calls=0,failed_calls=0
cmdstat_zrangebyscore:calls=146,usec=344,usec_per_call=2.36,rejected_calls=0,failed_calls=0

# Errorstats
errorstat_ERR:count=6432
errorstat_Index:count=1
errorstat_NOMASTERLINK:count=7656
errorstat_UNBLOCKED:count=1

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=61,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=19844 addr=127.0.0.1:54574 laddr=127.0.0.1:6379 fd=17 name=drapi-local-redis-client age=1543 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=49798 events=r cmd=hset user=default redir=-1
id=16172 addr=192.168.2.105:50936 laddr=192.168.1.105:6379 fd=18 name= age=5096 idle=0 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=17018 events=r cmd=replconf user=default redir=-1
id=58 addr=127.0.0.1:54126 laddr=127.0.0.1:6379 fd=13 name=drapi-local-redis-client age=13574 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=49798 events=r cmd=hset user=default redir=-1
id=59 addr=127.0.0.1:54128 laddr=127.0.0.1:6379 fd=14 name=drapi-local-redis-client age=13574 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=21 obl=0 oll=0 omem=0 tot-mem=49811 events=r cmd=blpop user=default redir=-1
id=52 addr=127.0.0.1:54096 laddr=127.0.0.1:6379 fd=9 name= age=13575 idle=23 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=17010 events=r cmd=info user=default redir=-1
id=60 addr=127.0.0.1:54130 laddr=127.0.0.1:6379 fd=15 name=drapi-local-redis-client age=13574 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=49798 events=r cmd=hset user=default redir=-1
id=15615 addr=127.0.0.1:41716 laddr=127.0.0.1:6379 fd=12 name=drapi-local-redis-client age=5370 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=17002 events=r cmd=ping user=default redir=-1
id=56 addr=127.0.0.1:54122 laddr=127.0.0.1:6379 fd=11 name=drapi-local-redis-client age=13574 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=49798 events=r cmd=hset user=default redir=-1
id=15604 addr=127.0.0.1:41692 laddr=127.0.0.1:6379 fd=10 name=drapi-local-redis-client age=5375 idle=0 flags=b db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=22 obl=0 oll=0 omem=0 tot-mem=49812 events=r cmd=blpop user=default redir=-1
id=64 addr=127.0.0.1:54156 laddr=127.0.0.1:6379 fd=16 name= age=13572 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=144 qbuf-free=32624 argv-mem=75 obl=4 oll=0 omem=0 tot-mem=49921 events=r cmd=hset user=default redir=-1

------ CURRENT CLIENT INFO ------
id=64 addr=127.0.0.1:54156 laddr=127.0.0.1:6379 fd=16 name= age=13572 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=144 qbuf-free=32624 argv-mem=75 obl=4 oll=0 omem=0 tot-mem=49921 events=r cmd=hset user=default redir=-1
argv[0]: 'HSET'
argv[1]: 'pagTask_2782'
argv[2]: 'createdTime'
argv[3]: '1669375098995'
argv[4]: 'mediaChannel'
argv[5]: 'chat'
argv[6]: 'mediaType'
argv[7]: 'CHAT'
argv[8]: 'id'
argv[9]: '2782'
8:M 25 Nov 2022 06:18:18.999 # key 'pagTask_2782' found in DB containing the following object:
8:M 25 Nov 2022 06:18:18.999 # Object type: 4
8:M 25 Nov 2022 06:18:18.999 # Object encoding: 5
8:M 25 Nov 2022 06:18:18.999 # Object refcount: 1

------ MODULES INFO OUTPUT ------
# search_version
search_RedisSearch_version:6.2.7

# search_index
search_number_of_indexes:1

# search_fields_statistics
search_fields_text:Text=2
search_fields_numeric:Numeric=1,Sortable=1

# search_runtime_configurations
search_concurrent_mode:OFF
search_enableGC:ON
search_minimal_term_prefix:2
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:1000000
search_max_aggregate_results:-1
search_search_pool_size:20
search_index_pool_size:8
search_gc_scan_size:100
search_min_phonetic_term_length:3

------ FAST MEMORY TEST ------
8:M 25 Nov 2022 06:18:18.999 # Bio thread for job type #0 terminated
8:M 25 Nov 2022 06:18:18.999 # Bio thread for job type #1 terminated
8:M 25 Nov 2022 06:18:18.999 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55f7039a9000 (122880 bytes)
*** Preparing to test memory region 55f7054ae000 (24576 bytes)
*** Preparing to test memory region 55f7054b4000 (8192 bytes)
*** Preparing to test memory region 7fcbb9f6f000 (122880 bytes)
*** Preparing to test memory region 7fcbb9f98000 (114688 bytes)
*** Preparing to test memory region 7fcbb9fb9000 (36864 bytes)
*** Preparing to test memory region 7fcbb9fc7000 (16384 bytes)
*** Preparing to test memory region 7fcbb9fcd000 (1318912 bytes)
*** Preparing to test memory region 7fcbba110000 (294912 bytes)
*** Preparing to test memory region 7fcbba15b000 (16384 bytes)
*** Preparing to test memory region 7fcbba160000 (28672 bytes)
*** Preparing to test memory region 7fcbba168000 (8192 bytes)
*** Preparing to test memory region 7fcbba16b000 (167936 bytes)
*** Preparing to test memory region 7fcbbad9d000 (49152 bytes)
*** Preparing to test memory region 7fcbbadab000 (135168 bytes)
*** Preparing to test memory region 7fcbbadce000 (249856 bytes)
*** Preparing to test memory region 7fcbbb570000 (45056 bytes)
*** Preparing to test memory region 7fcbbb57b000 (1073152 bytes)
*** Preparing to test memory region 7fcbbb717000 (12288 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

350:C 25 Nov 2022 06:18:21.022 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo

**Comment by ravidsin** [comment]
I need urgent help on this help. Would be of great help if I get some pointers on this crash.

**Comment by MeirShpilraien** [comment]
@ravidsin is this the entire crash report? I do not see the trace part...

**Comment by ravidsin** [comment]
This is the entire bug report that I see in Redis logs. Please see the attached log file . 
[stdout.log](https://github.com/RediSearch/RediSearch/files/10111373/stdout.log)

**Comment by ravidsin** [comment]
This crash is happening intermittently on different machines without any specific pattern.

**Comment by ravidsin** [comment]
Thanks @rafie  for the info. Redis does not create rdb file as we use diskless replication. I will try to get the output of the MONITOR command in next occurrence.

**Comment by ravidsin** [comment]
On a side note, I was wondering if https://github.com/RediSearch/RediSearch/pull/3017 bug is related in any way . Let me know!

**Comment by ravidsin** [comment]
While we wait for the next occurrence of the problem and collect output of Monitor command, Could you please let us know if we are hitting into #3017 ?
