### ISSUE TITLE
Redis Crash when free(): invalid pointer

### ISSUE THREAD

**Issue by githubname1024** [RediSearch/RediSearch#3262]
I deployed a redis cluster on Ubuntu.
The redisearch version is 2.6.3.
The redis version is 6.2.4.
There are six nodes(3 master/3 slave) in the cluster.
When I run the cluster failover, after a few seconds, the redis instance will crash. 
Is it a bug? Or how should I do failover on redis cluster with installing redisearch.
![图片](https://user-images.githubusercontent.com/100768089/205565698-936055ab-03c5-435b-954f-04f8e654bd5f.png)

**Comment by rafie** [comment]
Hello @githubname1024,
Can you please provide us with some reproduction code?
Thank you.
