### ISSUE TITLE
How to compare two fields? 

### ISSUE THREAD

**Issue by GollaSaiVenkatesh** [RediSearch/RediSearch#3265]
I have a requirement where I need to get all keys in the index which doesn't have the same value for two tag fields. 
For eg:
key A B C
key1 1 1 2
key2 1 2 3
key3 1 4 7
consider A, B and C are fields in the index and I want all the keys which don't have the same value for A and B  then the result should be key2, key3 since key1 contains the same value for A and B 

Is this possible using Redisearch queries?

**Comment by gkorland** [comment]
It's possible, but it won't be too efficient and will run a full scan.
```
ft.aggregate doc * LOAD 4 @__key @a @b @c FILTER "@a!=@b"
```
