### ISSUE TITLE
Redisearch is not installed through default make what we have & there is no prerequisites properly mentioned in the repo

### ISSUE THREAD

**Issue by vinayakgaonkar** [RediSearch/RediSearch#3271]
Hi Please check output below, make fails. We should mention this in the prerequisites of this repository. So its clear on what version make should be used. Or Git for that matter.

```
[root tmp]# cd RediSearch
[root RediSearch]# ls -lrt
total 100
drwxr-xr-x 10   126 Dec  9 15:54 tests
drwxr-xr-x  2    85 Dec  9 15:54 srcutil
drwxr-xr-x  9  4096 Dec  9 15:54 src
drwxr-xr-x  2  4096 Dec  9 15:54 sbin
-rw-r--r--  1 13537 Dec  9 15:54 README.md
drwxr-xr-x  2     42 Dec  9 15:54 pack
-rw-r--r--  1  18068 Dec  9 15:54 Makefile
-rw-r--r--  1   258 Dec  9 15:54 LICENSE.txt
drwxr-xr-x  2     40 Dec  9 15:54 licenses
drwxr-xr-x  4    32 Dec  9 15:54 docs
drwxr-xr-x 19   4096 Dec  9 15:54 deps
drwxr-xr-x  6     71 Dec  9 15:54 coord
-rw-r--r--  1  32350 Dec  9 15:54 commands.json
-rw-r--r--  1   355 Dec  9 15:54 codecov.yml
-rw-r--r--  1   7643 Dec  9 15:54 CMakeLists.txt
drwxr-xr-x  6     57 Dec  9 15:54 build
[root@ RediSearch]# make setup
deps/readies/mk/main:6: *** GNU Make version is too old. Aborting..  Stop.
```

**Comment by gkorland** [comment]
Can you please call `./sbin/setup`? it should straight the environment dependencies.

**Comment by vinayakgaonkar** [comment]
Thanks for your comment @gkorland . But the issue did not go away even after running ./sbin/setup. 
[root@ RediSearch]# ./sbin/setup
# readies version: 51e61b5
yum install -q -y ca-certificates
yum install -q -y curl wget unzip
/tmp/RediSearch/deps/readies/bin/enable-utf8
yum install -q -y git gawk jq openssl rsync unzip
yum install -q -y patch
yum install -q -y redhat-lsb-core
/tmp/RediSearch/deps/readies/bin/getepel
yum install -q -y libatomic
/tmp/RediSearch/deps/readies/bin/getgcc --modern
yum install -q -y libtool m4 automake openssl-devel
yum install -q -y python3-devel
dir=$(mktemp -d /tmp/tar.XXXXXX); (cd $dir; wget --no-verbose -O tar.tgz http://redismodules.s3.amazonaws.com/readies/gnu/gnu-tar-1.32-x64-centos7.tgz; tar -xzf tar.tgz -C /; ); rm -rf $dir
/usr/bin/python3 /tmp/RediSearch/deps/readies/bin/getcmake --usr
/usr/bin/python3 /tmp/RediSearch/deps/readies/bin/getrmpytools --reinstall --modern
yum install -q -y lcov
/usr/bin/python3 -m pip install --disable-pip-version-check --user  gevent
/usr/bin/python3 -m pip install --disable-pip-version-check --user  -r /tmp/RediSearch/tests/pytests/requirements.txt
/tmp/RediSearch/deps/readies/bin/getaws
NO_PY2=1 /tmp/RediSearch/deps/readies/bin/getpudb
[root@ RediSearch]# make setup
deps/readies/mk/main:6: *** GNU Make version is too old. Aborting..  Stop.

**Comment by rafie** [comment]
Hello @vinayakgaonkar,
After running `./sbin/setup` please invoke `bash -l` and then `make`.
This will run `/etc/profile.d/*` scripts what were installed by `./sbin/setup` to modify the environment (inc. `PATH`) to allow us to use a modern GCC toolchain that also includes the right `make` version.
