### ISSUE TITLE
Documentation: wording in Query_Syntax.md documentation.

### ISSUE THREAD

**Issue by jc-rsn** [RediSearch/RediSearch#3278]
In [Query Syntax](https://github.com/RediSearch/RediSearch/blob/master/docs/docs/reference/Query_Syntax.md) documentation may be it is better to phrase the first bullet point
as `Multi-word phrases that are simply a list of tokens, e.g. foo bar baz, and imply intersection (AND) of the terms.`
instead of `Multi-word phrases simply a list of tokens, e.g. foo bar baz, and imply intersection (AND) of the terms.`

**Comment by ashtul** [comment]
@nermiller

**Comment by nermiller** [comment]
Fixed by https://github.com/RediSearch/RediSearch/pull/3291
