### ISSUE TITLE
Hi Team,  I am running redis as a stand alone server using older version of redis (4.0.13 ) , now I would like to upgrade to new version of redis (7.0.4). How can I upgrade to latest version(7.0.4)?

### ISSUE THREAD

**Issue by Benerjee-git** [RediSearch/RediSearch#3282]

**Comment by gkorland** [comment]
See: [Getting started with Redis](https://redis.io/docs/getting-started/)

**Comment by Benerjee-git** [comment]
Can any one please help me

**Comment by gkorland** [comment]
@Benerjee-git did you follow the [Getting started with Redis](https://redis.io/docs/getting-started/) what went wrong?
