### ISSUE TITLE
FT.AGGREGATE [object Object] result

### ISSUE THREAD

**Issue by chkp-omris** [RediSearch/RediSearch#3286]
Hi, I'm using RediSearch to index JSON objects in which some fields are unstructured, and I'd like to query these fields.
I've defined an index as follows:
```
FT.CREATE idx ON JSON SCHEMA '$..*[?(@ =~ "")]' AS wildcardText TEXT SORTABLE '$..*[?(@ <= 0 || @ >= 0)]' AS wildcardNumeric NUMERIC SORTABLE
```
Which, to my understanding, should index every recursive field. So, fields with string value would be indexed as `TEXT` under the alias `wildcardText` and numeric values would be indexed as `NUMERIC` under the alias `wildcardNumeric`.

To demonstrate my issue, I'm setting a simple JSON object, which for this issue should be enough to demonstrate the usage. 
```
JSON.SET object1 . '{"attributes": {"x": 1, "y": 50}}'
```
Generally, the point is that the value of field `attributes` is always an object, but that object's structure is unknown at the time of index creation.

For my usage, I need to implement a query over RediSearch that returns all JSON objects that match a given condition. For example: `attributes.y >= 0 && attributes.y <= 49`, which in this case should NOT return `object1`.

This is problematic because my index isn't aware of `attributes.y`, it's aware of `wildcardNumeric`.
So I could've ran `FT.SEARCH idx '@wildcardNumeric:[0 49]'`, which would return `object1` because `attributes.x` is `1` and it's also indexed so it matches this query.
This isn't good enough for me for 2 reasons:
1. I have to filter the results on the client's end afterwards
2. I need to get from RediSearch the *correct* total number of objects, without having the objects themselves, so RediSearch has to filter the objects that match this query before it gives my client a result.

I then tried implementing this using `FT.AGGREGATE` combined with `LOAD`ing the relevant fields, and `FILTER`ing according to the condition I'm querying with. This is what I came up with:
```
FT.AGGREGATE idx '@wildcardNumeric:[0 49]' LOAD 2 * @attributes\.y FILTER '@attributes\.y >= 0 && @attributes\.y <= 49'
```
But the result I'm getting is just [object Object]:
```
1) "1"
2) 1) "[object Object]"
```

I'm thinking this is an error because I couldn't find any documentation or reference to it in RediSearch or RedisJSON's code. Nor did I find any issue regarding this, but since my usage is very uncommon, that's reasonable.

I also tried a matching `FILTER` to see if it will give me `object1`, but it returned the exact same result with [object Object].
```
FT.AGGREGATE idx '@wildcardNumeric:[0 49]' LOAD 2 * @attributes\.y FILTER '@attributes\.y >= 0 && @attributes\.y <= 50'
```

I'm testing all these commands using `docker run -p 6379:6379 redislabs/redisearch` BTW.

Could you please let me know whether this is an expected behavior or not?
And if it is expected, what does this result mean?

Thanks 😄

**Comment by oshadmi** [comment]
@chkp-omris I did not yet investigate your findings,
but you can try using redis-stack (`docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest`)
to do some "unstructured" queries on both NUMERIC (0 <= n <= 49) and TEXT attributes, for example:
```
127.0.0.1:6379> FT.CREATE idx ON JSON SCHEMA '$.attributes[*][?(@>=0 && @<=49)]' as num NUMERIC '$.attributes[*][?(@ =~ ".*")]' as txt TEXT
OK
127.0.0.1:6379> JSON.SET object1 . '{"attributes": {"x": 1, "y": 50, "z":"foo"}}'
OK
127.0.0.1:6379> JSON.SET object2 . '{"attributes": {"x": 1, "y": 49, "z":"bar"}}'
OK
127.0.0.1:6379> JSON.SET object3 . '{"attributes": {"x": 51, "y": 50, "w":"foobar"}}'
OK
127.0.0.1:6379> FT.SEARCH idx '@num:[0 51]'
1) (integer) 2
2) "object1"
3) 1) "$"
   2) "{\"attributes\":{\"x\":1,\"y\":50,\"z\":\"foo\"}}"
4) "object2"
5) 1) "$"
   2) "{\"attributes\":{\"x\":1,\"y\":49,\"z\":\"bar\"}}"
127.0.0.1:6379> FT.SEARCH idx '@txt:(foo*)'
1) (integer) 2
2) "object1"
3) 1) "$"
   2) "{\"attributes\":{\"x\":1,\"y\":50,\"z\":\"foo\"}}"
4) "object3"
5) 1) "$"
   2) "{\"attributes\":{\"x\":51,\"y\":50,\"w\":\"foobar\"}}"

```
