### ISSUE TITLE
redis-server Crashed 

### ISSUE THREAD

**Issue by guoyahao** [RediSearch/RediSearch#3293]
4058:C 22 Dec 2022 04:04:04.459 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
4058:C 22 Dec 2022 04:04:04.459 # Redis version=6.9.241, bits=64, commit=00000000, modified=0, pid=4058, just started
4058:C 22 Dec 2022 04:04:04.459 # Configuration loaded
4058:M 22 Dec 2022 04:04:04.461 # Server initialized

=== REDIS BUG REPORT START: Cut & paste starting from here ===
4058:M 22 Dec 2022 04:04:04.463 # Redis 6.9.241 crashed by signal: 6, si_code: -6
4058:M 22 Dec 2022 04:04:04.463 # Killed by PID: 4058, UID: 0
4058:M 22 Dec 2022 04:04:04.463 # Crashed running the instruction at: 0x7f3c6323d387

------ STACK TRACE ------
EIP:
/lib64/libc.so.6(gsignal+0x37)[0x7f3c6323d387]

Backtrace:
/lib64/libpthread.so.0(+0xf630)[0x7f3c635e4630]
/lib64/libc.so.6(gsignal+0x37)[0x7f3c6323d387]
/lib64/libc.so.6(abort+0x148)[0x7f3c6323ea78]
/lib64/libc.so.6(+0x2f1a6)[0x7f3c632361a6]
/lib64/libc.so.6(+0x2f252)[0x7f3c63236252]
/opt/redis-stack/lib/redisearch.so(+0xdfb51)[0x7f3c5a953b51]
/opt/redis-stack/lib/redisearch.so(RediSearch_InitModuleInternal+0x2ba)[0x7f3c5a9a8a5a]
/opt/redis-stack/bin/redis-server *:6379(moduleLoad+0xb9)[0x4ddd29]
/opt/redis-stack/bin/redis-server *:6379(moduleLoadFromQueue+0x33)[0x4ddfa3]
/opt/redis-stack/bin/redis-server *:6379(main+0x356)[0x440f56]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f3c63229555]
/opt/redis-stack/bin/redis-server *:6379[0x4413ba]

------ REGISTERS ------
4058:M 22 Dec 2022 04:04:04.464 # 
RAX:0000000000000000 RBX:00007f3c647f3000
RCX:ffffffffffffffff RDX:0000000000000006
RDI:0000000000000fda RSI:0000000000000fda
RBP:00007f3c63391f60 RSP:00007fff47df4b58
R8 :0000000000000000 R9 :00000000020eb520
R10:0000000000000008 R11:0000000000000202
R12:00007f3c5aacafbd R13:00007f3c5aacc1e0
R14:00007f3c5acb5948 R15:00007f3c5acbbcb8
RIP:00007f3c6323d387 EFL:0000000000000202
CSGSFS:0000000000000033
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b67) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b66) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b65) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b64) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b63) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b62) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b61) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b60) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5f) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5e) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5d) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5c) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5b) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b5a) -> 0000000000000000
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b59) -> 0000000000000020
4058:M 22 Dec 2022 04:04:04.464 # (00007fff47df4b58) -> 00007f3c6323ea78

------ INFO OUTPUT ------
# Server
redis_version:6.9.241
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:79cf147c911caf62
redis_mode:standalone
os:Linux 3.10.0-1160.6.1.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:4058
process_supervised:no
run_id:881c04596267bfcaae7fb844c57e255c74c8b792
tcp_port:6379
server_time_usec:1671653044463658
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:10708660
executable:/opt/redis-stack/bin/redis-server
config_file:/etc/redis-stack.conf
io_threads_active:0

# Clients
connected_clients:0
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
clients_in_timeout_table:0

# Memory
used_memory:908120
used_memory_human:886.84K
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:908120
used_memory_peak_human:886.84K
used_memory_peak_perc:100.54%
used_memory_overhead:192
used_memory_startup:0
used_memory_dataset:907928
used_memory_dataset_perc:99.98%
allocator_allocated:0
allocator_active:0
allocator_resident:0
total_system_memory:8200855552
total_system_memory_human:7.64G
used_memory_lua:37888
used_memory_vm_eval:37888
used_memory_lua_human:37.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:37888
used_memory_vm_total:75776
used_memory_vm_total_human:74.00K
used_memory_functions:184
used_memory_scripts:184
used_memory_scripts_human:184B
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:-nan
allocator_frag_bytes:0
allocator_rss_ratio:-nan
allocator_rss_bytes:0
rss_overhead_ratio:-nan
rss_overhead_bytes:0
mem_fragmentation_ratio:-nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:8
mem_replication_backlog:0
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:0
mem_cluster_links:0
mem_aof_buffer:8
mem_allocator:jemalloc-5.2.1
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:0
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1671653044
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:0
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
aof_current_size:0
aof_base_size:0
aof_pending_rewrite:0
aof_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:0
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:0
total_writes_processed:0
io_threaded_reads_processed:0
io_threaded_writes_processed:0
reply_buffer_shrinks:0
reply_buffer_expands:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:9b00680692140c05aa415bd2573092fd53bf6c86
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.001366
used_cpu_user:0.003955
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000
used_cpu_sys_main_thread:0.001330
used_cpu_user_main_thread:0.003991

# Modules

# Commandstats
cmdstat_info:calls=1,usec=26,usec_per_call=26.00,rejected_calls=0,failed_calls=0

# Errorstats

# Latencystats
latency_percentiles_usec_info:p50=26.111,p99=26.111,p99.9=26.111

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------

------ MODULES INFO OUTPUT ------

------ CONFIG DEBUG OUTPUT ------
io-threads-do-reads yes
lazyfree-lazy-eviction no
lazyfree-lazy-expire no
lazyfree-lazy-server-del no
lazyfree-lazy-user-del no
lazyfree-lazy-user-flush no
repl-diskless-sync yes
replica-read-only yes
activedefrag no
repl-diskless-load disabled
sanitize-dump-payload no
io-threads 3
list-compress-depth 0
proto-max-bulk-len 512mb
client-query-buffer-limit 1gb

------ FAST MEMORY TEST ------
*** Preparing to test memory region 866000 (2293760 bytes)
*** Preparing to test memory region 20b9000 (135168 bytes)
*** Preparing to test memory region 20da000 (135168 bytes)
*** Preparing to test memory region 20fb000 (159744 bytes)
*** Preparing to test memory region 7f3c5acb6000 (28672 bytes)
*** Preparing to test memory region 7f3c61200000 (8388608 bytes)
*** Preparing to test memory region 7f3c62054000 (8192 bytes)
*** Preparing to test memory region 7f3c6226e000 (8192 bytes)
*** Preparing to test memory region 7f3c635d0000 (20480 bytes)
*** Preparing to test memory region 7f3c637ed000 (16384 bytes)
*** Preparing to test memory region 7f3c63c50000 (16384 bytes)
*** Preparing to test memory region 7f3c647e2000 (45056 bytes)
*** Preparing to test memory region 7f3c647f2000 (8192 bytes)
*** Preparing to test memory region 7f3c647f4000 (4096 bytes)
*** Preparing to test memory region 7f3c647f7000 (4096 bytes)
.O.O.O.O.O.O.O.O.O.O.O.O.O.O.O
Fast memory test PASSED, however your memory can still be broken. Please run a memory test for several hours if possible.

------ DUMPING CODE AROUND EIP ------
Symbol: gsignal (base: 0x7f3c6323d350)
Module: /lib64/libc.so.6 (base 0x7f3c63207000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x7f3c6323d350 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
4058:M 22 Dec 2022 04:04:04.491 # dump of function (hexdump of 183 bytes):
648b0c25d4020000648b3425d002000085f67534b8ba0000000f0589c164890425d002000089c64863d74863f64863f9b8ea0000000f05483d00f0ffff771ef3c30f1f800000000085c97fdb89c8f7d881e1ffffff7f0f44c689c1ebca488b159c0a3900f7d86489024883c8ffc3669085ff780cf7dfe9850200000f1f440000488b05790a390064c70016000000b8ffffffffc3662e0f1f8400000000006690900f1f440000662e0f1f84000000000048c7c00f000000

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.

**Comment by gkorland** [comment]
Which version of Redis are you using? 
On which OS? 
Which RediSearch version? (how did you build/download it?)

From the report I see this strange numbers:
```
redis_version:6.9.241
os:Linux 3.10.0-1160.6.1.el7.x86_64 x86_64
```

**Comment by guoyahao** [comment]
> 您使用的是哪个版本的 Redis？ 在哪个操作系统上？ 哪个 RediSearch 版本？（你是如何构建/下载它的？）
> 
> 从报告中我看到这个奇怪的数字：
> 
> ```
> redis_version:6.9.241
> os:Linux 3.10.0-1160.6.1.el7.x86_64 x86_64
> ```

vi /etc/yum.repos.d/redis.repo

[Redis]
name=Redis
baseurl=http://packages.redis.io/rpm/rhel7
enabled=1
gpgcheck=1

curl -fsSL https://packages.redis.io/gpg > /tmp/redis.key
sudo rpm --import /tmp/redis.key
sudo yum install epel-release
sudo yum install redis-stack-server

**Comment by guoyahao** [comment]
yum info redis-stack-server
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Installed Packages
Name        : redis-stack-server
Arch        : x86_64
Version     : 7.0.0_RC2
Release     : 1.rhel7
Size        : 85 M
Repo        : installed
From repo   : Redis
Summary     : Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:
URL         : https://redis.io
License     : Redis Source Available License
Description : Redis Stack Server includes the Redis server with the following additional capabilities installed and ready to use:
            :  .
            : RedisJSON: Store, retrieve and perform atomic updates on JSON documents
            : RedisSearch: Full text search and secondary indexing over hashes and JSON documents
            : RedisTimeSeries: Store and manage time series data in Redis, perform aggregated queries and downsampling
            : RedisBloom: Extends Redis to include popular probabilistic data structures including Bloom and Cuckoo filters, Count-Min Sketch and Top-K
            : RedisGraph: Adds graph database and Cypher query capabilities to Redis

**Comment by guoyahao** [comment]
cat /proc/version
Linux version 3.10.0-1160.6.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Nov 17 13:59:11 UTC 2020

cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)

**Comment by guoyahao** [comment]
yum --showduplicates list redis-stack-server
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Installed Packages
redis-stack-server.x86_64                                                                                                                                                 7.0.0_RC2-1.rhel7                                                                                                                                                  @RedisAvailable Packages
redis-stack-server.x86_64                                                                                                                                                 6.2.0_v1-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 6.2.2_v2-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 6.2.2_v3-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 6.2.4_v3-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 6.2.4_v4-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 6.2.6_v0-1.rhel7                                                                                                                                                   Redis 
redis-stack-server.x86_64                                                                                                                                                 7.0.0_RC1-1.rhel7                                                                                                                                                  Redis 
redis-stack-server.x86_64                                                                                                                                                 7.0.0_RC2-1.rhel7                                                                                                                                                  Redis
