### ISSUE TITLE
Cannot unload module

### ISSUE THREAD

**Issue by xMizuki** [RediSearch/RediSearch#3309]
I downloaded RediSearch .so file from https://redis.com/redis-enterprise-software/download-center but it didn't work (`(error) Module Disabled in Open Source Redis`).
I tried to unload the module but it says ` (error) ERR Error unloading module: the module exports one or more module-side data types, can't unload`

What can I do to unload the module?

**Comment by xMizuki** [comment]
Can someone help please? When I try to load the real module now, it throws:
```
127.0.0.1:6379> module load /etc/redis/redisearch.so
(error) ERR Error loading the extension. Please check the server logs.
```

**Comment by gkorland** [comment]
> (error) ERR Error loading the extension. Please check the server logs.

What do you see in the server logs?

**Comment by xMizuki** [comment]
> > (error) ERR Error loading the extension. Please check the server logs.
> 
> What do you see in the server logs?

It says that it cannot initialize, but anyway after some hours redis crashed with error `Internal error in RDB reading offset 48233775, function at rdb.c:2627 -> The RDB file contains module data I can't load: no matching module type 'ReJSON-RL'`
