### ISSUE TITLE
Inconsistent behavior of sorting functionality

### ISSUE THREAD

**Issue by sergey-morenets** [RediSearch/RediSearch#3319]
Hi

Sorting documentation mentioned: 

`If an index includes sortable fields, you can add the SORTBY parameter to the search request (outside the query body), and order the results by it. `
https://redis.io/docs/stack/search/reference/sorting/

However I could created index without SORTABLE keyword and still can use SORTBY option. Is it error in the documentation/implementation?

```
FT.CREATE personIdx ON JSON SCHEMA $.name as name TEXT $.age as age NUMERIC 
JSON.SET person2 $ '{"name": "Peter", "age": 45}'
FT.SEARCH personIdx "@name:(John|Peter)" SORTBY name
```

Redis Stack: 7.0.6 RC3

**Comment by ashtul** [comment]
@sergey-morenets Thank you for the issue.
Indeed, we have added the functionality where the field data will be loaded dynamically if not set as SORTBALE.
@adrianoamaral @nermiller

**Comment by sergey-morenets** [comment]
Hi @ashtul 
Thank you for the update.
Does that mean SORTABLE keyword is not need anymore?

**Comment by oshadmi** [comment]
> Hi @ashtul Thank you for the update. Does that mean SORTABLE keyword is not needed anymore?

It can still be used for better latency as explained in the [doc](https://redis.io/docs/interact/search-and-query/advanced-concepts/sorting/#declaring-sortable-fields)
