### ISSUE TITLE
Escaping

### ISSUE THREAD

**Issue by hypo-thesis** [RediSearch/RediSearch#3320]
I have an index search as such :  

`{email : foo@bar.com}`

`ft.create U ON JSON PREFIX 1 U_ SCHEMA $.email AS email TEXT`

`ft.search U foo` > returns results
yet `ft.search U foo\\@bar` returns `1) "0"`

How can I search for the email ? [this ](https://github.com/RediSearch/RediSearch/pull/2852/commits/6ccc5b3d87fc5617f0189c3c4d3af1732d3c5983)didn't work.

**Comment by hypo-thesis** [comment]
It must be stored as TAG not as TEXT

**Comment by oshadmi** [comment]
@hypo-thesis You can use TEXT like this (more details [here](https://redis.io/docs/stack/search/reference/escaping/#the-rules-of-text-field-tokenization))
```
127.0.0.1:6379> ft.create U ON JSON PREFIX 1 U_ SCHEMA $.email AS email TEXT
OK
127.0.0.1:6379> JSON.SET U_1 $ '{"name":"homer", "email":"h\\@simpsons.com"}'
OK
127.0.0.1:6379> FT.SEARCH U '@email:h\@simpsons'
1) (integer) 1
2) "U_1"
3) 1) "$"
   2) "{\"name\":\"homer\",\"email\":\"h\\\\@simpsons.com\"}"


```
