### ISSUE TITLE
Queries  slow when data is updated quickly，data size 1200k,Result is not match

### ISSUE THREAD

**Issue by chiwenheng** [RediSearch/RediSearch#3322]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/5625556/210598192-8c86182b-1d77-446c-bb73-846b1b040c76.png">
<img width="559" alt="image" src="https://user-images.githubusercontent.com/5625556/210598335-3dd80e4d-8d69-4864-9499-a055ea1ac4eb.png">

<img width="815" alt="image" src="https://user-images.githubusercontent.com/5625556/210598564-2f562465-cba2-436e-9a73-91c70ffffcd1.png">

**Comment by chiwenheng** [comment]
# Modules
module:name=search,ver=20416,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]

# Server
redis_version:6.2.7
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:4496adb9316d923b
redis_mode:standalone
os:Linux 3.10.0-1062.el7.x86_64 x86_64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:186029
process_supervised:no
run_id:af53e595919afa485461c860ba5ea9122b9880c7
tcp_port:6380
server_time_usec:1672848584454530
uptime_in_seconds:39799
uptime_in_days:0
hz:10

**Comment by chiwenheng** [comment]
if need dump.rdb ?

**Comment by oshadmi** [comment]
@chiwenheng Thank you for reporting this.
Did you intend to close this issue?
If not, `dump.rdb` would be helpful.


> Result is not match

Can you please explain which result?

For longer queries TIMEOUT could affect the results. You can try adding `TIMEOUT 0` to `FT.SEARCH` to see you get all results.
