### ISSUE TITLE
Make Levenshtein Distance configurable

### ISSUE THREAD

**Issue by kugesh-Rajasekaran** [RediSearch/RediSearch#3328]

**Comment by ashtul** [comment]
@kugesh-Rajasekaran  Can you please ellaborate? You can currently choose 1,2 or 3 as distance using `%foo%`, `%%bar%%` or `%%%baz%%%`.

**Comment by kugesh-Rajasekaran** [comment]
Can we make the  Levenshtein Distance as configurable
something like this

```
   FT.SEARCH INDEX_KEY "@title:%WORD_TO_SEARCH%" DISTANCE_TO_MATCH  6
```

For the above code the  Levenshtein Distance can be until 6
