### ISSUE TITLE
"AS" command and property name containig "AS" string conflict

### ISSUE THREAD

**Issue by vzambo64** [RediSearch/RediSearch#3345]
The following statement drops error:

FT.SEARCH index * RETURN 3 "$.someJsonPath" AS asa

(error) Alias for RETURN cannot be `AS`

When alias name is starting with “AS” FT.SEARCH and FT.AGGREGATE drops error.
Is it a known feature or a bug?

Redis: 6.2.6
ReJSON: ver=20007
search: ver=20207

**Comment by oshadmi** [comment]
Fixed by #3259
