### ISSUE TITLE
FT.AGGREGATE LOAD sequence

### ISSUE THREAD

**Issue by vzambo64** [RediSearch/RediSearch#3347]
There is a strange feature that seems to be a bug in the FT.AGGREAGE LOAD command on JSON data.
When the sequence of the LOAD paths are changed the result of the FT.AGGREGATE different, LOAD results in missing properties in the reply by certain conditions.
Here is an example json object under a key in the database:

```json
{
   "asset": {
      "type": "vehicle",
      "alternativeIds": {
         "userId": "20040",
         "userId1": "20040"
      }
   } 
}
```

The `LOAD 2 "$.asset.alternativeIds","$.asset.alternativeIds.userId"` returns both - correct.
The `LOAD 2 "$.asset.alternativeIds.userId1","$.asset.alternativeIds.userId"` 
or the `LOAD 2 "$.asset.alternativeIds.userId","$.asset.alternativeIds.userId"` returns only one result - seems to be a bug.

It is not about the jsonPath, becuse:
`LOAD 2 "$.asset..userId1","$asset.alternativeIds.userId"` returns two results - correctly.

Workaround is only to LOAD the objects on a higher junction before objects of lower location in the tree.

Redis version=6.2.6
ReJSON ver=20007
search ver= 20207

**Comment by gkorland** [comment]
Are you sure about the Search/JSON versions? 
Can you please try with the latest redis-stack version?
```
docker run -p 6379:6379 redis/redis-stack-server:latest
```

It seems to work as expected:
```
127.0.0.1:6379> json.set a $ '{"asset":{"type":"vehicle","alternativeIds":{"userId":"20040","userId1": "20040"}}}'
OK
127.0.0.1:6379> ft.create idx on JSON PREFIX 1 a SCHEMA $.type as type TEXT
OK
127.0.0.1:6379> ft.AGGREGATE idx * LOAD 2 $.asset.alternativeIds $.asset.alternativeIds.userId
1) (integer) 1
2) 1) "$.asset.alternativeIds"
   2) "{\"userId\":\"20040\",\"userId1\":\"20040\"}"
   3) "$.asset.alternativeIds.userId"
   4) "20040"
127.0.0.1:6379> ft.AGGREGATE idx * LOAD 2 $.asset.alternativeIds.userId1 $.asset.alternativeIds.userId
1) (integer) 1
2) 1) "$.asset.alternativeIds.userId1"
   2) "20040"
   3) "$.asset.alternativeIds.userId"
   4) "20040"
```

**Comment by vzambo64** [comment]
Thank you for the test.
I got the same results. The example i sent was not proper.
Let's create a key with:
{
  "objectId": "32691",
  "persistent": {
    "static": {
      "asset": {
        "type": "vehicle",
        "alternativeIds": {
          "userId": "20040",
          "userId1": "20041"
        }
      }
    }
  }
}
JSON document.
Index:
FT.CREATE index ON JSON SCHEMA $.persistent.static.asset.type AS type TAG 
test:
FT.SEARCH index *
results in one result, OK.

FT.AGGREGATE  index * LOAD 7 "$.objectId" "$.persistent.static.asset.alternativeIds.userId" AS identifier "$.persistent.static.asset" AS data  
Result:
1) (integer) 1
2) 1) "$.objectId"
   2) "32691"
   3) "identifier"
   4) "20040"
The data property is missing.

FT.AGGREGATE  index * LOAD 7 "$.objectId" "$.persistent.static.asset" AS data  "$.persistent.static.asset.alternativeIds.userId" AS identifier
Result:
1) (integer) 1
2) 1) "$.objectId"
   2) "32691"
   3) "data"
   4) "{\"type\":\"vehicle\",\"alternativeIds\":{\"userId\":\"20040\",\"userId1\":\"20041\"}}"
   5) "identifier"
   6) "20040"
The three properties are there, OK.

FT.AGGREGATE  index * LOAD 7 "$.objectId" "$.persistent.static..alternativeIds.userId" AS identifier "$.persistent.static.asset" AS data
Result:
1) (integer) 1
2) 1) "$.objectId"
   2) "32691"
   3) "identifier"
   4) "20040"
   5) "data"
   6) "{\"type\":\"vehicle\",\"alternativeIds\":{\"userId\":\"20040\",\"userId1\":\"20041\"}}"
The three properties are there, OK.
The only difference between the first and the third FT.AGGREGATE command is in the second JSON path. Instead of "$.persistent.static.asset.alternativeIds.userId" used "$.persistent.static..alternativeIds.userId" path.

Test has been made with latest redis-stack version.
