### ISSUE TITLE
BUG - expired keys are deleted from the index during query execution

### ISSUE THREAD

**Issue by meiravgri** [RediSearch/RediSearch#3351]
In the current behavior, if loading the key from Redis keyspace fails (`RedisModule_OpenKey` fails), we delete the document from the spec. (added in PR  #2937  )
As `RedisModule_OpenKey` notifies if the key has expired, this causes two problems:
1. We might redundantly delete the document twice (once when the notification callback is called, and then when we return to the document loading function)
 
3. The master might have extended this key expiration time, but the slave wasn't updated yet, so although we shouldn't,
we remove the key from the index. As a result, the master and slave will not be the same.

Thanks :)

**Comment by oshadmi** [comment]
@meiravgri You refer to #2973 and I think you meant #2937

**Comment by meiravgri** [comment]
correct. Fixed

**Comment by oshadmi** [comment]
Fixed by #3355
