### ISSUE TITLE
How to aggregate tag fields

### ISSUE THREAD

**Issue by Goddywu** [RediSearch/RediSearch#3374]
I have these dataset.
```
JSON.SET live_agg:112 $ '{"liveId":"112","startTime":1675389770,"liveStatus":"1","deliverTimeLimit":20,"jobList":[{"jobId":"234","cityCode":"222","l1Code":"1","l2Code":"2","jobName":"JAVA"},{"jobId":"214","cityCode":"212","l1Code":"2","l2Code":"1","jobName":"IOS"}]}'
JSON.SET live_agg:124 $ '{"liveId":"124","startTime":1675389770,"liveStatus":"1","deliverTimeLimit":24,"jobList":[{"jobId":"12","cityCode":"222","l1Code":"1","l2Code":"4","jobName":"JAVA"},{"jobId":"13","cityCode":"122","l1Code":"4","l2Code":"3","jobName":"IOS"}]}'
```
This is my index.
```
FT.CREATE idx:live_agg ON JSON PREFIX 1 live_agg: SCHEMA $.liveId AS liveId TAG $.startTime AS startTime NUMERIC $.liveStatus AS liveStatus TAG $.deliverTimeLimit AS deliverTimeLimit NUMERIC $.jobList.*.jobId as jobId TAG $.jobList.*.cityCode AS cityCode TAG $.jobList.*.l1Code AS l1Code TAG  $.jobList.*.l2Code AS l2Code TAG 
```

Question:
1. how to get all jobIds in a specific live  

<img width="558" alt="image" src="https://user-images.githubusercontent.com/29056050/216554732-b6a127c1-f6e7-4e8c-ba64-d5fa6cceb8e1.png">
👆 I only got one jobId in live112.  

2. how to get all distinct jobId   （I think this is relate to Q1 ）

<img width="439" alt="image" src="https://user-images.githubusercontent.com/29056050/216555012-a7d821d2-95b4-4127-9a2f-5f00e41b361a.png">

**Comment by claridgicus** [comment]
Following along, my understanding after reading the documentation is that this is not possible.

**Comment by oshadmi** [comment]
Please add `DIALECT 3` (or greater) to the query.
From [doc](https://redis.io/docs/interact/search-and-query/query/):

> As of RediSearch v2.6.1, `DIALECT 3` returns JSON rather than scalars from multivalue attributes.
