### ISSUE TITLE
Sortby result is case sensitive regardless of UNF settings

### ISSUE THREAD

**Issue by jessy100** [RediSearch/RediSearch#3385]
Hi,

I'm trying to sort a sortable textField while using rediSearch + RedisJson. Whenever i sort on a text field it will first do A-Z and then a-z fields. I've tried playing with UNF on and off but it seems to make no difference. 

Reproduction:

FT.CREATE itemIdx ON JSON PREFIX 1 item: SCHEMA $.name AS name TEXT SORTABLE

JSON.SET item:1 $ '{"name":"aa"}'
JSON.SET item:2 $ '{"name":"bb"}'
JSON.SET item:3 $ '{"name":"dd"}'
JSON.SET item:4 $ '{"name":"CC"}'

ft.search itemIdx * sortby name desc RETURN 1 name 

result:

1) (integer) 4
2) "item:4"
3) 1) "name"
   2) "CC"
4) "item:1"
5) 1) "name"
   2) "aa"
6) "item:2"
7) 1) "name"
   2) "bb"
8) "item:3"
9) 1) "name"
   2) "dd"

i would expect CC to come third, not first.

Any known issues or workarounds in this regard?

**Comment by jessy100** [comment]
@oshadmi I see your PR, adjusting docs. Thank for clarifying! Does this effectively mean the case i describe above will never work with redis Json? Sorting regardless of case?

**Comment by MeirShpilraien** [comment]
Try this:
```
127.0.0.1:6379> ft.aggregate itemIdx * LOAD 1 @name apply lower(@name) as name_lower SORTBY 1 @name_lower
1) (integer) 4
2) 1) "name"
   2) "aa"
   3) "name_lower"
   4) "aa"
3) 1) "name"
   2) "bb"
   3) "name_lower"
   4) "bb"
4) 1) "name"
   2) "CC"
   3) "name_lower"
   4) "cc"
5) 1) "name"
   2) "dd"
   3) "name_lower"
   4) "dd"
```

**Comment by jessy100** [comment]
That works @MeirShpilraien . I will work on replacing my FT.Search with FT.Aggregate  :) Thank you very much.
