### ISSUE TITLE
Index and search JSON documents

### ISSUE THREAD

**Issue by fahadahammed** [RediSearch/RediSearch#3392]
When I tried to create the index following the example from [here](https://redis.io/docs/stack/search/indexing_json/):

```bash
> FT.CREATE itemIdx ON JSON PREFIX 1 item: SCHEMA $.name AS name TEXT $.description as description TEXT $.price AS price NUMERIC $.embedding AS embedding VECTOR FLAT 6 DIM 4 DISTNACE_METRIC L2 TYPE FLOAT32
"Bad arguments for algorithm FLAT: DISTNACE_METRIC"
```

It is giving `Bad arguments for algorithm FLAT: DISTNACE_METRIC`. What we are doing wrong?

**Comment by GuyAv46** [comment]
Hello
Seems like there is a typo in the documentation. Will be fixed.
Please try `DISTANCE_METRIC` instead of `DISTNACE_METRIC`
Thanks for reporting the issue!
