### ISSUE TITLE
Redis search inconsistent result and unusual behavior

### ISSUE THREAD

**Issue by nsharma28** [RediSearch/RediSearch#3411]
Versions : 
Redis == 4.5.1 
RedisSearch == 2.1.1 

We are storing data in below format (JSON):
Key : 1:99817194206008 
Value :  { 
"geom":"}r|wFvsidMfCl@v@P??z@T??x@Z@?zC|A@@HN@@BL?@?T??Cf@?@ET" 
"color":"#969393" 
"lat":40.782549421819645 
"lon":-74.27467417737601 
"isupdated":false 
} 
There are approx 4.3 milions keys in the 0th db. We do bulk insertion using pipe operator:  
pipe.json().set(Key,'$',Value) 

We have created index on 'lat' and 'lon' using below command:
FT.CREATE geoFunc_Class1Index ON JSON PREFIX 1 1: SCHEMA $.lat AS lat NUMERIC $.lon AS lon NUMERIC.

We are Updating only color value using Redis Json Set Command. In which we use below command to update and we use it with the pipe operator for bulk update. Every 10 seconds we update 100 k data using below command:

 pipe.json().set(Key,'$.color',Value) 

We search data using below command:
FT.SEARCH geoFunc_Class1Index '@lon:[-73.30511072070027 (-73.18938889972561] @lat:[40.70732758510509 (40.73539081740466]'

Now our problem is, when we don't do any update then redis search works perfectly and give proper counts in return. But after running color update code after sometime (30 min - 1 hour approx) it either gave 0 result or less count than expected. However, that particular key exists in the db and satisfying the search criterion, still redis search does not return them in result.

When we delete all keys and reinsert them it starts working normally.
We are only updating color value and nothing else we have verified the code many times. But why updating color causing such issue is beyond our understanding.

**Comment by oshadmi** [comment]
@nsharma28 Please try adding a parameter `TIMEOUT 0` to `FT.SEARCH` command to see if it is related to timeout.

**Comment by ebuxk** [comment]
@nsharma28 
This looks related to our issue. After a seemingly random amount of time ft.search just doesn't return results despite the keys and fields existing.
Could you check what version of Redis Server and RedisSearch on the server you are using? We started noticing this issue with Redis 6.2.6 & RediSearch 2.4.3.

Potentially related issue: https://github.com/RediSearch/RediSearch/issues/3370

Our solution is to detect this index corruption then recreate the index. We do this by inserting dummy data every few seconds then running ft.search. If ft.search doesn't return the dummy data, then we recreate the index.

@oshadmi
My team has seen a very similar issue on DBs with only a handful of keys.

**Comment by nsharma28** [comment]
@ebuxk 
we are using Redis Server  6.2.10 and RedisSearch  2.2.6. Our both indexes are also numeric.

**Comment by nsharma28** [comment]
@ebuxk in which version of Redis Server and RedisSearch it was working fine ??

**Comment by ebuxk** [comment]
> @ebuxk in which version of Redis Server and RedisSearch it was working fine ??

@nsharma28 
Sorry I just realized there was a typo in my above post. I meant RedisSearch v2.6.4 but typed our RedisJSON version of 2.4.3 instead. I'm going to edit that post to fix this error.
We were on RedisSearch 2.4.16, then were auto updated to 2.6.4 through our RedisLabs subscription. It wasn't until after this update that we started noticing issues. Doesn't mean there weren't issues before, we just didn't notice them before.

**Comment by nsharma28** [comment]
@ebuxk as you said that there are 20 redis db and you are facing issue in 3 of them. Is it working fine in another Redis with same versions ?

**Comment by ebuxk** [comment]
We have about 20 redis DB's. About half of them don't see very much, if any load. These are DB's on standby for developer sandboxes or external-QA deployments.
Every DB that does see any amount of load has eventually exhibited this corrupted index behavior.
At this point we've probably seen it on 6 to 8 of our 20 DBs, we stopped rigorously tracking this metric as it seemed inevitable that any DB with our versions would corrupt eventually.
