### ISSUE TITLE
Redisearch inconsistent result and query syntax order

### ISSUE THREAD

**Issue by ackelle** [RediSearch/RediSearch#3437]
Versions:

Redis 7.0.6
RediSearch-2.6.4

We have created index below command:

FT.CREATE idx:table ON HASH PREFIX 1 table: SCHEMA ApplicationId TAG DestinationName TEXT OriginName TEXT

There are two TEXT field and one TAG field in our query. 

We try to filter data in redis below rules:
•	DestinationName  **CONTAINS** “3gppnetwork.org”
•	ApplicationId  **NOT EQUAL** 17121
•	OriginName  **NOT CONTAINS** “4gppnetwork.org”

When we run below command, redisearch giving us consistent result:
FT.SEARCH idx:diameters "(@DestinationName :(3gppnetwork\.org) -@ApplicationId :{17121} -@OriginName :(4gppnetwork\.org))"

When we relocate conditions on query, redisearch giving us different result from first: (We changed order of ApplicationId and DestinationName rules)
FT.SEARCH idx:diameters "(-@ApplicationId :{17121}  @DestinationName :(3gppnetwork\.org) -@OriginName :(4gppnetwork\.org))"

Is there any rule order between operator?
We observe that redisearch giving us consistent result when NOT operator located last on query. is it true approach for getting consistent result? 

SQL WHERE Clause syntax does not affected by relocation condition between AND operator. Why redisearch couldnt work like this?

**Comment by oshadmi** [comment]
@ackelle Please add the parameter `DIALECT 2` to the `FT.SEARCH` command.
Please see [query syntax](https://redis.io/docs/stack/search/reference/query_syntax/) doc for more details.
Also related to the [`DEFAULT_DIALECT`](https://redis.io/docs/stack/search/configuring/#default_dialect) configuration
