### ISSUE TITLE
Highlighter doesn't work if fields are not provided

### ISSUE THREAD

**Issue by kefahi** [RediSearch/RediSearch#3459]
According to the [documentation](https://redis.io/docs/stack/search/reference/highlight/) (and this sounds like the best desirable behavior as well) ...

`If no FIELDS directive is passed, then all fields returned are highlighted.`

However, if "FIELDS" are not passed, nothing is highlighted.

`FT.SEARCH myindex "test" HIGHLIGHT`

Simply returns the whole matching json documents without any highlight. 

Using :

- RedisJson 2.4.4
- RediSearch 2.6.5
- Redis 7.0.5

**Comment by meiravgri** [comment]
Please provide your index schema.

**Comment by saadadel** [comment]
Steps to reproduce 

1- create index:

```
FT.CREATE myindex ON JSON SCHEMA $.title AS title TEXT $.desc as desc TEXT
```

2- add json doc:

```
JSON.SET j1 $ '{"title":"foo", "desc":"more about foo"}'
```

3- add another json doc:

```
JSON.SET j2 $ '{"title":"bar", "desc":"more about bar"}'
```

4- search with HIGHLIGHT:

```
FT.SEARCH myindex "about" HIGHLIGHT
```

Result: nothing is highlighted
