### ISSUE TITLE
Indexing on Hash Requires Fields to Be Escaped (dashes don't work)

### ISSUE THREAD

**Issue by SimonJTurner** [RediSearch/RediSearch#3464]
# Indexing on Hash Requires Fields to be Escaped (dashes don't work)

The [RedisSearch 1.2 release notes](https://docs.redis.com/latest/modules/redisearch/release-notes/redisearch-1.2-release-notes/#backslash-escaping) hint at this, but it seems to still be causing confusion.

## Related Issues/Threads:
#2019
#3204 
[Getting Started #107](https://github.com/RediSearch/redisearch-getting-started/issues/107)
#478 

## Summary
RedisSearch is treating dashes (`-`) within hash fields as separators when creating indexes. It is expected that the query would have to honor properly escaping of `-` (negation symbol) and others, but it's less expected that data-at-rest would be consumed this way, and, it is in conflict with the notes on #2019, specifically ["No, you won't have to escape on insertion"](https://github.com/RediSearch/RediSearch/issues/2019#issuecomment-851392607). To be fair, it is true that the dash(`-`) does not need escaped when specifying fields in a `HSET` operation, but it can be clarified.

Follow the steps below to prove the behavior in question! In the meantime, to @segfaulty, @jeremytm, @vixalien, and @flowt-au, it seems like the best options are to replace any dashes (on write) with `\-` in order to have the index tokenizer pick up your values as you intend them, perhaps use some other char, or even add another field to search against (with more normalized data).

## Repro

Set up your hashes and index.

```sh
HSET docs:1 title full-text
HSET docs:2 title full\-text
HSET docs:3 title full\\-text

FT.CREATE idx:dashes ON HASH PREFIX 1 docs: SCHEMA title TEXT
```

Naive example, which works as expected.

```sh
FT.SEARCH idx:dashes full-text 

1) "0"
//  Explain:
"INTERSECT {
    UNION {
        full
        +full(expanded)
    }
    NOT{
        text
    }
}
"
```

---

The query `full\-text`, (evaluated against the index as `full-text`), matches against `docs:2`. So, `docs:2`'s `title` field (value: `full\-text`) is in the index as `full-text`).

```sh
FT.SEARCH idx:dashes full\-text
1) "1"
2) "docs:2"
3) 1) "title"
   2) "full\-text"
// Explain
"UNION {
  full-text
  +full-text(expanded)
}
"
```

Finally, it becomes clear that the index's tokenizer splits on `-` in the field, which seems defective. Both of these `VERBATIM` queries return the same result `docs:1`, our control/default.

```sh
ft.SEARCH idx:dashes @title:full VERBATIM
// Explain
"@title:full
"
ft.SEARCH idx:dashes @title:text VERBATIM
// Explain
"@title:text
"

//Results for each
1) "1"
2) "docs:1"
3) 1) "title"
   2) "full-text"
```

Hopefully this tidies up a few loose threads and provides one place to address them, but in the meantime I'm just gonna bite the bullet and store with the escape, but having data-at-rest lose a touch of integrity is not ideal.

**Comment by vixalien** [comment]
thanks for the tip

**Comment by flowt-au** [comment]
Thanks, I will look at that. :-)
