### ISSUE TITLE
Vector similarity - Following the documentation does not work

### ISSUE THREAD

**Issue by Barbery** [RediSearch/RediSearch#3496]
I follow the document below:
https://redis.io/docs/stack/search/indexing_json/#:~:text=60%2C70%2C80%2C90%2C100%5D%2C%5C%22vendor_id%5C%22%3A%5B100%2C300%5D%7D%22-,Index%20JSON%20arrays%20as%20VECTOR,-Starting%20with%20RediSearch

but seems not work, where is wrong?

```bash
127.0.0.1:6379> FT.CREATE itemIdx5 ON JSON PREFIX 1 item: SCHEMA $.embedding[*] AS embedding VECTOR FLAT 6 DIM 4 DISTANCE_METRIC L2 TYPE FLOAT32
OK
127.0.0.1:6379> JSON.SET item:1 $ '{"name":"Noise-cancelling Bluetooth headphones","description":"Wireless Bluetooth headphones with noise-cancelling technology","price":99.98,"stock":25,"colors":["black","silver"],"embedding":[[0.87,-0.15,0.55,0.03]]}'
OK
127.0.0.1:6379> JSON.SET item:2 $ '{"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","price":64.99,"stock":17,"colors":["black","white"],"embedding":[[-0.7,-0.51,0.88,0.14],[-0.8,-0.15,0.33,-0.01]]}'
OK
127.0.0.1:6379> FT.SEARCH itemIdx5 '*=>[KNN 2 @embeddings $blob]' PARAMS 2 blob \x01\x01\x01\x01 DIALECT 2
0
```

**Comment by Barbery** [comment]
> Here you created a vector field named `embedding` and you are searching on `embeddings`. We will fix the documentation so the name is consistent
> 
> Notice that this example is a multi-value scenario. you can simplify the scenario for single-value (single vector for each field in each document) if you want

You are right, problem solved. 
I have another question, can I use `PARAMS 2 blob [1,1,1,1] DIALECT 2` instead of `PARAMS 2 blob \x01\x01\x01\x01 DIALECT 2` ? I try, response error:`(error) Error parsing vector similarity query: query vector blob size (22) does not match index's expected size (16).`

**Comment by GuyAv46** [comment]
no. redis-cli expects to get the vector as a binary blob. you can use one of Redis' clients (like redispy) where it's simpler to do so. check out [this](https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb) notebook for example

**Comment by Barbery** [comment]
> no. redis-cli expects to get the vector as a binary blob. you can use one of Redis' clients (like redispy) where it's simpler to do so. check out [this](https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb) notebook for example

So sad, I use phpredis to connect redis server, I don't know how to covert binary blob like python `query_vector.tobytes()`,

**Comment by GuyAv46** [comment]
No worries, RediSearch will be supported in the next [predis](https://github.com/predis/predis) minor release (2.2).

**Comment by vladvildanov** [comment]
@Barbery Hi, RediSearch support will be added in next `v2.2` release in another client Predis (wrapper around phpredis). You can simply pass `blob` argument as byte-string, here's a code snippet, but as I said it's still on development and will be available soon 

```
$client = new Client();

$ftCreateArguments = (new CreateArguments())
    ->on('JSON')
    ->prefix(['item:']);

$schema = [
    new VectorField('$.embedding[*]', 'FLAT', ['DIM', 4, 'DISTANCE_METRIC', 'L2', 'TYPE', 'FLOAT'], 'embedding'),
];

$client->ftcreate('itemIdx5', $schema, $ftCreateArguments);

$client->jsonset(
    'item:1',
    '$',
    '{"name":"Noise-cancelling Bluetooth headphones","description":"Wireless Bluetooth headphones with noise-cancelling technology","price":99.98,"stock":25,"colors":["black","silver"],"embedding":[[0.87,-0.15,0.55,0.03]]}'
);

$client->jsonset(
    'item:2',
    '$',
    '{"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","price":64.99,"stock":17,"colors":["black","white"],"embedding":[[-0.7,-0.51,0.88,0.14],[-0.8,-0.15,0.33,-0.01]]}'
);

$ftSearchArguments = (new SearchArguments())
    ->params(['blob', '\x01\x01\x01\x01'])
    ->dialect('2');

var_dump($client->ftsearch('itemIdx5', '*=>[KNN 2 @embedding $blob]', $ftSearchArguments));
exit;
```
Output:
```
array(5) {
  [0]=>
  int(2)
  [1]=>
  string(6) "item:1"
  [2]=>
  array(4) {
    [0]=>
    string(17) "__embedding_score"
    [1]=>
    string(13) "1.08280003071"
    [2]=>
    string(1) "$"
    [3]=>
    string(217) "{"name":"Noise-cancelling Bluetooth headphones","description":"Wireless Bluetooth headphones with noise-cancelling technology","price":99.98,"stock":25,"colors":["black","silver"],"embedding":[[0.87,-0.15,0.55,0.03]]}"
  }
  [3]=>
  string(6) "item:2"
  [4]=>
  array(4) {
    [0]=>
    string(17) "__embedding_score"
    [1]=>
    string(14) "0.771500051022"
    [2]=>
    string(1) "$"
    [3]=>
    string(193) "{"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","price":64.99,"stock":17,"colors":["black","white"],"embedding":[[-0.7,-0.51,0.88,0.14],[-0.8,-0.15,0.33,-0.01]]}"
  }
}
```

**Comment by chayim** [comment]
@vladvildanov can you take a look with *predis*?
