### ISSUE TITLE
Querying tag fields throw syntax error

### ISSUE THREAD

**Issue by rasrov** [RediSearch/RediSearch#3497]

**Comment by rasrov** [comment]
Hi,

I am trying to create a simple tag query and execute with RedisInsight, but I am not sure why the following sintaxys is throwing an error.

`FT.SEARCH my-index "@tags:{ Is raining }"`

I always getting this error:

`Syntax error at offset 27 near raining`

I tryed with another text and it's working properlly. I don't know why is only throwing error when I write "Is" befor.

**Comment by oshadmi** [comment]
@rasrov Please try adding an argument `DIALECT 2` to the command

**Comment by rasrov** [comment]
@oshadmi

Thanks, it's works!

But I have another question.

How can I add `DIALECT 2` argument into EntityStream query of Redis OM Spring library?
