### ISSUE TITLE
Aggregations with multiple params on the same field

### ISSUE THREAD

**Issue by claridgicus** [RediSearch/RediSearch#3500]
Question, Bug or Feature Request - I'm not sure!

My understanding is that I can feed the AGGREGATE command a SEARCH query and get an aggregate by running my ops on it.
With that understanding, I assumed I was able to run the same complexity of SEARCH query.

Given an index like this
`{
				'$.title': {
					type: SchemaFieldTypes.TEXT,
					SORTABLE: 'UNF',
					AS: 'title',
				},
				'$.type': {
					type: SchemaFieldTypes.TEXT,
					AS: 'type',
				},
				'$.tags': {
					type: SchemaFieldTypes.TAG,
					AS: 'tags',
				},
			},`

Running an Aggregate query like 

`@tags:{sa|vic} @tags:{gin} GROUPBY 1 @type`

Results in an error
[ErrorReply: Syntax error at offset n near type]

Running an Aggregate like 

`@tags:{sa|vic} GROUPBY 1 @type`

Is successful

If this is the correct behavior, A case be made to provide a helpful error message to a redis rookie, that detects if the query is too complex for aggregate

I'm using redislabs - redisstack latest available
RediSearch v. 20605
RedisJSON v. 2.4.5
RedisGraph v. 2.10.8
RedisTimeSeries v. 1.8.5
RedisBloom v. 2.4.4

node.js 18.x
redis: "4.6.5" npm package

**Comment by claridgicus** [comment]
A slight twist - if I'm using redisinsights

and I run this.

`FT.AGGREGATE index '@price:[10 9000] @tags:{style|country}' GROUPBY 1 @vendor`

It works - but if I run it without encapsulating the search query - it fails

`FT.AGGREGATE index @price:[10 9000] @tags:{style|country} GROUPBY 1 @vendor`

**Comment by oshadmi** [comment]
@claridgicus The syntax is
`FT.AGGREGATE index query_expression  [arguments...]`
Please wrap with quotes the query expression, excluding the various arguments of [FT.AGGREGATE](https://redis.io/commands/ft.aggregate/) , such as the `GROUPBY`, etc., for example, 
`FT.AGGREGATE index '@tags:{sa|vic} @tags:{gin}' GROUPBY 1 @type`
