### ISSUE TITLE
Build Filed

### ISSUE THREAD

**Issue by ucanmailsharath** [RediSearch/RediSearch#3503]
build failed with following steps in AWS EC-2 Amazon Linux 2 AMI

git clone --recursive https://github.com/RediSearch/RediSearch.git 3 RediSearch2
git branch
* master
make setup
[ec2-user@ip-1xx-xx-xx-29 RediSearch]$ make build
Makefile:9: deps/readies/mk/main: No such file or directory
Makefile:223: /defs: No such file or directory
Makefile:255: /rules: No such file or directory
./sbin/pack.sh: line 7: /home/ec2-user/RediSearch/deps/readies/shibumi/defs: No such file or directory
./sbin/pack.sh: line 59: /home/ec2-user/RediSearch/deps/readies/bin/platform: No such file or directory
./sbin/pack.sh: line 62: /home/ec2-user/RediSearch/deps/readies/bin/platform: No such file or directory
./sbin/pack.sh: line 65: /home/ec2-user/RediSearch/deps/readies/bin/platform: No such file or directory
/home/ec2-user/RediSearch/sbin/getver: line 7: /home/ec2-user/RediSearch/deps/readies/shibumi/defs: No such file or directory
/home/ec2-user/RediSearch/sbin/getver: line 7: /home/ec2-user/RediSearch/deps/readies/shibumi/defs: No such file or directory
make: *** No rule to make target '/rules'.  Stop.

**Comment by rafie** [comment]
Hello @ucanmailsharath,
The clone/build sequence is as follows:
```
git clone --recursive https://github.com/RediSearch/RediSearch.git
cd RediSearch
./sbin/setup
bash -l
make
```
Also, you may use CircleCI/Github Actions workflows as a reference.

**Comment by manugarri** [comment]
@rafie Im still having issues with the `getepel` step on Amazon linux 2. 

As a side note, someone should update the `build source` section on the [documentation](https://redis.io/docs/stack/search/quick_start/).
