### ISSUE TITLE
How to filter MAX COUNT value on AGGREGATION

### ISSUE THREAD

**Issue by rasrov** [RediSearch/RediSearch#3508]
Hi!

I'm trying to filter max count value of aggregation query.

I have this query:

`FT.AGGREGATE eventIdx *
    GROUPBY 4 @incidentType @section @road @category
        REDUCE COUNT 0 as numIncidents
    GROUPBY 4 @incidentType @section @road @category
        REDUCE MAX 1 @numIncidents as maxNumIncidents
        FILTER "@maxNumIncidents > 2"
    SORTBY 4 @section ASC @maxNumIncidents DESC
    LIMIT 0 10000`

| incidentType | section | road | category | maxNumIncidents|
|--------|--------|--------|--------|--------|
| Is raining | 1 | i66 | Weather Incident | 23|
| Light snow | 1 | i66 | Weather Incident | 18|
| 1 | 1 | i66 | Slippery Road | 11|
| 2 | 1 | i66 | Slippery Road | 4|
| 3 | 1 | i66 | Slippery Road | 3|

But I'm trying to get this result:

| incidentType | section | road | category | maxNumIncidents|
|--------|--------|--------|--------|--------|
| Is raining | 1 | i66 | Weather Incident | 23|
| 1 | 1 | i66 | Slippery Road | 11|

Is this posible?

**Comment by GuyAv46** [comment]
Hello!
I'll try to break it down if you don't mind. the first table can be achieved by the first section of the command:
`FT.AGGREGATE eventIdx * GROUPBY 4 @incidentType @section @road @category REDUCE COUNT 0 as numIncidents ...`
the second aggregation is unnecessary as every row now is unique by the 4 provided fields.

Now I'm assuming from the desired table, I guess you want to get the max row by `maxNumIncidents` with a unique category, right? if that's the case, you have to group by category alone, and then you can reduce `numIncidents` by `MAX`:

`FT.AGGREGATE idx * GROUPBY 4 @incidentType @section @road @category REDUCE COUNT 0 as numIncidents GROUPBY 1 @category REDUCE MAX 1 @numIncidents as numIncidents FILTER "@numIncidents > 2" SORTBY 2 @numIncidents DESC LIMIT 0 10000`
which is
```
FT.AGGREGATE idx * 
    GROUPBY 4 @incidentType @section @road @category
        REDUCE COUNT 0 as numIncidents
    GROUPBY 1 @category
        REDUCE MAX 1 @numIncidents as numIncidents
    FILTER "@numIncidents > 2"
    SORTBY 2 @numIncidents DESC LIMIT 0 10000
```
result:
```
1) (integer) 2
2) 1) "category"
   2) "Weather Incident"
   3) "numIncidents"
   4) "23"
3) 1) "category"
   2) "Slippery Road"
   3) "numIncidents"
   4) "11"
```
which is

| category | numIncidents|
|--------|--------|
| Weather Incident | 23|
| Slippery Road | 11|

if you don't want to lose the other columns, the only solution I can think of is to use [`REDUCE FIRST_VALUE`](https://redis.io/docs/stack/search/reference/aggregations/#supported-groupby-reducers) for each field you want to keep. 
the query `FT.AGGREGATE idx * GROUPBY 4 @incidentType @section @road @category REDUCE COUNT 0 as numIncidents GROUPBY 1 @category REDUCE MAX 1 @numIncidents as numIncidents REDUCE FIRST_VALUE 4 @incidentType by @numIncidents DESC as incidentType REDUCE FIRST_VALUE 4 @section by @numIncidents DESC as section REDUCE FIRST_VALUE 4 @road by @numIncidents DESC as road FILTER "@numIncidents > 2" SORTBY 4 @section ASC @numIncidents DESC LIMIT 0 10000`
which is
```
FT.AGGREGATE idx *
    GROUPBY 4 @incidentType @section @road @category
        REDUCE COUNT 0 as numIncidents
    GROUPBY 1 @category
        REDUCE FIRST_VALUE 4 @incidentType by @numIncidents DESC as incidentType
        REDUCE FIRST_VALUE 4 @section by @numIncidents DESC as section
        REDUCE FIRST_VALUE 4 @road by @numIncidents DESC as road
        REDUCE MAX 1 @numIncidents as numIncidents
    FILTER "@numIncidents > 2"
    SORTBY 4 @section ASC @numIncidents DESC LIMIT 0 10000
```

will result in:
```
1) (integer) 2
2)  1) "category"
    2) "Weather Incident"
    3) "incidentType"
    4) "Is raining"
    5) "section"
    6) "1"
    7) "road"
    8) "i66"
    9) "numIncidents"
   10) "23"
3)  1) "category"
    2) "Slippery Road"
    3) "incidentType"
    4) "1"
    5) "section"
    6) "1"
    7) "road"
    8) "i66"
    9) "numIncidents"
   10) "11"
```
or

| category | incidentType | section | road | maxNumIncidents|
|--------|--------|--------|--------|--------|
| Weather Incident | Is raining | 1 | i66 | 23|
| Slippery Road | 1 | 1 | i66 | 11|

which is mostly what you asked for but the `category` column has moved to the beginning

Another approach will be to filter the desired results on the application side, of course.

let me know if that's answered your question

**Comment by rasrov** [comment]
Hi! @GuyAv46 

This is interesting but certainly not what I'm looking for.

I need to keep the specified grouping `@incidentType @section @road @category`.

| IncidentType | section | road | category | numIncidents
|--------|--------|--------|--------|--------|
| Is raining | 1 | i66| Weather Incident| 13|
| Light snow | 1 | i66| Weather Incident | 11|
| 1 | 1| i66 | Slippery Road| 9 |
| 2 | 1| i66| Slippery Road| 4 |
| 3 | 1| i66| Slippery Road| 2 | 
| Is raining | 2 | i66 | Weather Incident| 7|
| Light snow | 2 | i66| Weather Incident | 10|
| 1 | 2| i66 | Slippery Road | 3 |
| 2 | 2| i66 | Slippery Road | 8 |
| 3 | 2| i66 | Slippery Road | 1 | 
| Is raining | 1 | i101 | Weather Incident| 8 |
| Light snow | 1 | i101 | Weather Incident | 7 |
| 1 | 1 | i101 | Slippery Road | 9 |
| 2 | 1 | i101 | Slippery Road | 4 |
| 3 | 1 | i101 | Slippery Road | 2 | 
| Is raining | 3 | i66 | Weather Incident| 1 |
| Light snow | 3 | i66 | Weather Incident | 3 |
| 1 | 3 | i66 | Slippery Road | 5 |
| 2 | 3 | i66 | Slippery Road | 4 |
| 3 | 3 | i66 | Slippery Road | 2 | 

I have to get this result:

| IncidentType | section | road | category | numIncidents
|--------|--------|--------|--------|--------|
| Is raining | 1 | i66| Weather Incident| 13|
| 1 | 1| i66 | Slippery Road| 9 |
| Is raining | 1 | i101 | Weather Incident| 8 |
| 1 | 1 | i101 | Slippery Road | 9 |
| Light snow | 2 | i66| Weather Incident | 10|
| 2 | 2| i66 | Slippery Road | 8 |
| Light snow | 3 | i66 | Weather Incident | 3 |
| 1 | 3 | i66 | Slippery Road | 5 |

Could I achieve this result without having to do it on the application side (java) to avoid overloading the service?

**Comment by GuyAv46** [comment]
OK, can you explain the expected reduction here? I'm not sure I understand. Why do you keep the specified rows or why do you drop the others?

**Comment by rasrov** [comment]
Hii @GuyAv46!

Iwant to group all records by this 4 fields (@incidentType @section @road and @category) and get count value from them, and then get the highets numIncidents grouped by @section @road and @category.


Sorry if I have not explained the issue in a clearer way.

**Comment by rasrov** [comment]
Hi again @GuyAv46!

I think is something like this, right?

```
FT.AGGREGATE idx  *
    GROUPBY 4 @incidentType @section @road @category
        REDUCE COUNT 0 as numIncidents
    GROUPBY 3 @section @road @category
        REDUCE FIRST_VALUE 4 @incidentType by @numIncidents DESC as incidentType
        REDUCE MAX 1 @numIncidents as maxNumIncidents
        FILTER "@maxNumIncidents > 2"
    SORTBY 4 @section ASC @maxNumIncidents DESC
    LIMIT 0 10000
``` 

With this query get the desired result 😊

**Comment by GuyAv46** [comment]
I suspected that that's what you wanted. Yep seems like you figured it out correctly :)
