### ISSUE TITLE
RediSearch cluster support for OSS

### ISSUE THREAD

**Issue by Aadit-Bhojgi** [RediSearch/RediSearch#3510]
At the [Cluster support section](https://github.com/RediSearch/RediSearch#cluster-support) it is stated that cluster support is only for Enterprise versions, which is not right.
Coordinator is available for RediSearch OSS versions too -> https://forum.redis.com/t/anything-to-do-to-get-redisearch-to-search-across-clusters/1943/2
README documentation should be updated for this.

Related issues:

- https://github.com/redis-stack/redis-stack-rpm/issues/6
- https://github.com/RediSearch/RediSearch/issues/2970

**Comment by nermiller** [comment]
Thanks, @gkorland, I'll take care of this!

**Comment by Designxiaozai** [comment]
Which version of Redis Search OSS and corresponding Redis version should I use now? I have tested multiple versions and encountered different errors when creating Redis cluster nodes.
