### ISSUE TITLE
NUMERIC negate doesn't work as exepcted

### ISSUE THREAD

**Issue by ienjreny** [RediSearch/RediSearch#3520]
We are trying to use negate with NUERIC field and AND operator but we get unexpected results.

# create data

- HSET user:1234 userid 1234 fname Ismail lname Anjrin age 33
- HSET user:4321 userid 4321 fname Humam lname Anjrin age 15
- HSET user:1235 userid 1235 fname Ali lname Ahmed age 22
- HSET user:1236 userid 1236 fname Suad lname Dina age 44
- HSET user:1237 userid 1237 fname Ahmed lname Fadi age 39
- HSET user:1238 userid 1238 fname Mohamad lname Kasem age 57
- HSET user:1239 userid 1239 fname Katbi lname Riyadh age 37
- HSET user:123912340 userid 1239,12340 fname Ibn lname Sina age 88
- HSET user:1300 userid 1300 fname Katbi lname Riyadh age 33

# create index
FT.CREATE idx-users ON HASH PREFIX 1 user: SCHEMA userid TAG fname TEXT lname TEXT age NUMERIC

# Results
We expect the following query will return all rows where age != 33 and userid = 1300 which is 0 rows

FT.SEARCH idx-users "-@age:[33 33] @userid:{1300}"

But actually, the above query returns all rows, and when we use the following query, it works as expected

FT.SEARCH idx-users "@userid:{1300} -@age:[33 33]"

**Comment by ienjreny** [comment]
Fixed by using () for the queries

FT.SEARCH idx-users "(-@age:[33 33]) (@userid:{1300})"

**Comment by oshadmi** [comment]
@ienjreny Could also use [`DIALECT 2`](https://redis.io/docs/stack/search/reference/query_syntax/) argument,e.g.,
```
FT.SEARCH idx-users "-@age:[33 33] @userid:{1300}" DIALECT 2 
```

**Comment by ienjreny** [comment]
> @ienjreny Could also use [`DIALECT 2`](https://redis.io/docs/stack/search/reference/query_syntax/) argument,e.g.,
> 
> ```
> FT.SEARCH idx-users "-@age:[33 33] @userid:{1300}" DIALECT 2 
> ```

Yes, it is working fine too, thank you
