### ISSUE TITLE
Index range query suddently work incorrect

### ISSUE THREAD

**Issue by githubname1024** [RediSearch/RediSearch#3524]
Dear RediSearch team, 
I load the redisearch module in a redis and deployed sentinel. 
redis version is 6.2.4 & redisearch version is 2.6.3
And I have created many indexs, and work well.
But after about one or two month, one of the index does not work correctly when using range query by a parameter.
We keep add data always, and the defined index will index the data.
This is suddently happened, and there is not error log in the redis.
Is there good idea to analyze this problem? And what I can supply for help?
Thank you very much.

The detail info:
1. the index schema contains an attribute, [identifier, $.lastInviteTime, attribute, lastInviteTime, type, NUMERIC]
2. when create a new index which schema is same as the incorrect one, it works well.
3. the search query clause
    3.1 FT.SEARCH **userIdx** (@lastInviteTime:[1.6001056E9 1.680192E9]) LIMIT 0 0 
          the incorret index will return 0
    3.2 FT.SEARCH userIdxNew (@lastInviteTime:[1.6001056E9 1.680192E9]) LIMIT 0 0 
          it will return 2012
    3.3 FT.SEARCH **userIdx** (**-**@lastInviteTime:[1.6001056E9 1.680192E9]) LIMIT 0 0 
          the incorret index will return a count not 0
          the lastInviteTime in the record may be null
    3.4 FT.SEARCH userIdxNew -(@lastInviteTime:[1.6001056E9 1.680192E9]) LIMIT 0 0 
          it will return a count

**Comment by githubname1024** [comment]
@oshadmi 
I saw there a new release of v2.6.12. And there is a bug fix about numeric range. Is this release fix my issue?

Thank you very much.

![图片](https://github.com/RediSearch/RediSearch/assets/100768089/947a7ca3-a315-46a8-aab1-c20c550c3e9f)

**Comment by oshadmi** [comment]
@githubname1024 @slipvayne It is likely to have been fixed in version [v2.6.12](https://github.com/RediSearch/RediSearch/releases/tag/v2.6.12)
Related #3606

Can you please try 2.6.12?
