### ISSUE TITLE
bf_index.search python method throwing syntax error

### ISSUE THREAD

**Issue by SuryaKorivipaduPractice** [RediSearch/RediSearch#3526]
Hi. I'm trying the code present in the notebook - https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb

There's a method called 'bf_index.search' to search the vectors. I've called this method and it's throwing error - 'Syntax error at offset 1 near >['

I've seen similar problem in another github issue - https://github.com/RediSearch/RediSearch/issues/3497 . They suggested adding 'DIALECT 2'. They were using FT.create command. 

But in my notebook(https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb), it's the python code to create search query. The exact line of code looks like below:
q = redisearch.Query(f'*=>[KNN {k} @{vector_field_name} $vec_param]').sort_by(f'{vector_field_name}_score').paging(0,k).return_field(f'{vector_field_name}_score')

I've searched a lot in the internet for this command syntax. But I'm not able to find any solution. Where to add 'DIALECT 2' in this code? 

Am I going in the right direction? Please check my issue and help.

**Comment by GuyAv46** [comment]
Hey!
This demo is a very early demo and a bit out-of-date.
As of today, you should use `redispy` instead of `redisearchpy`.
you are correct about the dialect, there was an assumption in this demo that the server's default is already `DIALECT 2`. I also see that the use of the default score name is wrong. (should be `.sort_by(f'__{vector_field_name}_score')` instead of `.sort_by(f'{vector_field_name}_score')` for example)

Until we update it, I suggest you look at [this demo](https://github.com/RediSearch/RediSearch/blob/master/docs/docs/vecsim-hybrid_queries_examples.ipynb), which uses `redispy` syntax and address the dialect by setting the default.
notice that you can also add `.dialect(2)` to the query directly as well.

**Comment by GuyAv46** [comment]
You can also check out [this simple demo](https://github.com/redis/redis-py/blob/master/docs/examples/search_vector_similarity_examples.ipynb) from `redis-py`

**Comment by SuryaKorivipaduPractice** [comment]
Hi @GuyAv46 
I've gone through following notebooks once again.
https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb

I've added .dialect(2) to redisearch.Query command. The command looks as follows:
q = redisearch.Query(f'*=>[KNN {k} @{vector_field_name} $vec_param]').sort_by(f'{vector_field_name}_score').paging(0,k).dialect(2).return_field(f'{vector_field_name}_score')
Now this command throws the error - 'Query' object has no attribute 'dialect'

Thanks for providing the notebook link: https://github.com/RediSearch/RediSearch/blob/master/docs/docs/vecsim-hybrid_queries_examples.ipynb . There is a similar notebook: https://github.com/RediSearch/RediSearch/blob/master/docs/docs/vecsim-range_queries_examples.ipynb . In this notebook, there's below code:
redis_conn.ft().config_set("default_dialect", 2)
This throws error: unknown command 'FT.CONFIG'
I've read somewhere in github issues that redis_conn.ft() doesn't allow config in Redis Cloud vector database. I've opted for free trail of Azure Redis Cloud vector database by clicking 'Try Redis Cloud' button in the website: https://redis.io/docs/stack/search/reference/vectors/#create-a-vector-field

Thanks for providing one more simple demo: https://github.com/redis/redis-py/blob/master/docs/examples/search_vector_similarity_examples.ipynb
But this also doesn't work. While importing VectorField, it throws the error: 'cannot import name 'RedisClusterException' from 'redis.exceptions' '

However, I've figured out a way to load vectors from this notebook: https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb
Then I'm able to query vectors from FT.SEARCH commands which I found in this website: https://redis.io/docs/stack/search/reference/vectors/#create-a-vector-field
Parallely I saved the loaded vectors(random numpy arrays), got the query result in bytes, converted the bytes back to numpy array and then tried to check if this numpy array exists in loaded vectors(random numpy array)

I faced too many challenges in this process. Finally I feel that this notebook(https://github.com/RediSearch/RediSearch/blob/master/docs/docs/Vector-Similarity-for-RediSearch.ipynb) looks fine but the search command should be updated to support DIALECT parameter

**Comment by GuyAv46** [comment]
Thanks for the follow-up experience report and sorry for the inconvenience.
`redisearch-py` is deprecated so it's not going to support dialect settings.
I'll look into the other two problems you mentioned.
