### ISSUE TITLE
How can I search for people with friends having name "AJ" and age 23.

### ISSUE THREAD

**Issue by arhamwynk** [RediSearch/RediSearch#3536]
Lets say i have created an index of documents like these
`{
   "name":"ar",
   "age" : 23,
   "friends":[
      {
         "name":"AJ",
         "age":23
      },
      {
         "name":"Ae",
         "age":24
      }
   ]
}`
Where name has been attributed to lets say TEXT , how do I attribute the friends object such that i can query to get all the people names whose one of the friend is {"AJ",23} ie person with age 23 and Name {"AJ"}.

Without using any lua script, if yes then minimal.
But want to keep this approach scalable as there may be many other nested jsons in the object, reduce future effort.

Wanted to use redis search since we are storing data on redis.

If there is any other Redis based approach that can help apart from REDISJSON + REDISearch.
Please suggest the same.

This is an example use case.

**Comment by oshadmi** [comment]
@arhamwynk 
You can use RediSearch to index attributes within arrays of objects, for example:
```
127.0.0.1:6379> JSON.SET doc:1 $ '{ "name":"ar", "age" : 23, "friends":[ { "name":"AJ", "age":23 }, { "name":"Ae", "age":24 } ] }'
OK
127.0.0.1:6379> JSON.SET doc:2 $ '{ "name":"ar", "age" : 23, "friends":[ { "name":"AJ", "age":24 }, { "name":"Ae", "age":23 } ] }'
OK
127.0.0.1:6379> FT.CREATE idx ON JSON SCHEMA '$.friends[*].name' AS fname TEXT '$.friends[*].age' AS fage NUMERIC
OK
127.0.0.1:6379> FT.SEARCH idx '@fname:(AJ) @fage:[23 23]'
1) (integer) 2
2) "doc:2"
3) 1) "$"
   2) "{\"name\":\"ar\",\"age\":23,\"friends\":[{\"name\":\"AJ\",\"age\":24},{\"name\":\"Ae\",\"age\":23}]}"
4) "doc:1"
5) 1) "$"
   2) "{\"name\":\"ar\",\"age\":23,\"friends\":[{\"name\":\"AJ\",\"age\":23},{\"name\":\"Ae\",\"age\":24}]}"
```
In order to return attributes that match the index **but only under the same object** you can use `FT.AGGREGATE` with a `FILTER`, using a JSONPath filter, for example:
```
127.0.0.1:6379> FT.AGGREGATE idx '@fname:(AJ) @fage:[23 23]' LOAD 3 '$.friends[?(@.age==23 && @.name=="AJ")]' AS same_obj FILTER 'exists(@same_obj)' LOAD 1 __key
1) (integer) 2
2) 1) "same_obj"
   2) "{\"name\":\"AJ\",\"age\":23}"
   3) "__key"
   4) "doc:1"
```

**Comment by oshadmi** [comment]
Related #3229
