### ISSUE TITLE
How can I save memory?

### ISSUE THREAD

**Issue by KimDroid** [RediSearch/RediSearch#354]
Hi.

I have 20,000 datas in redisearch.
3 Indexes and 8 rows each key
I created indexes with (NOOFFSETS NOHL NOFREQS NOFIELDS STOPWORDS 0) options.
and memory stats is...

> MEMORY STATS
 1)  "peak.allocated"
 2)  "206794816"
 3)  "total.allocated"
 4)  "152517784"
 5)  "startup.allocated"
 6)  "786912"
 7)  "replication.backlog"
 8)  "0"
 9)  "clients.slaves"
 10)  "0"
 11)  "clients.normal"
 12)  "133920"
 13)  "aof.buffer"
 14)  "0"
 15)  "db.0"
 16)    1)   "overhead.hashtable.main"
  2)   "1419704"
  3)   "overhead.hashtable.expires"
  4)   "824"

 17)  "overhead.total"
 18)  "2341360"
 19)  "keys.count"
 20)  "28939"
 21)  "keys.bytes-per-key"
 22)  "5243"
 23)  "dataset.bytes"
 24)  "150176424"
 25)  "dataset.percentage"
 26)  "98.975517272949219"
 27)  "peak.percentage"
 28)  "73.753204345703125"
 29)  "fragmentation"
 30)  "1.9905027151107788"
 
And....
> FT.INFO my_index
......
......
 7)  "num_docs"
 8)  "19621"
 9)  "max_doc_id"
 10)  "281401"
 11)  "num_terms"
 12)  "8460"
 13)  "num_records"
 14)  "120549"
 15)  "inverted_sz_mb"
 16)  "0.12161636352539062"
 17)  "offset_vectors_sz_mb"
 18)  "0"
 19)  "doc_table_size_mb"
 20)  "23.616111755371094"
 21)  "sortable_values_size_mb"
 22)  "63.812042236328125"
 23)  "key_table_size_mb"
 24)  "1.1691274642944336"
 25)  "records_per_doc_avg"
 26)  "6.1438764588960808"
 27)  "bytes_per_record_avg"
 28)  "1.0578602891770152"
 29)  "offsets_per_term_avg"
 30)  "0"
 31)  "offset_bits_per_record_avg"
 32)  "-nan"
 33)  "gc_stats"
 34)    1)   "current_hz"
  2)   "1.1184784173965454"
  3)   "bytes_collected"
  4)   "1096624"
  5)   "effectiv_cycles_rate"
  6)   "0.45139606355849082"

 35)  "cursor_stats"
 36)    1)   "global_idle"
  2)   "0"
  3)   "global_total"
  4)   "0"
  5)   "index_capacity"
  6)   "128"
  7)   "index_total"
  8)   "0"

 
**dataset.bytes is about 143MB...!!
I think it is too much big size.
On the other hand, elasticsearch got 77MB...

1. How can I reduce memory size?
2. For Aggregation, must I set "SORTABLE" option?**

**Comment by itamarhaber** [comment]
Hello @KimDroid,

> 1. How can I reduce memory size?

You can use the `NOSAVE` option when `FT.ADD`ing to the index, to skip the creation of the actual document and only index it.

That said, the fragmentation of that instance is a little high, which also contributes to the memory consumption.

> 2. For Aggregation, must I set "SORTABLE" option?

Yes, that requirement is in the documentation ;)
