### ISSUE TITLE
Cosine similarity search return the wrong result.

### ISSUE THREAD

**Issue by af913337456** [RediSearch/RediSearch#3540]
mine search redis command is:

```
FT.SEARCH ai_qa6 *=>[KNN 3 @embedding $embedding as score] SORTBY score DESC DIALECT 2 LIMIT 0 3 PARAMS 2 embedding [...]
```

and the score result is wrong, when i use '1 - result', it comes the right value, also, i run the same embedding list by mine owne `cosineSimilarity` function below, it is the right value. So confusion! what the problem of this?

@DvirDukhan 

```golang
func cosineSimilarity(a, b []float64) float64 {
	dotProduct := 0.0
	aNorm := 0.0
	bNorm := 0.0
	for i := 0; i < len(a); i++ {
		dotProduct += a[i] * b[i]
		aNorm += a[i] * a[i]
		bNorm += b[i] * b[i]
	}
	aNorm = math.Sqrt(aNorm)
	bNorm = math.Sqrt(bNorm)
	return dotProduct / (aNorm * bNorm)
}
```

**Comment by DvirDukhan** [comment]
hi @af913337456 
please refer to the docs https://redis.io/docs/stack/search/reference/vectors/
we do `1-cosineSimilarity` to calculate the distance

**Comment by af913337456** [comment]
> hi @af913337456 please refer to the docs https://redis.io/docs/stack/search/reference/vectors/ we do `1-cosineSimilarity` to calculate the distance

@DvirDukhan thanks for reply, but i am not calculate the distance, but the calculate the similarity. 
Doesn't it mean that the larger the calculated value, the higher the similarity?

**Comment by af913337456** [comment]
@DvirDukhan
