### ISSUE TITLE
How to resolve and locate about hash_indexing_failures.

### ISSUE THREAD

**Issue by yangwn** [RediSearch/RediSearch#3559]
I'm using RedisSearch, the version is  RediSearch v. 2.6.5 and RedisJSON v. 2.4.4
But I found sometime happen this problem in monitor backend.

When I used FT.INFO command to monitor parameter, I found the hash_indexing_failures is not 0.
I want to confirm what's wrong about Index, and how to locate this problem?

**Comment by gkorland** [comment]
```
hash_indexing_failures: number of failures due to operations not compatible with index schema.
```
You can compare the keys in the index to the real amount of keys in Redis
