### ISSUE TITLE
Wrong results on simple aggregation query

### ISSUE THREAD

**Issue by rasrov** [RediSearch/RediSearch#3560]
Hii!

I'm trying to do some tests for the jedi library, but I'm having some troubles about it.

I documented all here https://github.com/redis/jedis/issues/3406 but from jedis can't help me.

In short, I'm having trouble aggregate query.

I didn't get the expected results and I don't know why.

**Comment by adrianoamaral** [comment]
hi @rasrov I look it on the other thread, can you confirm if you don't have issues with your index on the first case? FT.INFO you can check `num_docs` and `hash_index_failure`, to confirm if you have all documents proper indexed. Another way is trying a simple `FT.SEARCH idxname "*"` to see if all results were indexed.

**Comment by rasrov** [comment]
Hii @adrianoamaral 

Ouh, I only see 2 documents when I run the `FT.SEARCH idxname "*"` query, but in the RedisInsight browser I see them all.

I have had some fails with formats. Thanks for response! 🚀
