### ISSUE TITLE
Hash cannot be found in index (even though it exists) v2.6.9

### ISSUE THREAD

**Issue by mattadams** [RediSearch/RediSearch#3570]
I have an index with 49008 num_docs. FT.INFO shows "indexing" to be 0 and "percent_indexed" of 1. "hash_indexing_failures" is 0. The definition looks like this:

```
idx:scans ON hash PREFIX 1 "scans:" SCHEMA code TEXT SORTABLE type TEXT SORTABLE subtype TEXT SORTABLE date TEXT SORTABLE
```
However, in some cases FT.SEARCH is returning either no results where there should be results, or nonsensical results (things that shouldn't match show up). This occurred in v2.2.10 and also occurs in v2.6.9. When searching for a specific hash (of which there is only one that matches in this case):

```
127.0.0.1:6379> FT.SEARCH idx:scans "@code:BE"
1) (integer) 0
```

However this key/hash exists in the index:

```
127.0.0.1:6379> ft.search idx:scans * inkeys 1 scans:30344
1) (integer) 1
2) "scans:30344"
3)  1) "scan_id"
    2) "30344"
    3) "inserted_at"
    4) "2023-05-12 02:02:54.693908-06"
    5) "date"
    6) "2011-05-20"
    7) "time"
    8) ""
    9) "open"
   10) "14.34"
   11) "high"
   12) "14.34"
   13) "low"
   14) "14.34"
   15) "close"
   16) "14.34"
   17) "volume"
   18) "0"
   19) "adjustment_factor"
   20) ""
   21) "adjustment_type"
   22) ""
   23) "extended"
   24) ""
   25) "type"
   26) "last"
   27) "subtype"
   28) ""
   29) "code"
   30) "BE"
```
Am I doing something wrong or do we have a bug here?

**Comment by GuyAv46** [comment]
This is probably related to [Stop-words](https://redis.io/docs/stack/search/reference/stopwords/), words that are too common in your data and therefore are not indexed. The default stop-word list contains the word “be” so this is probably why the document in your example is not found.

You can specify your own STOPWORDS list (see the `FT.CREATE` documentation for that), and consider using TAG fields for such short and specific strings

Hope that helps

**Comment by mattadams** [comment]
Perfect. Thank you! Stop-words was definitely the problem here.
