### ISSUE TITLE
How do I check if the index is built finish?

### ISSUE THREAD

**Issue by CodePythonFollow** [RediSearch/RediSearch#3577]
When I insert a certain vector data, I have to wait a while to find the results. Now that I've inserted five million data, I'd like to know if the index is being built, or something went wrong. （FLAT 1536 dim） 

```python
def test():
    res = Redis(redis_url="redis://127.0.0.1:6379", db=0,
                index_name='summary')
    start_time = time.time()
    print('total', len(res.client.keys("summary*")))
    result = res.similarity_search(embedding=s['summary_vector_quantity'], k=1)
    print('res', len(result))
    print("spend", time.time() - start_time)
    for item in result:
        print(item)

test()
"""
output:
total 5013514
res 0
spend 16.92986512184143
"""
```
docker: redis-stack-server:latest

**Comment by meiravgri** [comment]
Hello :)
You can check `ft.info your_index_name` under `percent_indexed`. If it equals 1 indexing phase is finished.

**Comment by CodePythonFollow** [comment]
Thanks for your reply. 
Why the retrieval vector is empty after index completed , is it because the amount of data is too large？
If I switch the index to HNSW, can I retrieve the data for i need？
Any suggestions for similarity retrieval of tens of millions of data volumes on 1536 dimensions?

**Comment by chayim** [comment]
@CodePythonFollow what library are you using for your redis calls?

**Comment by meiravgri** [comment]
ft.info also provides the `vector_index_sz_mb`, see that it's not 0.
Also, make sure that the query dimensions equal the index vectors' dim
It could be helpful if you share your `ft.create` command and some`hset` example.

**Comment by CodePythonFollow** [comment]
@meiravgri Thank you very much, I think it should be a problem with the flat mode, I can index millions of data with HNSW and return it quickly and correctly.

**Comment by meiravgri** [comment]
HNSW queries are indeed much faster, but flat index should work as well
Thanks for bringing this to our attention.

**Comment by CodePythonFollow** [comment]
@meiravgri Have you ever encountered a situation where the Flat index is empty after the index is successfully built, related to the amount of data and data dimension?

**Comment by meiravgri** [comment]
We suspect that you reach the query timeout limit when running with flat index.
The default query timeout behavior is to return 0.
You could use a client that supports 
`FT.CONFIG SET ON_TIMEOUT FAIL`
and then run your query
If the server crushes, this is probably the problem.
It will be very helpful, thanks :)

* to reset to the default configuration run `FT.CONFIG SET ON_TIMEOU RETURN`
