### ISSUE TITLE
How do I make a combination of ANDs and ORs 

### ISSUE THREAD

**Issue by hekurankastrati** [RediSearch/RediSearch#3585]
I have this query in SQL
SELECT * FROM `table` 
WHERE 
`year` = '2023' AND
( (`type` = 1 AND `category` IN (a,b,c) ) OR (`type` = 2 AND `category` IN ('d,e,f') ) )

Is it possible to apply same logic in Redis using Redisearch?

**Comment by oshadmi** [comment]
@hekurankastrati
Yes.
AND operator is implicit, e.g., `@text_field:(hello world) @tag_field:{someTag} @numeric_field:[10 20]`

OR operator is `|` (pipe), e.g., `@text_field:(hello world) | @tag_field:{someTag} | @numeric_field:[10 20]`

Can combine expressions using parentheses `(` `)` . Add `DIALECT 2` argument to the `FT.SEARCH` query.

IN can be done using OR. For text and tag fields can also be done in short  e.g., `@text_field:(val1|val2|...)` and `@tag_field:{tag1|tag2|...}`

Please see [query syntax](https://redis.io/docs/stack/search/reference/query_syntax/) for more options and details.

**Comment by hekurankastrati** [comment]
Thanks a lot @oshadmi 

I tried this in my terminal and I can see it is working.
