### ISSUE TITLE
How to query for numeric fields for negative values.

### ISSUE THREAD

**Issue by ridersofrohan** [RediSearch/RediSearch#3590]
Not sure if I'm querying NumericField's wrong for negative numbers. I ran an aggregate to check to make sure that we have keys that have the NumericField set as a negative number, but when I try and search for that field, it does not seem to work. Any ideas here?

`FT.SEARCH 'idx:odd' '@normalized_league:{mlb} @bet_price:[2000 6000]'` works fine

`FT.SEARCH 'idx:odd' '@normalized_league:{mlb} @bet_price:[-3000 -1000]'` does not seem to work.

```
FT.AGGREGATE 'idx:odd' '@normalized_league:{mlb}' GROUPBY 1 @bet_price REDUCE count 0


125) 1) "bet_price"
     2) "550"
     3) "__generated_aliascount"
     4) "42"
126) 1) "bet_price"
     2) "-210"
     3) "__generated_aliascount"
     4) "73"
127) 1) "bet_price"
     2) "155"
     3) "__generated_aliascount"
     4) "55"
128) 1) "bet_price"
     2) "1700"
     3) "__generated_aliascount"
     4) "4"
129) 1) "bet_price"
     2) "-190"
     3) "__generated_aliascount"
     4) "73"
130) 1) "bet_price"
     2) "-375"
     3) "__generated_aliascount"
     4) "31"
```

- RediSearch: v 2.6.9
- RedisJSON: v 2.4.7
- RedisTimeSeries: v 1.6.17

**Comment by gkorland** [comment]
I don't see any issues with negative numbers support
```
127.0.0.1:6379> FT.CREATE idx on JSON schema $.a as a numeric
OK
127.0.0.1:6379> json.set k1 $ '{"a":-100}'
OK
127.0.0.1:6379> json.set k2 $ '{"a":-200}'
OK
127.0.0.1:6379> json.set k3 $ '{"a":200}'
OK
127.0.0.1:6379> ft.search idx '@a:[-3000 -5]'
1) (integer) 2
2) "k1"
3) 1) "$"
   2) "{\"a\":-100}"
4) "k2"
5) 1) "$"
   2) "{\"a\":-200}"
```

Can you please provide a more complete example? 
1. FT.CREATE
2. Example data

**Comment by ridersofrohan** [comment]
Sorry, this was resolved. We asked redislabs to upgrade our cluster and thus the redisearch version. All we needed to do was recreate the indexes. Thanks for looking into it.
