### ISSUE TITLE
multi-modal vector search

### ISSUE THREAD

**Issue by realalexgalenko** [RediSearch/RediSearch#3592]
Trying to understand how Redis handles search over two or more vector fields. Looked around and everyone is using single vector field via [KNN @vec $BLOB] type search. 

I created a schema with two vector fields. Say, vector1 and vector2. I can run vector similarity search on either vector1 or vector2 just fine. Is there a way to a query those two fields jointly? OR chain KNN queries (can it be done in single query?) that would first get K1 Nearest Neighbours  with respect to vector 1 and then limit search result further to K2 Nearest Neighbours referencing vector2? 

Thanks!

**Comment by GuyAv46** [comment]
As of today we don’t support multiple KNN queries in the same search command. You can try using vector range ([read about them here](https://redis.io/docs/stack/search/reference/vectors/)) query to first get all vectors within a specified radius, and then perform a KNN query on the results. 

For example
```
FT.SEARCH idx “@vec:[VECTOR_RANGE 0.42 $BLOB1]=>[KNN 10 @vec $BLOB2]” PARAMS … DIALECT 2 …
```

**Comment by realalexgalenko** [comment]
thats not a bad alternative, thanks!
