### ISSUE TITLE
FT.AGGREGATE

### ISSUE THREAD

**Issue by akelmj** [RediSearch/RediSearch#3595]
Hi,

Trying to run this AGGREGATE:

`FT.AGGREGATE leadIdx "*" APPLY "year(@createdate)" AS year GROUPBY 2 @status @year SORTBY 2 @year ASC`

![image](https://github.com/RediSearch/RediSearch/assets/8736967/1af75dc6-fd53-4e63-b5bc-ce5e2dc24cdc)

and i get empty result.
the "createdate" is timetamp and if i query it using ft.search i get results from it.

![image](https://github.com/RediSearch/RediSearch/assets/8736967/9382e1e4-147b-41df-9fbd-676bb16e7e8d)

what wrong with my AGGREGATE syntax?

Thnaks.

**Comment by GuyAv46** [comment]
`APPLY` does not load implicitly the fields it needs. Is `@createdate` defined as sortable? If not, try loading it first:
```
FT.AGGREGATE leadIdx "*" LOAD 1 @createdate APPLY "year(@createdate)" AS year GROUPBY 2 @status @year SORTBY 2 @year ASC
```

**Comment by akelmj** [comment]
thank you , it work.

But the year is not correct:

![image](https://github.com/RediSearch/RediSearch/assets/8736967/983e00e1-1706-44b0-a288-76a9f67509e6)

![image](https://github.com/RediSearch/RediSearch/assets/8736967/eb7c5399-e201-4968-96f8-cf82b1e3fbe9)

whats the proplem here?

**Comment by GuyAv46** [comment]
Err... seems odd
is `@createdate` part of the index schema? is it defined as NUMERIC?

**Comment by akelmj** [comment]
> Err... seems odd is `@createdate` part of the index schema? is it defined as `NUMERIC`?

Yes.

**Comment by GuyAv46** [comment]
Figured it out
RediSearch assumes the timestamp is given in seconds, and your time was passed in milliseconds, as the image you provided suggests.
you can either store it in seconds in the first place, or convert to seconds in the `APPLY` expression:
```
FT.AGGREGATE leadIdx "*" LOAD 1 @createdate APPLY "year(@createdate/1000)" AS year GROUPBY 2 @status @year SORTBY 2 @year ASC
```
Hope that helps
