### ISSUE TITLE
v2.6.9  require redis 7.1.0, and it is not available

### ISSUE THREAD

**Issue by aqp** [RediSearch/RediSearch#3602]
v2.6.9  require redis 7.1.0, and it is not available

$ make run
2604594:C 26 May 2023 04:35:29.500 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
2604594:C 26 May 2023 04:35:29.500 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=2604594, just started
2604594:C 26 May 2023 04:35:29.500 # Configuration loaded
2604594:M 26 May 2023 04:35:29.501 * Increased maximum number of open files to 10032 (it was originally set to 1024).
2604594:M 26 May 2023 04:35:29.501 * monotonic clock: POSIX clock_gettime

2604594:M 26 May 2023 04:35:29.502 # Server initialized
2604594:M 26 May 2023 04:35:29.503 # Module /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so failed to load: /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so: cannot open shared object file: No such file or directory
2604594:M 26 May 2023 04:35:29.503 # Can't load module from /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so: server aborting
make: *** [Makefile:406: run] Error 1

**Comment by gkorland** [comment]
2.6.9 doesn't require 7.1.0.
Only the 2.8.x requires >7.2 (meaning Redis 7.2)

Checking the error you get it doesn't seem related to this.

```
 2604594:M 26 May 2023 04:35:29.503 # Module /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so failed to load: /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so: cannot open shared object file: No such file or directory
```

**Comment by kasem-sm** [comment]
> v2.6.9 require redis 7.1.0, and it is not available
> 
> $ make run 2604594:C 26 May 2023 04:35:29.500 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo 2604594:C 26 May 2023 04:35:29.500 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=2604594, just started 2604594:C 26 May 2023 04:35:29.500 # Configuration loaded 2604594:M 26 May 2023 04:35:29.501 * Increased maximum number of open files to 10032 (it was originally set to 1024). 2604594:M 26 May 2023 04:35:29.501 * monotonic clock: POSIX clock_gettime
> 
> 2604594:M 26 May 2023 04:35:29.502 # Server initialized 2604594:M 26 May 2023 04:35:29.503 # Module /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so failed to load: /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so: cannot open shared object file: No such file or directory 2604594:M 26 May 2023 04:35:29.503 # Can't load module from /root/RediSearch/RediSearch/bin/linux-x64-release/search/redisearch.so: server aborting make: *** [Makefile:406: run] Error 1

did you find any solution?

**Comment by rasrov** [comment]
Hii! @gkorland
 
I am trying to run **redis-server** with **RediSearch** and **RedisJSON** modules on **Ubuntu 22.04** and I am getting the same error.

I've downloaded, make setup and make built both repositories to generate **.so** file.
https://github.com/RediSearch/RediSearch
https://github.com/RedisJSON/RedisJSON

Moved both **.so** to **/etc/redis/** path and modified **redis.conf** to add following data into **loadmodule** section:
* loadmodule /etc/redis/redisearch.so
* loadmodule /etc/redis/rejson.so

**redis-server version**
Redis server v=7.0.11 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=3af367a78d5e21e9

**/var/log/reds/redis-server.log**
> <search> Redis version found by RedisSearcj : 7.0.11 - oss
> <search> Redis version is too old, please upgrade to redis 7.1.0 and above.
> Module /etc/redis/redisearch.so initialization failed. Module not loaded
> Can't load module from /etc/redis/redisearch.so: server aborting

I also tried to download precompiled **.so** from [Redis Download Center](https://app.redislabs.com/?_gl=1*y4xdq0*_gcl_au*NDk2NDE1NDc5LjE2ODQ5MTIyMzc.*_ga*MjAwOTEyMTE2NS4xNjg0OTEyMjM3*_ga_8BKGRQKRPV*MTY4NTY1ODE1MC4yLjAuMTY4NTY1ODE1MC42MC4wLjA.#/rlec-downloads) and **redis-server** starts well, but when I try to run some command like FT.SEARCH I am always getting : 
> module disabled in open source redis

**Comment by gaohc001** [comment]
may be try
chmod  775 /etc/redis/redisearch.so
chmod 775 /etc/redis/rejson.so

**Comment by kasem-sm** [comment]
I don't know if this make sense but installing redis stack fixed the issue.

**Comment by alpintrekker** [comment]
Could anyone point out, which release of RediSearch can be compiled to work with Redis OSS 7.0.11?!

```
170717:C 29 Jun 2023 11:56:01.701 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
170717:C 29 Jun 2023 11:56:01.701 # Redis version=7.0.11, bits=64, commit=00000000, modified=0, pid=170717, just started
170717:C 29 Jun 2023 11:56:01.701 # Configuration loaded
170717:M 29 Jun 2023 11:56:01.702 * monotonic clock: POSIX clock_gettime
170717:M 29 Jun 2023 11:56:01.702 * Running mode=standalone, port=6379.
170717:M 29 Jun 2023 11:56:01.702 # Server initialized
170717:M 29 Jun 2023 11:56:01.704 * <search> Redis version found by RedisSearch : 7.0.11 - oss
170717:M 29 Jun 2023 11:56:01.704 # <search> Redis version is too old, please upgrade to redis 7.1.0 and above.
170717:M 29 Jun 2023 11:56:01.704 # Module /usr/local/lib/redisearch.so initialization failed. Module not loaded
170717:M 29 Jun 2023 11:56:01.704 # Can't load module from /usr/local/lib/redisearch.so: server aborting
```

RediSearch definitively looks requiring ```redis 7.1.0 and above```.

**Comment by alpintrekker** [comment]
Figured out: cloning the RediSearch repository with `v2.6.9' tag specified gives the properly configured repo for building RediSearch,  which works with Redis Server 7.0.11 OSS, like this:

`git clone --recursive -b v2.6.9 https://github.com/RediSearch/RediSearch.git`
