### ISSUE TITLE
COMO FAZER SCAPING DATATIME

### ISSUE THREAD

**Issue by jeandejesus** [RediSearch/RediSearch#3612]
tenho um json no fromato :
{dataHoraPublicacao:"2023-05-11T11:42:33.000Z}

estou tentando fazer redis search:
FT.SEARCH NoticiaController:DetalharNoticia: "@dataHoraPublicacao:2023-05-08T10:54:09.000Z"
"Syntax error at offset 33 near T10"

JA TENTEI USAR UMA BARRA INVERTIDA, DUAS, JA TENTEI 
FT.SEARCH NoticiaController:DetalharNoticia: '@dataHoraPublicacao:{$V}' PARAMS 2 V '2023-05-08T10:54:09.000Z', NÃO DA ERRO MAS VOLTA 0.

ALGUÉ SABE ALGUMA OUTRA ALTERNATIVA ?

----

I have a json in format:
```
{"PublicationDateTime":"2023-05-11T11:42:33.000Z"}
```

I'm trying to do redis search:
```
FT.SEARCH NoticiaController:DetalharNoticia: "@dataHoraPublicacao:2023-05-08T10:54:09.000Z"
```

"Syntax error at offset 33 near T10"

I'VE TRIED TO USE ONE INVERSE BAR, TWO, I'VE TRIED
```
FT.SEARCH NoticiaController:DetalharNoticia: '@dataHoraPublicacao:{$V}' PARAMS 2 V '2023-05-08T10:54:09.000Z', 
```
NO ERROR BUT BACK 0.

Does anyone know another alternative?

**Comment by gkorland** [comment]
@jeandejesus  can you please share your `FT.CREATE` command?

**Comment by gkorland** [comment]
Notice you need to escape it to avoid tokenization 
See: https://redis.io/docs/stack/search/reference/escaping/

```
127.0.0.1:6379> FT.CREATE idx on JSON schema $.PublicationDateTime as dataHoraPublicacao TAG
OK
127.0.0.1:6379> json.set a $ '{"PublicationDateTime":"2023-05-11T11:42:33.000Z"}'
OK
127.0.0.1:6379> FT.SEARCH idx '@dataHoraPublicacao:{2023\-05\-11T11\:42\:33\.000Z}'
1) (integer) 1
2) "a"
3) 1) "$"
   2) "{\"PublicationDateTime\":\"2023-05-11T11:42:33.000Z\"}"
```
