### ISSUE TITLE
SET MAXSEARCHRESULTS problem

### ISSUE THREAD

**Issue by akelmj** [RediSearch/RediSearch#3619]
Hi,

I change the MAXSEARCHRESULTS from 10000 to 15000 and the server is not responding.

The server is crashed and i restart it to work again :(

I use this command:

`FT.CONFIG SET MAXSEARCHRESULTS 15000 `

I there any Idea to fix that?

**Comment by gkorland** [comment]
which version of Search are you using? How did you run the server?

**Comment by akelmj** [comment]
> 

redis_version:6.2.7
module:name=search,ver=20414,api=1
module:name=ReJSON,ver=20200

i run it with docker.

All work perefect , just change the MAXSEARCHRESULTS make problem.

**Comment by meiravgri** [comment]
Can you please share the server log after the crush?

**Comment by akelmj** [comment]
> 
Not right now , i restarted the server and the log is lost. I'll  try to create a test server and send the log if possible.

**Comment by akelmj** [comment]
It work after I restart the server and use redis-cli.
