### ISSUE TITLE
Unable to build Redis latest version and v2.6.6

### ISSUE THREAD

**Issue by ksriudupa** [RediSearch/RediSearch#3621]
Getting below errors.  Tried with latest gcc versions.  How to avoid these errors

Consolidate compiler generated dependencies of target VectorSimilarity
[ 81%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/algorithms/brute_force/brute_force_factory.cpp.o
[ 81%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/algorithms/hnsw/hnsw_factory.cpp.o
[ 81%] Building CXX object deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/vec_sim.cpp.o
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/vec_sim_index.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:11,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/vec_sim.cpp:10:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/vec_sim_interface.h:154:25: error: inline function ‘virtual void VecSimIndexInterface::setLastSearchMode(VecSearchMode)’ used but never defined [-Werror]
     virtual inline void setLastSearchMode(VecSearchMode mode) = 0;
                         ^~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/build.make:132: deps/VectorSimilarity/src/CMakeFiles/VectorSimilarity.dir/VecSim/vec_sim.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:76:5: error: inline function ‘vecsim_stl::abstract_priority_queue<DistType, long unsigned int>* BruteForceIndex<DataType, DistType>::getNewMaxPriorityQueue() [with DataType = double; DistType = double]’ used but never defined [-Werror]
     getNewMaxPriorityQueue() = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/vector_block.h:10,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:10,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:44:27: error: inline function ‘size_t vecsim_stl::abstract_priority_queue<Priority, Value>::size() const [with Priority = double; Value = long unsigned int; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline size_t size() const = 0;
                           ^~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:40:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::emplace(Priority, Value) [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void emplace(Priority p, Value v) = 0;
                         ^~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:42:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::pop() [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void pop() = 0;
                         ^~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:43:53: error: inline function ‘const std::pair<_T1, _T2> vecsim_stl::abstract_priority_queue<Priority, Value>::top() const [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline const std::pair<Priority, Value> top() const = 0;
                                                     ^~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:80:5: error: inline function ‘std::unique_ptr<vecsim_stl::abstract_results_container> BruteForceIndex<DataType, DistType>::getNewResultsContainer(size_t) const [with DataType = double; DistType = double; size_t = long unsigned int]’ used but never defined [-Werror]
     getNewResultsContainer(size_t cap) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:14,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_results_container.h:23:25: error: inline function ‘virtual void vecsim_stl::abstract_results_container::emplace(size_t, double)’ used but never defined [-Werror]
     virtual inline void emplace(size_t id, double score) = 0;
                         ^~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_results_container.h:29:39: error: inline function ‘virtual VecSimQueryResult* vecsim_stl::abstract_results_container::get_results()’ used but never defined [-Werror]
     virtual inline VecSimQueryResult *get_results() = 0;
                                       ^~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:87:5: error: inline function ‘VecSimBatchIterator* BruteForceIndex<DataType, DistType>::newBatchIterator_Instance(void*, VecSimQueryParams*) const [with DataType = double; DistType = double; VecSimBatchIterator = VecSimBatchIterator]’ used but never defined [-Werror]
     newBatchIterator_Instance(void *queryBlob, VecSimQueryParams *queryParams) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:84:25: error: inline function ‘void BruteForceIndex<DataType, DistType>::setVectorId(labelType, idType) [with DataType = double; DistType = double; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void setVectorId(labelType label, idType id) = 0;
                         ^~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:83:25: error: inline function ‘void BruteForceIndex<DataType, DistType>::replaceIdOfLabel(labelType, idType, idType) [with DataType = double; DistType = double; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void replaceIdOfLabel(labelType label, idType new_id, idType old_id) = 0;
                         ^~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:76:5: error: inline function ‘vecsim_stl::abstract_priority_queue<DistType, long unsigned int>* BruteForceIndex<DataType, DistType>::getNewMaxPriorityQueue() [with DataType = float; DistType = float]’ used but never defined [-Werror]
     getNewMaxPriorityQueue() = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/vector_block.h:10,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:10,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:44:27: error: inline function ‘size_t vecsim_stl::abstract_priority_queue<Priority, Value>::size() const [with Priority = float; Value = long unsigned int; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline size_t size() const = 0;
                           ^~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:40:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::emplace(Priority, Value) [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void emplace(Priority p, Value v) = 0;
                         ^~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:42:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::pop() [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void pop() = 0;
                         ^~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:43:53: error: inline function ‘const std::pair<_T1, _T2> vecsim_stl::abstract_priority_queue<Priority, Value>::top() const [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline const std::pair<Priority, Value> top() const = 0;
                                                     ^~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:8:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:80:5: error: inline function ‘std::unique_ptr<vecsim_stl::abstract_results_container> BruteForceIndex<DataType, DistType>::getNewResultsContainer(size_t) const [with DataType = float; DistType = float; size_t = long unsigned int]’ used but never defined [-Werror]
     getNewResultsContainer(size_t cap) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:87:5: error: inline function ‘VecSimBatchIterator* BruteForceIndex<DataType, DistType>::newBatchIterator_Instance(void*, VecSimQueryParams*) const [with DataType = float; DistType = float; VecSimBatchIterator = VecSimBatchIterator]’ used but never defined [-Werror]
     newBatchIterator_Instance(void *queryBlob, VecSimQueryParams *queryParams) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:84:25: error: inline function ‘void BruteForceIndex<DataType, DistType>::setVectorId(labelType, idType) [with DataType = float; DistType = float; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void setVectorId(labelType label, idType id) = 0;
                         ^~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force.h:83:25: error: inline function ‘void BruteForceIndex<DataType, DistType>::replaceIdOfLabel(labelType, idType, idType) [with DataType = float; DistType = float; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void replaceIdOfLabel(labelType label, idType new_id, idType old_id) = 0;
                         ^~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/bfs_batch_iterator.h:8,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_single.h:10,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/brute_force_factory.cpp:9:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/bf_batch_iterator.h:36:43: error: inline function ‘VecSimQueryResult_Code BF_BatchIterator<DataType, DistType>::calculateScores() [with DataType = float; DistType = float]’ used but never defined [-Werror]
     virtual inline VecSimQueryResult_Code calculateScores() = 0;
                                           ^~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/brute_force/bf_batch_iterator.h:36:43: error: inline function ‘VecSimQueryResult_Code BF_BatchIterator<DataType, DistType>::calculateScores() [with DataType = double; DistType = double]’ used but never defined [-Werror]
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:13,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:44:27: error: inline function ‘size_t vecsim_stl::abstract_priority_queue<Priority, Value>::size() const [with Priority = double; Value = long unsigned int; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline size_t size() const = 0;
                           ^~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:43:53: error: inline function ‘const std::pair<_T1, _T2> vecsim_stl::abstract_priority_queue<Priority, Value>::top() const [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline const std::pair<Priority, Value> top() const = 0;
                                                     ^~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:42:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::pop() [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void pop() = 0;
                         ^~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:44:27: error: inline function ‘size_t vecsim_stl::abstract_priority_queue<Priority, Value>::size() const [with Priority = float; Value = long unsigned int; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline size_t size() const = 0;
                           ^~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:43:53: error: inline function ‘const std::pair<_T1, _T2> vecsim_stl::abstract_priority_queue<Priority, Value>::top() const [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline const std::pair<Priority, Value> top() const = 0;
                                                     ^~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:42:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::pop() [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void pop() = 0;
                         ^~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:204:25: error: inline function ‘void HNSWIndex<DataType, DistType>::setVectorId(labelType, idType) [with DataType = double; DistType = double; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void setVectorId(labelType label, idType id) = 0;
                         ^~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:197:55: error: inline function ‘candidatesLabelsMaxHeap<DistType>* HNSWIndex<DataType, DistType>::getNewMaxPriorityQueue() const [with DataType = double; DistType = double; candidatesLabelsMaxHeap<DistType> = vecsim_stl::abstract_priority_queue<double, long unsigned int>]’ used but never defined [-Werror]
     virtual inline candidatesLabelsMaxHeap<DistType> *getNewMaxPriorityQueue() const = 0;
                                                       ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:13,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:40:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::emplace(Priority, Value) [with Priority = double; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void emplace(Priority p, Value v) = 0;
                         ^~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:202:5: error: inline function ‘std::unique_ptr<vecsim_stl::abstract_results_container> HNSWIndex<DataType, DistType>::getNewResultsContainer(size_t) const [with DataType = double; DistType = double; size_t = long unsigned int]’ used but never defined [-Werror]
     getNewResultsContainer(size_t cap) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:15,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_results_container.h:23:25: error: inline function ‘virtual void vecsim_stl::abstract_results_container::emplace(size_t, double)’ used but never defined [-Werror]
     virtual inline void emplace(size_t id, double score) = 0;
                         ^~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_results_container.h:29:39: error: inline function ‘virtual VecSimQueryResult* vecsim_stl::abstract_results_container::get_results()’ used but never defined [-Werror]
     virtual inline VecSimQueryResult *get_results() = 0;
                                       ^~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:204:25: error: inline function ‘void HNSWIndex<DataType, DistType>::setVectorId(labelType, idType) [with DataType = float; DistType = float; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void setVectorId(labelType label, idType id) = 0;
                         ^~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:197:55: error: inline function ‘candidatesLabelsMaxHeap<DistType>* HNSWIndex<DataType, DistType>::getNewMaxPriorityQueue() const [with DataType = float; DistType = float; candidatesLabelsMaxHeap<DistType> = vecsim_stl::abstract_priority_queue<float, long unsigned int>]’ used but never defined [-Werror]
     virtual inline candidatesLabelsMaxHeap<DistType> *getNewMaxPriorityQueue() const = 0;
                                                       ^~~~~~~~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:13,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:40:25: error: inline function ‘void vecsim_stl::abstract_priority_queue<Priority, Value>::emplace(Priority, Value) [with Priority = float; Value = long unsigned int]’ used but never defined [-Werror]
     virtual inline void emplace(Priority p, Value v) = 0;
                         ^~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:202:5: error: inline function ‘std::unique_ptr<vecsim_stl::abstract_results_container> HNSWIndex<DataType, DistType>::getNewResultsContainer(size_t) const [with DataType = float; DistType = float; size_t = long unsigned int]’ used but never defined [-Werror]
     getNewResultsContainer(size_t cap) const = 0;
     ^~~~~~~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:205:25: error: inline function ‘void HNSWIndex<DataType, DistType>::resizeLabelLookup(size_t) [with DataType = double; DistType = double; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline void resizeLabelLookup(size_t new_max_elements) = 0;
                         ^~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:203:25: error: inline function ‘void HNSWIndex<DataType, DistType>::replaceIdOfLabel(labelType, idType, idType) [with DataType = double; DistType = double; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void replaceIdOfLabel(labelType label, idType new_id, idType old_id) = 0;
                         ^~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:205:25: error: inline function ‘void HNSWIndex<DataType, DistType>::resizeLabelLookup(size_t) [with DataType = float; DistType = float; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline void resizeLabelLookup(size_t new_max_elements) = 0;
                         ^~~~~~~~~~~~~~~~~
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:203:25: error: inline function ‘void HNSWIndex<DataType, DistType>::replaceIdOfLabel(labelType, idType, idType) [with DataType = float; DistType = float; labelType = long unsigned int; idType = unsigned int]’ used but never defined [-Werror]
     virtual inline void replaceIdOfLabel(labelType label, idType new_id, idType old_id) = 0;
                         ^~~~~~~~~~~~~~~~
In file included from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw.h:13,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_single.h:9,
                 from /root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/algorithms/hnsw/hnsw_factory.cpp:7:
/root/bvd/redis266/RediSearch/deps/VectorSimilarity/src/VecSim/utils/vecsim_stl.h:44:27: error: inline function ‘size_t vecsim_stl::abstract_priority_queue<Priority, Value>::size() const [with Priority = double; Value = unsigned int; size_t = long unsigned int]’ used but never defined [-Werror]
     virtual inline size_t size() const = 0;

**Comment by meiravgri** [comment]
Hi :)
try to update the submodules
`git submodules update --init`

**Comment by ksriudupa** [comment]
Thanks for your suggestion.
git submodule update --init
Submodule path 'deps/VectorSimilarity': checked out '4e065d8d66bb2c89532018adccdb5642f0252c3f'
Submodule path 'deps/googletest': checked out 'e2239ee6043f73722e7aa812a459f54a28552929'
Submodule path 'deps/hiredis': checked out 'c14775b4e48334e0262c9f168887578f4a368b5d'
Submodule path 'deps/libuv': checked out '0c1fa696aa502eb749c2c4735005f41ba00a27b8'
Submodule path 'deps/readies': checked out '59712b120ed6d8b39fde438d3860ca8e7262e6c1'

Now getting different error:
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/include/avx512fintrin.h:5946:10: error: ‘__Y’ is used uninitialized [-Werror=uninitialized]
 5946 |   return (__m256d) __builtin_ia32_extractf64x4_mask ((__v8df) __A,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 5947 |                                                      __imm,
      |                                                      ~~~~~~
 5948 |                                                      (__v4df)
      |                                                      ~~~~~~~~
 5949 |                                                      _mm256_undefined_pd (),
      |                                                      ~~~~~~~~~~~~~~~~~~~~~~~
 5950 |                                                      (__mmask8) -1);
      |                                                      ~~~~~~~~~~~~~~

Thanks

**Comment by GuyAv46** [comment]
This is a bug in a GNU library with GCC version 12. you can read about it [here](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105593) and [here](https://github.com/pytorch/pytorch/issues/77939)

as a workaround, you can compile with GCC 11, or disable treating warnings as errors in the VectorSimilarity library

Hope that helps :)

**Comment by ksriudupa** [comment]
Thanks again.  Binary built now 👍
