### ISSUE TITLE
Redisearch inconsistent result when i use multiple not query with tag data type

### ISSUE THREAD

**Issue by ackelle** [RediSearch/RediSearch#3623]
Versions:

Redis 7.0.6
RediSearch-2.6.4

We have created index below command:

FT.CREATE idx:table ON HASH PREFIX 1 table: SCHEMA DestinationName TAG WITHSUFFIXTRIE

We try to filter data in redis below rules:
• DestinationName **NOT EQUALS** “NOTEXIST”
• DestinationName **NOT ENDSWITH** "network.tcp"
• DestinationName **NOT ENDSWITH** “abc.org”

**NOTE** :  Redisearch module imported in DIALECT 2 mode.

When we run below command, redisearch giving us inconsistent result:
FT.SEARCH idx:table "-@DestinationName :{NOTEXIST} -@DestinationName :{*network\\.tcp} -@DestinationName :{*abc\\.org}" 

We use **-** for **NOT** condition at the beginning of the subquery like -@DestinationName ....
We observe that redisearch giving us inconsistent result when multiple NOT operator located on query above. 

What is the problem in this case?
Can you help me?

**Comment by oshadmi** [comment]
@ackelle Is the field `DestinationRealm` part of the schema?

**Comment by ackelle** [comment]
> 
i am sorry for naming wrongly :( i am a victim because of copy paste, i have editted the question. can you check again? thank you :)

**Comment by ackelle** [comment]
can you review my question?
