### ISSUE TITLE
duplicate KEY ?? is it a BUG?

### ISSUE THREAD

**Issue by akelmj** [RediSearch/RediSearch#3647]
Hi,

i have an index with key name "sku" that is unique.

why i see duplicate from the same key?

![image](https://github.com/RediSearch/RediSearch/assets/8736967/a1a10297-5fa3-4869-a3b6-9fc683cc9ac2)

Thanks.

**Comment by oshadmi** [comment]
@akelmj You can use the [`KEYS`](https://redis.io/commands/keys/) with a pattern to list relevant existing keys.
Please mind key names are case sensitive.
If key names are indeed identical, can you please try to reproduce this with `redis-cli`,
Or share the index definition and the `FT.SEARCH` query you are using?

**Comment by akelmj** [comment]
I use KEYS ,
There was space after the sku so it add id as another key.

"173411"
"173411 "

Thanks it save me ;)
