### ISSUE TITLE
Python Error during  Rediserach (v2.8.2) build on UBI 9.1

### ISSUE THREAD

**Issue by ksriudupa** [RediSearch/RediSearch#3652]
Getting following error when building Redisearch 2.8.2 on UBI 9.1

#9 128.4 + cd RediSearch
#9 128.4 + make build SHOW=1 OFFICIAL=1
#9 128.5 deps/readies/mk/main:49: *** Cannot find python3 interpreter.
#9 128.5 You can install one by running 'make setup'..  Stop.

If I add "make setup" then I am getting below error
 Problem: problem with installed package curl-minimal-7.76.1-23.el9_2.1.x86_64
#10 105.1   - package curl-minimal-7.76.1-23.el9_2.1.x86_64 conflicts with curl provided by curl-7.76.1-23.el9_2.1.x86_64
#10 105.1   - conflicting requests
#10 105.1 command failed: yum install -q -y curl wget unzip

Found siimilar problem reported https://github.com/RediSearch/RediSearch/issues/3185 this solution is already in place in main file

**Comment by rafie** [comment]
Hello @ksriudupa ,
The RediSearch build sequence goes as follows:
```
./sbin/setup
bash -l
make
```

**Comment by ksriudupa** [comment]
./sbin/setup is same as make setup and throws same error "conflict with curl package version"
UBI 9 images are publicly available

**Comment by rafie** [comment]
UBI 9 are publicly available, but (please correct me if I'm wrong) using a package manager requires a license, which make them unusable for our purposes. We overcome this by using rock/alma to build, then one can use the resulting binaries on UBI.
I'm now fixing rocky/alma 9 support - it will be soon available on master and 2.8 branches.

**Comment by ksriudupa** [comment]
Thanks for the update,  Yes avoid installing curl.  I tried removing this package before running make setup but it failed for few more packages which are not available with UBI 9

**Comment by ksriudupa** [comment]
Any update on UBI 9 compatible build ? How can I avoid redisearch build errors in UBI 9?

**Comment by ksriudupa** [comment]
Added “--build-arg PYTHON_VER=3” argument to docker build to reolve python3 interpreter error
