### ISSUE TITLE
Redisearch inconsistent result when i use multiple not query with tag data type

### ISSUE THREAD

**Issue by ackelle** [RediSearch/RediSearch#3662]
Versions:

Redis 7.0.6
RediSearch-2.6.4

We have created index below command:

FT.CREATE idx:table ON HASH PREFIX 1 table: SCHEMA DestinationName TAG WITHSUFFIXTRIE

We try to filter data in redis below rules:
• DestinationName NOT EQUALS “NOTEXIST”
• DestinationName NOT ENDSWITH "network.tcp"
• DestinationName NOT ENDSWITH “abc.org”

NOTE : Redisearch module imported in DIALECT 2 mode.

When we run below command, redisearch giving us inconsistent result:
FT.SEARCH idx:table "-@DestinationName :{NOTEXIST} -@DestinationName :{*network\.tcp} -@DestinationName :{*abc\.org}"

We use - for NOT condition at the beginning of the subquery like -@DestinationName ....
We observe that redisearch giving us inconsistent result when multiple NOT operator located on query above.

What is the problem in this case?
Can you help me?

**Comment by GuyAv46** [comment]
Hey
Can you try using `DIALECT 2` or above?

**Comment by GuyAv46** [comment]
Can you please include `FT.EXPLAIN` or `FT.EXPLAINCLI` output of the query/different queries?

**Comment by ackelle** [comment]
> Can you please include `FT.EXPLAIN` or `FT.EXPLAINCLI` output of the query/different queries?

thx for answer;

![image](https://github.com/RediSearch/RediSearch/assets/14054113/3268773b-16d7-47c2-b8f4-c2678ab0232e)

does dialect 2 support suffix?

i try to filter by using suffix in redis query (the redis query is top of the uploaded image), but FT.EXPLAINCLI gives me prefix result. why?

**Comment by ackelle** [comment]
> @ackelle Using redis-stack, the following behavior seems OK (RediSearch 2.6.9) Are you seeing different behavior?
> 
> ```
> docker run -d -p 6379:6379 -p 8001:8001 redis/redis-stack:latest
> redis-cli
> 
> > FT.CREATE idx:table ON HASH PREFIX 1 table: SCHEMA DestinationName TAG WITHSUFFIXTRIE
> 
> > hset table:1 DestinationName "abc.com"
> > hset table:2 DestinationName "NOTEXIST"
> > hset table:3 DestinationName "sub1.abc.com"
> > hset table:4 DestinationName "sub1.xyz.com"
> > hset table:5 DestinationName "sub1.network.tcp"
> > hset table:6 DestinationName "network.tcp"
> > hset table:7 DestinationName "redis.com"
> 
> 
> > FT.SEARCH idx:table '-@DestinationName:{*abc\.com} -@DestinationName:{NOTEXIST} -@DestinationName:{*network\.tcp}' DIALECT 2 
> 1) (integer) 2
> 2) "table:4"
> 3) 1) "DestinationName"
>    2) "sub1.xyz.com"
> 4) "table:7"
> 5) 1) "DestinationName"
>    2) "redis.com"
> 
> 
> > FT.SEARCH idx:table '-(@DestinationName:{*abc\.com} |  @DestinationName:{NOTEXIST} | @DestinationName:{*network\.tcp})' DIALECT 2 
> 1) (integer) 2
> 2) "table:4"
> 3) 1) "DestinationName"
>    2) "sub1.xyz.com"
> 4) "table:7"
> 5) 1) "DestinationName"
>    2) "redis.com"
> ```



> 
thx for answer,

if i try with big data like key size 11594, the first record is consistent but rest of record is inconsistent so result is inconsistent as you below;

127.0.0.1:6379> **DBSIZE**
(integer) **11594**
127.0.0.1:6379> **FT.SEARCH idx:table_1 "-@DestinationName :{NOTEXIST} -@DestinationName :{*network\\.tcp} -@DestinationName :{*abc\\.org}" dialect 2**
 1) (integer) 18
 2) "KARTAL_1:227"
 3) 1) "**DestinationName**"
    2) "**answer.github.com**"
    3) "UniqueId"
    4) "0x892cba340x00700149"
 4) "KARTAL_1:9492"
 5) 1) "DestinationName"
    2) "htc.ytm005.erm285.abc.org"
    3) "UniqueId"
    4) "0x9b1e3cb80x0040c3f0"
 6) "KARTAL_1:9539"
 7) 1) "DestinationName"
    2) "htc.ytm865.erm405.abc.org"
    3) "UniqueId"
    4) "0x1723ed8d0x00209fff"
 8) "KARTAL_1:9929"
 9) 1) "DestinationName"
    2) "htc.ytm055.erm460.abc.org"
    3) "UniqueId"
    4) "0x961005130x005095d9"


if i try with small data like key size 555, the result is consistent as you below;

127.0.0.1:6379> **DBSIZE**
(integer) **555**
127.0.0.1:6379> **FT.SEARCH idx:table_1 "-@DestinationName :{NOTEXIST} -@DestinationName :{*network\\.tcp} -@DestinationName :{*abc\\.org}" dialect 2**
1) (integer) 1
2) "KARTAL_1:227"
3) 1) "DestinationName"
   2) "answer.github.com"
   3) "UniqueId"
   4) "0x892cba340x00700149"

**Comment by ackelle** [comment]
@oshadmi what is the effect of DBSIZE in this case? is this related by special character?

**Comment by oshadmi** [comment]
@ackelle More keys (larger DBSIZE) may return more results and it may take longer. It could be that a timeout occurs and some of the results are not returned. You can try adding `TIMEOUT 0` to the query and see if you get consistent results, e.g.,
`FT.SEARCH .... dialect 2 timeout 0`
