### ISSUE TITLE
Inconsistent query results RediSearch

### ISSUE THREAD

**Issue by chaa012** [RediSearch/RediSearch#3663]
I have ~800k keys in my redis server , and they are all hashes , I am trying to do specific queries on my data however my query results are incredibly inconsistent ,I'm not sure whether that's a Redis problem or a problem when it comes to intializing the redis indexes and ft.search query .

I created my index this way : FT.CREATE idxfx:fx ON HASH PREFIX 1 Forex schema counterpart AS counterpart TEXT portfolio AS portfolio TAG internal AS internal TEXT initiatorSide AS initiatorSide TEXT

These two queries return different results : 
 ----FT.SEARCH idxfx:fx "@counterpart:ABITIBI @portfolio:{ ENTRYPL_IMPORT2 | CSSFXG2_2_NFCN | SEQ_SC6_A } ((@internal:No) | (@initiatorSide:No))" RETURN 5 counterpart portfolio contractClass internal initiatorSide 

1) "1"
2) "Forex:818798"
3) 1) "counterpart"
   2) "ABITIBI"
   3) "portfolio"
   4) "ENTRYPL_IMPORT2"
   5) "contractClass"
   6) "Single financial contract"
   7) "internal"
   8) "No"
   9) "initiatorSide"
   10) "No"

---FT.SEARCH idxfx:fx "@counterpart:ABITIBI @portfolio:{ ENTRYPL_IMPORT2 | CSSFXG2_2_NFCN | SEQ_SC6_A } ((@internal:Yes) | (@initiatorSide:No))" RETURN 5 counterpart portfolio contractClass internal initiatorSide
1) "0"

These two queries should return the same answer usually since | means "OR" in redis however this is not the case in here .

**Comment by chaa012** [comment]
@oshadmi do you have any clue into what could be the cause for this?

**Comment by chaa012** [comment]
I used it , I also used the TIMEOUT 0 in case it's a timeout issue , but the issue persists .

**Comment by oshadmi** [comment]
@chaa012 `No` is a [`stopword`](https://redis.io/docs/stack/search/reference/stopwords/)
You can add to the index definition `STOPWORDS 0` to see if it solves the issue.

In addition, please note that attributes are case sensitive so in `FT.SEARCH` you should use `@portfolio` as in the index definition.

You can use [`FT.EXPLAIN`](https://redis.io/commands/ft.explain/) instead of `FT.SEARCH` to see how the query is evaluated.
For example (when using `redis-cli --raw`)
```
> FT.EXPLAIN idxfx:fx "@counterpart:ABITIBI @portfolio:{ ENTRYPL_IMPORT2 | CSSFXG2_2_NFCN | SEQ_SC6_A } ((@internal:Yes) | (@initiatorSide:No))" RETURN 5 counterpart portfolio contractClass internal initiatorSide DIALECT 2
INTERSECT {
  @counterpart:UNION {
    @counterpart:abitibi
    @counterpart:+abitibi(expanded)
  }
  TAG:@portfolio {
    entrypl_import2
    cssfxg2_2_nfcn
    seq_sc6_a
  }
  UNION {
    @internal:UNION {
      @internal:yes
      @internal:+yes(expanded)
    }
    @initiatorSide:UNION {
      @initiatorSide:no
      @initiatorSide:+no(expanded)
    }
  }
}


```

**Comment by chaa012** [comment]
As @oshadmi said , the problem was related to the stopword "No", so thank you so much the query seems to be correct right now , however the issue still persist in that I only get a part of the data that seems to correspond to the query and each time I requery the data , I get more and more results ,I am using TIMEOUT 0 but the issue persists , and I have no idea as to why Redis has this behaviour.

**Comment by oshadmi** [comment]
@chaa012 Could be that keys are being updated affecting the query?

**Comment by chaa012** [comment]
Not really the whole data set is not being modified, I realised that the query index takes a long time to take into account all the keys i have in my redis server(~800k) , whenever I run the ft.info command, the number of docs keeps being increased until it reaches the number of documents I currently have , but in order to do so it's taking a long time , and I have no idea how to speed up the process ,or how this could scale out .

**Comment by chaa012** [comment]
I don't suppose it's a normal thing , because it's unreal to wait more than an hour for the index creation to be able to query on all of our data ? Do you have any clue as to why this is @oshadmi ?

**Comment by chaa012** [comment]
Can anyone please help , My company's target is for 3 minutes index creation so I'm not sure how to do that .

**Comment by ofekshenawa** [comment]
Hey @chaa012 ,
I looked into the problem you mentioned about Redis database's indexing being slow. I tested it on my own Mac M1 using redis-stack and found that the indexing process in Redis is actually working well. To confirm this, I created 800,000 keys that meet your requirements and checked how long it took to index them.

To do this, I used the following Python script

```
import redis
import random
import string

# Establish a connection to Redis
redis_client = redis.Redis(host='localhost', port=6379)
def random_string():
    ltrs = string.ascii_letters
    random_string = "".join(random.choice(ltrs) for _ in range(random.randint(0,10)))
    return random_string

def random_sentence():
    random_sentence = " ".join(random_string() for _ in range(random.randint(0,10)))
    return random_sentence

def generate_random_value():
    # Define the key-value pairs
    portfolios = ["ENTRYPL_IMPORT2", "CSSFXG2_2_NFCN","SEQ_SC6_A"]
    key_value_pairs = {
        "counterpart": "ABITIBI",
        "portfolio": random.choice(portfolios),
        "contractClass": random_sentence(),
        "internal": "No",
        "initiatorSide": "No"
    }
    return key_value_pairs


for i in range(800000):
    # Set the key-value pairs in Redis
    redis_client.hmset(f"Forex:{i}", generate_random_value())

#index creation
redis_client.execute_command("FT.CREATE idxfx:fx ON HASH PREFIX 1 Forex schema counterpart AS counterpart TEXT portfolio AS portfolio TAG internal AS internal TEXT initiatorSide AS initiatorSide TEXT")
```

And here you can find the logs from `redis-stack-server`:
```
53430:M 26 Jun 2023 14:10:56.520 * <module> Scanning index idxfx:fx in background
53430:M 26 Jun 2023 14:11:03.025 * <module> Scanning index idxfx:fx in background: done (scanned=800000)
```

These logs indicate that Redis scanned and indexed all 800,000 entries in the “idxfx:fx” index within the given timeframe. The indexing process completed successfully in approximately 7 seconds.

**Comment by chaa012** [comment]
Hi @ofekshenawa , thank you for your response , I wasn't so clear in my question , but I have created a new index with about 150 fields (since I have 150 fields and clients could query on any of them ,I supposed having a pre-defined index with all the fields is better ) and it took over 2 hours to scan through the documents I have , I know that 150 is a huge number but it should not take this much time ,what could possibly be making the indexing take so long? How could I debug this?
