### ISSUE TITLE
Quickstart: Searching and Querying Redis data

### ISSUE THREAD

**Issue by DenisLutsky** [RediSearch/RediSearch#3709]
Can someone please explain to me, which node.js library is used in this example? 
And why do you use different examples for programming languages and Redis CLI commands?

If there used [redis-om](https://www.npmjs.com/package/redis-om) so why don't you add a description for this functionality to npm readme? 
But I think in those examples used [node-redis](https://www.npmjs.com/package/redis) lib, with [search](https://github.com/redis/node-redis/tree/a7d5bc7ca4da6cde66140ae4fea96a8ea6e7ce64/packages/search) addon.

Is it correct?

**Comment by uglide** [comment]
Hi @DenisLutsky 
Thanks for the feedback. 

In the "Quickstart: Searching and Querying Redis data" we use [node-redis](https://www.npmjs.com/package/redis) client. You can click on the "Quick-Start" button at the bottom of each code snippet to learn more about how to install and use the client:
<img width="851" alt="Screenshot 2023-07-17 at 12 25 16" src="https://github.com/RediSearch/RediSearch/assets/1655867/1ac32086-d314-4d72-9096-b4b9feb843d6">

Regarding the 

> And why do you use different examples for programming languages and Redis CLI commands?

Please point out on which steps you see deviations in code examples.
