### ISSUE TITLE
question: code of NewIndexSpec strange

### ISSUE THREAD

**Issue by freecw** [RediSearch/RediSearch#3720]
IndexSpec *NewIndexSpec(const char *name) {
  IndexSpec *sp = rm_calloc(1, sizeof(IndexSpec));
  sp->fields = rm_calloc(sizeof(FieldSpec), SPEC_MAX_FIELDS);

}

sp->fields = rm_calloc(sizeof(FieldSpec), SPEC_MAX_FIELDS);
should it be  sp->fields = rm_calloc(SPEC_MAX_FIELDS, sizeof(FieldSpec)); ?

**Comment by alonre24** [comment]
You're probably right. In practice, it makes no difference. 
Thanks
