### ISSUE TITLE
help: JSON text field lost its content after a day or more 

### ISSUE THREAD

**Issue by chenlizhao** [RediSearch/RediSearch#3722]
I had a phone field which was text sortable, when I saved data in JSON with "phone":"+85268576716", it was correct at that time, but after one day or more, the phone was changed to 85268576716, the "+" symbol was lost, please help me!

**Comment by chenlizhao** [comment]
https://redis.io/docs/interact/search-and-query/advanced-concepts/sorting/, it it related to Normalization (UNF option?

**Comment by oshadmi** [comment]
@chenlizhao Can you please share more info, such as the index definition, the related JSON document, which update operations were performed, etc.
