### ISSUE TITLE
Search and sorting

### ISSUE THREAD

**Issue by linjiadian** [RediSearch/RediSearch#3727]
How can I make the search result order by random?

**Comment by GuyAv46** [comment]
By random do you mean random shuffle or not sorted?
You can get the results unsorted using `FT.AGGREGATE`, which does not sort the results by default. If no sorting is specified, the results will be returned in some order depending on the query.
If you actually want to get the results in some random order (so if you query the same command over and over you'll get different results/ ordered in a different order), there is no built-in method for doing so. You can try looking into `APPLY` expressions to generate some random value for each doc and then sort by it (although there is also no direct way to do so at the moment), if your docs have some timestamp in them you can try and generate, using numeric or time operations, or by using a slightly different APPLY expression every time (something like `APPLY '@doc_id * <random int here> % 100`).
Lastly, you can always get all the relevant results and choose randomly or order them randomly on the client side.

**Comment by GuyAv46** [comment]
In addition, you can implement your own [scoring extension](https://redis.io/docs/interact/search-and-query/administration/extensions/#the-scoring-function-api) that will return some random value.
Take a look on [these examples](https://github.com/RediSearch/RediSearch/tree/master/tests/ctests/ext-example) for how to add your own extensions
