### ISSUE TITLE
RediSearch 2.8.X require redis version >7.2

### ISSUE THREAD

**Issue by githubname1024** [RediSearch/RediSearch#3750]
Dear @gkorland :
I saw RediSearch 2.8.X require the minimal redis version is 7.2. 
The requirement is in 2.8.4, 2.8.3 and 2.8.2 release notes, but the 2.8.1 requires the minimal redis version is 6.2.
And the redis 7.2 does not release yet.
Does the 2.8.X truly require the redis > 7.2, or it is a mistake?

Thank you very much.

**Comment by LiorKogan** [comment]
7.2 is indeed the minimal Redis version for RediSearch 2.8
It will be released soon.

**Comment by Designxiaozai** [comment]
请问你调研好了么 用的什么版本呢
