### ISSUE TITLE
[BUG] some instance in redis cluster always print the Re-Authenticating

### ISSUE THREAD

**Issue by githubname1024** [RediSearch/RediSearch#3762]
I deploy a redis cluster with build Redisearch Coord=oss. And set the right OSS_GLOBAL_PASSWORD before running the instance.
The cluster has 3 masters and 3 slaves.

After deployed, I check the redis instance log. It may occur the error log as following in one master and slave group. 
It occur this error log when this instance link to all other instances.
 
![图片](https://github.com/RediSearch/RediSearch/assets/100768089/0ee2ef41-1da4-44cc-a792-6a7eb598ccfe)

And I try to shutdown and restart the bad redis instance. And after restart it, other instances may occur link to this one Re-Auth. And this instance error log disapper.

But when I shutdown all the instances, sleep a while and restart all. All the instances will OK.

I add log to print auth in RediSearch,  I got the following as below. 

The auth is wrong, and it is from redis command key's value (truncate the key's value, for example, the value contains "https://www.google.com/search"). 

![图片](https://github.com/RediSearch/RediSearch/assets/100768089/64227d58-315c-4de1-abf6-9d8318136111)

Is it a bug when get the MREndpoint(MRConn) info? Is there any idea about how to slove this problem?

Thank you very much.

**Comment by githubname1024** [comment]
@oshadmi Is there any news about this issue? Please tell me if there is any news that I missed. Thank you very much.

**Comment by Designxiaozai** [comment]
请问你用的什么版本呢

**Comment by Designxiaozai** [comment]
能告知下么

**Comment by githubname1024** [comment]
redis version: 6.2.13
redisearch version: 2.6.12
