### ISSUE TITLE
FT.CREATE: Sortable TAG field

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [RediSearch/RediSearch#3770]
Hi,

As per [documentation](https://redis.io/commands/ft.create/):

`SORTABLE - NUMERIC, TAG, TEXT, or GEO attributes can have an optional SORTABLE argument.`

<img width="659" alt="Screenshot 2023-08-17 at 11 38 43 AM" src="https://github.com/RediSearch/RediSearch/assets/1003384/a71e4a2e-aed2-44f6-bb41-cbae3cf65501">

But when I try to create index for JSON documents with 1 field as TAG SORTABLE, then I get following error:

`(error) On JSON, cannot set tag field to sortable - fieldName`

Can you please help here?

**Comment by slorello89** [comment]
Upgrade your RediSearch version, this was a thing when RedisJSON + Search first came out but has since been resolved.
