### ISSUE TITLE
RediSearch Performance unstable 

### ISSUE THREAD

**Issue by chouaib-laaouina** [RediSearch/RediSearch#3796]
I have 1.5 million keys stored in my Redis server, distributed across 10 different hash structures that I'm querying. Each hash structure has a varying number of entries; for example, Forex has 800,000 entries, while Commodities has only 4,000. I run the same query on all of these hash structures. When I conduct tests using Jaeger, I observe that query times can vary widely—sometimes they're as fast as a few tens of milliseconds, but occasionally they can take up to 2 seconds, which is unacceptable for my needs. I'm trying to understand why this inconsistency occurs and how I can diagnose and resolve the issue.

To provide some context, here's an example of the indexing approach I'm using. I create a single index that covers hundreds of attributes using the following syntax:

FT.CREATE idx:Forex STOPWORDS 0 ON HASH PREFIX 1 Forex SCHEMA attribute Type ...

In terms of data structure, my keys follow the format Forex:id, where each 'id' is unique.

![image](https://github.com/RediSearch/RediSearch/assets/91499771/bc322763-0a75-4ab5-8542-2a827aefb289)

As illustrated in the image, queries related to other regions have been processed quickly, while forex and commodities experienced significant delays, despite commodities having the least amount of data.

**Comment by filipecosta90** [comment]
@chouaib-laaouina please share the full index definition, the setup details, and the output of ft.profile for the offending query (ft.profile docs in https://redis.io/commands/ft.profile/).
The above should help getting more context on where is your time being spent within RediSearch.

**Comment by chouaib-laaouina** [comment]
Hi for the index I can't share the exact attribute names but I'm creating an index for each type of Hash, and the schema is on all the fields so basically a couple hundred fields which types are either TAG or  Numeric .When it comes to the setup details, nothing out of the default stuff , I'm just setting MAXSEARCHRESULTS to -1. This is how i create my JedisPool in Java . 

This is in the constructor code and is only called once : 
```
GenericObjectPoolConfig<Connection> connection_conf = new GenericObjectPoolConfig<>();
            connection_conf.setMaxTotal(10);
            JedisClientConfig jedisClientConfig = DefaultJedisClientConfig.builder().socketTimeoutMillis(10000000).build();
            HostAndPort config = new HostAndPort("IP", 6379);
            jedis = new JedisPooled(connection_conf, config, jedisClientConfig);
```
This is an example of how I'm querying : 
FTSearchParams params = new FTSearchParams();
        params.returnFields("portfolio","internal",.......);//Over 50 fields
        params.limit(0, Integer.MAX_VALUE);
        String idx = "idx:allForex";
         jedis.ftSearch(idx, "(@portfolio:{ portfolio1|portfolio2}) (@counterpart:{ counterpart1}) (@internal:{ No})) RETURN 18 return1 return2 ...", params)
         
        
This is the return of the profile command , im not sure why but im getting "Syntax error at offset 212 near FI_GCC_CDS" when running it in redis insight cli . 
         
FT.PROFILE idx:allForex Search Query "(@portfolio:{ ARBI_WASH_AD|FX_SPLIWASH_AD|FX_HDGWASH_AD|ROLL_WASH_AD|SELL_WASH_AD|SELL_STORE_AD|OBU|EUROBONDS|SUKUK|DERIVATIVES|FX_E-COMMERCE|FX_FLOWS|FX_MANAGEMENT_S|IMM_REPO|BEC_STRUCTURE|BEC_VANILLA|FI_GCC_CDS}) (@counterpart:{ MLCCTP_14328}) (@internal:{ No})"

**Comment by chouaib-laaouina** [comment]
Hey , anyone got a clue into what could be wrong  @sazzad16 @filipecosta90

**Comment by chouaib-laaouina** [comment]
Hey , anyone got a clue into what could be wrong @sazzad16 @filipecosta90
