### ISSUE TITLE
[BUG] [REDIS STACK] SORT function does not return the same ordering of the list

### ISSUE THREAD

**Issue by lejdiprifti** [RediSearch/RediSearch#3803]
Describe the bug

When I try to use the SORT function, it does not return the same ordering of the list in RedisStack.

To reproduce

Get a list using the SORT function, then make an operation to update one element in the list. If the field that you are searching for has the same value for some elements, you will see that the element that you update, tops the list in the second SORT query that you will make. Use the FT.SEARCH function.

Expected behavior

I expect to receive the same list based on the field I am searching, without depending on the update I make on the element.

**Comment by K-Jo** [comment]
@lejdiprifti can you elaborate a bit on your search query and which update you are making on your data?

**Comment by lejdiprifti** [comment]
Sure!

This is the command I am executing.
`FT.SEARCH "index" "@id:{4555bcbd\\-1d15\\-46f1\\-9acb\\-91e29c1f63f5} @param1:{ee2aa256\\-5c67\\-42cb\\-871f\\-a402fcdf2160}" "SORTBY" "param2"  DESC LIMIT 0 3000`

This outputs a certain list.
Then, I go and update the `param3`.

If for two JSON objects the `param2` is equal, the JSON object I updated recently will come up before the other objects.

**Comment by lejdiprifti** [comment]
In order to fix this issue, I came up with a workaround. 

I added an `index` to each JSON object I store in redis. Then, I use the `FT.AGGREGATE` function to query and sort by multiple fields.

Why `FT.AGGREGATE`?
Because the `FT.SEARCH` does not give the opportunity to sort by more than one field.
