### ISSUE TITLE
[BUG] error is override 

### ISSUE THREAD

**Issue by liuqianhong6007** [RediSearch/RediSearch#3806]
![企业微信截图_422d309e-bb08-4035-a387-db63b24ef2c6](https://github.com/RediSearch/RediSearch/assets/31907732/dd15ac52-bb7d-4630-91a5-dff97aaa2e92)

**Comment by GuyAv46** [comment]
Hey
Where is this code snippet from?

**Comment by liuqianhong6007** [comment]
> Hey Where is this code snippet from?

Sorry, it's "https://github.com/RediSearch/redisearch-go/blob/ef2058b4f14cfb94cc14635a7030bc21279061c0/redisearch/client.go#L271" in redissearch-go.

**Comment by oshadmi** [comment]
@chayim should move to redisearch-go repo?
