### ISSUE TITLE
FT.CREATE - `NOINDEX` explanation needs updating, is unclear / misleading.

### ISSUE THREAD

**Issue by simonprickett** [RediSearch/RediSearch#3815]
The description for `NOINDEX` is unclear / misleading here:

>NOINDEX - Attributes can have the NOINDEX option, which means they will not be indexed. This is useful in conjunction with SORTABLE, to create attributes whose update using PARTIAL will not cause full reindexing of the document. If an attribute has NOINDEX and doesn't have SORTABLE, it will just be ignored by the index.

https://redis.io/commands/ft.create/

It's my understanding that `NOINDEX` should be used for `SORTABLE` fields where you want to sort by the field but not do any sort of search e.g. numeric ranges on it.

The mention of updates and `PARTIAL` here is confusing and isn't something that helps the user.

**Comment by Didas-git** [comment]
The description is also unclear/misleading on the `field and type options` page.

> NOINDEX indicates that the field is not indexed. This is useful for storing { ... } that you don't want to search for, but you still want to retrieve them in search results.

https://redis.io/docs/interact/search-and-query/basic-constructs/field-and-type-options/
