### ISSUE TITLE
[BUG] Redis vector search does not return required number of documents for large K

### ISSUE THREAD

**Issue by ruslaniv** [RediSearch/RediSearch#3833]
**Describe the bug**

I have deployed a RedisSearch server to test vector similarity search. I have followed this guide pretty much exactly, **using HNSW algorithm**:
1. [Using Redis as a Vector Database with OpenAI](https://github.com/openai/openai-cookbook/blob/main/examples/vector_databases/redis/getting-started-with-redis-and-openai.ipynb)

My main goal was to test RedisSearch performance for medium size datasets (~20 million documents) and large number of returned documents (~5_000 to 10_000) because ElasticSearch solution for vector similarity search was very slow once we start increasing `k` and `num_candidates` to return a large resulting set. 

We have an embedding model and based on tests with ES it generates adequate embeddings. 

So since we only needed to test the performance (time aspect) of Redis VSS, to save time and money on generating real embeddings with our model, I generated fake embeddings for every document by: 
```
list(np.random.rand(1024))
```
and then indexed 20 million documents into Redis. So now when I perform search and request 1_000 documents I do get 1_000 documents back consistently. 
But requesting 5_000 documents or more, I start getting either empty sets or sets with number of documents less than specified amount. 

This part I do not understand. Nowhere in the code I specified that I needed documents with similarity score above some specific value. I just need 5_000 or 10_000 documents with any score. 

**How can I have Redis VSS return required number of documents with any similarity score?**

======================================================

**To Reproduce**

1. Create an index using HNSW algorithm
2. Insert millions of documents with embedding field containing a number of random floats
3. Search for 10_000 documents without specifying a threshold value for minimum score

**Expected behavior**
10_000 documents with any score should be returned

**Environment (please complete the following information):**
 - ubuntu 22.04.3
 - Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz
- Version
* RediSearch v. 2.8.4
* RedisJSON v. 2.6.6
* RedisTimeSeries v. 1.10.4
* RedisBloom v. 2.6.3
* Triggers and Functions v. 20011

**Additional context**
Search snippet:
```python
    def search_redis(
        redis_client: redis.Redis,
        user_query: str,
        index_name: str = INDEX_NAME,
        vector_field: str = "embedding",
        return_fields: list = ["id", "user_id", "title", "vector_score"],
        hybrid_fields = "*",
        k: int = 100,
    ):
        embedded_query = get_fake_embeddings() # 1024 random floats
        base_query = f'{hybrid_fields}=>[KNN {k} @{vector_field} $vector AS vector_score]'
        query = (
            Query(base_query)
             .return_fields(*return_fields)
             .sort_by("vector_score")
             .paging(0, k)
             .dialect(2)
        )
        params_dict = {"vector": np.array(embedded_query).astype(dtype=np.float32).tobytes()}
        results = redis_client.ft(index_name).search(query, params_dict)
        return results.docs
```

**Comment by ruslaniv** [comment]
@meiravgri Thank you for your quick reply. I did amend the query with the timeout method like this:

```python
...
query = (
        Query(base_query)
         .return_fields(*return_fields)
         .sort_by("vector_score")
         .paging(0, k)
         .dialect(2)
         .timeout(0)
    )
...
```
This indeed helped to alleviate the problem and I started getting exactly 10_000 documents quite more often. 
But there are still cases when I'd be getting 0 or x < 10_000 number of documents. 

Are there any further step I can take to troubleshoot this problem?

**Comment by meiravgri** [comment]
@ruslaniv Can you tell in what cases you get 0 or x < 10_000 results? 
What is the difference between one run and another?
Also it would be helpful if you could share the input to the `base_query`arg.

**Comment by ruslaniv** [comment]
@meiravgri 
I just rerun this piece of code in Jupyter:
```python
%time r = search_redis(redis_client, 'large red apples', k=10_000)
print(len(r))
```

But I think the query part would be irrelevant in my case, since the query embedding is generated like this: 
```python
def get_fake_embeddings():
    return list(np.random.rand(1024))
```
And this ^^^ is the same code I used to generate fake embeddings for the documents that I later indexed into Redis VSS

**Comment by meiravgri** [comment]
One possible reason for getting less than `K` results, is that you are performing a hybrid query, and the prefiltering yields less than `k` results.
Please refer to the [vector similarity query docs](https://redis.io/docs/interact/search-and-query/query/#vector-similarity-search)
![Untitled](https://github.com/RediSearch/RediSearch/assets/109056284/ff232686-c0e2-4966-833b-f1d18d7e3de3)

Also, it is not clear from your example what is the `'large red apples'` argument. Seems like it is supposed to be `user_query` but I don't see where you use this argument.

**Comment by ruslaniv** [comment]
@meiravgri thank you for your answer! 
I changed the query to be a pure KNN query like this:

```python
base_query = f'(*)=>[KNN {k} @{vector_field} $vector AS vector_score]'
```
but I'm still getting 0 results I would say in 20% of the searches I perform.

As for the search query `large red apples` you are right, it is not being used in my current example, it's just a placeholder. In real world scenario this search query will be passed into the search function and embedded in this line: 
```python
embedded_query = get_fake_embeddings() # 1024 random floats
```
but of course instead of generating random 1024 floats I would get a real representation from our embedding model.
In this current example, this search query can be discarded, sorry for the confusion ))

**Comment by ruslaniv** [comment]
Also, at [SO](https://stackoverflow.com/a/77053014/3678257) i got a pointer to check out this option [ON_TIMEOUT](https://redis.io/docs/interact/search-and-query/basic-constructs/configuration-parameters/#on_timeout) by setting timeout value to some small size and setting `ON_TIMEOUT` to `Fail` instead of default `Return` which would cause Redis to actually fail in case of a timeout. 
But when I tried to run 
```python
redis_client.config_set('on_timeout', 'fail')
```
I got an error 
```shell
ResponseError: Unknown option or number of arguments for CONFIG SET - 'on_timeout'
```

**Comment by meiravgri** [comment]
This is not a redis configuration, but the redisearch module configuration
try `redis_client.ft().config_set("ON_TIMEOUT", "FAIL")`

**Comment by meiravgri** [comment]
Did you notice any common parameters or outputs for the cases where you get 0 results?

**Comment by ruslaniv** [comment]
Ahh, ok! 
Well, I think it really was a timeout issue after all. 

When I tried setting either one of the following settings to some very large number, like this
```python
redis_client.ft().config_set('TIMEOUT', '10000000')
#XOR
Query(base_query)... .timeout(100_000_000))
```
I finally started getting consistent results of 10_000 elements in the resulting set. Some queries did take up to 2 seconds (based on `time` Jupyter cell magic) but most of them were in 0.5 - 1 second range. 
I'm not sure why setting `timeout` to `0` did not work.

Setting `timeout` to some very small number like 10 and keeping `k=10_000` would always result in an empty set and execution time was very close to 10 milliseconds (again based on Jupyter cell magic)

Also setting `on_timeout` to `fail` like this:
```python
redis_client.ft().config_set('ON_TIMEOUT', 'fail')
```
did not seem to have any effect, at least in the Jupyter I was not seeing any errors.

**Comment by meiravgri** [comment]
`redis_client.ft().config_set('TIMEOUT', '10000000')` sets the default timeout for every query.
The second overrides the timeout for the **current** query: `Query(base_query)... .timeout(100_000_000))`
So combining the first with `redis_client.ft().config_set('ON_TIMEOUT', 'fail')` won't have any effect if you are not getting timeouts.

WRT `TIMEOUT 0`: A known bug in redis-py, it will be fixed soon. As a temporary workaround, you can explicitly set it using `redis_client.execute_command.("FT.CONFIG", "SET", "TIMEOUT", "0")`

Regarding the query time: 
You can try to reduce it by **adding the returned fields** to the index schema ("id", "user_id", "title") **as SORTABLE** fields.
You can use [FT.ALTER](https://redis.io/commands/ft.alter/) instead of rebuilding your index.

Also, to get more information on the query results & times you can run it using [FT.PROFILE](https://redis.io/commands/ft.profile/)

Let me know if it helps :)

**Comment by ruslaniv** [comment]
Yes, I can confirm that setting 
```python
redis_client.ft().config_set('TIMEOUT', '0')
```
and removing `timeout` setting from the `Query` object also helped to consistently get 10_000 results. 

I will definitely play with setting these fields as sortable and with query profiler.

**Thank you very much for all your help!**

**Comment by meiravgri** [comment]
opened a PR to redis-py to support `query.timeout(0)`
https://github.com/redis/redis-py/pull/2934
