### ISSUE TITLE
[BUG] SORTBY value is giving inconsistent results

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [RediSearch/RediSearch#3866]
**Describe the bug**
My all JSON documents have same value of 1 field. When I sort on this field by ascending and descending order, I get different results

**To Reproduce**
Please follow below redis-cli commands

```shell
192.168.22.129:6380> JSON.SET employee:1 $ '{"id": 1, "name":"Abhijeet", "department":"tech"}'
OK
192.168.22.129:6380> JSON.SET employee:2 $ '{"id": 2, "name":"Mohan", "department":"tech"}'
OK
192.168.22.129:6380> JSON.SET employee:3 $ '{"id": 3, "name":"Sunil", "department":"tech"}'
OK

192.168.22.129:6380> FT.CREATE idx:employee ON JSON PREFIX 1 "employee:" SCHEMA $.id as id NUMERIC SORTABLE $.name as name TEXT SORTABLE $.department as department TEXT SORTABLE
OK
(3.80s)

192.168.22.129:6380> FT.SEARCH idx:employee "@department:tech" sortby department asc
1) (integer) 3
2) "employee:2"
3) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":2,\"name\":\"Mohan\",\"department\":\"tech\"}"
4) "employee:3"
5) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":3,\"name\":\"Sunil\",\"department\":\"tech\"}"
6) "employee:1"
7) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":1,\"name\":\"Abhijeet\",\"department\":\"tech\"}"

192.168.22.129:6380> FT.SEARCH idx:employee "@department:tech" sortby department desc
1) (integer) 3
2) "employee:1"
3) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":1,\"name\":\"Abhijeet\",\"department\":\"tech\"}"
4) "employee:3"
5) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":3,\"name\":\"Sunil\",\"department\":\"tech\"}"
6) "employee:2"
7) 1) "department"
   2) "tech"
   3) "$"
   4) "{\"id\":2,\"name\":\"Mohan\",\"department\":\"tech\"}"
``` 
1. You can execute above redis-cli commands in sequence.
2. I created 3 employees, then created index & then searched by @department:tech.
3. I sorted twice. Once by department in ascending order & next time by department in descending order.

**Observed behavior**
I saw that the employees are listed in following order if I sort by department in ascending order.
2, 3, 1
But if I sort by department in descending order, then I get employees in following order:
1, 3, 2

**Expected behavior**
Since the value of department is same as `tech` for all the 3 employees, I expect result of both search should be same although I sort it by ascending or descending order.

**Screenshots**
<img width="1424" alt="Screenshot 2023-09-15 at 7 54 31 PM" src="https://github.com/RediSearch/RediSearch/assets/1003384/b491eafe-a331-44d4-9e8e-8d3096a32cb3">

**Environment :**
 - CPU model: 
 - redis_version:7.2.0
 - os:Linux 5.15.128-1 x86_64; arch_bits:64

**Comment by alonre24** [comment]
Hi @ABHIJEET-MUNESHWAR,
There is no such guarantee - when you SORTBY some field, all you should expect is to have your results sorted by this specific field.
Note that if you care about secondary sorting by another field (`id` for instance) you can use [`ft.aggregate` command ](https://redis.io/commands/ft.aggregate/).
For example: `FT.AGGREGATE idx:employee "@department:tech" sortby 4 @department desc @id asc`

**Comment by lejdiprifti** [comment]
> Hi @ABHIJEET-MUNESHWAR, There is no such guarantee - when you SORTBY some field, all you should expect is to have your results sorted by this specific field. Note that if you care about secondary sorting by another field (`id` for instance) you can use [`ft.aggregate` command ](https://redis.io/commands/ft.aggregate/). For example: `FT.AGGREGATE idx:employee "@department:tech" sortby 4 @department desc @id asc`

that works!
