### ISSUE TITLE
[BUG] unexpected search result when filtering TEXT Fields with command: FT.SEAERCH 

### ISSUE THREAD

**Issue by SHU-Yce** [RediSearch/RediSearch#3925]
First, I build an index called index:server and sn is one of TEXT Field in this index.
`> FT.CREATE index:server ON JSON PREFIX 1 "ci/" FILTER '@ci_type == "server"' SCHEMA $.ci_type AS ci_type TEXT $.sn AS sn TEXT`

Then, I add some documents.
```
> JSON.SET ci/server/2206 $ {"ci_type":"server","sn":"6CU430G8NC"}
> JSON.SET ci/server/2205 $ {"ci_type":"server","sn":"6CU430G8NS"}
> JSON.SET ci/server/2207 $ {"ci_type":"server","sn":"6CU430G8NE"}
```

Finally, I use FT.SEARCH to filter sn, and get unexpected search results.

```
> FT.SEARCH index:server "@sn:6CU430G8N"
1) (integer) 2
2) "ci/server/2204"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
4) "ci/server/2205"
5) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
```

```
> FT.SEARCH index:server "@sn:6CU430G8NS"
1) (integer) 2
2) "ci/server/2205"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
4) "ci/server/2204"
5) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
```

```
> FT.SEARCH index:server "@sn:6CU430G8NC"
1) (integer) 1
2) "ci/server/2206"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
```

When I search with the query: @sn:6CU430G8N, I expect to get the documents whose sn equal 6CU430G8N.However, it returns 2 documents whose sn starts 6CU430G8N.
When I search with the query: @sn:6CU430G8NS, I expect to get the documents whose sn equal 6CU430G8NS.However, it returns 2 documents whose sn starts with 6CU430G8N.
But when I search with the query: @sn:6CU430G8NC, it works well.

Is there any thing I've done wrong?

**Comment by nafraf** [comment]
Hi @SHU-Yce, 
For `ci_type` and `sn` fields, the TAG field type seems to be a better alternative:

> TAG - Allows exact-match queries, such as categories or primary keys, against the value in this attribute. For more information, see [Tag Fields](https://redis.io/docs/interact/search-and-query/advanced-concepts/tags/).

```sh
127.0.0.1:6379> FT.CREATE index:server ON JSON PREFIX 1 "ci/" FILTER '@ci_type == "server"' SCHEMA $.ci_type AS ci_type TAG $.sn AS sn TAG
127.0.0.1:6379> JSON.SET ci/server/2206 $ '{"ci_type":"server","sn":"6CU430G8NC"}'
127.0.0.1:6379> JSON.SET ci/server/2205 $ '{"ci_type":"server","sn":"6CU430G8NS"}'
127.0.0.1:6379> JSON.SET ci/server/2207 $ '{"ci_type":"server","sn":"6CU430G8NE"}'
```

```sh
127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8N}"
1) (integer) 0
127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8NS}"
1) (integer) 1
2) "ci/server/2205"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8NC}"
1) (integer) 1
2) "ci/server/2206"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
```

**Comment by SHU-Yce** [comment]
> Hi @SHU-Yce, For `ci_type` and `sn` fields, the TAG field type seems to be a better alternative:
> 
> > TAG - Allows exact-match queries, such as categories or primary keys, against the value in this attribute. For more information, see [Tag Fields](https://redis.io/docs/interact/search-and-query/advanced-concepts/tags/).
> 
> ```shell
> 127.0.0.1:6379> FT.CREATE index:server ON JSON PREFIX 1 "ci/" FILTER '@ci_type == "server"' SCHEMA $.ci_type AS ci_type TAG $.sn AS sn TAG
> 127.0.0.1:6379> JSON.SET ci/server/2206 $ '{"ci_type":"server","sn":"6CU430G8NC"}'
> 127.0.0.1:6379> JSON.SET ci/server/2205 $ '{"ci_type":"server","sn":"6CU430G8NS"}'
> 127.0.0.1:6379> JSON.SET ci/server/2207 $ '{"ci_type":"server","sn":"6CU430G8NE"}'
> ```
> 
> ```shell
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8N}"
> 1) (integer) 0
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8NS}"
> 1) (integer) 1
> 2) "ci/server/2205"
> 3) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:{6CU430G8NC}"
> 1) (integer) 1
> 2) "ci/server/2206"
> 3) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
> ```

@nafraf Thanks for your reply.
I don't expect to index the sn field by TAG. Because I also want to match sn in fuzzy mode :
`> FT.SEARCH index:server "6CU430G8NS*"`
So I want to figure out why this problem happened when I index sn with TEXT field.

**Comment by nafraf** [comment]
@SHU-Yce I understand. The multiple results when using TEXT fields are related to stemming expansion.
There are some alternatives:

For TAG fields you can try the wildcard query:
```sh
127.0.0.1:6379> FT.SEARCH index:server "@sn:{w'6CU430G8N*'}" DIALECT 2
1) (integer) 3
2) "ci/server/2206"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
4) "ci/server/2205"
5) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
6) "ci/server/2207"
7) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
```

For TEXT fields try the option `VERBATIM`:

> VERBATIM
does not try to use stemming for query expansion but searches the query terms verbatim.

```sh
FT.CREATE index:server ON JSON PREFIX 1 "ci/" FILTER '@ci_type == "server"' SCHEMA $.ci_type AS ci_type TEXT $.sn AS sn TEXT
JSON.SET ci/server/2206 $ '{"ci_type":"server","sn":"6CU430G8NC"}'
JSON.SET ci/server/2205 $ '{"ci_type":"server","sn":"6CU430G8NS"}'
JSON.SET ci/server/2207 $ '{"ci_type":"server","sn":"6CU430G8NE"}'
```

```sh
127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8N" VERBATIM
1) (integer) 0
127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8N*" VERBATIM
1) (integer) 3
2) "ci/server/2206"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
4) "ci/server/2205"
5) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
6) "ci/server/2207"
7) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8NS" VERBATIM
1) (integer) 1
2) "ci/server/2205"
3) 1) "$"
   2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
```

**Comment by SHU-Yce** [comment]
> @SHU-Yce The multiple results when using TEXT fields are related to stemming expansion. There are some alternatives:
> 
> For TAG fields you can try the wildcard query:
> 
> ```shell
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:{w'6CU430G8N*'}" DIALECT 2
> 1) (integer) 3
> 2) "ci/server/2206"
> 3) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
> 4) "ci/server/2205"
> 5) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
> 6) "ci/server/2207"
> 7) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
> ```
> 
> For TEXT fields try the option `VERBATIM`:
> 
> > VERBATIM
> > does not try to use stemming for query expansion but searches the query terms verbatim.
> 
> ```shell
> FT.CREATE index:server ON JSON PREFIX 1 "ci/" FILTER '@ci_type == "server"' SCHEMA $.ci_type AS ci_type TEXT $.sn AS sn TEXT
> JSON.SET ci/server/2206 $ '{"ci_type":"server","sn":"6CU430G8NC"}'
> JSON.SET ci/server/2205 $ '{"ci_type":"server","sn":"6CU430G8NS"}'
> JSON.SET ci/server/2207 $ '{"ci_type":"server","sn":"6CU430G8NE"}'
> ```
> 
> ```shell
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8N" VERBATIM
> 1) (integer) 0
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8N*" VERBATIM
> 1) (integer) 3
> 2) "ci/server/2206"
> 3) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NC\"}"
> 4) "ci/server/2205"
> 5) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
> 6) "ci/server/2207"
> 7) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NE\"}"
> 127.0.0.1:6379> FT.SEARCH index:server "@sn:6CU430G8NS" VERBATIM
> 1) (integer) 1
> 2) "ci/server/2205"
> 3) 1) "$"
>    2) "{\"ci_type\":\"server\",\"sn\":\"6CU430G8NS\"}"
> ```

@nafraf Thanks a lot. That solve my problem.
