### ISSUE TITLE
[BUG] Redis Search isn't returning records with underscore

### ISSUE THREAD

**Issue by ABHIJEET-MUNESHWAR** [RediSearch/RediSearch#3935]
**Describe the bug**
I inserted few records having underscore in them. Those aren't listed in search.

**To Reproduce**
Please follow below redis-cli commands

```shell
192.168.22.129:6380> JSON.SET employee:1 $ '{"id":1, "name":"NY_A", "salary": 123456}'
OK
192.168.22.129:6380> JSON.SET employee:2 $ '{"id":2, "name":"NY_B", "salary": 123456}'
OK
192.168.22.129:6380> JSON.SET employee:3 $ '{"id":3, "name":"NY_C", "salary": 123456}'
OK
192.168.22.129:6380> JSON.SET employee:4 $ '{"id":4, "name":"NY_D", "salary": 123456}'
OK
192.168.22.129:6380> JSON.SET employee:5 $ '{"id":5, "name":"NY_EFG", "salary": 123456}'
OK

192.168.22.129:6380> FT.SEARCH idx:employee "@id:[1 1] @salary:[123456 123456]"
1) (integer) 0
192.168.22.129:6380> FT.SEARCH idx:employee "@name:*NY_* @salary:123456"
1) (integer) 0
192.168.22.129:6380> FT.SEARCH idx:employee "@id:1 @name:*NY_A* @salary:[123456 123456]"
1) (integer) 0
192.168.22.129:6380> FT.SEARCH idx:employee "@name:*NY_A*"
1) (integer) 0
(0.69s)
192.168.22.129:6380> FT.SEARCH idx:employee "@name:*NY_*"
1) (integer) 0
(1.16s)
192.168.22.129:6380> FT.SEARCH idx:employee "@name:*NY_* @salary:[123456 123456]"
1) (integer) 1
2) "employee:5"
3) 1) "$"
   2) "{\"id\":5,\"name\":\"NY_EFG\",\"salary\":123456}"
192.168.22.129:6380> JSON.SET employee:6 $ '{"id":6, "name":"NY_F_G_H", "salary": 123456}'
OK
```

1. You can execute above redis-cli commands in sequence.
2. I created 5 employees, then created index & then searched by name.

**Observed behavior**
1. I searched by employee ID and Salary. But no result.
2. I searched by name and salary. But I get only 1 record out of 5.

**Expected behavior**
When I search for `@name:*NY_*`,  I expect all 5 records should be listed in result as those records have their name match with search term *NY_*.

**Screenshots**
<img width="1728" alt="Screenshot 2023-10-11 at 12 20 04 AM" src="https://github.com/RediSearch/RediSearch/assets/1003384/99fcb40d-9a51-4e60-a5ca-6a4faf6c354c">

**Environment (please complete the following information):**
 - CPU model:
 - redis_version:7.2.0
 - redis search version: [v2.8.4](https://github.com/RediSearch/RediSearch/releases/tag/v2.8.4)
 - os:Linux 5.15.128-1 x86_64; arch_bits:64

**Comment by adrianoamaral** [comment]
@ABHIJEET-MUNESHWAR I tried to reproduce your steps using Redis Stack 7.2 with Search 2.8.4 and JSON 2.6.6, but could see some of the behaviours that you found. Can you confirm the JSON version? 

For matching queries with `NUMERIC` field as you include in some of them, it requires adding both min and max value (`@salary:[123456 123456]`) 

Following some of the queries using the same index:
```
JSON.SET employee:1 $ '{"id":1, "name":"NY_A", "salary": 123456}'
JSON.SET employee:2 $ '{"id":2, "name":"NY_B", "salary": 123456}'
JSON.SET employee:3 $ '{"id":3, "name":"NY_C", "salary": 123456}'
JSON.SET employee:4 $ '{"id":4, "name":"NY_D", "salary": 123456}'
JSON.SET employee:5 $ '{"id":5, "name":"NY_EFG", "salary": 123456}'

FT.CREATE idx:employee ON JSON PREFIX 1 "employee:" SCHEMA $.id as id NUMERIC SORTABLE $.name as name TEXT SORTABLE $.salary as salary NUMERIC SORTABLE

127.0.0.1:6379> FT.SEARCH idx:employee "@id:[1 1] @salary:[123456 123456]"
1) (integer) 1
2) "employee:1"
3) 1) "$"
   2) "{\"id\":1,\"name\":\"NY_A\",\"salary\":123456}"

127.0.0.1:6379> FT.SEARCH idx:employee "@name:(*NY_*) @salary:[123456 123456]"
 1) (integer) 5
 2) "employee:1"
 3) 1) "$"
    2) "{\"id\":1,\"name\":\"NY_A\",\"salary\":123456}"
 4) "employee:4"
 5) 1) "$"
    2) "{\"id\":4,\"name\":\"NY_D\",\"salary\":123456}"
 6) "employee:5"
 7) 1) "$"
    2) "{\"id\":5,\"name\":\"NY_EFG\",\"salary\":123456}"
 8) "employee:3"
 9) 1) "$"
    2) "{\"id\":3,\"name\":\"NY_C\",\"salary\":123456}"
10) "employee:2"
11) 1) "$"
    2) "{\"id\":2,\"name\":\"NY_B\",\"salary\":123456}"

127.0.0.1:6379> FT.SEARCH idx:employee "@id:[1 1] @name:*NY_A* @salary:[123456 123456]"
1) (integer) 1
2) "employee:1"
3) 1) "$"
   2) "{\"id\":1,\"name\":\"NY_A\",\"salary\":123456}"

127.0.0.1:6379> FT.SEARCH idx:employee "@name:*NY_*"
 1) (integer) 5
 2) "employee:1"
 3) 1) "$"
    2) "{\"id\":1,\"name\":\"NY_A\",\"salary\":123456}"
 4) "employee:4"
 5) 1) "$"
    2) "{\"id\":4,\"name\":\"NY_D\",\"salary\":123456}"
 6) "employee:5"
 7) 1) "$"
    2) "{\"id\":5,\"name\":\"NY_EFG\",\"salary\":123456}"
 8) "employee:3"
 9) 1) "$"
    2) "{\"id\":3,\"name\":\"NY_C\",\"salary\":123456}"
10) "employee:2"
11) 1) "$"
    2) "{\"id\":2,\"name\":\"NY_B\",\"salary\":123456}"
```

**Comment by ABHIJEET-MUNESHWAR** [comment]
I'm using JSON version [v2.6.6](https://github.com/RedisJSON/RedisJSON/releases/tag/v2.6.6).

I dropped above index along with data & created new JSON documents & _again faced unusual results_.

I can see only 1 out of 3 records if I search with `@name:*NY_*`. I see all 3 records when I add 1 more condition of salary to name. i.e. `"@name:*NY_* @salary:[123456 123456]"`

Below are the redis-cli commands:

```shell
JSON.SET employee:1 $ '{"id":1, "name":"NY_Acbd_Efgh", "salary": 123456}'
JSON.SET employee:2 $ '{"id":2, "name":"NY_Ijkl_Mnop", "salary": 123456}'
JSON.SET employee:3 $ '{"id":3, "name":"NY_Qrst_uvwx_yz", "salary": 123456}'
FT.CREATE idx:employee ON JSON PREFIX 1 "employee:" SCHEMA $.id as id NUMERIC SORTABLE $.name as name TEXT SORTABLE $.salary as salary NUMERIC SORTABLE
FT.SEARCH idx:employee "@name:*NY_*"
FT.SEARCH idx:employee "@name:*NY_* @salary:[123456 123456]"
```

<img width="1387" alt="Screenshot 2023-10-11 at 8 06 10 PM" src="https://github.com/RediSearch/RediSearch/assets/1003384/dba6080e-1195-40b9-bffb-eee8353234ad">

**Comment by ABHIJEET-MUNESHWAR** [comment]
@adrianoamaral

I'm using JSON version [v2.6.6](https://github.com/RedisJSON/RedisJSON/releases/tag/v2.6.6).

I dropped above index along with data & created new JSON documents & _again faced unusual results_.

I can see only 1 out of 3 records if I search with `@name:*NY_*`. I see all 3 records when I add 1 more condition of salary to name. i.e. `"@name:*NY_* @salary:[123456 123456]"`

Below are the redis-cli commands:

```shell
JSON.SET employee:1 $ '{"id":1, "name":"NY_Acbd_Efgh", "salary": 123456}'
JSON.SET employee:2 $ '{"id":2, "name":"NY_Ijkl_Mnop", "salary": 123456}'
JSON.SET employee:3 $ '{"id":3, "name":"NY_Qrst_uvwx_yz", "salary": 123456}'
FT.CREATE idx:employee ON JSON PREFIX 1 "employee:" SCHEMA $.id as id NUMERIC SORTABLE $.name as name TEXT SORTABLE $.salary as salary NUMERIC SORTABLE
FT.SEARCH idx:employee "@name:*NY_*"
FT.SEARCH idx:employee "@name:*NY_* @salary:[123456 123456]"
```
<img width="1387" alt="Screenshot 2023-10-11 at 8 06 10 PM" src="https://github.com/RediSearch/RediSearch/assets/1003384/df7ee359-3bfd-4bae-ac32-44af17c09d57">

**Comment by GuyAv46** [comment]
I tried to reproduce your steps again and I got all the results in both cases:
```bash
127.0.0.1:6379> JSON.SET employee:1 $ '{"id":1, "name":"NY_Acbd_Efgh", "salary": 123456}'
OK
127.0.0.1:6379> JSON.SET employee:2 $ '{"id":2, "name":"NY_Ijkl_Mnop", "salary": 123456}'
OK
127.0.0.1:6379> JSON.SET employee:3 $ '{"id":3, "name":"NY_Qrst_uvwx_yz", "salary": 123456}'
OK
127.0.0.1:6379> FT.CREATE idx:employee ON JSON PREFIX 1 "employee:" SCHEMA $.id as id NUMERIC SORTABLE $.name as name TEXT SORTABLE $.salary as salary NUMERIC SORTABLE
OK
127.0.0.1:6379> FT.SEARCH idx:employee "@name:*NY_*"
1) (integer) 3
2) "employee:2"
3) 1) "$"
   2) "{\"id\":2,\"name\":\"NY_Ijkl_Mnop\",\"salary\":123456}"
4) "employee:1"
5) 1) "$"
   2) "{\"id\":1,\"name\":\"NY_Acbd_Efgh\",\"salary\":123456}"
6) "employee:3"
7) 1) "$"
   2) "{\"id\":3,\"name\":\"NY_Qrst_uvwx_yz\",\"salary\":123456}"
127.0.0.1:6379> FT.SEARCH idx:employee "@name:NY_*"
1) (integer) 3
2) "employee:2"
3) 1) "$"
   2) "{\"id\":2,\"name\":\"NY_Ijkl_Mnop\",\"salary\":123456}"
4) "employee:1"
5) 1) "$"
   2) "{\"id\":1,\"name\":\"NY_Acbd_Efgh\",\"salary\":123456}"
6) "employee:3"
7) 1) "$"
   2) "{\"id\":3,\"name\":\"NY_Qrst_uvwx_yz\",\"salary\":123456}"
127.0.0.1:6379> FT.SEARCH idx:employee "@name:*NY_* @salary:[123456 123456]"
1) (integer) 3
2) "employee:2"
3) 1) "$"
   2) "{\"id\":2,\"name\":\"NY_Ijkl_Mnop\",\"salary\":123456}"
4) "employee:1"
5) 1) "$"
   2) "{\"id\":1,\"name\":\"NY_Acbd_Efgh\",\"salary\":123456}"
6) "employee:3"
7) 1) "$"
   2) "{\"id\":3,\"name\":\"NY_Qrst_uvwx_yz\",\"salary\":123456}"
```

**Comment by ABHIJEET-MUNESHWAR** [comment]
Hi @GuyAv46 , @adrianoamaral ,

I tried same query for more than 8000 records where redis fails to search.

This is the example:

I created total of 8820 JSON documents as given in this file.

[Bug.txt](https://github.com/RediSearch/RediSearch/files/13032929/Bug.txt)



Then I created index as follows:

`
FT.CREATE idx:custom_search ON JSON PREFIX 1 "custom_search:" SCHEMA $.entityId as entityId NUMERIC SORTABLE $.entityIdString as entityIdString TEXT $.entityType AS entityType TEXT SORTABLE $.resourceType AS resourceType TAG $.resourceValue AS resourceValue NUMERIC $.name AS name TEXT SORTABLE $.escapedName AS escapedName TEXT $.createdAt as createdAt NUMERIC SORTABLE $.updatedAt as updatedAt NUMERIC SORTABLE
`

Then I queried 2 records using JSON.GET:
`
127.0.0.1:6379> JSON.GET custom_search:table_order:11989
"{\"entityId\":11989,\"entityIdString\":\"11989\",\"entityType\":\"DINE_IN\",\"name\":\"NY_Order_Bidder_PG\",\"escapedName\":\"NY_Order_Bidder_PG\",\"resourceType\":\"CUSTOMER\",\"resourceValue\":10642,\"createdAt\":1663007400,\"updatedAt\":1693333800,\"metaData\":{\"hierarchy\":{}}}"

127.0.0.1:6379> JSON.GET custom_search:table_order:11990
"{\"entityId\":11990,\"entityIdString\":\"11990\",\"entityType\":\"DINE_IN\",\"name\":\"NY_Order_Bidder_NON-PG\",\"escapedName\":\"NY_Order_Bidder_NON\\\\-PG\",\"resourceType\":\"CUSTOMER\",\"resourceValue\":10642,\"createdAt\":1663007400,\"updatedAt\":1692297000,\"metaData\":{\"hierarchy\":{}}}"
`
I was able to get results for above two JSON documents.

But when I search for `Order`, I get zero matching results.

127.0.0.1:6379> FT.SEARCH idx:custom_search " (  ( @entityIdString:(Order) | @entityIdString:(Order*) | @entityIdString:(*Order) | @entityIdString:(*Order*) )  |  ( @escapedName:(Order) | @escapedName:(Order*) | @escapedName:(*Order) | @escapedName:(*Order*) )  ) @resourceType:{CUSTOMER} @resourceValue:[10642 10642]"
1) (integer) 0


Any idea of why redis search didn't work in this case?

**Comment by ABHIJEET-MUNESHWAR** [comment]
Moved my latest reply [here](https://github.com/RediSearch/RediSearch/issues/3971)
