### ISSUE TITLE
[Feature Request] Hybrid Search Integration

### ISSUE THREAD

**Issue by dsanmart** [RediSearch/RediSearch#3937]
It would be very useful for RAG applications to have a hybrid search module in Redis Search that combines the best of dense and sparse methods retrieval.

The solution would be similar to [Weaviate's hybrid search](https://weaviate.io/developers/weaviate/api/graphql/search-operators#hybrid) and ideally with smart fusion methods like the ones they used.

Knowing that you already have BM25 and vector search implemented, this should be a relatively quick feature to implement.

**Comment by alonre24** [comment]
Thanks @dsanmart 
Hybrid scoring search is already on our road map.

**Comment by dsanmart** [comment]
Thanks @alonre24 , and where can I find this road map? Or when are you planing to release this feature?
