### ISSUE TITLE
[BUG] RediSearch escaping filter values

### ISSUE THREAD

**Issue by alexander-schranz** [RediSearch/RediSearch#4092]
## Describe the bug

While working on correct escaping of filters in different search engine in the [SEAL the search engine abstraction layer](https://github.com/schranz-search/schranz-search) for PHP i stumble over some issues when try to filter with special chars in it. 

## To Reproduce

1. Create a Index:

```bash
FT.CREATE test_complex ON JSON PREFIX 1 test_complex SCHEMA $['uuid'] AS uuid TAG SORTABLE $['title'] AS title TEXT $['article'] AS article TEXT $['blocks']['text'][*]['title'] AS blocks__text__title TEXT $['blocks']['text'][*]['description'] AS blocks__text__description TEXT $['blocks']['embed'][*]['title'] AS blocks__embed__title TEXT $['footer']['title'] AS footertitle TEXT $['created.raw'] AS created__raw TAG SORTABLE $['commentsCount'] AS commentsCount NUMERIC SORTABLE $['rating'] AS rating NUMERIC SORTABLE $['isSpecial'] AS isSpecial TAG $['comments'][*]['text'] AS commentstext TEXT $['tags'][*] AS tags TEXT $['tags.raw'][*] AS tags__raw TAG $['categoryIds'][*] AS categoryIds NUMERIC
```

2. Create the Document

```
JSON.SET test_complex:79848403-c1a1-4420-bcc2-06ed537e0d4d $ {"uuid":"79848403-c1a1-4420-bcc2-06ed537e0d4d","title":"Other Blog","header":{"video":{"media":"https:\/\/www.youtube.com\/watch?v=iYM2zFP3Zn0"}},"article":"<article><h2>Other Subtitle<\/h2><p>A html field with some content<\/p><\/article>","footer":{"title":"Other Footer"},"created":"2022-12-26T12:00:00+01:00","commentsCount":0,"rating":2.5,"isSpecial":false,"comments":[],"tags":["UI","UX","?"],"tags.raw":["UI","UX","?"],"categoryIds":[2,3]}
```

3. Try to Search

```
FT.SEARCH test_complex @tags__raw:{?} DIALECT 3

# or more complex

FT.SEARCH test_complex @tags__raw:{The\ 17\"\ O\'Conner\ \&\&\ O\`Series\ \n\ OR\ a\ \|\|\ 1\%2\ book\?} DIALECT 3
```

The `?` can be replaced by some of this values:

**Following fails**:

```bash
A \n break;
The 17\" O'Conner && O`Series a
c b a
||
a || b
book?
O`Series
?
```

**Following works**:

```
17"
O'Conner
A´Other
OR a
1%2
1%2 book
The 17\" O'Conner && O`Series
The 17\" O'Conner && O`Series b
```

Based on the docs (https://redis.io/docs/interact/search-and-query/advanced-concepts/escaping/) we are escaping the listed characters `,.<>{}[]"':;!@#$%^&*()-+=~` with `\` but still lot of situation filter does not work. 

So the docs seems incomplete there are more characters to escape like `|, `´` `?` but not sure 🤔  

My current list is so following:

```
,.<>{}[]"\':;!@#$%^&*()-+=~?|`´
```

But still strange:  

`The 17\" O'Conner && O`Series a`: Does not work  
`The 17\" O'Conner && O`Series b`: Does work

So there must still something strange with the filter with special chars.

**Update** to the a b example when also escaping white space ` ` it works. But what still does not work is filter containing a line break `\n` not yet tested tabs or other special chars in PHP

## Environment (please complete the following information):

 - OS: MacOS Docker 
 - CPU model ARM
 - Version/branch redis/redis-stack:7.2.0-v2

**Additional context**

I tested different filters and create a document with the same name some of them works but some of them don't work:

**Comment by nafraf** [comment]
Hello @alexander-schranz, thanks for the report
1. There are some missing separators in the list of separators in the docs. This is the list of separators listed in the source [code](https://github.com/RediSearch/RediSearch/blob/fd60a0b8debb233f679770bb86e528c251d1c853/src/toksep.h#L13):
```
space + tab + ,./(){}[]:;~!@#$%^&*-=+|'`"<>? 
```
2.  Could you share an example of how are you creating a doc with a complex text and the list of terms that it generates?
``FT.TAGVALS index field_name``

**Comment by alexander-schranz** [comment]
@nafraf Thx for your reponse.

> Could you share an example of how are you creating a doc with a complex text?

It is the "tag" from type TAG field above in the description `tags TEXT $['tags.raw'][*] AS tags__raw TAG`. Its a field just for filtering.

```
FT.CREATE test_complex ON JSON PREFIX 1 test_complex SCHEMA "$['tags'][*]" AS tags TEXT "$['tags.raw'][*]" AS tags__raw TAG
```

Where the tags_raw field contain the special chars which we try to filter on exact match.

The whole code is also available in https://github.com/schranz-search/schranz-search/pull/298 requires PHP / composer to run:

```
git clone git@github.com:alexander-schranz/schranz-search.git
git checkout bugfix/redisearch-escaping

# go to redis adapter
cd packages/seal-redisearch-adapter

# start redis
docker compose up

# install deps
composer install

# run test failing test
composer test -- --filter="testEqualConditionSpecialString"
```

> space + tab + ,./(){}[]:;~!@#$%^&*-=+|'`"<>? 

There is one thing which still does not work when the filter contains a linebreak. So for example `"Some \n new line"` does not work.

**Comment by oshadmi** [comment]
@alexander-schranz 

Is this helpful?

```
127.0.0.1:6379> FT.CREATE test_complex ON JSON PREFIX 1 test_complex SCHEMA "$['tags'][*]" AS tags TEXT "$['tags.raw'][*]" AS tags__raw TAG
OK
127.0.0.1:6379> JSON.SET test_complex:79848403-c1a1-4420-bcc2-06ed537e0d4d__B $ '{"tags":["UI","UX","?"],"tags.raw":["UI","UX","hello\\nworld"]}'
OK

127.0.0.1:6379> FT.SEARCH test_complex "@tags__raw:{hello\\\\nworld}"
1) (integer) 1
2) "test_complex:79848403-c1a1-4420-bcc2-06ed537e0d4d__B"
3) 1) "$"
   2) "{\"tags\":[\"UI\",\"UX\",\"?\"],\"tags.raw\":[\"UI\",\"UX\",\"hello\\\\nworld\"]}"

```

**Comment by alexander-schranz** [comment]
@oshadmi I will check it out today evening. What I see is the `JSON.SET` the value was also modified that is something we can not do `"hello\\nworld"` need to be `"hello\nworld"`. Else it would be returned incorrectly by `JSON.GET`.

**Comment by alexander-schranz** [comment]
This works:

```
FT.CREATE test_complex ON JSON PREFIX 1 test_complex SCHEMA "$['tags'][*]" AS tags TEXT "$['tags.raw'][*]" AS tags__raw TAG
OK

JSON.SET test_complex:79848403-c1a1-4420-bcc2-06ed537e0d4d__B $ '{"tags":["UI","UX","?"],"tags.raw":["UI","UX","hello\nworld"]}'
OK

FT.SEARCH test_complex "@tags__raw:{hello\\\nworld}"
```

Strangely it requires some type of "double escaping" for `"\n"` the normal escape method does not work as it ends just in `"\\n"` but to work with redis it need to be `"\\\n"` so the escapeFilter method in my case in PHP looks like this:

```php
$escapedValue = \str_replace(
    "\n",
    "\\\n", // see
    \addcslashes($value, ',./(){}[]:;~!@#$%^&*-=+|\'`"<>?' . " " . "\t")
);
```

@oshadmi thx for your help.
