### ISSUE TITLE
[BUG] Document search with location is showing outside of search radius

### ISSUE THREAD

**Issue by jawalker0** [RediSearch/RediSearch#4163]
**Describe the bug**

I'm using RediSearch to search through documents that contain coordinates. When I run a radius search, I am occasionally getting results that are located a short distance outside of the search distance. 

**To reproduce**

Create a document with an indexed set of coordinates. Add entries with these coordinates:
(37.35141,-79.18003)
(37.35141,-79.18003)
(37.35722,-79.17139)
(37.43583,-79.16883)

Running the following query should return the first 3 entries, but not the fourth. Those coordinates are approximately 5-6 miles from the center of the search.

`ft.search indexName "@coords:[37.34060346114586 -79.17873661760095 2 mi]"`

**Expected behavior**

Running the query should show the first 3 entries, as they are the only ones inside the search radius. 

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04 
 - CPU model: i7-1165G7
 - Version/branch RedisStack 7.2

**Additional context**
I've got this query hooked up to a map, so that it refires as I move the center and adjust the zoom level to show me what's on the map based on the current screen. I've also noticed some results (in a larger data set) blinking in and out during those adjustments when they should still be visible on the map. But the 4th search result above doesn't show up on the map because it's too far away and off screen, but it's coming back in the query results.

I have not attempted to reproduce this with standard Redis GeoSpatial data and searching outside of the `ft.search` command.

**Comment by meiravgri** [comment]
Hi @jawalker0 
Please ensure you follow the expected [query syntax](https://redis.io/docs/interact/search-and-query/query/geo-spatial/), where the longitude is defined before the latitude:
`FT.SEARCH index "@geo_field:[lon lat radius unit]"`

To illustrate, I calculated the distance between the 4th entry and the query using the above syntax. With longitude defined first, the calculated distance was 1.41 miles. However, when switching the order of longitude and latitude, the distance calculated was 6.6 miles.

Hope it helps.

**Comment by jawalker0** [comment]
Thank you, that was the problem. I had flipped the coordinates when the UI map was not showing any results. I've refactored everything the use the correct pairs and that solved the issue.
