### ISSUE TITLE
Clarification on FT.DICT commands behavior

### ISSUE THREAD

**Issue by shohamazon** [RediSearch/RediSearch#4304]
Hello, I hope this message finds you well:)

I have been exploring the `FT.DICT` commands (`FT.DICTADD`, `FT.DICTDEL`, `FT.DICTDUMP`), and I enchanted some behaviors that I would like to seek clarification on.

On first look, they looks like a key based commands. But when I ran COMMAND INFO on each of the commands, I get that the key index is 0 (which is no key).

```
COMMAND INFO FT.DICTDEL
1) 1) "FT.DICTDEL"
    2) (integer) -1
    3) 1) readonly
    2) module
    4) (integer) 0
    5) (integer) 0
    6) (integer) 0
    7) (empty array)
    8) (empty array)
    9) (empty array)
    10) (empty array)
```

```
COMMAND INFO FT.DICTDUMP
1)  1) "FT.DICTDUMP"
    2) (integer) -1
    3) 1) readonly
       2) module
    4) (integer) 0
    5) (integer) 0
    6) (integer) 0
    7) (empty array)
    8) (empty array)
    9) (empty array)
   10) (empty array)

```
```
COMMAND INFO FT.DICTADD
1)  1) "FT.DICTADD"
    2) (integer) -1
    3) 1) readonly
       2) module
    4) (integer) 0
    5) (integer) 0
    6) (integer) 0
    7) (empty array)
    8) (empty array)
    9) (empty array)
   10) (empty array)
```

My questions are, what are the request and response policies of the FT.DICT commands?
What are the purposes of a dictionary in RediSearch? Where would I typically use it?
And what is the behavior of this commands? are they key based? 

I will appreciate it if you can clarify this points. 

Thank you very much.

**Comment by raz-mon** [comment]
Hi @shohamazon,

Thanks for reaching out!

I recommend taking a look at the commands' [docs](https://redis.io/commands/), in which you can find the exact request and response specifications per command.

Regarding their use, please see the [`FT.SPELLCHECK`](https://redis.io/commands/ft.spellcheck/) command, which performs a spellcheck to a query. Basically it checks it with regard to specific dictionaries and terms from them.

**Comment by raz-mon** [comment]
Hi @shohamazon,
Sorry for the late reply.

The `FT.DICTADD` and `FT.DICTDEL` commands' policies are:
* Request_policy: `all_shards`.
* Response_policy: `all_succeeded`

Regarding the `FT.DICTDUMP` command, it implements the default behavior as depicted [here](https://redis.io/docs/reference/command-tips/).

We'll add this to the documentation, FYI @adrianoamaral.

**Comment by shohamazon** [comment]
Thank you so much @raz-mon ! 🙂
