### ISSUE TITLE
Tag lower-casing tansformation not handling accents or non-ASCII characters

### ISSUE THREAD

**Issue by jorge-anova** [RediSearch/RediSearch#4315]
Tag lower-casing transformation not handling accents or non-ASCII characters.

Creating index data:
1. FT.CREATE users SCHEMA nametag TAG SORTABLE
2. FT.ADD users user1 1.0 FIELDS nametag "ÁREA DE SERVICIO"

Searching with correct casing:
FT.AGGREGATE users "@nametag:{ÁREA DE SERVICIO}" LOAD 1 @nametag
1) "1"
2) 1) "nametag"
   2) "\xc3\x81REA DE SERVICIO"
   
Searching with lower case but character with accent with correct casing:
FT.AGGREGATE users "@nametag:{Área de servicio}" LOAD 1 @nametag
1) "1"
2) 1) "nametag"
   2) "\xc3\x81REA DE SERVICIO"

Searching with lower case:
FT.AGGREGATE users "@nametag:{área de servicio}" LOAD 1 @nametag
1) "0"

So, for character with accent or non-ASCII characters we need to pass the correct casing to get the result.

Tested with RediSearch v.2.6.6.

**Comment by nafraf** [comment]
This issue is related to https://github.com/RediSearch/RediSearch/issues/2015

**Comment by raz-mon** [comment]
Hi @jorge-anova,

As @nafraf mentioned, this is related #2015 and #4311 (which you reported), and hopefully will be addressed soon.

We will update upon advancement.

Thanks for noticing and reaching out again 👍

**Comment by ashtul** [comment]
@jorge-anova TAG fields support only ascii by design. For UTF support you should use TEXT fields.
