### ISSUE TITLE
README missing build instructions

### ISSUE THREAD

**Issue by joeywhelan** [RediSearch/RediSearch#4414]
There's no clear guidance on how to build this binary.  Below is a set of steps I've found to work, but not sure if these are supposed to be in a more general setup script.  I'm happy to update the README with these steps via PR, if that's appropriate. 

git clone https://github.com/RediSearch/RediSearch.git
cd RediSearch/deps
git clone https://github.com/RedisLabsModules/readies.git   
cd ..
make setup
make fetch
make build

**Comment by meiravgri** [comment]
hi @joeywhelan 
you can find prerequisites and instructions on how to build from source here:
https://redis.io/docs/interact/search-and-query/deprecated/development/

**Comment by joeywhelan** [comment]
I actually attempted to follow that doc.  Couple problems with your suggestion:

1.  That doc is marked as deprecated.
2.  The install procedure it outlines fails.  (./sbin/setup)

Net, we need a current and correct document for build.
