### ISSUE TITLE
RediSearch dead-lock

### ISSUE THREAD

**Issue by vzambo64** [RediSearch/RediSearch#4472]
Followup of https://github.com/RediSearch/RediSearch/issues/4445
Upgraded RedisSearch to 2.8.11.
In a few days, we also got two deadlocks.

After checking the previous bug documentation - I have realized, that RedisJson also should be migrated to v2.6.9 (from v2.6.7).
Can you please help me. Please check if this is the case, or we have some different issue?

Environment:

    GCP VM
    OS: [ ubuntu 18.04.]
    Redis: 7.2.2
    ReJSON 2.6.7
    search: 2.8.11
    timeseries: 1.10.9
    graph: compiled recently no version info

The watchdog stack traces:

13035:signal-handler (1707978883) 
--- WATCHDOG TIMER EXPIRED ---

------ STACK TRACE ------
EIP:
/opt/redis-stack/lib/rejson.so(+0xd4752)[0x7f39cd316752]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f39dbcb5980]
/opt/redis-stack/lib/rejson.so(+0xd4752)[0x7f39cd316752]
/opt/redis-stack/lib/rejson.so(+0xbf324)[0x7f39cd301324]
/opt/redis-stack/lib/rejson.so(+0x7d42c)[0x7f39cd2bf42c]
/opt/redis-stack/lib/rejson.so(+0x82873)[0x7f39cd2c4873]
/opt/redis-stack/lib/rejson.so(+0x828e3)[0x7f39cd2c48e3]
/opt/redis-stack/lib/rejson.so(+0x7dc64)[0x7f39cd2bfc64]
/opt/redis-stack/lib/rejson.so(+0x880dc)[0x7f39cd2ca0dc]
/opt/redis-stack/lib/rejson.so(+0x88465)[0x7f39cd2ca465]
/opt/redis-stack/lib/rejson.so(+0xa9328)[0x7f39cd2eb328]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1ce02d)[0x7f39ce91b02d]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1cc6aa)[0x7f39ce9196aa]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1cb097)[0x7f39ce918097]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x168fe5)[0x7f39ce8b5fe5]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1cb97a)[0x7f39ce91897a]
/opt/redis-stack/lib/redisearch_v2.8.11.so(startPipeline+0x37)[0x7f39ce8acad7]
/opt/redis-stack/lib/redisearch_v2.8.11.so(sendChunk+0x315)[0x7f39ce8ad125]
/opt/redis-stack/lib/redisearch_v2.8.11.so(AREQ_Execute+0x37)[0x7f39ce8adaf7]
/opt/redis-stack/lib/redisearch_v2.8.11.so(RSAggregateCommand+0x1c0)[0x7f39ce8ae660]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(RedisModuleCommandDispatcher+0x59)[0x555c76f4fcd9]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(call+0xfe)[0x555c76ebf89e]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(processCommand+0x92a)[0x555c76ec07da]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(processInputBuffer+0xeb)[0x555c76e96acb]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(readQueryFromClient+0x3d1)[0x555c76e97e81]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(+0x10b936)[0x555c76ec2936]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(+0x111249)[0x555c76ec8249]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(aeProcessEvents+0x321)[0x555c76e42e11]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(aeMain+0x1d)[0x555c76e431fd]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(main+0x364)[0x555c76e387f4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f39db8d3c87]
/opt/redis-stack/bin/redis-server 127.0.0.1:6380(_start+0x2a)[0x555c76e38eba]
13035:signal-handler (1707978883) --------

The sentinel swapped to another instance, that also crashed few hours later:
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(_start+0x2a)[0x55f17fb45eba]
16954:signal-handler (1708007416) --------

16954:M 15 Feb 2024 14:30:16.488 * Module fork exited pid: 28926, retcode: 0, bysignal: 0
16954:M 15 Feb 2024 14:30:16.752 - Module fork started pid: 28963 
16954:M 15 Feb 2024 14:30:18.695 * Module fork exited pid: 28963, retcode: 0, bysignal: 0
16954:signal-handler (1708007420) 
--- WATCHDOG TIMER EXPIRED ---

------ STACK TRACE ------
EIP:
/opt/redis-stack/lib/rejson.so(+0xd4839)[0x7f56b9f1f839]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f56c6edc980]
/opt/redis-stack/lib/rejson.so(+0xd4839)[0x7f56b9f1f839]
/opt/redis-stack/lib/rejson.so(+0xbf324)[0x7f56b9f0a324]
/opt/redis-stack/lib/rejson.so(+0x7d42c)[0x7f56b9ec842c]
/opt/redis-stack/lib/rejson.so(+0x7d497)[0x7f56b9ec8497]
/opt/redis-stack/lib/rejson.so(+0x7d497)[0x7f56b9ec8497]
/opt/redis-stack/lib/rejson.so(+0x880dc)[0x7f56b9ed30dc]
/opt/redis-stack/lib/rejson.so(+0x88465)[0x7f56b9ed3465]
/opt/redis-stack/lib/rejson.so(+0xa9328)[0x7f56b9ef4328]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1ce02d)[0x7f56b981102d]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1cc6aa)[0x7f56b980f6aa]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x1cb097)[0x7f56b980e097]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x168fe5)[0x7f56b97abfe5]
/opt/redis-stack/lib/redisearch_v2.8.11.so(+0x17309d)[0x7f56b97b609d]
/opt/redis-stack/lib/redisearch_v2.8.11.so(startPipeline+0x37)[0x7f56b97a2ad7]
/opt/redis-stack/lib/redisearch_v2.8.11.so(sendChunk+0x315)[0x7f56b97a3125]
/opt/redis-stack/lib/redisearch_v2.8.11.so(AREQ_Execute+0x37)[0x7f56b97a3af7]
/opt/redis-stack/lib/redisearch_v2.8.11.so(RSAggregateCommand+0x1c0)[0x7f56b97a4660]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(RedisModuleCommandDispatcher+0x59)[0x55f17fc5ccd9]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(call+0xfe)[0x55f17fbcc89e]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(processCommand+0x92a)[0x55f17fbcd7da]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(processInputBuffer+0xeb)[0x55f17fba3acb]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(readQueryFromClient+0x3d1)[0x55f17fba4e81]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x10b936)[0x55f17fbcf936]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x111249)[0x55f17fbd5249]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(aeProcessEvents+0x321)[0x55f17fb4fe11]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(aeMain+0x1d)[0x55f17fb501fd]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(main+0x364)[0x55f17fb457f4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f56c6afac87]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(_start+0x2a)[0x55f17fb45eba]
16954:signal-handler (1708007420) --------

16954:M 15 Feb 2024 14:30:25.578 - Module fork started pid: 29053 

16954:signal-handler (1708007427) 
--- WATCHDOG TIMER EXPIRED ---

------ STACK TRACE ------
EIP:
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x1cd41f)[0x55f17fc9141f]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12980)[0x7f56c6edc980]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x1cd41f)[0x55f17fc9141f]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(lua_pushlstring+0x3a)[0x55f17fc883aa]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(luaCallFunction+0x10b)[0x55f17fb89c9b]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(evalGenericCommand+0x4be)[0x55f17fb76bbe]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(call+0xfe)[0x55f17fbcc89e]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(processCommand+0x92a)[0x55f17fbcd7da]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(processInputBuffer+0xeb)[0x55f17fba3acb]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(readQueryFromClient+0x3d1)[0x55f17fba4e81]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x10b936)[0x55f17fbcf936]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(+0x111249)[0x55f17fbd5249]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(aeProcessEvents+0x321)[0x55f17fb4fe11]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(aeMain+0x1d)[0x55f17fb501fd]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(main+0x364)[0x55f17fb457f4]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x7f56c6afac87]
/opt/redis-stack/bin/redis-server 127.0.0.1:6382(_start+0x2a)[0x55f17fb45eba]
16954:signal-handler (1708007427) --------

16954:M 15 Feb 2024 14:30:27.309 - Accepted 127.0.0.1:47746

**Comment by GuyAv46** [comment]
Yes, the solution to the deadlock had to be made in redis, RediSearch and RedisJSON. It is present on early RediSearch 2.8 patches, and is fixed by using redis 7.2, RediSearch 2.8.10, and RedisJSON 2.6.9.
Here is [the fix on RedisJSON](https://github.com/RedisJSON/RedisJSON/pull/1095)

**Comment by vzambo64** [comment]
Thank you very much.
Deployed the new version - hope the issue will disappear.

What is the best to do with the stack traces when Redis crashes?
Is this the right place to ask for help?

**Comment by GuyAv46** [comment]
If the stack trace or crashing command are related to RediSearch, this is the right place :)
