### ISSUE TITLE
[QUESTION] Wildcards not working inside the string

### ISSUE THREAD

**Issue by nijaaouikhalil** [RediSearch/RediSearch#4478]
**Describe the bug**
Redis wildcards not working when it's inside a string/tag
opposed to what the documentation here suggests:

https://redis.io/docs/interact/search-and-query/advanced-concepts/query_syntax/#wildcard-matching

**To Reproduce**
redis-10001.rc.example.com:10001> ft.create idx2 prefix 1 docs: schema foo text
OK
redis-10001.rc.example.com:10001> hset docs:11 foo "11111"
(integer) 1
redis-10001.rc.example.com:10001> hset docs:12 foo "11011"
(integer) 1

I need to be able to return both of the above documents in the FT.search:

ft.search idx1 "@foo:{11?11}"
or
 ft.search idx1 "@foo:{11*11}"
result none of the above matched the two documents.

**Expected behavior**
both documents should have been returned

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu 20.04]
Redis verision: 7.2.0 
RedisSearch: 2.8.8

**Comment by GuyAv46** [comment]
Hey 👋  thanks for reaching out!
For anything else of prefix or suffix search, you have to wrap the word with a single quote (`'`) and add the prefix `w`, Python-style.

Can you try again with
```
ft.search idx1 "@foo:{w'11?11'}"
```
and report if it worked for you?

**Comment by nijaaouikhalil** [comment]
Thanks for the quick reply, but still getting the same result 
(thanks for the catch about the TAG, it was a typo)

**Comment by GuyAv46** [comment]
No problem.
Can you please retry with `DIALECT 2` or higher?

**Comment by nijaaouikhalil** [comment]
correct !! using:
 ft.search idx2 "@foo:(w'11?11')" DIALECT 2 
 worked thanks a lot
