### ISSUE TITLE
[BUG] Is There a offset limit when using `limit offset num`

### ISSUE THREAD

**Issue by ayouman95** [RediSearch/RediSearch#4493]
**Describe the bug**
When I use the command 
```sql
FT.SEARCH idx:vertical_MY "@vertical:Video @status:{unused} @os:{android}" limit 10000 2
```
it returns just a number.

**To Reproduce**
1. insert records (>10000)
2. search records with `limit 10000 2`

**Expected behavior**
return two records

**Screenshots**
![image](https://github.com/RediSearch/RediSearch/assets/156737219/74ccbd8f-d0ee-495d-a0b5-acc7c1e242cc)

**Environment (please complete the following information):**
 - OS: [Amazon Linut 2023 Linux version 6.1.77-99.164.amzn2023.aarch64]
 - CPU model arm64
 - Version/branch [redis/redis-stack-server:latest]

**Additional context**
the result count with my search condition  is greator than 10000
![image](https://github.com/RediSearch/RediSearch/assets/156737219/4372197a-acf9-411c-a348-c6ed65eb1c04)

**Comment by raz-mon** [comment]
Hi @ayouman95, thanks for reaching out!
This is the default limit of the search results returned for an `FT.SEARCH` command, you can see this by running `FT.INFO idx:vertical_MY`, and observing the `MAXSEARCHRESULTS` config param (notice that there is a parallel `MAXAGGREGATERESULTS` for `FT.AGGREGATE` commands).
You can change this by using `FT.CONFIG SET MAXSEARCHRESULTS <value>`, and then get the wanted number of results from your command.
