### ISSUE TITLE
[BUG] Wildcard redisearch on TEXT field does not return result

### ISSUE THREAD

**Issue by TomlDev** [RediSearch/RediSearch#4509]
**Describe the bug**
I have a wildcard query that searches in a TEXT field. For some parts of the text I get a result, for others not.

**To Reproduce**
This is my cash entry:
```
{
cacheKey:"User.6231f1219f9ffa0014d7e8f2"
id:"6231f1219f9ffa0014d7e8f2"
name:"A"
myText:"605b0abd3e44800029463796_deviceGroupSeparator_6228b539c0fe490013a3ef66_deviceGroupSeparator_62456413a8c1db0013bb5c64_deviceGroupSeparator_6228b68fc0fe490013a41334_deviceGroupSeparator_6228bc64c0fe490013a4e395_deviceGroupSeparator_605b0abd3e44800029463796_deviceGroupSeparator_6228b539c0fe490013a3ef66_deviceGroupSeparator_62456413a8c1db0013bb5c64_deviceGroupSeparator_6228b68fc0fe490013a41334_deviceGroupSeparator_622a01989f9ffa0014d564bc_deviceGroupSeparator_605b0abd3e44800029463796_deviceGroupSeparator_6228b539c0fe490013a3ef66_deviceGroupSeparator_62456413a8c1db0013bb5c64_deviceGroupSeparator_6228b68fc0fe490013a41334_deviceGroupSeparator_622a01b09f9ffa0014d56c65_deviceGroupSeparator_"
}
```
This search will return the correct result: ✅
```
FT.SEARCH idx:Users "@myText:*605b0abd3e44800029463796*"
```
This search will return the correct result: ✅
```
FT.SEARCH idx:Users "@myText:*6228b539c0fe490013a3ef66*"
```

This search will return no result: ❌
```
FT.SEARCH idx:Users "@myText:*6228b68fc0fe490013a41334*"
```

Both times, the searched string is included in the `myText` field.

**Expected behavior**
It should return the cache entry both times.

I know that it is adviced to use TAG fields instead, but I don't have full control over the code, so it would be good to get it to work with TEXT fields.

I also tried with this command (increased dialect up to 4):
```
FT.SEARCH idx:Users "@roleAssignmentsDeviceGroupIds:(w'*6228bc64c0fe490013a4e395*')" DIALECT 2
```

**Environment (please complete the following information):**
 - Version/branch: docker container, image: redis/redis-stack:latest

**Comment by nafraf** [comment]
Hi @TomlDev, thanks for the clear report.
The terms have a maximum length of 128 characters, so, for your document the term stored in the index is:
``605b0abd3e44800029463796_devicegroupseparator_6228b539c0fe490013a3ef66_devicegroupseparator_62456413a8c1db0013bb5c64_devicegroup``
Look that the strings ``605b0abd3e44800029463796`` and ``6228b539c0fe490013a3ef66`` are part of the first 128 characters, but ``6228b68fc0fe490013a41334`` not. That explains your results.

There are some alternatives that I could think now:
1. Can you reduce the string length? Maybe replace ``devicegroupseparator`` by a single character.
2. Replace ``_`` by white space, with this, each sequence of character between white spaces will be a term, and the doc will be found.

**Comment by TomlDev** [comment]
Thanks for the quick reply!
Okay, that explains it. Both of your proposals work.

So the solution is to fix the place where the string gets created, I will close the issue 👍🏽
