### ISSUE TITLE
[BUG] Unable to do full-text exact search with a colon in the text

### ISSUE THREAD

**Issue by w-biggs** [RediSearch/RediSearch#4514]
**Describe the bug**
I have a field ("metadata") that contains JSON strings as TEXT. I am trying to query for text fields that contain the text `\"score\":1`. I can't seem to do a query for that text, however. This query seems like it should work, but I get `Syntax error at offset 20 near \"score\"`:

`FT.SEARCH {ImageDescriptions} "@metadata:\"\\\"score\\\":1\""`

Escaping the colon gives me 0 results:

`FT.SEARCH {ImageDescriptions} "@metadata:\"\\\"score\\\"\:1\""`

The issue seems to be the colon, as this doesn't even work:

`FT.SEARCH {ImageDescriptions} "@metadata:\"\:1\""`

**To Reproduce**
1. TEXT field contains `"score":1`
2. `FT.SEARCH {ImageDescriptions} "@metadata:\"\:1\""` gives back 0 results.

**Expected behavior**
There are matching results.

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04.3 LTS
 - Version/branch: 7.2.4 (via `redis/redis-stack:latest` docker image)

**Comment by nafraf** [comment]
Hi @w-biggs, thanks for the report
For TEST fields, the character `:` is considered as a separator, and two terms will be created. This can be confirmed by a query where with two conditions:
```sh
127.0.0.1:6379> FT.CREATE idx ON JSON SCHEMA $.t AS t TEXT
OK
127.0.0.1:6379> JSON.SET doc1 $ '{"t":"\"score\":1"}'
OK
127.0.0.1:6379> FT.search idx '@t:score @t:1'
1) (integer) 1
2) "doc1"
3) 1) "$"
   2) "{\"t\":\"\\\"score\\\":1\"}"
```
At this moment, the separators are not configurable.

An alternative for your case is to use TAG field:
```sh
127.0.0.1:6379> FT.CREATE idx ON JSON SCHEMA $.t AS t TAG
OK
127.0.0.1:6379> JSON.SET doc1 $ '{"t":"\"score\":1"}'
OK
127.0.0.1:6379> FT.search idx '@t:{\"score\"\:1}'
1) (integer) 1
2) "doc1"
3) 1) "$"
   2) "{\"t\":\"\\\"score\\\":1\"}"
```

**Comment by w-biggs** [comment]
Got it, thank you. For my use case I think I need to stick with TEXT but I think I can work around this issue.
