### ISSUE TITLE
L2 distance computation misunderstanding in documentation

### ISSUE THREAD

**Issue by Voveka98** [RediSearch/RediSearch#4558]
Hi! Thanks for your work!

I am trying to dive into RadiSearch and have a question:
In documentation about L2 distance there is a vector base with 2 vectors: 
```go
127.0.0.1:6379> FT.CREATE itemIdx5 ON JSON PREFIX 1 item: SCHEMA $.embeddings[*] AS embeddings VECTOR FLAT 6 DIM 4 DISTANCE_METRIC L2 TYPE FLOAT32
OK
127.0.0.1:6379> JSON.SET item:1 $ '{"name":"Noise-cancelling Bluetooth headphones","description":"Wireless Bluetooth headphones with noise-cancelling technology","price":99.98,"stock":25,"colors":["black","silver"],"embeddings":[[0.87,-0.15,0.55,0.03]]}'
OK
127.0.0.1:6379> JSON.SET item:2 $ '{"name":"Wireless earbuds","description":"Wireless Bluetooth in-ear headphones","price":64.99,"stock":17,"colors":["black","white"],"embeddings":[[-0.7,-0.51,0.88,0.14],[-0.8,-0.15,0.33,-0.01]]}'
OK

Therefore vectors are:
[-0.8,-0.15,0.33,-0.01]
[-0.7,-0.51,0.88,0.14]
```

Then you send a request with vector [1, 1, 1, 1]
```go
FT.SEARCH itemIdx5 '*=>[KNN 2 @embeddings $blob AS dist]' SORTBY dist PARAMS 2 blob \x01\x01\x01\x01 DIALECT 2
```

And get as a result next distances:
```go
2) "item:2"
3) 1) "dist"
   2) "0.771500051022"
   3) "$"
   4) "{\"name\":\"Wireless earbuds\",\"description\":\"Wireless Bluetooth in-ear headphones\",\"price\":64.99,\"stock\":17,\"colors\":[\"black\",\"white\"],\"embeddings\":[[-0.7,-0.51,0.88,0.14],[-0.8,-0.15,0.33,-0.01]]}"
4) "item:1"
5) 1) "dist"
   2) "1.08280003071"
   3) "$"
   4) "{\"name\":\"Noise-cancelling Bluetooth headphones\",\"description\":\"Wireless Bluetooth headphones with noise-cancelling technology\",\"price\":99.98,\"stock\":25,\"colors\":[\"black\",\"silver\"],\"embeddings\":[[0.87,-0.15,0.55,0.03]]}"
```

In documentation about distances L2 distance says that L2 computes as:
```go
sqrt(sum((x_i - y_i)**2)).
```

I tried to compute distance manually and got another results:
```go
L2([1, 1, 1, 1], [-0.8,-0.15,0.33,-0.01]) = 2.4559
L2([1, 1, 1, 1], [-0.7,-0.51,0.88,0.14]) = 2.43
```

Can you please explain me where i am wrong?

**Comment by meiravgri** [comment]
Hi @Voveka98 
When passing a binary blob to the CLI, **enclosing it in quotes is essential**. Otherwise, each character is interpreted as one byte. You can find more information about this in the [Redis documentation](https://redis.io/docs/connect/cli/).

The binary blob "\x01\x01\x01\x01" you provided is only 4 bytes long, but a 16-byte blob is expected (**dim * sizeof(float)**).
Ensure that you're passing the **correct blob size** for your data.

In addition to that, **we don't apply sqrt** on the distance value. Therefore, the expected distance is
```
(sum((x_i - y_i)**2))
```

Good luck :)

**Comment by meiravgri** [comment]
Regarding documentation, we acknowledge that while it might be a bit confusing, the decision to skip sqrt operation is made to save computation time during the query process.

For the second question, I'm not personally familiar with Go. it's worth noting that the Go client doesn't directly support Redisearch integration. If you're looking for an alternative method, you might consider referring to the [Python client ](https://redis-py.readthedocs.io/en/stable/examples/search_vector_similarity_examples.html) documentation, where they provide an example of converting vectors into binary blobs using the `tobytes()` function. 

Additionally, you can explore the [RedisVL](https://github.com/RedisVentures/redisvl) repository, which offers an easy start Python client dedicated to using Redis as a vector database.

**Comment by Voveka98** [comment]
Ok, thanks a lot!
