### ISSUE TITLE
[BUG] I can't run "make build" command successfully

### ISSUE THREAD

**Issue by aedudon** [RediSearch/RediSearch#4560]
**Describe the bug**
I face some issues when i try to run "make build" command. i already run "make setup". i use redis 6+
![image](https://github.com/RediSearch/RediSearch/assets/109790101/f5336590-7864-4801-8cb9-9f159d3e5ac2)
![image](https://github.com/RediSearch/RediSearch/assets/109790101/cb69978e-9b62-47a6-8827-3ad64c483c81)
![image](https://github.com/RediSearch/RediSearch/assets/109790101/a346c871-7a5e-4346-9c79-6bd908cd1a1a)

Anyone can help me pls.

**Comment by meiravgri** [comment]
Hi @aedudon 
We have changed the building dependencies.
`make setup` is no longer needed.
To build the module you need to download boost headers.
you can use the script provided in our library
```
cd  .install
./install_boost 1.83.0
cd ..
```
make sure you delete the previously generated `bin` directory and then run `make` again.
let me know if you encounter any issues.

**Comment by aedudon** [comment]
my command: 
"git clone --recursive https://github.com/RediSearch/RediSearch.git"
"cd  .install"
"./install_boost 1.83.0"
"cd .."
"make"
 is right ?

**Comment by aedudon** [comment]
> Hi @aedudon We have changed the building dependencies. `make setup` is no longer needed. To build the module you need to download boost headers. you can use the script provided in our library
> 
> ```
> cd  .install
> ./install_boost 1.83.0
> cd ..
> ```
> 
> make sure you delete the previously generated `bin` directory and then run `make` again. let me know if you encounter any issues.
check for me

**Comment by ShogunPanda** [comment]
It worked for me as well. 
Nit: it's `./install_boost.sh 1.83.0`.

I strongly suggest you put this instruction somewhere in the documentation.

**Comment by meiravgri** [comment]
thanks, fixed

We are working on updating the documentation.
