### ISSUE TITLE
Facing build issue on PPC64LE architecture.

### ISSUE THREAD

**Issue by vinodk99** [RediSearch/RediSearch#4575]
**Describe the bug**
While building facing issues.

**Expected behavior**
Build need to passed 

**Environment (please complete the following information):**
 - OS:RHELl9
 - CPU model:ppc64le
 - Version/branch :v2.8.13

**Additional context**
`[root@9b789160fca7 RediSearch]# make build TEST=1

Generating /RediSearch/bin/linux-ppc64le-release/search/Makefile ...
Not searching for unused variables given on the command line.
# OS=linux
# OSNICK=centos9
# ARCH=ppc64le
-- The C compiler identification is GNU 11.4.1
-- The CXX compiler identification is GNU 11.4.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
# CMAKE_C_COMPILER_ID: GNU
# VectorSimilarity root: /RediSearch/deps/VectorSimilarity
# VectorSimilarity binroot: /RediSearch/bin/linux-ppc64le-release/search/deps/VectorSimilarity
# VectorSimilarity static build: ON
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for getauxval
-- Looking for getauxval - found
-- BOOST_DIR is not empty: /RediSearch/.install/boost
-- Found Python: /usr/bin/python3.9 (found version "3.9.18") found components: Interpreter
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: /RediSearch/bin/linux-ppc64le-release/search

Building /RediSearch/bin/linux-ppc64le-release/search/redisearch.so ...
[  0%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/alloc.c.o
[  0%] Building CXX object src/geometry/CMakeFiles/redisearch-geometry.dir/query_iterator.cpp.o
[  0%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/args.c.o
[  0%] Building C object deps/friso/CMakeFiles/friso.dir/friso.c.o
[  0%] Building C object deps/phonetics/CMakeFiles/metaphone.dir/double_metaphone.c.o
[  1%] Building CXX object src/geometry/CMakeFiles/redisearch-geometry.dir/rtree.cpp.o
[  0%] Building CXX object src/geometry/CMakeFiles/redisearch-geometry.dir/geometry_api.cpp.o
[  1%] Building C object example_extension/CMakeFiles/example_extension.dir/example.c.o
[  2%] Building CXX object tests/cpptests/redismock/CMakeFiles/redismock.dir/redismock.cpp.o
[  2%] Building C object _deps/cpu_features-build/CMakeFiles/unix_based_hardware_detection.dir/src/hwcaps.c.o
[  2%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/filesystem.c.o
[  2%] Building C object tests/c_utils/CMakeFiles/apistubs.dir/api_stubs.c.o
[  3%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces_no_optimization.dir/L2/L2.cpp.o
[  3%] Building CXX object deps/googletest/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  3%] Building C object deps/snowball/CMakeFiles/snowball.dir/libstemmer/libstemmer.c.o
[  3%] Building C object CMakeFiles/rscore.dir/deps/base64/base64.c.o
[  4%] Linking C static library libapistubs.a
[  4%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/stack_line_reader.c.o
[  4%] Built target apistubs
[  4%] Building C object CMakeFiles/rscore.dir/deps/base64/base64_check.c.o
[  4%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces_no_optimization.dir/IP/IP.cpp.o
[  5%] Building C object CMakeFiles/rscore.dir/deps/cndict/cndict_data.c.o
[  5%] Linking C shared library libexample_extension.so
[  5%] Built target unix_based_hardware_detection
[  5%] Building C object CMakeFiles/rscore.dir/deps/geohash/geohash.c.o
[  5%] Built target example_extension
[  5%] Building C object deps/snowball/CMakeFiles/snowball.dir/runtime/api.c.o
[  5%] Building C object CMakeFiles/rscore.dir/deps/geohash/geohash_helper.c.o
[  6%] Building C object deps/snowball/CMakeFiles/snowball.dir/runtime/utilities.c.o
[  8%] Building C object CMakeFiles/rscore.dir/deps/libnu/cesu8.c.o
[  8%] Building C object _deps/cpu_features-build/CMakeFiles/utils.dir/src/string_view.c.o
[  8%] Linking CXX static library libVectorSimilaritySpaces_no_optimization.a
[  8%] Built target VectorSimilaritySpaces_no_optimization
[  8%] Building C object CMakeFiles/rscore.dir/deps/libnu/ducet.c.o
[  8%] Building C object CMakeFiles/rscore.dir/deps/libnu/extra.c.o
[  8%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_basque.c.o
In file included from /RediSearch/src/geometry/rtree.cpp:7:
/RediSearch/src/geometry/rtree.hpp:20:10: fatal error: boost/geometry/geometry.hpp: No such file or directory
   20 | #include <boost/geometry/geometry.hpp>             // duh...
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/geometry/CMakeFiles/redisearch-geometry.dir/build.make:104: src/geometry/CMakeFiles/redisearch-geometry.dir/rtree.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /RediSearch/src/geometry/geometry_api.cpp:8:
/RediSearch/src/geometry/rtree.hpp:20:10: fatal error: boost/geometry/geometry.hpp: No such file or directory
   20 | #include <boost/geometry/geometry.hpp>             // duh...
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/geometry/CMakeFiles/redisearch-geometry.dir/build.make:76: src/geometry/CMakeFiles/redisearch-geometry.dir/geometry_api.cpp.o] Error 1
[  8%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_catalan.c.o
[  9%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_danish.c.o
[  9%] Building C object CMakeFiles/rscore.dir/deps/libnu/strcoll.c.o
[ 10%] Building C object CMakeFiles/rscore.dir/deps/libnu/strings.c.o
[ 10%] Building C object CMakeFiles/rscore.dir/deps/libnu/tofold.c.o
[ 11%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/cmdparse.c.o
[ 11%] Built target utils
[ 11%] Building C object CMakeFiles/rscore.dir/deps/libnu/tolower.c.o
[ 11%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/heap.c.o
[ 12%] Building C object CMakeFiles/rscore.dir/deps/libnu/toupper.c.o
[ 12%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_dutch.c.o
[ 12%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16.c.o
[ 12%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_english.c.o
[ 13%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_finnish.c.o
[ 13%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16be.c.o
[ 14%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16he.c.o
[ 14%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf16le.c.o
[ 14%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32.c.o
[ 14%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/periodic.c.o
[ 14%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32be.c.o
/RediSearch/deps/snowball/src_c/stem_ISO_8859_1_finnish.c: In function ‘finnish_ISO_8859_1_stem’:
/RediSearch/deps/snowball/src_c/stem_ISO_8859_1_finnish.c:655:13: note: the layout of aggregates containing vectors with 4-byte alignment has changed in GCC 5
  655 |     {   int c1 = z->c;
      |             ^~
[ 15%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32he.c.o
[ 15%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf32le.c.o
[ 15%] Building C object CMakeFiles/rscore.dir/deps/libnu/utf8.c.o
[ 16%] Building C object CMakeFiles/rscore.dir/deps/libnu/validate.c.o
[ 16%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_french.c.o
[ 16%] Building CXX object tests/cpptests/redismock/CMakeFiles/redismock.dir/util.cpp.o
[ 16%] Building C object CMakeFiles/rscore.dir/deps/libnu/version.c.o
[ 17%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/priority_queue.c.o
[ 17%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_german.c.o
[ 17%] Building C object CMakeFiles/rscore.dir/deps/miniz/miniz.c.o
[ 18%] Building C object CMakeFiles/rscore.dir/deps/thpool/thpool.c.o
[ 19%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_indonesian.c.o
[ 19%] Building C object CMakeFiles/rscore.dir/deps/triemap/triemap.c.o
[ 19%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/sds.c.o
[ 19%] Built target metaphone
[ 19%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_aarch64_linux_or_android.c.o
[ 19%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_irish.c.o
[ 19%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_arm_linux_or_android.c.o
[ 20%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_mips_linux_or_android.c.o
[ 20%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_italian.c.o
[ 20%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_norwegian.c.o
[ 20%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_ppc_linux.c.o
[ 21%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_porter.c.o
[ 21%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_portuguese.c.o
[ 21%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_spanish.c.o
[ 21%] Building C object CMakeFiles/rscore.dir/deps/wildcard/wildcard.c.o
/RediSearch/deps/friso/friso.c: In function ‘friso_new_token’:
/RediSearch/deps/friso/friso.c:309:25: note: the layout of aggregates containing vectors with 4-byte alignment has changed in GCC 5
  309 | FRISO_API friso_token_t friso_new_token(void) {
      |                         ^~~~~~~~~~~~~~~
[ 21%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_x86_freebsd.c.o
[ 22%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_swedish.c.o
[ 23%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_x86_linux_or_android.c.o
[ 24%] Building C object deps/friso/CMakeFiles/friso.dir/friso_array.c.o
[ 24%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_x86_macos.c.o
[ 24%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_2_hungarian.c.o
[ 24%] Building C object _deps/cpu_features-build/CMakeFiles/cpu_features.dir/src/impl_x86_windows.c.o
[ 24%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_2_romanian.c.o
[ 25%] Linking C static library libcpu_features.a
[ 27%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_KOI8_R_russian.c.o
[ 27%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_exec.c.o
[ 27%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/strings.c.o
[ 27%] Built target cpu_features
[ 27%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_plan.c.o
[ 27%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_arabic.c.o
[ 27%] Building C object deps/friso/CMakeFiles/friso.dir/friso_hash.c.o
[ 27%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/util.c.o
[ 27%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_armenian.c.o
[ 27%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_basque.c.o
[ 27%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces.dir/space_aux.cpp.o
[ 27%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces.dir/L2_space.cpp.o
[ 28%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_catalan.c.o
[ 29%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces.dir/IP_space.cpp.o
[ 29%] Building C object deps/friso/CMakeFiles/friso.dir/friso_lexicon.c.o
[ 29%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_danish.c.o
[ 29%] Building CXX object deps/VectorSimilarity/src/VecSim/spaces/CMakeFiles/VectorSimilaritySpaces.dir/spaces.cpp.o
make[2]: *** [CMakeFiles/Makefile2:750: src/geometry/CMakeFiles/redisearch-geometry.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 30%] Building C object deps/rmutil/CMakeFiles/rmutil.dir/vector.c.o
[ 30%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_dutch.c.o
[ 31%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_english.c.o
/RediSearch/deps/friso/friso_lexicon.c: In function ‘new_lex_entry’:
/RediSearch/deps/friso/friso_lexicon.c:92:15: note: the layout of aggregates containing vectors with 2-byte alignment has changed in GCC 5
   92 |     e->length = (uchar_t) length;    //length
      |     ~~~~~~~~~~^~~~~~~~~~~~~~~~~~
[ 31%] Linking CXX static library libVectorSimilaritySpaces.a
[ 31%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_request.c.o
[ 31%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/exprast.c.o
[ 31%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_finnish.c.o
[ 31%] Built target VectorSimilaritySpaces
[ 32%] Building C object deps/friso/CMakeFiles/friso.dir/friso_link.c.o
[ 32%] Built target rmutil
[ 33%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/expression.c.o
[ 33%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_french.c.o
/RediSearch/deps/snowball/src_c/stem_UTF_8_finnish.c: In function ‘finnish_UTF_8_stem’:
/RediSearch/deps/snowball/src_c/stem_UTF_8_finnish.c:659:13: note: the layout of aggregates containing vectors with 4-byte alignment has changed in GCC 5
  659 |     {   int c1 = z->c;
      |             ^~
[ 34%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_german.c.o
[ 34%] Building C object deps/friso/CMakeFiles/friso.dir/friso_string.c.o
[ 34%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_greek.c.o
[ 34%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/lexer.c.o
[ 34%] Building C object deps/friso/CMakeFiles/friso.dir/friso_ctype.c.o
[ 34%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_hindi.c.o
[ 35%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_hungarian.c.o
[ 35%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_indonesian.c.o
[ 36%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/parser.c.o
[ 36%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/date.c.o
[ 37%] Building C object deps/friso/CMakeFiles/friso.dir/friso_UTF8.c.o
[ 37%] Building C object deps/friso/CMakeFiles/friso.dir/friso_GBK.c.o
[ 37%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/function.c.o
[ 37%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_irish.c.o
[ 37%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_italian.c.o
[ 38%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_lithuanian.c.o
[ 38%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_nepali.c.o
[ 38%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/geo.c.o
[ 38%] Built target friso
[ 38%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_norwegian.c.o
[ 39%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/math.c.o
[ 39%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/string.c.o
[ 40%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_porter.c.o
[ 40%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_portuguese.c.o
[ 40%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_romanian.c.o
[ 40%] Building C object CMakeFiles/rscore.dir/src/aggregate/group_by.c.o
[ 41%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_russian.c.o
[ 41%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducer.c.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count.c.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count_distinct.c.o
[ 42%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/deviation.c.o
[ 42%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_serbian.c.o
[ 42%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_spanish.c.o
[ 42%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_swedish.c.o
[ 43%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_tamil.c.o
[ 43%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_turkish.c.o
[ 44%] Building C object deps/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_yiddish.c.o
[ 44%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/first_value.c.o
[ 44%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/minmax.c.o
[ 44%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/quantile.c.o
[ 45%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/random_sample.c.o
[ 45%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/sum.c.o
[ 45%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/to_list.c.o
[ 45%] Building C object CMakeFiles/rscore.dir/src/alias.c.o
[ 46%] Building C object CMakeFiles/rscore.dir/src/buffer.c.o
[ 46%] Building C object CMakeFiles/rscore.dir/src/byte_offsets.c.o
[ 46%] Building C object CMakeFiles/rscore.dir/src/cndict_loader.c.o
[ 47%] Building C object CMakeFiles/rscore.dir/src/concurrent_ctx.c.o
[ 47%] Building C object CMakeFiles/rscore.dir/src/config.c.o
[ 47%] Building C object CMakeFiles/rscore.dir/src/cursor.c.o
[ 48%] Building C object CMakeFiles/rscore.dir/src/debug_commands.c.o
[ 48%] Building C object CMakeFiles/rscore.dir/src/dictionary.c.o
[ 48%] Building C object CMakeFiles/rscore.dir/src/doc_table.c.o
[ 49%] Building C object CMakeFiles/rscore.dir/src/doc_types.c.o
[ 49%] Building C object CMakeFiles/rscore.dir/src/document.c.o
[ 49%] Building C object CMakeFiles/rscore.dir/src/document_add.c.o
[ 49%] Building C object CMakeFiles/rscore.dir/src/document_basic.c.o
[ 50%] Building C object CMakeFiles/rscore.dir/src/extension.c.o
[ 50%] Building C object CMakeFiles/rscore.dir/src/ext/default.c.o
[ 50%] Building C object CMakeFiles/rscore.dir/src/field_spec.c.o
[ 51%] Building C object CMakeFiles/rscore.dir/src/fields_global_stats.c.o
[ 51%] Building C object CMakeFiles/rscore.dir/src/fork_gc.c.o
[ 51%] Building C object CMakeFiles/rscore.dir/src/forward_index.c.o
[ 52%] Building C object CMakeFiles/rscore.dir/src/fragmenter.c.o
[ 52%] Building C object CMakeFiles/rscore.dir/src/gc.c.o
[ 52%] Building C object CMakeFiles/rscore.dir/src/geo_index.c.o
[ 52%] Building C object CMakeFiles/rscore.dir/src/geometry_index.c.o
[ 52%] Built target snowball
[ 53%] Building C object CMakeFiles/rscore.dir/src/highlight_processor.c.o
[ 53%] Building C object CMakeFiles/rscore.dir/src/hll/hll.c.o
[ 53%] Building C object CMakeFiles/rscore.dir/src/hybrid_reader.c.o
[ 54%] Building C object CMakeFiles/rscore.dir/src/id_list.c.o
[ 54%] Building C object CMakeFiles/rscore.dir/src/index.c.o
[ 54%] Building C object CMakeFiles/rscore.dir/src/index_result.c.o
[ 54%] Building C object CMakeFiles/rscore.dir/src/info/field_spec_info.c.o
[ 55%] Building C object CMakeFiles/rscore.dir/src/indexer.c.o
[ 55%] Building C object CMakeFiles/rscore.dir/src/info/index_error.c.o
[ 56%] Building C object CMakeFiles/rscore.dir/src/info_command.c.o
[ 56%] Building C object CMakeFiles/rscore.dir/src/inverted_index.c.o
[ 56%] Building C object CMakeFiles/rscore.dir/src/json.c.o
[ 56%] Building C object CMakeFiles/rscore.dir/src/language.c.o
[ 57%] Building C object CMakeFiles/rscore.dir/src/metric_iterator.c.o
[ 57%] Building C object CMakeFiles/rscore.dir/src/module.c.o
[ 57%] Building C object CMakeFiles/rscore.dir/src/notifications.c.o
[ 58%] Building C object CMakeFiles/rscore.dir/src/numeric_filter.c.o
/RediSearch/src/notifications.c: In function ‘Initialize_RdbNotifications’:
/RediSearch/src/notifications.c:397:5: warning: ‘RedisModuleEvent_ReplBackup’ is deprecated [-Wdeprecated-declarations]
  397 |     int success = RedisModule_SubscribeToServerEvent(ctx, RedisModuleEvent_ReplBackup, ReplicaBackupCallback);
      |     ^~~
In file included from /RediSearch/src/config.h:10,
                 from /RediSearch/src/notifications.c:7:
/RediSearch/deps/RedisModulesSDK/redismodule.h:594:5: note: declared here
  594 |     RedisModuleEvent_ReplBackup = {
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
[ 58%] Building C object CMakeFiles/rscore.dir/src/numeric_index.c.o
[ 58%] Building C object CMakeFiles/rscore.dir/src/offset_vector.c.o
/RediSearch/src/hybrid_reader.c: In function ‘NewHybridVectorIterator’:
/RediSearch/src/hybrid_reader.c:407:16: note: the layout of aggregates containing vectors with 8-byte alignment has changed in GCC 5
  407 | IndexIterator *NewHybridVectorIterator(HybridIteratorParams hParams, QueryError *status) {
      |                ^~~~~~~~~~~~~~~~~~~~~~~
[ 59%] Building C object CMakeFiles/rscore.dir/src/optimizer_reader.c.o
[ 59%] Building C object CMakeFiles/rscore.dir/src/param.c.o
[ 59%] Building C object CMakeFiles/rscore.dir/src/phonetic_manager.c.o
[ 59%] Building C object CMakeFiles/rscore.dir/src/print_version.c.o
[ 60%] Building C object CMakeFiles/rscore.dir/src/profile.c.o
[ 60%] Building C object CMakeFiles/rscore.dir/src/qint.c.o
[ 61%] Building C object CMakeFiles/rscore.dir/src/query.c.o
[ 61%] Building C object CMakeFiles/rscore.dir/src/query_error.c.o
[ 61%] Building C object CMakeFiles/rscore.dir/src/query_optimizer.c.o
[ 61%] Building C object CMakeFiles/rscore.dir/src/query_param.c.o
[ 62%] Building C object CMakeFiles/rscore.dir/src/query_parser/v1/lexer.c.o
[ 62%] Building C object CMakeFiles/rscore.dir/src/query_parser/v1/parser.c.o
[ 62%] Building C object CMakeFiles/rscore.dir/src/query_parser/v2/lexer.c.o
[ 63%] Building C object CMakeFiles/rscore.dir/src/query_parser/v2/parser.c.o
[ 63%] Building C object CMakeFiles/rscore.dir/src/rdb.c.o
[ 63%] Building C object CMakeFiles/rscore.dir/src/redis_index.c.o
[ 63%] Building C object CMakeFiles/rscore.dir/src/redisearch_api.c.o
[ 64%] Building C object CMakeFiles/rscore.dir/src/reply.c.o
[ 64%] Building C object CMakeFiles/rscore.dir/src/result_processor.c.o
[ 64%] Building C object CMakeFiles/rscore.dir/src/rlookup.c.o
[ 65%] Building C object CMakeFiles/rscore.dir/src/rs_geo.c.o
/RediSearch/src/index.c: In function ‘NewUnionIterator’:
/RediSearch/src/index.c:161:12: note: the layout of aggregates containing vectors with 8-byte alignment has changed in GCC 5
  161 |   ctx->num = num;
      |   ~~~~~~~~~^~~~~
[ 65%] Building C object CMakeFiles/rscore.dir/src/rules.c.o
[ 65%] Building C object CMakeFiles/rscore.dir/src/rwlock.c.o
[ 66%] Building C object CMakeFiles/rscore.dir/src/score_explain.c.o
[ 66%] Building C object CMakeFiles/rscore.dir/src/sortable.c.o
[ 66%] Building C object CMakeFiles/rscore.dir/src/spec.c.o
[ 66%] Building C object CMakeFiles/rscore.dir/src/spell_check.c.o
[ 67%] Building C object CMakeFiles/rscore.dir/src/stemmer.c.o
[ 67%] Building C object CMakeFiles/rscore.dir/src/stopwords.c.o
[ 67%] Building C object CMakeFiles/rscore.dir/src/suffix.c.o
[ 68%] Building C object CMakeFiles/rscore.dir/src/suggest.c.o
[ 68%] Building C object CMakeFiles/rscore.dir/src/summarize_spec.c.o
[ 68%] Building C object CMakeFiles/rscore.dir/src/synonym_map.c.o
[ 69%] Building C object CMakeFiles/rscore.dir/src/tag_index.c.o
[ 69%] Building C object CMakeFiles/rscore.dir/src/tokenize.c.o
[ 70%] Building C object CMakeFiles/rscore.dir/src/tokenize_cn.c.o
[ 70%] Building C object CMakeFiles/rscore.dir/src/trie/levenshtein.c.o
[ 70%] Building C object CMakeFiles/rscore.dir/src/trie/rune_util.c.o
[ 70%] Building C object CMakeFiles/rscore.dir/src/trie/sparse_vector.c.o
[ 70%] Building C object CMakeFiles/rscore.dir/src/trie/trie.c.o
[ 71%] Building C object CMakeFiles/rscore.dir/src/trie/trie_type.c.o
[ 71%] Building C object CMakeFiles/rscore.dir/src/util/arr.c.o
[ 71%] Building C object CMakeFiles/rscore.dir/src/util/array.c.o
[ 72%] Building C object CMakeFiles/rscore.dir/src/util/block_alloc.c.o
[ 72%] Building C object CMakeFiles/rscore.dir/src/util/dict.c.o
[ 72%] Building C object CMakeFiles/rscore.dir/src/util/fnv.c.o
[ 73%] Building C object CMakeFiles/rscore.dir/src/util/heap.c.o
[ 73%] Building C object CMakeFiles/rscore.dir/src/util/khtable.c.o
[ 73%] Building C object CMakeFiles/rscore.dir/src/util/logging.c.o
[ 73%] Building C object CMakeFiles/rscore.dir/src/util/mempool.c.o
[ 74%] Building C object CMakeFiles/rscore.dir/src/util/misc.c.o
[ 74%] Building C object CMakeFiles/rscore.dir/src/util/minmax_heap.c.o
[ 74%] Building C object CMakeFiles/rscore.dir/src/util/quantile.c.o
[ 75%] Building C object CMakeFiles/rscore.dir/src/util/references.c.o
[ 75%] Building C object CMakeFiles/rscore.dir/src/util/threadpool_api.c.o
[ 75%] Building C object CMakeFiles/rscore.dir/src/util/workers.c.o
[ 76%] Building C object CMakeFiles/rscore.dir/src/value.c.o
[ 76%] Building C object CMakeFiles/rscore.dir/src/varint.c.o
[ 76%] Building C object CMakeFiles/rscore.dir/src/vector_index.c.o
[ 77%] Linking CXX static library libredismock.a
[ 77%] Built target redismock
[ 77%] Built target rscore
In file included from /RediSearch/deps/googletest/googletest/src/gtest-all.cc:41:
/RediSearch/deps/googletest/googletest/src/gtest.cc: In constructor ‘testing::TestInfo::TestInfo(const string&, const string&, const char*, const char*, testing::internal::CodeLocation, testing::internal::TypeId, testing::internal::TestFactoryBase*)’:
/RediSearch/deps/googletest/googletest/src/gtest.cc:2714:1: note: the layout of aggregates containing vectors with 4-byte alignment has changed in GCC 5
 2714 | TestInfo::TestInfo(const std::string& a_test_suite_name,
      | ^~~~~~~~
[ 77%] Linking CXX static library ../../../lib/libgtest.a
[ 77%] Built target gtest
make[1]: *** [Makefile:136: all] Error 2
make: *** [/RediSearch/deps/readies/mk/cmake.rules:31: /RediSearch/bin/linux-ppc64le-release/search/redisearch.so] Error 2
`

**Comment by GuyAv46** [comment]
Hey @vinodk99, thanks for reaching out!
Seems like you don't have `boost` installed. you can get the missing files by running the script `install_boost.sh` in `.install` or by following any boost library installation guide.
Please refer to [this comment](https://github.com/RediSearch/RediSearch/issues/4560#issuecomment-2024987343) for using our installation script

**Comment by vinodk99** [comment]
@GuyAv46 ,Thanks now it's working

**Comment by GuyAv46** [comment]
Happy to help!
