### ISSUE TITLE
the results obtained after indexing are incomplete

### ISSUE THREAD

**Issue by AllKai** [RediSearch/RediSearch#4585]
My Redis cluster is deployed in Kubernetes with a total of 6 nodes, including 3 masters and 3 slaves. We are using the image: redis/redis-stack-server:7.2.0-v10

<img width="1541" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/9de6b345-a12d-4464-a7e2-effc0c0412f4">

**Issue**:

There are 11 data entries with keys starting with STORE-DATA-INFO: in my cluster. However, after I indexed this prefix, when I execute the command FT.SEARCH IDX:STORE-SEARCH '*', I can only retrieve 6 entries

**Existing dataset**：

<img width="1405" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/8d12266a-af1f-489d-ba25-52f90056bb2d">

**Creation statement**：

FT.CREATE IDX:STORE-SEARCH ON JSON PREFIX 1 STORE-DATA-INFO: SCHEMA
    $.categoryId AS categoryId TAG SEPARATOR ","
    $.storeSourceType AS storeSourceType NUMERIC
    $.storeName AS storeName TEXT NOSTEM
    $.storeType AS storeType NUMERIC
    $.localRegionProvinceCode AS localRegionProvinceCode TAG SEPARATOR ","
    $.localRegionCityCode AS localRegionCityCode TAG SEPARATOR ","
    $.localRegionCountyCode AS localRegionCountyCode TAG SEPARATOR ","
    $.longitudeLatitude AS longitudeLatitude GEO SORTABLE
    $.status AS status NUMERIC
    $.serviceScore AS serviceScore NUMERIC SORTABLE

**Query result**：

<img width="1385" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/3c81f43f-d237-486d-8133-2436217982d1">

-----------------------------
**My redis.conf file content**：

loadmodule /opt/redis-stack/lib/redisearch.so
loadmodule /opt/redis-stack/lib/redisgears.so v8-plugin-path /opt/redis-stack/lib/libredisgears_v8_plugin.so
loadmodule /opt/redis-stack/lib/redistimeseries.so
loadmodule /opt/redis-stack/lib/rejson.so
loadmodule /opt/redis-stack/lib/redisbloom.so
appendonly yes
io-threads 2
io-threads-do-reads yes
dynamic-hz yes
aof-use-rdb-preamble yes
appendfsync everysec
no-appendfsync-on-rewrite yes
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes
aof-rewrite-incremental-fsync yes
activedefrag yes
active-defrag-ignore-bytes 100mb
active-defrag-threshold-lower 10
active-defrag-threshold-upper 80
active-defrag-cycle-min 25
active-defrag-cycle-max 75
cluster-enabled yes
cluster-config-file /var/lib/redis/nodes.conf
cluster-node-timeout 5000
dir /var/lib/redis
port 6379
bind 0.0.0.0
requirepass meichengrediscluster
masterauth meichengrediscluster

------------------------------------
We have another index with the same issue. When there is only one document in the index, it cannot retrieve any data even though it should

**Comment by AllKai** [comment]
I found a configuration item in the official documentation called OSS_GLOBAL_PASSWORD. Since keys are distributed across different node slots in the cluster, and because my cluster has a password, the missing query results could be due to RediSearch being unable to access data from other nodes. However, after configuring OSS_GLOBAL_PASSWORD, my Redis pod failed to start.

**Comment by AllKai** [comment]
Here is one of my JSON structured data, and key is DRIVE-INFO:1730152758256041984

```
{
  "channelId": "ae9096fffe424cd0-00000001-00001578-f8fc94fbbe8f5e96-d952e41e",
  "sessionToken": "53889412a3454de1940686c0bf90dbc4",
  "driverId": "1730152758256041984",
  "location": "112.534329,37.836268",
  "driverPhoneNumber": "18636110528",
  "surname": "郭",
  "status": 0,
  "cityOrderId": null,
  "region": "1401",
  "holdLine": "-1",
  "typeOfBoarding": -1,
  "driveInfo": {
    "carId": "1730166228145836032",
    "carNumber": "晋ARR922",
    "carColor": "黑色",
    "carBrand": "大众汽车牌SVW71411AM",
    "carType": "小型杨车",
    "carSeat": 4,
    "driverType": 2,
    "driveAge": 5,
    "summaryId": "1776925166400610304",
    "lineIds": [
      "1735177506354573312"
    ],
    "departureStartTime": "10:00:00",
    "departureEndTime": "12:00:00"
  },
  "serviceId": "1739920189715275776",
  "ordersInfo": null,
  "reserveOrderIds": null,
  "remainingSeats": 4,
  "intercityReserveOrderInfo": {},
  "offlineOrders": {},
  "offlineCancelOrderIds": []
}
```

I created an index for this：

```
FT.CREATE IDX:ENGINE-DRIVE-SEARCH ON JSON PREFIX 1 DRIVE-INFO: SCHEMA
    $.driverId AS driverId TAG
    $.location AS location GEO SORTABLE
    $.status AS status NUMERIC
    $.region AS region TAG
    $.holdLine AS holdLine TAG
    $.typeOfBoarding AS typeOfBoarding NUMERIC
    $.remainingSeats AS remainingSeats NUMERIC
    $.driveInfo.carSeat AS carSeat NUMERIC
    $.driveInfo.driverType AS driverType NUMERIC
    $.driveInfo.lineIds.* AS lineIds TAG
```
<img width="1385" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/9421af80-2a73-4d7c-b5e8-f8d50ae2fe36">

**Comment by AllKai** [comment]
> Here is one of my JSON structured data, and key is DRIVE-INFO:1730152758256041984
> 
> ```
> {
>   "channelId": "ae9096fffe424cd0-00000001-00001578-f8fc94fbbe8f5e96-d952e41e",
>   "sessionToken": "53889412a3454de1940686c0bf90dbc4",
>   "driverId": "1730152758256041984",
>   "location": "112.534329,37.836268",
>   "driverPhoneNumber": "18636110528",
>   "surname": "郭",
>   "status": 0,
>   "cityOrderId": null,
>   "region": "1401",
>   "holdLine": "-1",
>   "typeOfBoarding": -1,
>   "driveInfo": {
>     "carId": "1730166228145836032",
>     "carNumber": "晋ARR922",
>     "carColor": "黑色",
>     "carBrand": "大众汽车牌SVW71411AM",
>     "carType": "小型杨车",
>     "carSeat": 4,
>     "driverType": 2,
>     "driveAge": 5,
>     "summaryId": "1776925166400610304",
>     "lineIds": [
>       "1735177506354573312"
>     ],
>     "departureStartTime": "10:00:00",
>     "departureEndTime": "12:00:00"
>   },
>   "serviceId": "1739920189715275776",
>   "ordersInfo": null,
>   "reserveOrderIds": null,
>   "remainingSeats": 4,
>   "intercityReserveOrderInfo": {},
>   "offlineOrders": {},
>   "offlineCancelOrderIds": []
> }
> ```
> 
> I created an index for this：
> 
> ```
> FT.CREATE IDX:ENGINE-DRIVE-SEARCH ON JSON PREFIX 1 DRIVE-INFO: SCHEMA
>     $.driverId AS driverId TAG
>     $.location AS location GEO SORTABLE
>     $.status AS status NUMERIC
>     $.region AS region TAG
>     $.holdLine AS holdLine TAG
>     $.typeOfBoarding AS typeOfBoarding NUMERIC
>     $.remainingSeats AS remainingSeats NUMERIC
>     $.driveInfo.carSeat AS carSeat NUMERIC
>     $.driveInfo.driverType AS driverType NUMERIC
>     $.driveInfo.lineIds.* AS lineIds TAG
> ```
> 
> <img alt="image" width="1385" src="https://private-user-images.githubusercontent.com/48918555/320275625-9421af80-2a73-4d7c-b5e8-f8d50ae2fe36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODc1OTUsIm5iZiI6MTcxMjQ4NzI5NSwicGF0aCI6Ii80ODkxODU1NS8zMjAyNzU2MjUtOTQyMWFmODAtMmE3My00ZDdjLWI1ZTgtZjhkNTBhZTJmZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDEwNTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhYzBiZDE5MDgyNWNiM2NiZjU4NDc4YWIzMWEyMGQxZjhlMjBhZDcxOGQ5MmNmNTM5ZGJlZGZlYjU0NTIwY2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fLvKkmYKH94JS2ulAbzhs7OCMfhynvMf7QhCmhYCzuM">

But in the single-node redis-stack with the same image, I can search for the data

**Comment by GuyAv46** [comment]
Hi :)
Are the different redis instances connected to each other in a redis cluster? I believe the available docker images don't contain the cluster options and components.
What is the error message you get when launching with the `OSS_GLOBAL_PASS` configuration?

**Comment by AllKai** [comment]
> Hi :)
> Are the different redis instances connected to each other in a redis cluster? I believe the available docker images don't contain the cluster options and components.
> What is the error message you get when launching with the `OSS_GLOBAL_PASS` configuration?

Our cluster status is normal, as all our microservices except for accessing Redissearch have encountered no errors with any read/write requests to Redis. When I add `loadmodule /opt/redis-stack/lib/redisearch.so OSS_GLOBAL_PASSWORD meichengrediscluster` to my redis.conf, I receive an error message indicating that the OSS_GLOBAL_PASSWORD configuration item cannot be found when starting up. Similarly, when I use the `FT.CONFIG.HELP OSS_GLOBAL_PASSWORD` command to retrieve this configuration item, an empty list is returned.

**Comment by GuyAv46** [comment]
So this confirms you don't have a ReiSearch instance that supports clustering and cross-cluster communication for searching. you can build RediSearch from source with clustering support by running `make build COORD=1`.
Hope this helps

**Comment by GuyAv46** [comment]
and on a side note, if you want to search your Chinese `TEXT` fields, you might want to declare the index language as Chinese

**Comment by AllKai** [comment]
> So this confirms you don't have a ReiSearch instance that supports clustering and cross-cluster communication for searching. you can build RediSearch from source with clustering support by running `make build COORD=1`.
> Hope this helps

Could you please provide more detailed instructions on how to proceed?

**Comment by AllKai** [comment]
> and on a side note, if you want to search your Chinese `TEXT` fields, you might want to declare the index language as Chinese

I understand. The main issue here lies in incomplete data retrieval during the queries

**Comment by GuyAv46** [comment]
On a machine with the right OS and architecture for your docker:
1. Clone this Repository
2. If you don't have [boost](https://www.boost.org/) installed, you can run (from the project root directory) `cd .install && ./install_boost.sh 1.83.0 && cd ..`
3. run `make build COORD=1`.

you will get the library binary `redisearch.so` that supports cluster searches. From here you will have to prepare your docker-compose steps or build your own docker image. I'm no expert but I saw many guides on the internet for how to do so.

**Comment by AllKai** [comment]
> On a machine with the right OS and architecture for your docker:
> 
> 1. Clone this Repository (recursively)
> 2. If you don't have [boost](https://www.boost.org/) installed, you can run (from the project root directory) `cd .install && ./install_boost.sh 1.83.0 && cd ..`
> 3. run `make build COORD=1`.
> 
> you will get the library binary `redisearch.so` that supports cluster searches. From here you will have to prepare your docker-compose steps or build your own docker image. I'm no expert but I saw many guides on the internet for how to do so.

Alright, I'll give it a try.

**Comment by AllKai** [comment]
make build COORD=1

make: /bin/platform: No such file or directory
Makefile:288: /rules: No such file or directory
make: *** No rule to make target '/rules'.  Stop.

What is the situation?

**Comment by GuyAv46** [comment]
have you cloned the repository recursively? `git clone --recurse-submodules`

**Comment by GuyAv46** [comment]
On CI we test with 10 and above. 9 might work as well

**Comment by AllKai** [comment]
> On CI we test with 10 and above. 9 might work as well

After successfully executing make build COORD=1, where is the compiled redisearch.so file located? Additionally, I noticed in other questions that someone mentioned the oss-module.so file is also needed to support Redis clustering. Is that correct?

**Comment by AllKai** [comment]
> > On CI we test with 10 and above. 9 might work as well
> 
> After successfully executing make build COORD=1, where is the compiled redisearch.so file located? Additionally, I noticed in other questions that someone mentioned the oss-module.so file is also needed to support Redis clustering. Is that correct?

<img width="1495" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/75e6163e-0ea5-44d8-8b95-368e0f498bc7">

**Comment by GuyAv46** [comment]
it should be under `bin/linux-x64-release/coord-oss/module-oss.so` or similar. seems like your subdirectory was named `--release`.

**Comment by AllKai** [comment]
> it should be under `bin/linux-x64-release/coord-oss/module-oss.so` or similar. seems like your subdirectory was named `--release`. You need this file instead of the `bin/linux-x64-release/search/redisearch.so`

So, do I need to add another line "--loadmodule module-oss.so OSS_GLOBAL_PASSWORD xxx" to the configuration file?

**Comment by GuyAv46** [comment]
should be enough. Let me know if you manage to search now

**Comment by AllKai** [comment]
> should be enough. Let me know if you manage to search now

<img width="715" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/ad171062-ce9b-4f52-bf42-0bce6549496e">

<img width="1495" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/7b7e59ff-d37a-4df7-a5fc-a7ff2633fc9a">

why?

**Comment by GuyAv46** [comment]
odd. Are you sure the container copied the file? is the `ls` output of the container? is it working with another module(without the configuration)?

**Comment by GuyAv46** [comment]
You should build the module on the same architecture and OS as your server

**Comment by AllKai** [comment]
> You should build the module on the same architecture and OS as your server

I compiled using the same architecture, but it still doesn't work. However, compared to last time, it seems that there is an additional error message containing libcrypto.so.1.1:

My file directory is correct, and the owner, group, and permissions are the same as the other module files in the container.

<img width="1436" alt="image" src="https://github.com/RediSearch/RediSearch/assets/48918555/01311494-2676-44cc-864b-0d23a9dec565">

**Comment by GuyAv46** [comment]
Do you have SSL 1.1 installed on the server? you can check with `openssl version`.

**Comment by AllKai** [comment]
> Do you have SSL 1.1 installed on the server? you can check with `openssl version`.

I've resolved it, but now when loading, it reports a new error: /opt/redis-stack/lib/module-oss.so failed to load: /opt/redis-stack/lib/module-oss.so: cannot dynamically load position-independent executable

**Comment by GuyAv46** [comment]
what gcc, make, cmake, glibc version do you have? what glibc version do you have on your server?

**Comment by AllKai** [comment]
> what gcc, make, cmake, glibc version do you have? what glibc version do you have on your server?

This is an issue with the redis-stack team's image. I'm planning to switch from a cluster setup to a standalone one for now
[https://github.com/redis-stack/redis-stack](url)
