### ISSUE TITLE
[Feature Request] int8 or float16 support for vector fields

### ISSUE THREAD

**Issue by snewcomer** [RediSearch/RediSearch#4609]
**Is your feature request related to a problem? Please describe.**
It is possible to support expand VectorField support to int8 and/or float16 with redis?  If so, I would be happy to work on this.

**Additional context**
Previous work here - https://github.com/RediSearch/RediSearch/pull/3129

**Comment by DvirDukhan** [comment]
float16 and bfloat16 are supported as of RediSearch 2.10.
