### ISSUE TITLE
make cmd not working on linux system [RediSearch Installation]

### ISSUE THREAD

**Issue by Serinkaushik** [RediSearch/RediSearch#4621]
I have been trying to install RediSearch on my machine after following few of the documentation I am not able to use make cmd it throws up a bunch of error.
After going through few previous documents, I found out that make cmd is not required and instead we have to type in ./install_boost.sh 1.83.0 . Can someone guide me on what has to be done or can provide me a proper documentation about it

**Screenshots**

![error](https://github.com/RediSearch/RediSearch/assets/124284431/467b34ad-442b-4a67-adb9-b6bb8c39376f)

**Environment (please complete the following information):**
 - Ubuntu 18.04.5

**Comment by nafraf** [comment]
Hi @Serinkaushik, please try the following to install the dependencies in your system:
```sh
cd .install
bash ubuntu_18.04.sh
cd ..
make
```

**Comment by Serinkaushik** [comment]
Bunch of dependencies were installed after the bash script even though encountering the same error. 
![image](https://github.com/RediSearch/RediSearch/assets/124284431/5f037799-c034-4cd7-8483-ec026fea75a3)

**Comment by Serinkaushik** [comment]
Sorry to disturb you @nafraf, Now make cmd is working but the next step make setup is not working and it is throwing up the error as **ModuleNotFoundError: No module named 'apt_pkg'** . Tried doing every other solution available on the web but nothing worked. Also attaching the screenshot of it.

 
![image](https://github.com/RediSearch/RediSearch/assets/124284431/a912de6e-411a-4aca-8c8e-9c1f44308299)

**Comment by nafraf** [comment]
Hi @Serinkaushik! If the make cmd worked without errors, then you can find the module in `./bin/linux-x64-release/search/redisearch.so`
And you can start redis server loading the module:
`redis-server --loadmodule ./bin/linux-x64-release/search/redisearch.so`

**Comment by nafraf** [comment]
The redis-server you are using is old, please try to use a more recent version 7.x or 6.x.
BTW, if you don't need to compile/use the module from latest source code, you can also try the module running [Redis Stack on docker](https://redis.io/docs/latest/operate/oss_and_stack/install/install-stack/docker/#redisredis-stack-server)

**Comment by Serinkaushik** [comment]
**Thank You! The problem is resolved I Switched my WSL from 18.04 to 22.04 and followed all your steps.**

![image](https://github.com/RediSearch/RediSearch/assets/124284431/96f06b95-65f9-4705-aec1-d8dc41b08a45)
