### ISSUE TITLE
[BUG] `disjoint` query for geoshapes yields incorrect results

### ISSUE THREAD

**Issue by gerzse** [RediSearch/RediSearch#4664]
**Describe the bug**

I create a `geoshape` index and then store some points and polygons in some documents. When I search the index with the `disjoint` operator, I get unexpected results. For comparison, searching with the `intersects` operators yields correct results.

**To Reproduce**
1. Run the following commands:

```
FLUSHALL
FT.CREATE idx SCHEMA g GEOSHAPE FLAT
HSET point1 g "POINT (10 10)"
HSET point2 g "POINT (50 50)"
HSET polygon1 g "POLYGON ((20 20, 25 35, 35 25, 20 20))"
HSET polygon2 g "POLYGON ((60 60, 65 75, 70 70, 65 55, 60 60))"
FT.SEARCH idx "@g:[intersects $shape]" NOCONTENT DIALECT 3 PARAMS 2 shape "POLYGON ((15 15, 75 15, 50 70, 20 40, 15 15))"
FT.SEARCH idx "@g:[disjoint $shape]" NOCONTENT DIALECT 3 PARAMS 2 shape "POLYGON ((15 15, 75 15, 50 70, 20 40, 15 15))"
```

**Expected behavior**

For the `intersects` query, the result should contain `polygon1` and `point2`. This works fine.

For the `disjoint` query, the result should contain `polygon2` and `point1`. However, only `point1` is returned, the polygon is not picked up.

**Screenshots**

Here is a picture with the shapes:

![image](https://github.com/RediSearch/RediSearch/assets/5439601/9bb7dc11-eea3-4253-acd6-b069d3cf60ca)

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - CPU model: i7-13800H
 - Version/branch: locally build module from commit with hash `ec9b62afc`

**Comment by ephraimfeldblum** [comment]
Hi, thanks for bringing this bug to our attention. It is fixed in the 2.10 branch, #4700.
