### ISSUE TITLE
[BUG]The num_neighbours parameter of knn does not take effect

### ISSUE THREAD

**Issue by lin17182210** [RediSearch/RediSearch#4670]
**Describe the bug**
When num_neighbours <=10, the amount of data returned is equal to num_neighbours, but when num_neighbours>10, only 10 items are returned
when num_neighbours=3, len(result)=3
<img width="893" alt="image" src="https://github.com/RediSearch/RediSearch/assets/39157511/310e445d-dd1d-4d55-bf32-6da0517330a9">
<img width="340" alt="image" src="https://github.com/RediSearch/RediSearch/assets/39157511/a527241a-392f-4414-b9be-cd7d7046c6b1">

bug num_neighbours=20, len(result)=10
<img width="930" alt="image" src="https://github.com/RediSearch/RediSearch/assets/39157511/4f6d7ec2-f216-4fd9-b615-304a95278bb2">
<img width="293" alt="image" src="https://github.com/RediSearch/RediSearch/assets/39157511/ee2f4195-5fb0-4b80-9688-0c2645064d25">
I use docker to pull redis:redis/redis-stack-server:latest
What causes this problem and how should I troubleshoot it?

**Comment by meiravgri** [comment]
Hi @lin17182210 
FT.SEARCH is limited by default to return 10 results.
you can use `LIMIT first count` to define the number of results.
Attahing also the  python client API for defining LIMIT:
https://redis-py.readthedocs.io/en/stable/examples/search_json_examples.html#Paginating-and-Ordering-search-Results

Also, would like to know why you closed the ticket

Thanks
