### ISSUE TITLE
[BUG] log level for "Skip background reindex scan, redis version contains loaded event." too high - [MOD-7181]

### ISSUE THREAD

**Issue by kkmuffme** [RediSearch/RediSearch#4704]
**Describe the bug**
`# <search> Skip background reindex scan, redis version contains loaded event.` means this is a warning (bc of the "#")
However, this is irrelevant normally, and should be logged as notice ("*") or verbose ("-") at most

**To Reproduce**
Not sure

**Expected behavior**
Error level should not be warning

**Environment (please complete the following information):**
 - OS: rocky 9
 - Version/branch 2.8.13

**Comment by GuyAv46** [comment]
Hey @kkmuffme, Thanks for reaching out!
I agree. Version `2.8` and forward don't even support redis versions with no loading event.
I'll open a ticket to fix it.

**Comment by GuyAv46** [comment]
Already merged to master, soon to all the relevant version branches.
Will be part of the next patch releases.
