### ISSUE TITLE
[BUG]Text infix matching cannot return the corresponding result

### ISSUE THREAD

**Issue by zzq0341** [RediSearch/RediSearch#4807]
**Describe the bug**
When there are many documents，Text infix matching cannot return the corresponding result
**To Reproduce**
1. 127.0.0.1:6399> flushdb
  OK

2. 127.0.0.1:6399> hset AccountForSearch_1_+72227037600 number \\+72227037600 team test_t extId 2 plainName \\+72227037600 email johny\\.z\\@test\\.com 
(integer) 5

3. 127.0.0.1:6399> dbsize
(integer) 1

4. 127.0.0.1:6399> ft.create idx_accountForSearch on hash prefix 1 AccountForSearch schema plainName text WEIGHT 100 email text WEIGHT 90 signature text WEIGHT 80 buName text WEIGHT 70  number text WEIGHT 60  team tag avatar text NOINDEX extId NUMERIC NOINDEX
OK

5. 127.0.0.1:6399> ft.search idx_accountForSearch '@email:\*test\* @plainName:\\+72227037600' limit 0 500
 a) (integer) 1
 b) "AccountForSearch_1_+72227037600"
 c)  a) "number"
     b) "\\\\+72227037600"
     c) "team"
     d) "test_t"
     e) "extId"
     f) "2"
     g) "plainName"
     h) "\\\\+72227037600"
     i) "email"
     j) "johny\\\\.z\\\\@test\\\\.com"

6. 127.0.0.1:6399> dbsize
(integer) 3432

7. 127.0.0.1:6399> ft.search idx_accountForSearch '@email:\*test\* @plainName:\\+72227037600' limit 0 500
 a) (integer) 0

8. 127.0.0.1:6399> ft.search idx_accountForSearch '@email:\*z\\@test\* @plainName:\\+72227037600' limit 0 500
 a) (integer) 1
 b) "AccountForSearch_1_+72227037600"
 c)  a) "number"
     b) "\\\\+72227037600"
     c) "team"
     d) "test_t"
     e) "extId"
     f) "2"
     g) "plainName"
     h) "\\\\+72227037600"
     i) "email"
     j) "johny\\\\.z\\\\@test\\\\.com"

**Expected behavior**
Step 7 outputs the same result as Step 8

**Screenshots**
<img width="1085" alt="截屏2024-06-27 20 16 24" src="https://github.com/RediSearch/RediSearch/assets/67300105/817614e1-683e-4e41-b980-fff8e6726de1">

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.4 LTS (Bionic Beaver)
 - CPU: x86_64
 - Version/branch: module:name=search,ver=20814,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
 - redis_version:7.2.5 

**Additional context**
I tried email text weight 90 WITHSUFFIXTRIE NOSTEM, but it didn't work either
Step 6 I initialized some data

**Comment by zzq0341** [comment]
Who can help me solve this problem?Is it that I used it wrong?

**Comment by nafraf** [comment]
Hi @zzq0341,
I'm trying to replicate the error using the following script, but it is working. Could you give me more details of how are you creating the data on step 6?
<details>
<summary>Test script:</summary>

```python
import redis
import time

def waitForIndex(r, idx):
    i = 0
    while True:
        res = r.execute_command("ft.info", idx)
        if int(res[res.index(b'indexing') + 1]) == 0:
            break
        time.sleep(1)
        i += 1

# Connnect to Redis
hostname = 'localhost'
port=6379

r = redis.Redis(host=hostname, port=port)
r.ping()
r.execute_command('flushdb')
time.sleep(1)

# Create one doc
print("Create one doc ...")
index_name = 'idx_accountForSearch'
prefix = 'AccountForSearch'
cmd = 'hset AccountForSearch_1_+72227037600 number \\+72227037600 team test_t extId 2 plainname \\+72227037600 email johny\\.z\\@test\\.com'
print(cmd)
ok = r.execute_command(cmd)
print(ok)

# Generate Index 
print("Generate Index ...")
cmd = 'ft.create idx_accountForSearch on hash prefix 1 AccountForSearch '
cmd += 'schema plainname text WEIGHT 100 email text WEIGHT 90 signature '
cmd += 'text WEIGHT 80 buName text WEIGHT 70 number text WEIGHT 60 '
cmd += 'team tag avatar text NOINDEX extId NUMERIC NOINDEX'
print(cmd)
ok = r.execute_command(cmd)
print(ok)
waitForIndex(r, index_name)

print("-----------------------------------")
dbsize = r.execute_command("dbsize")
print("DBSIZE:", dbsize)
search_cmd = ["ft.search", "idx_accountForSearch", '@email:*test* @plainname:\\+72227037600', "limit", 0, 500]
print(*search_cmd)
res = r.execute_command(*search_cmd)
print(res)

print("-----------------------------------")
print("Create more data ...")
docs = 10000
for i in range(docs):
    number = 72227038000 + i
    key = f'{prefix}_{str(i)}_+{str(number)}'
    cmd = 'HSET ' + key
    cmd += ' plainname \\+' + str(number)
    cmd += ' number \\+' + str(number)
    cmd += ' team test_t'
    cmd += ' email johny\\.z\\@test\\.com' + str(number)
    r.execute_command(cmd)

print("-----------------------------------")
dbsize = r.execute_command("dbsize")
print("DBSIZE:", dbsize)
print(*search_cmd)
res = r.execute_command(*search_cmd)
print(res)

```

</details>

<details>
<summary>Output:</summary>

```sh
Create one doc ...
hset AccountForSearch_1_+72227037600 number \+72227037600 team test_t extId 2 plainname \+72227037600 email johny\.z\@test\.com
5
Generate Index ...
ft.create idx_accountForSearch on hash prefix 1 AccountForSearch schema plainname text WEIGHT 100 email text WEIGHT 90 signature text WEIGHT 80 buName text WEIGHT 70 number text WEIGHT 60 team tag avatar text NOINDEX extId NUMERIC NOINDEX
b'OK'
-----------------------------------
DBSIZE: 1
ft.search idx_accountForSearch @email:*test* @plainname:\+72227037600 limit 0 500
[1, b'AccountForSearch_1_+72227037600', [b'number', b'\\+72227037600', b'team', b'test_t', b'extId', b'2', b'plainname', b'\\+72227037600', b'email', b'johny\\.z\\@test\\.com']]
-----------------------------------
Create more data ...
-----------------------------------
DBSIZE: 10001
ft.search idx_accountForSearch @email:*test* @plainname:\+72227037600 limit 0 500
[1, b'AccountForSearch_1_+72227037600', [b'number', b'\\+72227037600', b'team', b'test_t', b'extId', b'2', b'plainname', b'\\+72227037600', b'email', b'johny\\.z\\@test\\.com']]
```

</details>

**Comment by zzq0341** [comment]
Hi @nafraf 
Thank you very much. I randomly generated some data, and with this data, I can reproduce it.
[init.txt](https://github.com/user-attachments/files/16467888/init.txt)

**Comment by nafraf** [comment]
Thanks. Now I could see the problem. It occurs only when the infix is used as part of an intersection.
```sh
127.0.0.1:6379> ft.search idx1 '@email:*test*' limit 0 0
1) (integer) 200
127.0.0.1:6379> ft.search idx1 '@plainname:\+72227037600' limit 0 500
1) (integer) 1
2) "AccountForSearch_1_+72227037600"
3)  1) "number"
    2) "\\+72227037600"
    3) "team"
    4) "test_t"
    5) "extId"
    6) "9"
    7) "plainname"
    8) "\\+72227037600"
    9) "email"
   10) "johny\\.z\\@test\\.com"
127.0.0.1:6379> ft.search idx1 '@email:*test* @plainname:\+72227037600' limit 0 500
1) (integer) 0
127.0.0.1:6379> ft.search idx1 '@email:*test* | @plainname:\+72227037600' limit 0 0
1) (integer) 200
```

**Comment by zzq0341** [comment]
@nafraf 
127.0.0.1:6379> ft.search idx1 '@email:*test*' limit 0 0
1) (integer) 200
It seems to be caused by matching 200, but all data can be matched, which should be 4001. Perhaps this place is based on performance considerations.

**Comment by nafraf** [comment]
@zzq0341
To get results, you need to set a bigger value in `MAXPREFIXEXPANSION` parameter. The default value (200) is limiting your results.
```sh
127.0.0.1:6379> FT.CONFIG SET MAXPREFIXEXPANSIONS 5000
OK
127.0.0.1:6379> ft.search idx1 '@email:*test*  @plainname:\+72227037600' limit 0 500
1) (integer) 1
2) "AccountForSearch_1_+72227037600"
3)  1) "number"
    2) "\\+72227037600"
    3) "team"
    4) "test_t"
    5) "extId"
    6) "9"
    7) "plainname"
    8) "\\+72227037600"
    9) "email"
   10) "johny\\.z\\@test\\.com"
127.0.0.1:6379> ft.search idx1 '@email:*test* | @plainname:\+72227037600' limit 0 0
1) (integer) 4001
```
