### ISSUE TITLE
[BUG] Boost query is not working as expected

### ISSUE THREAD

**Issue by satheeshthoughtclan** [RediSearch/RediSearch#4828]
**Describe the bug**

When we use FT.AGGREGATE query with boost weightage, we see that the records which match the boost query are not being boosted to the top of the results.

**To Reproduce**

Create below index:

`
FT.CREATE idx_inst ON JSON PREFIX 1 inst: SCHEMA $.oid AS oid TAG SORTABLE $.snm AS snm TEXT SORTABLE
`

Insert below data:

```
JSON.SET inst:1 $ '{"oid": "1", "snm": "bank\\ of\\ america bac"}'
JSON.SET inst:2 $ '{"oid": "2", "snm": "american\\ express\\ company amx"}'
JSON.SET inst:3 $ '{"oid": "3", "snm": "american\\ airlines\\ group\\ inc aal"}'
JSON.SET inst:4 $ '{"oid": "4", "snm": "british\\ american\\ tobacco\\ plc bri"}'
JSON.SET inst:5 $ '{"oid": "5", "snm": "ericsson\\ b eric\\ b"}'
JSON.SET inst:6 $ '{"oid": "6", "snm": "ericsson\\ a eric\\ a"}'
JSON.SET inst:7 $ '{"oid": "7", "snm": "ericsson\\ b eribr"}'
```

As you can see from above list, we have three records which are starting with "eric". In below query, we are boosting those records which start with this. But we still don't see them at the top.
 
`
FT.AGGREGATE idx_inst "(@snm:eric* | @snm:*eric*) | (@snm:eric*) => { $weight: 5.0; }" LOAD 2 @oid @snm LIMIT 0 10
`

**Expected behavior**

The records which match the boost query must be boosted to the top.

**Environment (please complete the following information):**
 - Azure Redis Enterprise
 - Redis Version: 6.0.20
 - Redis Search Version: 2.6.12

**Comment by adrianoamaral** [comment]
hi @satheeshthoughtclan thanks for reaching out.

FT.AGGREGATE needs to state what you need to SORTBY explicitly. Different than with FT.SEARCH, where sorting is implicitly enabled.

So you can try the FT.SEARCH equivalent syntax:

```
127.0.0.1:6379> FT.SEARCH idx_inst "(@snm:eric* | @snm:*eric*) | (@snm:eric*) => { $weight: 5.0; }" WITHSCORES RETURN 2 oid snm
 1) (integer) 7
 2) "inst:5"
 3) "21"
 4) 1) "oid"
    2) "5"
    3) "snm"
    4) "ericsson\\ b eric\\ b"
 5) "inst:6"
 6) "21"
 7) 1) "oid"
    2) "6"
    3) "snm"
    4) "ericsson\\ a eric\\ a"
 8) "inst:7"
 9) "14"
10) 1) "oid"
    2) "7"
    3) "snm"
    4) "ericsson\\ b eribr"
11) "inst:1"
12) "3"
13) 1) "oid"
    2) "1"
    3) "snm"
    4) "bank\\ of\\ america bac"
14) "inst:2"
15) "3"
16) 1) "oid"
    2) "2"
    3) "snm"
    4) "american\\ express\\ company amx"
17) "inst:3"
18) "3"
19) 1) "oid"
    2) "3"
    3) "snm"
    4) "american\\ airlines\\ group\\ inc aal"
20) "inst:4"
21) "3"
22) 1) "oid"
    2) "4"
    3) "snm"
    4) "british\\ american\\ tobacco\\ plc bri"
 
```
We planned to have one option to load the `@__score` as a field and use it in the SORTBY stage. Check the release notes when available.

**Comment by satheeshthoughtclan** [comment]
Hi @adrianoamaral ,

Thanks for your response. Will verify this query and let you know.

**Comment by satheeshthoughtclan** [comment]
This is not required anymore as we have changed our sorting approach (functionally). Closing this request. Thanks!
