### ISSUE TITLE
[BUG] JSON.MGET is not returning all records in Cluster deployment

### ISSUE THREAD

**Issue by satheeshthoughtclan** [RediSearch/RediSearch#4829]
**Describe the bug**

When we use Clustered Redis Enterprise instance, JSON.MGET is not returning all records.

**To Reproduce**

Insert below records:

```
JSON.SET inst:SE0011452051 $ '{"oid": "SE0011452051", "snm": "AAA"}'
JSON.SET inst:SE0011452077 $ '{"oid": "SE0011452077", "snm": "BBB"}'
JSON.SET inst:SE0011452085 $ '{"oid": "SE0011452085", "snm": "CCC"}'
JSON.SET inst:SE0002801670 $ '{"oid": "SE0002801670", "snm": "DDD"}'
JSON.SET inst:SE0004384691 $ '{"oid": "SE0004384691", "snm": "EEE"}'
JSON.SET inst:SE0004384692 $ '{"oid": "SE0004384692", "snm": "FFF"}'
JSON.SET inst:SE0004385692 $ '{"oid": "SE0004385692", "snm": "GGG"}'
```

With the above data, below JSON.MGET statement returns only 4 of the 7 records.
 
```
JSON.MGET inst:SE0011452051 inst:SE0011452077 inst:SE0011452085 inst:SE0002801670 inst:SE0004384691 inst:SE0004384692 inst:SE0004385692 .
```

JSON.MGET with only those missing records is returning them.
 
```
JSON.MGET inst:SE0011452085 inst:SE0002801670 inst:SE0004384692 .
```

**Expected behavior**

All records matching given query must be returned.

**Environment (please complete the following information):**
 - Azure Redis Enterprise Cluster
 - Redis Version: 6.0.20
 - Redis JSON Version: 2.4.7

**Comment by LiorKogan** [comment]
This belongs to https://github.com/RedisJSON/RedisJSON. (Similar issue: https://github.com/RedisJSON/RedisJSON/issues/1094)

Anyway, `JSON.MGET`, like many other Redis commands, require all keys to reside on the same hash slot.

Quoting from https://redis.io/docs/latest/operate/rs/databases/durability-ha/clustering/ :
> Multi-key commands: Redis offers several commands that accept multiple keys as arguments. In a clustered database, most multi-key commands are not allowed across slots. 

Are you getting a CROSSSLOT error?

**Comment by satheeshthoughtclan** [comment]
Hi @LiorKogan ,

We are not getting any errors. We just get partial results.

In the "clustering" link you have shared, MGET is included as being supported in clustered deployment. Does that not extend to JSON.MGET?

**Note:** Sorry for raising it in the wrong project. Should I close this and raise under RedisJSON?

**Comment by LiorKogan** [comment]
Cross-slot support is not offered for `JSON.MGET`.  We may introduce it in the future.

For now, not getting a CROSSSLOT error is a bug we need to fix.

**Comment by satheeshthoughtclan** [comment]
Sure. Thanks for checking!

**Comment by oshadmi** [comment]
Closing since it is related to RedisJSON (MOD-7315)
