### ISSUE TITLE
Build Failure Due to Missing Boost Header File: boost/unordered/unordered_flat_map.hpp

### ISSUE THREAD

**Issue by Almondzdigital** [RediSearch/RediSearch#4868]
Environment:

Operating System: Ubuntu 22.04
Redisearch Version: 2.8.14
Boost Version: (Initially, an older version; upgraded to 1.75.0)
CMake Version: 3.22.1
Steps to Reproduce:

Download and extract Redisearch version 2.8.14.
Ensure all necessary dependencies are installed (libboost-all-dev, cmake, etc.).
Attempt to build Redisearch using the make command.

output: 

In file included from /root/RediSearch/src/geometry/rtree.cpp:7:
 /root/RediSearch/src/geometry/rtree.hpp:22:10: fatal error: boost/unordered/unordered_flat_map.hpp: No such file or directory
   22 | #include <boost/unordered/unordered_flat_map.hpp>  // is faster than std::unordered_map?
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/geometry/CMakeFiles/redisearch-geometry.dir/build.make:104: src/geometry/CMakeFiles/redisearch-geometry.dir/rtree.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /root/RediSearch/src/geometry/geometry_api.cpp:8:
 /root/RediSearch/src/geometry/rtree.hpp:22:10: fatal error: boost/unordered/unordered_flat_map.hpp: No such file or directory
   22 | #include <boost/unordered/unordered_flat_map.hpp>  // is faster than std::unordered_map?
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[3]: *** [src/geometry/CMakeFiles/redisearch-geometry.dir/build.make:76: src/geometry/CMakeFiles/redisearch-geometry.dir/geometry_api.cpp.o] Error 1
make[2]: *** [CMakeFiles/Makefile2:721: src/geometry/CMakeFiles/redisearch-geometry.dir/all] Error 2
make[1]: *** [Makefile:136: all] Error 2
make: *** [/root/RediSearch/deps/readies/mk/cmake.rules:31: /root/RediSearch/bin/linux-x64-release/search/redisearch.so] Error 2

**Comment by meiravgri** [comment]
hello @Almondzdigital 
please use the script to install boost:
```
cd ./install
./install_boost.sh 1.83.0
```

Let me know if you need any further help.
Thanks

**Comment by Almondzdigital** [comment]
Thanks @meiravgri 

It worked. Thanks for quick response.
