### ISSUE TITLE
[BUG] Unexpected Data Interference Between two indexes

### ISSUE THREAD

**Issue by FAHADALIYOUSAF** [RediSearch/RediSearch#4881]
**Describe the bug**
I am encountering an issue with Redis when using hash indexes (IndexType.HASH). I have created two hash indexes named "Testing_index_hnsw_FAY_m_500_construct_50000" and "Testing_index_hnsw_FAY_m_500_construct_50000_rm" on the same Redis instance within a Redis cluster. Each index has distinct fields and prefixes, yet I'm observing unexpected behavior where updating data in "Testing_index_hnsw_FAY_m_500_construct_50000_rm" seems to reflect on "Testing_index_hnsw_FAY_m_500_construct_50000".

Specifically, when I query FT.INFO Testing_index_hnsw_FAY_m_500_construct_50000, it shows a non-zero/the exact count of Testing_index_hnsw_FAY_m_500_construct_50000_rm documents, despite having no documents explicitly added to "Testing_index_hnsw_FAY_m_500_construct_50000". Furthermore, retrieving keys from "Testing_index_hnsw_FAY_m_500_construct_50000" returns zero keys.

**To Reproduce**
**use redis cluster**
1.first create first index using schema:
index_name = <index_name>
title = TextField(name="title")
text_embedding = VectorField("embeddings",
"HNSW", {
"TYPE": "FLOAT32",
"DIM": VECTOR_DIM,
"DISTANCE_METRIC": DISTANCE_METRIC,
"M": 500,
"EF_CONSTRUCTION": 50000
}
)
url = TextField(name="url")
part_id = NumericField(name="part_id")
text = TextField(name="text")
doc_type = TextField(name="doc_type")
doc_id = TextField(name="doc_id")

      fields = [title,text_embedding,url,part_id,text,doc_type,doc_id ]
     master_cluster.ft(index_name).create_index(
    fields = fields,
    definition = IndexDefinition(prefix=[<index_name>], index_type=IndexType.HASH)
)
2. upload some data in index 
3. after uploading is done create a second index with almost same name add some postfix to differenciate between two indexes by:
index_name = <index_name>_rm
title = TextField(name="title")
text_embedding = VectorField("embeddings",
"HNSW", {
"TYPE": "FLOAT32",
"DIM": VECTOR_DIM,
"DISTANCE_METRIC": DISTANCE_METRIC,
"M": 500,
"EF_CONSTRUCTION": 50000
}
)
url = TextField(name="url")
part_id = NumericField(name="part_id")
text = TextField(name="text")
doc_type = TextField(name="doc_type")
doc_id = TextField(name="doc_id")

      fields = [title,text_embedding,url,part_id,text,doc_type,doc_id ]
     master_cluster.ft(index_name).create_index(
    fields = fields,
    definition = IndexDefinition(prefix=[<index_name>_rm], index_type=IndexType.HASH)
)
4. upload data in second index 
5. upload data on both index in format:
f"{index_name}_doc:{<unique_id>}_test{{<index_name>}}" 

**Expected behavior**
when you upload data in second index the number of doc in first index also starting to increase 

**Screenshots**
refer to this link i have explained the problem in detail:
https://github.com/redis/redis/issues/13435

**Environment (please complete the following information):**
 - OS: Windows

**Comment by meiravgri** [comment]
Hi @FAHADALIYOUSAF 
Could you please share an exmaple of updating/inserting data to `Testing_index_hnsw_FAY_m_500_construct_50000_rm` (hset command) that cause the described behaviour?

**Comment by FAHADALIYOUSAF** [comment]
Hi @meiravgri,
  this is how i upload data:
  doc_key = f"{index_name}_doc:{str(part_id)}_test{{Testing_index_hnsw_FAY_m_500_construct_50000_rm}}"
field = {
    "title": str(title),
    "url": str(url),
    "part_id": int(part_id),
    "doc_type": str(doc_type),
    "text": str(text),
    "doc_id": str(doc_id),
    "embeddings":embedding,
}
try:
    master_cluster.hset(doc_key, mapping=field)

except Exception as e:
    print(f"An Error occured while uploading data in redis: {e}")

**Comment by meiravgri** [comment]
Hi @FAHADALIYOUSAF,

The issue you're encountering arises from the way prefixes are used in index definitions. The prefix determines which documents are indexed based on their key. In your case, the prefix for the second index ("Testing_index_hnsw_FAY_m_500_construct_50000_rm") includes the prefix for the first index ("Testing_index_hnsw_FAY_m_500_construct_50000").

As a result, any document key that starts with "Testing_index_hnsw_FAY_m_500_construct_50000_rm" also starts with "Testing_index_hnsw_FAY_m_500_construct_50000", leading to these documents being indexed by both indices.

To resolve this, ensure that the prefixes are distinct enough so that no overlap occurs.
Hope that helps!
