### ISSUE TITLE
[BUG] Redis Cluster: Pagination via LIMIT causes records to get duplicated in subsequent pages in RedisSearch

### ISSUE THREAD

**Issue by shrihari-nasdaq** [RediSearch/RediSearch#4883]
## Description
Hi team.
We are encountering an issue with RedisSearch on Azure Redis Cluster (Preview) where records start to get duplicated on subsequent pages during pagination using the LIMIT clause. This behavior occurs after navigating through a few pages of results.

Observations:

- This behavior does not occur in a non-clustered environment.
- This behavior does not occur in a clustered environment also if you use only one `LOAD 1 field1` parameter. We get a unique set of pages throughout the pagination.
- As soon as we add more `LOAD` parameters, this issue becomes easily replicable every time ( Not in Non-Clustered instance)

## Expected Behavior
Records should not be duplicated on subsequent pages during pagination.

## Actual Behavior
Records are duplicated on subsequent pages during pagination.

## Steps to Reproduce
1. Create data in Redis using the provided script.
2. Validate pagination using the provided script.
3. Observe that records are duplicated on subsequent pages.

### Script to create data in Redis
1. Generate JSON objects and Redis commands using the following script:

```python
import json
import random
import string

# Function to generate a random string
def random_string(length=10):
    letters = string.ascii_letters
    return ''.join(random.choice(letters) for i in range(length))

def main():
    
    # Number of JSON objects and fields
    num_json_objects = 20000
    num_fields = 35

    # Generate JSON objects
    json_objects = []
    for i in range(num_json_objects):
        json_obj = {}
        for j in range(num_fields):
            key = f"field{j+1}"
            if j == 0:
                json_obj[key] = str(i+1)
            else:
                value = random_string()
                json_obj[key] = value
        json_objects.append(json_obj)

    # Generate Redis bulk commands
    prefix = "user:"
    commands = []
    for idx, json_obj in enumerate(json_objects):
        key = f"{prefix}{idx+1}"
        json_str = json.dumps(json_obj)
        command = f"JSON.SET {key} . '{json_str}'"
        commands.append(command)

    # Write commands to a file
    with open('json_user_seed.txt', 'w') as file:
        for command in commands:
            file.write(command + '\n')

if __name__ == "__main__":
    main()
```
2. Execute the generated `json_user_seed.txt` commands in redis-cli to add the user documents.
3. Create an index for the 35 fields:

```
FT.CREATE idx_user ON JSON PREFIX 1 user: SCHEMA $.field1 AS field1 TAG SORTABLE $.field2 AS field2 TAG SORTABLE $.field3 AS field3 TAG SORTABLE $.field4 AS field4 TAG SORTABLE $.field5 AS field5 TAG SORTABLE $.field6 AS field6 TAG SORTABLE $.field7 AS field7 TAG SORTABLE $.field8 AS field8 TAG SORTABLE $.field9 AS field9 TAG SORTABLE $.field10 AS field10 TAG SORTABLE $.field11 AS field11 TAG SORTABLE $.field12 AS field12 TAG SORTABLE $.field13 AS field13 TAG SORTABLE $.field14 AS field14 TAG SORTABLE $.field15 AS field15 TAG SORTABLE $.field16 AS field16 TAG SORTABLE $.field17 AS field17 TAG SORTABLE $.field18 AS field18 TAG SORTABLE $.field19 AS field19 TAG SORTABLE $.field20 AS field20 TAG SORTABLE $.field21 AS field21 TAG SORTABLE $.field22 AS field22 TAG SORTABLE $.field23 AS field23 TAG SORTABLE $.field24 AS field24 TAG SORTABLE $.field25 AS field25 TAG SORTABLE $.field26 AS field26 TAG SORTABLE $.field27 AS field27 TAG SORTABLE $.field28 AS field28 TAG SORTABLE $.field29 AS field29 TAG SORTABLE $.field30 AS field30 TAG SORTABLE $.field31 AS field31 TAG SORTABLE $.field32 AS field32 TAG SORTABLE $.field33 AS field33 TAG SORTABLE $.field34 AS field34 TAG SORTABLE $.field35 AS field35 TAG SORTABLE
```

### Script to validate pagination
Note:  If there are no custom exceptions thrown, then no duplication of ids was found.

```python
import redis
import ssl



initCount = -1
visited = dict()
pagenumber = -1


def get_redis_cluster_connection(host="127.0.0.1", port=6379, password=""):
    return redis.Redis(host=host, port=port, password=password, ssl=True, ssl_cert_reqs="none")



def validatePageResponse(redis_conn, page_size, max_page_number):
    global pagenumber
    for page_number in range(1, max_page_number + 1):
        pagenumber = page_number
        offset = (page_number - 1) * page_size
        query = f"FT.AGGREGATE idx_user '*' SORTBY 6 @field4 DESC @field3 ASC @field1 ASC LIMIT {offset} {page_size} LOAD 35 field1 field2 field3 field4 field5 field6 field7 field8 field9 field10 field11 field12 field13 field14 field15 field16 field17 field18 field19 field20 field21 field22 field23 field24 field25 field26 field27 field28 field29 field30 field31 field32 field33 field34 field35"
        response = redis_conn.execute_command(query)
        if response:
            process_response(response)



def process_response(response):
    global initCount, visited, dupes, pagenumber
    if not response:
        return
    
    if initCount == -1:
        initCount = response[0]
    elif initCount != response[0]:
        raise Exception(f"Total record didn't match: initCount: {initCount}, response: {response[0]} in the page: {pagenumber}")
    
    for data in response[1:]:
        _id = ""
        for j, d in enumerate(data):
            c = d.decode("utf-8")
            if j % 2 == 0:
                _id = c
                continue
            if d == "":
                raise Exception("No Id found")
            if _id != "field1":
                continue
            if c in visited:
                raise Exception(f"Duplicate found id: {c}, at page: {pagenumber}, previously seen at page: {visited[c]}")
            else:
                visited[c] = pagenumber

def main():

    # Kindly add required credential to establish connection to a cluster
    ip="redis_cluster_ip"
    port="redis_cluster_port"
    password="redis_cluster_password"

    # FT Index
    idx_user = "idx_user"

    redis_client_conn = get_redis_cluster_connection(ip, port, password) 

    # page_size * max_page_number must be equal to or greater than total number records for the search, so that we dont miss out pages at the end
    page_size = 100
    max_page_number = 200

    global initCount
    global visited
    global pagenumber

    # flushing old lookup data before the fresh run
    initCount = -1
    visited = dict()
    pagenumber = -1
    
    validatePageResponse(redis_client_conn, page_size, max_page_number)


if __name__ == "__main__":
    main()
```
Note: We have used following RedisSearch Query for the testing of paginated records and we have also checked, we arent timing out on our response. ( In both clustered and Non Clustered instances).
```
FT.AGGREGATE idx_user '*' SORTBY 6 @field4 DESC @field3 ASC @field1 ASC LIMIT {offset} {page_size} LOAD 35 field1 field2 field3 field4 field5 field6 field7 field8 field9 field10 field11 field12 field13 field14 field15 field16 field17 field18 field19 field20 field21 field22 field23 field24 field25 field26 field27 field28 field29 field30 field31 field32 field33 field34 field35
```
If we run the same script on a Non Clustered Redis instance, we won't be seeing any duplicated page documents

## Additional Information
- Redis version: 7.2.3
- RediSearch version: 2.8.12
- RedisJson: 2.6.9

Kindly let us know if there is anything we are missing or if you need any additional information.

**Comment by shrihari-nasdaq** [comment]
We placed the LOAD command after SORTBY because placing it after the QUERY often resulted in timeouts. Once we moved the LOAD command after SORTBY, we started receiving all records within the timeout duration.

Here if you want more info about this issue, please check this comment

https://github.com/RediSearch/RediSearch/issues/4742#issuecomment-2219859870

**Comment by GuyAv46** [comment]
1. Regarding the `LOAD` step placement - it is always recommended to have any `LOAD` step after all filtering steps if possible. Even if the loaded data is cached by `SORTABLE` and `UNF`, it has some overhead to add it to the row. A sorting step takes all the results that pass the query until EOF and yields only the top k results to the rest of the pipeline. Let's say 10k results passed the query, and the sorter in your query yields 100 results. It is much more efficient to load the data only for those 100 results instead of loading it for all 10k, as most of them are going to be discarded anyway.
2. Pagination may be inconsistent if the documents are updated between different calls, especially between equal (from the sorter POV) results. A better way to achieve paginations with `FT.AGGREGATE` is to use [cursors](https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/aggregations/#cursor-api). It will also improve the query performance as it is executed only once, and not re-executed each time for specific paging. Notice that I pass to the LIMIT the total number of results, and to the cursor's count the page size:
```python
def validatePageResponse(redis_conn, page_size, max_page_number):
    global pagenumber
    cursor_id = None
    for page_number in range(1, max_page_number + 1):
        pagenumber = page_number
        if cursor_id is None:
            query = f"FT.AGGREGATE idx_user '*' SORTBY 6 @field4 DESC @field3 ASC @field1 ASC LIMIT 0 {page_size * max_page_number} LOAD 35 field1 field2 field3 field4 field5 field6 field7 field8 field9 field10 field11 field12 field13 field14 field15 field16 field17 field18 field19 field20 field21 field22 field23 field24 field25 field26 field27 field28 field29 field30 field31 field32 field33 field34 field35" \
                    " WITHCURSOR COUNT {page_size}"
            response, cursor_id = redis_conn.execute_command(query)
        else:
            response, cursor_id = redis_conn.execute_command('FT.CURSOR', 'READ', 'idx_user', cursor_id)
        if response:
            process_response(response)
        if cursor_id == 0:
            break # cursor is depleted. No more results
```
3. Using cursors will solve the pagination problem if you have a sorter in the pipeline, but in some cases, it might still suffer from the same issue. You might want to add to the sorting parameters a final fallback that will ensure uniqueness to the sorting values

**Comment by shrihari-nasdaq** [comment]
Hi @GuyAv46
Thank you for the response.

Glad we got to know about LOAD behavior.

Coming to the sorting, we have tested on a sorting field that would not be updated, also tested when there were no write operation on JSONs, we were still getting duplicated ids.

**Comment by GuyAv46** [comment]
Any update to the JSON object can cause this issue, even if none of the changed data is relevant to the query or even indexed by RediSearch. Can you also confirm that some different documents have the same values for `@field4`, `@field3`, and `@field1`?

Regarding the rewind limitation - It's true that the cursors cannot be rewind, but dropping the cursor and creating a new one. It will probably still be more efficient than calculating the specific paging every time. But you know best what's the common pattern of user's pagination order

**Comment by shrihari-nasdaq** [comment]
Post creation of the documents only then we started with pagination testing script with only one sort field, `SORTBY 1 @field1 ASC` and 35 LOAD fields, still the same duplication behavior was observed at later pages.

In our application, No, there wont be any instance where field1, field3, field4 will be same across two or more documents, but in the example it could be, as its a randomly generated string. 

Here an updated code, with single unique field for sorting param
```python
def validatePageResponse(redis_conn, page_size, max_page_number):
    global pagenumber
    for page_number in range(1, max_page_number + 1):
        pagenumber = page_number
        offset = (page_number - 1) * page_size
        query = f"FT.AGGREGATE idx_user '*' SORTBY 2 @field1 DESC LIMIT {offset} {page_size} LOAD 35 field1 field2 field3 field4 field5 field6 field7 field8 field9 field10 field11 field12 field13 field14 field15 field16 field17 field18 field19 field20 field21 field22 field23 field24 field25 field26 field27 field28 field29 field30 field31 field32 field33 field34 field35"
        response = redis_conn.execute_command(query)
        if response:
            process_response(response)
    
```

**Comment by GuyAv46** [comment]
I could not reproduce the issue with the given steps, I tried with both versions of `validatePageResponse`.
I don't believe it can be reproduced without performing updates in between, or another possibility is that long queries get timed out in some shards but not others, resulting in missing the correct results for the specific pagination and the choosing of previously returned results.
Can you try reproducing the issue with `TIMEOUT 0` added to the query, to eliminate the possibility of timeouts?

**Comment by shrihari-nasdaq** [comment]
Unfortunately, Azure doesn't allow us use any config related commands, either in query or using ft.config 
Is there a way, where we can validate timeouts in individual shards, please let us know?.
Also, data response also doesn't have this query meta data (i.e. time elapsed during the process of query exec).
I too believe it could be timeout, because as soon we add more LOAD fields, we are observing this issue, when I keep LOAD to 1 field, I don't find duplicates, if its indeed a timeout issue, is there a way where in we efficiently LOAD large number of fields? We strongly resist against increasing timeouts, because it may hinder other redis calls from our application

**Comment by shrihari-nasdaq** [comment]
@GuyAv46 since it's preview access we were able to use timeout in the query, like you mentioned, it looks like it was timing out issue, as soon as I added timeout 5000, we got 0 duplicates.
We'll thoroughly test and confirm it.

But wanted to know, how to monitor shards timeouts? is there a tool for it or any useful commands?

**Comment by GuyAv46** [comment]
Of course, `TIMEOUT 0` is very much not recommended for production environment.
You can specify the `TIMEOUT` for specific commands without changing the default timeout configuration, so if you have a testing environment you can do this experiment.

You actually can see if you got a timeout with your RediSearch version, but only using RESP3. You’ll need to configure your connection client to use RESP3. In the RESP3 reply, you have a warning section that will tell if a timeout occurred even with the default `ON_TIMEOUT RETURN` configuration

**Comment by shrihari-nasdaq** [comment]
Sure @GuyAv46, We'll try connection with RESP3, and monitor it. Thank you so much.
