### ISSUE TITLE
[BUG] FT.TAGVALS Returns values that no longer exist

### ISSUE THREAD

**Issue by blendicavlad** [RediSearch/RediSearch#4888]
**Describe the bug**
FT.TAGVALS Returns values that no longer exist. E.g. if a value is already indexed and it gets updated or deleted, the old value that no longer exists will still be matched by FT.TAGVALS. 

**To Reproduce**
1. Create index: `FT.CREATE testIndex ON JSON PREFIX 1 'testData' SCHEMA $.job AS job TAG`
2. Create data: `json.set testData.1 . "{\"job\" : \"SRE\"}"` `json.set testData.2 . "{\"job\" : \"Mayor\"}"`
3. Query `FT.TAGVALS testIndex job` -> returns: SRE, Mayor
4. Update data: `json.set testData.1 . "{\"job\" : \"test\"}"`
5. Query `FT.TAGVALS testIndex job` -> returns: SRE, Mayor, test -> but "SRE" no longer exists
6. This reproduces also if the key is deleted entirely `del testData.1` or by key expiration

**Expected behavior**
After updating an already indexed value and changing its TAG, the old value should not appear anymore in the FT.TAGVALS query 

**Environment (please complete the following information):**
 - OS: RedHat 8.8 Ootpa
 - CPU model: Intel Xeon Gold 5317
 - Version/branch: Redis 7.2.3, RedisSearch 2.8.9

**Comment by nafraf** [comment]
Hi @blendicavlad 
That's the expected behavior, the old values are only cleaned after the number of non cleaned documents exceeds [FORK_GC_CLEAN_THRESHOLD](https://redis.io/docs/latest/develop/interact/search-and-query/basic-constructs/configuration-parameters/#fork_gc_clean_threshold) (default value 100)

**Comment by GuyAv46** [comment]
Hey @blendicavlad, thanks for reaching out.
As @nafraf said, this is because the GC did not clean the value yet, but it might be solvable. Will investigate and report soon.

May I ask what is your use-case of `FT.TAGVALS`? This command is about to be deprecated

**Comment by blendicavlad** [comment]
Hi @GuyAv46, I work on a high performance application that is using Redis as a primary DB. We need TAGVALS to be able to run DISTINCT queries on a tag field from a JSON index. Initially we have tried using ft.aggregate with GROUPBY but that takes 32 seconds on our dataset. TAGVALS returns in about 100ms

**Comment by GuyAv46** [comment]
I agree the documentation is not fully clear. This is a temporary edge case so it was probably overlooked.

1. You shouldn't expect this behavior for `FT.SEARCH` and `FT.AGGREGATE`. They never return deleted results. I believe this is why you measured long execution times for `FT.AGGREGATE` - this is the "correct" and long way to collect this information: for each document, add the tag to the list if it's not there yet. When `FT.TAGVALS` iterates over the tag index, it does not verify that each value has at least one document that is not marked for deletion. If it were, the performance would be the same as collecting it with `FT.AGGREGATE`.
2. Basically yes. Also, the index is locked while applying the GC changes so it might have some effect on the throughput at that moment. Lastly, redis supports a single fork at a time, so if you use [persistence](https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/) or have multiple indexes, they might delay each other work. On the other hand each GC iteration might be faster if it has less work to do

**Comment by blendicavlad** [comment]
Thank you for the clarifications. I'll close the issue as resolved 👍

**Comment by blendicavlad** [comment]
@GuyAv46 one last thing, are you aware of any other FT commands where the index cleanup might affect the result set, similar to TAGVALS?

**Comment by GuyAv46** [comment]
No. Especially not the commonly used ones `FT.SEARCH`, `FT.AGGREGATE`, `FT.CURSOR` and the write commands (create, alter, dropindex, and so on)
