### ISSUE TITLE
Please clarify cursors allocation per index

### ISSUE THREAD

**Issue by elglogins** [RediSearch/RediSearch#4892]
**Describe the Question**
I am seeking clarification on how the allocation of the maximum number of cursors per index works in RedisSearch.

**Context and Background**
I'm testing what I can achieve by using large data set of array of strings, and cursor api in concurrent setup. I caught exceptions with message : "Too many cursors allocated for index"

- I've been exploring the source code, particularly the cursor management in `AREQ_StartCursor` and `Cursors_Reserve`.
- I noticed the `spec->cursorsCap` parameter is used to limit the number of active cursors per index.

**Specific Code References**
```c
// Excerpt from cursor management code
if (spec && (spec->activeCursors >= spec->cursorsCap)) {
    /** Collect idle cursors now */
    Cursors_GCInternal(cl, 0);
    if (spec->activeCursors >= spec->cursorsCap) {
        QueryError_SetError(status, QUERY_ELIMIT, "Too many cursors allocated for index");
        goto done;
    }
}
```

**Expected Explanation**
- The logic behind setting and enforcing the maximum number of cursors per index.
- How cursorsCap is initialized and whether it can be configured by users.
- Any best practices

Thanks in advance

**Comment by elglogins** [comment]
Hi @GuyAv46 , thanks for quick and descriptive response!

My intensions are similar to following example, having an index of 500 000 entries, where each is a document - id: string; categoryId: string; subCategory: string;

When request comes, it executes FT.AGGREGATE() with filter on category id, load only 'id' field value with cursor. In while loop, it reads cursor, dispatches for further async processing, repeat, while there is cursor & documents loaded. If I understand correctly, cursor is cleaned up as the moment i use FT CURSOR READ, so they should be short living in this scenario. As mentioned earlier, this would be concurrent environment, where I would like to test of what are the limits, would it be possible to reach 100 concurrent requests doing this? 

500 000 is not really the desired limit I have in my mind, in my hopes it could go as high as 4 000 000. I have considered other alternatives:
- FT SEARCH with offset, but offset, seems to perform significantly worse comparing to AGGREGATION
- SORTED SET with score. Retrieve count of items, use ZRANGEBYSCORE to get in parallel batches, kind of works. But I don't have rich querying capability of FT.

Thanks in advance

**Comment by GuyAv46** [comment]
so in your case using cursors sounds reasonable. You should be able to reach 100 concurrent requests.

A cursor is released once it is depleted - once `FT.CURSOR READ` returns 0 as the next cursor id. Until it is depleted, it is kept in its current state. If you know you don't need a specific cursor anymore, you can delete it explicitly with `FT.CURSOR DEL`.

Note that `FT.AGGREGATE` also supports pagination, but it means the query is recomputed for each chunk so a worse performance is expected.

**Comment by elglogins** [comment]
If i have 100 000 matches in index, and page size is 1000, does it mean, it makes 10 cursors, where they are released only when once last cursor on page 10 returns 0 as next cursor id.

Or does it, creates only 1 cursor, that is maintained and updated through out all of these pages? Meaning, i had only 1 cursor reserved.

Thanks for clarification

**Comment by GuyAv46** [comment]
The second option.
A single cursor that will return 1000 results and its ID for each `FT.CURSOR READ` call, and when the last 1000 results are sent it will send the ID as 0.

`FT.AGGREGATE idx ... WITHCURSOR COUNT 1000` -> 1000 results, id 12345.
`FT.CURSOR READ idx 12345` -> 1000 results, id 12345. X8 times
`FT.CURSOR READ idx 12345` -> 1000 results, id 0. indicates there are no more results

**Comment by elglogins** [comment]
Great, I will do some more testing from my side. 

In your opinion why 128 is the limit, and why not to have it configurable? I'm just thinking, in case I want to go beyond 128 concurrent requests using different cursors, do I really have any options here?

Thanks for help :-)

**Comment by GuyAv46** [comment]
To be honest, no. This decision was made a few years before I joined the project.

We can turn this issue into a feature request to make this limit configurable.

For now, the only option is to build from the source and define this number as a higher value.

**Comment by elglogins** [comment]
> To be honest, no. This decision was made a few years before I joined the project.
> 
> 
> 
> We can turn this issue into a feature request to make this limit configurable.
> 
> 
> 
> For now, the only option is to build from the source and define this number as a higher value (or implement it as a configurable value).

Thanks for all the feedback 👏🏽👍🏽
