### ISSUE TITLE
FT.AGGREGATE VERBATIM returns unexpected result when in cluster mode

### ISSUE THREAD

**Issue by atakavci** [RediSearch/RediSearch#4893]
**Describe the bug**
Aggregate works the way expected in standalone mode , when we run it in cluster mode VERBATIM does not seem to work and keep using stemmed query. 

**To Reproduce**
1. Run following script on a cluster node
```
"FT.CREATE" "TEST_INDEX" "SCHEMA" "name" "TEXT" "SORTABLE"
"HSET" "data1" "name" "hello kitty"
"FT.AGGREGATE" "TEST_INDEX" "kitti" load 1 name
"FT.AGGREGATE" "TEST_INDEX" "kitti" VERBATIM  load 1 name
```

**Expected behavior**
You can see the diff in two examples one from cluster 
1- this is executed on a standalone redis and it gives the expected output;
```
127.0.0.1:6379> "FT.CREATE" "TEST_INDEX" "SCHEMA" "name" "TEXT" "SORTABLE"
OK
127.0.0.1:6379> "HSET" "data1" "name" "hello kitty"
(integer) 1
127.0.0.1:6379> "FT.AGGREGATE" "TEST_INDEX" "kitti" load 1 name
1) (integer) 1
2) 1) "name"
   2) "hello kitty"
127.0.0.1:6379>  "FT.AGGREGATE" "TEST_INDEX" "kitti" "VERBATIM" load 1 name
1) (integer) 0
127.0.0.1:6379> 
```

2 - this is output from cluster node and looks like fails to apply VERBATIM
```
127.0.0.1:16380> "FT.CREATE" "TEST_INDEX" "SCHEMA" "name" "TEXT" "SORTABLE"
OK
127.0.0.1:16380> "HSET" "data1" "name" "hello kitty"
(integer) 0
127.0.0.1:16380> "FT.AGGREGATE" "TEST_INDEX" "kitti" load 1 name
1) (integer) 1
2) 1) "name"
   2) "hello kitty"
127.0.0.1:16380> "FT.AGGREGATE" "TEST_INDEX" "kitti" VERBATIM  load 1 name
1) (integer) 1
2) 1) "name"
   2) "hello kitty"
127.0.0.1:16380> 

```

**Screenshots**
![Screenshot from 2024-07-30 09-47-48](https://github.com/user-attachments/assets/16c3233d-d25a-4d10-a857-6ebd81b741e9)

**Environment (please complete the following information):**
 - OS: [ubuntu 22.04]
 - CPU model  [ i7-1270P ]
 - Version/branch : dockerhub redis/redis-stack-server:edge

**Comment by GuyAv46** [comment]
Hey @atakavci, thanks for reaching out.

Thanks for the bug report, even though `VERBATIM` is not officially supported with `FT.AGGREGATE`. I'll open a ticket to solve it.

I also tested with `FT.SEARCH`, and it seems to work as expeted

**Comment by GuyAv46** [comment]
Fixed. Should be available on redis-stack:edge soon if not already. Will be available on the next patch of all maintained versions
