### ISSUE TITLE
`FT.SUGADD` ... `INCR` borks payload values

### ISSUE THREAD

**Issue by stockholmux** [RediSearch/RediSearch#490]
If you add a payload to a suggestion
```
127.0.0.1:6379> ft.sugadd testsearch RediSearch 1.0 PAYLOAD "RediSearch, an awesome search engine"
```

Then you later increment that value
```
127.0.0.1:6379> ft.sugadd testsearch RediSearch 1.0 INCR
```
Finally, when you try to retrieve the suggestions

```
127.0.0.1:6379> ft.sugget testsearch R WITHPAYLOADS
1) "RediSearch"
2) (nil)
```
The payload is lost. This is a little unexpected since I think the INCR is more of an update.

Perhaps it's an enhancement, but it makes sense that there should be some way to increment the score only if you consider that `FT.SUGADD` ... `INCR` can be used to update scores based on search  or click popularity. The payload might be done on some sort of initial load and then the scores are refined over time - that payload information might not be present or easy to get later on.

**Comment by mnunberg** [comment]
This seems to be a result of the Trie implementation itself. I'll see if I can change it in a way so as to not ruin it.
