### ISSUE TITLE
[BUG] Compilation error on Rocky Linux 9.4

### ISSUE THREAD

**Issue by gsnick** [RediSearch/RediSearch#4977]
Hello,
On Rocky Linux release 9.4 (Blue Onyx) RediSearch fails to compile with the error:

_In file included from /tmp/RediSearch/src/geometry/rtree.cpp:7:
/tmp/RediSearch/src/geometry/rtree.hpp:22:10: fatal error: boost/unordered/unordered_flat_map.hpp: No such file or directory
   22 | #include <boost/unordered/unordered_flat_map.hpp>  // is faster than std::unordered_map?
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[ 61%] Building C object CMakeFiles/rscore.dir/src/numeric_index.c.o
make[3]: *** [src/geometry/CMakeFiles/redisearch-geometry.dir/build.make:104: src/geometry/CMakeFiles/redisearch-geometry.dir/rtree.cpp.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /tmp/RediSearch/src/geometry/geometry_api.cpp:8:
/tmp/RediSearch/src/geometry/rtree.hpp:22:10: fatal error: boost/unordered/unordered_flat_map.hpp: No such file or directory
   22 | #include <boost/unordered/unordered_flat_map.hpp>  // is faster than std::unordered_map?
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated._

Steps to reproduce:

cd /tmp/
rm -rf /tmp/RediSearch
git clone --recursive https://github.com/RedisLabsModules/RediSearch.git
cd RediSearch/

git checkout tags/$(curl --silent "https://api.github.com/repos/RediSearch/RediSearch/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
git submodule update --init --recursive
make build.

Below is a list of installed boost packages:

boost-regex-1.75.0-8.el9.x86_64
boost-system-1.75.0-8.el9.x86_64
boost-thread-1.75.0-8.el9.x86_64
boost-filesystem-1.75.0-8.el9.x86_64
boost-chrono-1.75.0-8.el9.x86_64
boost-context-1.75.0-8.el9.x86_64
boost-atomic-1.75.0-8.el9.x86_64
boost-date-time-1.75.0-8.el9.x86_64
boost-python3-1.75.0-8.el9.x86_64
boost-wave-1.75.0-8.el9.x86_64
boost-log-1.75.0-8.el9.x86_64
boost-fiber-1.75.0-8.el9.x86_64
boost-coroutine-1.75.0-8.el9.x86_64
boost-type_erasure-1.75.0-8.el9.x86_64
boost-timer-1.75.0-8.el9.x86_64
boost-locale-1.75.0-8.el9.x86_64
boost-container-1.75.0-8.el9.x86_64
boost-contract-1.75.0-8.el9.x86_64
boost-graph-1.75.0-8.el9.x86_64
boost-iostreams-1.75.0-8.el9.x86_64
boost-math-1.75.0-8.el9.x86_64
boost-nowide-1.75.0-8.el9.x86_64
boost-program-options-1.75.0-8.el9.x86_64
boost-random-1.75.0-8.el9.x86_64
boost-serialization-1.75.0-8.el9.x86_64
boost-stacktrace-1.75.0-8.el9.x86_64
boost-test-1.75.0-8.el9.x86_64
boost-numpy3-1.75.0-8.el9.x86_64
boost-1.75.0-8.el9.x86_64
boost-devel-1.75.0-8.el9.x86_64

Can you please advise why it does not compile?
Thank you.

**Comment by kei-nan** [comment]
Hello gsnick,

Can you try specifying BOOST_DIR in the make command to point the build process to where the boost headers can be located?
Note that by default it assumes it is under the `.install/boost` path.

Let us know if that solves your issue.

**Comment by gsnick** [comment]
Hello,
This was solved: yum install boost1.81-devel
A newer version of boost is required.
