### ISSUE TITLE
[BUG] redisearch under cluster mode may cause a lot of slow logs

### ISSUE THREAD

**Issue by githubname1024** [RediSearch/RediSearch#5035]
**Describe the bug**
I deployed a redis cluster loading RediSearch.
When I execute the FT.SEARCH command, there will be a lot slow logs.
From my understanding, RediSearch uses a module client to call the other master redis to get the _ft.search result, and then aggreate them.
The process of calling other redis does not block redis core, as I think, so the time spent on these calls should not be included in the command execution time.
However, currently, this time is included, which easily results in slow logs (longer than 10ms).

**Expected behavior**
Not counted the time of waiting for calling other master redis. So the command will not be counted as slow log.

**Additional context**
I also create an issue in redis. https://github.com/redis/redis/issues/13546

**Comment by meiravgri** [comment]
Hi @githubname1024 Thanks for approaching :) !
We define a query latency as the time from it was received from the user until the user got back the response.
This time might include aggregating the results collected from all the shards in the cluster.
Indeed, some operations are executed in the background, allowing parallel execution of commands received from other clients.

Hope it answers your concern.

**Comment by githubname1024** [comment]
@meiravgri 
Thank you for your reply.
I fully understand and accept what you said. And the design is indeed great and reasonable.

I was just wondering if there's a way to avoid logging commands that actually take up less time in Redis into the slow query log.
Currently, almost all the entries in the slow logs are FT.SEARCH commands, which might result in other potentially real slow queries being overlooked.

I think the slow log should be based on the actual time taken by the Redis main thread, rather than the execution time of command, such as the FT.SEARCH using backgroud thread.

I am looking forward to your reply or pointing out any mistakes I might have made.

**Comment by meiravgri** [comment]
Hi @githubname1024,
Search commands tend to be heavier compared to basic Redis commands. 
We aim to optimize user experience by allowing Redis to handle other commands while we prepare and aggregate results from the shards in the background. However, the definition of command execution time is consistent across Redis commands: we measure it from when the client issues the command until the response is delivered.

The time a command spends in the main thread is an internal implementation detail, and while background processing helps improve concurrency, it doesn't alter how the total execution time is measured for logging purposes.

I hope this clarifies things, and feel free to reach out if you have any more questions.

**Comment by githubname1024** [comment]
@meiravgri 
Got it. Thank you very much.

I will consult the Redis team about options for excluding certain commands from being logged as slow queries, or for separating module commands into a distinct slow log, such as a 'module slow log'.

**Comment by meiravgri** [comment]
@githubname1024 
I'll close the ticket for now. Let me know if you have further questions.
