### ISSUE TITLE
Unable to Retrieve Original NumPy Float Array from Redis Stored Embedding Vector

### ISSUE THREAD

**Issue by jayong-sv** [RediSearch/RediSearch#5037]
I stored an embedding vector in Redis using the following method:

```python
obj = {
    "vector": trk.features[-1].astype(np.float32).tobytes(),
    ...
}
pipe.hset(key, mapping=obj)
```

Later, when I retrieve the vector using the following query:

```python
query = (
    Query(f"*=>[KNN {k} @vector $vec as score]")
    .sort_by("score")
    .return_fields("id", "score", "img_path", "trk_id", "vector")
    .paging(0, k)
    .dialect(2)
)
```

The retrieved vector comes out as a string like this:

```
'\x0cG<\x00\x00\x00\x00\x08=\x00\x00\x00\x00\x1c+\x00\x00\x00\x00I\x15\x0cG<xI\x15\x00\x00\x00\x00I\x0cGx\x00\x00\x00\x00\x00\x00\x00\x00:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x\x0cG\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0cG\x00\x00\x00\x00I\u07fc\x0cG\x00\x00\x00\x00\x0cǼ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0cG\x00\x00\x00\x00\x00\x00\x00\x00Q!\x00...'
```

I need a way to convert this string back into the original NumPy float array. Ideally, I’d like to handle this in Python.

I tried the following code:

```python
np.frombuffer(bytearray(vector, 'utf8'), dtype=np.float32)
```

However, I encountered this error:

```
ValueError: buffer size must be a multiple of element size
```

Is there a way to convert this string back into a NumPy float array? Any suggestions on how to fix this would be appreciated.

**Comment by meiravgri** [comment]
I believe that this is a question to Numpy on how to convert binary blobs to Numpy array.
However, this worked for me:
```
arr = np.float32([1,2,3])
r.hset("test", "vec", arr.tobytes())
buffer = r.hget("test", "vec")
print(buffer)
buff_to_arr = np.frombuffer(buffer, dtype=np.float32)
print(buff_to_arr)
```

output:
```
b'\x00\x00\x80?\x00\x00\x00@\x00\x00@@'
[1. 2. 3.]
```
Hope it helps :)

**Comment by jayong-sv** [comment]
@meiravgri 

Thank you for the quick reply! As you mentioned, when using `hget`, the datatype is returned as bytes, so I can convert it back to the original NumPy array without issue.

However, when I search for the data using the following query:

```python
query = (
    Query(f"*=>[KNN {k} @vector $vec as score]")
    .sort_by("score")
    .return_fields("id", "score", "img_path", "trk_id", "vector")
    .paging(0, k)
    .dialect(2)
)

query_params = {
    "vec": embedding.astype(np.float32).tobytes()
}
docs = self.redis.ft(self.redis_index_name).search(query, query_params).docs
results = [d.__dict__ for d in docs if float(d['score']) <= threshold]
```

The datatype of `result[0]["vector"]` is returned as a string, like this:

```
'\x0cG<\x00\x00\x00\x00\x08=\x00\x00\x00\x00\x1c+\x00\x00\x00\x00I\x15\x0cG<xI\x15\x00\x00\x00\x00I\x0cGx\x00\x00\x00\x00\x00\x00\x00\x00:\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00x\x0cG\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0cG\x00\x00\x00\x00I\u07fc\x0cG\x00\x00\x00\x00\x0cǼ\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0cG\x00\x00\x00\x00\x00\x00\x00\x00Q!\x00...'
```

So, I am unable to convert it back to the original NumPy array using the method you suggested. I encountered the following error: `TypeError: a bytes-like object is required, not 'str'` 

I'm wondering if it's expected for the `vector` value to be returned as a string when running a Query(KNN)?
Is there a way to get the value as bytes directly instead of as a string?

**Comment by meiravgri** [comment]
Hi @jayong-sv,
latest versions of `redis-py` elaborated `return_field` with an additional argument allowing to disable the decoding of the return value.
```
query = (
    Query(f"*=>[KNN 2 @vec $vec as score]")
    .return_field("vec", decode_field=False)
    .paging(0, 2)
    .dialect(2)
)
```
Note that it is supported with `return_field` and not `return_fields`

now this snippet outputs the expected array:
```
docs = r.ft("idx").search(query, query_params).docs
vec_ret = docs[0]["vec"]
vec_to_arr = np.frombuffer(vec_ret, dtype=np.float32)
```

Hope it helps :)

**Comment by jayong-sv** [comment]
@meiravgri  Thank you so much!!!
