### ISSUE TITLE
[BUG] Redis hangs for hours after restart loading bgsave dump

### ISSUE THREAD

**Issue by nantiferov** [RediSearch/RediSearch#5050]
**Describe the bug**

We have cluster with 3 master + 3 replicas with latest search module v2.10.7, built with `make build COORD=oss`. Memory usage is 3*9Gb=27Gb in total.

Noticed issue with very long restart (~2.5 hours) of replica from bgsave dump. Basically redis startup log looks as usual, but then everything stuck after `# <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12881979120B` message and only in verbose loglevel possible to see repeating messages `<module> vector index 'et' - Updating HNSW index capacity from 3168256 to 3169280`

Logs:

```log
...
36580:S 26 Sep 2024 09:32:54.755 * Loading RDB produced by version 7.4.0
36580:S 26 Sep 2024 09:32:54.755 * RDB age 31 seconds
36580:S 26 Sep 2024 09:32:54.755 * RDB memory usage when created 9055.51 Mb
36580:S 26 Sep 2024 09:32:54.755 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12882034216B
36580:S 26 Sep 2024 09:32:54.755 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12881979120B
# verbose logs enabled
36580:S 26 Sep 2024 10:35:01.648 - <module> vector index 'et' - Updating HNSW index capacity from 3168256 to 3169280
36580:S 26 Sep 2024 10:35:03.078 - <module> vector index 'et' - Updating HNSW index capacity from 3169280 to 3170304
36580:S 26 Sep 2024 10:35:04.496 - <module> vector index 'et' - Updating HNSW index capacity from 3170304 to 3171328
...
36580:S 26 Sep 2024 11:55:54.534 - <module> vector index 'et' - Updating HNSW index capacity from 6547456 to 6548480
36580:S 26 Sep 2024 11:55:56.127 - <module> vector index 'et' - Updating HNSW index capacity from 6548480 to 6549504
36580:S 26 Sep 2024 11:55:57.715 - <module> vector index 'et' - Updating HNSW index capacity from 6549504 to 6550528
# verbose logs disabled
36580:S 26 Sep 2024 11:56:41.368 * Done loading RDB, keys loaded: 6586782, keys expired: 0.
36580:S 26 Sep 2024 11:56:41.368 * <search> Loading event ends
36580:S 26 Sep 2024 11:56:41.368 * MASTER <-> REPLICA sync: Finished with success
```

**To Reproduce**
1. Generate search index around 10Gb data per node.
2. Restart replica.
3. Wait for hours to it became connected (need to set loglevel to verbose to see any progress in logs).
4. During all this time, replica will be in `sync` state and switch to `connected` only after couple of hours
P.S. I haven't tested in simple master/replica setup without cluster, but have a feeling that it might have same issue.

**Expected behavior**
Time of restart of replica with enabled RediSearch module shouldn't differ much from usual Redis. Something like 2-3 minutes max with this amount of data.

**Screenshots**
Not applicable.

**Environment (please complete the following information):**
 - OS: [e.g. ubuntu 22.04]
 - CPU model: Graviton2, aarch64
 - Version: 2.10.7, Redis: 7.4.0 - oss, JSON module: v2.8.4
 - Search module built with `make build COORD=oss` to work with Cluster
 - Redis configuration close to defaults, RediSearch module - defaults

```log
$ redis-cli info modules
# Modules
module:name=search,ver=21007,api=1,filters=0,usedby=[],using=[ReJSON],options=[handle-io-errors]
module:name=ReJSON,ver=20804,api=1,filters=0,usedby=[search],using=[],options=[handle-io-errors]

# search_version
search_version:2.10.7
search_redis_version:7.4.0 - oss

# search_index
search_number_of_indexes:2

# search_fields_statistics
search_fields_vector:Vector=2,HNSW=2

# search_memory
search_used_memory_indexes:797191783
search_used_memory_indexes_human:760.2613525390625
search_total_indexing_time:16084202

# search_cursors
search_global_idle:0
search_global_total:0

# search_gc
search_bytes_collected:0
search_total_cycles:315
search_total_ms_run:102148

# search_dialect_statistics
search_dialect_1:0
search_dialect_2:0
search_dialect_3:0
search_dialect_4:0

# search_runtime_configurations
search_enableGC:ON
search_minimal_term_prefix:2
search_minimal_stem_length:4
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:1000000
search_max_aggregate_results:-1
search_gc_scan_size:100
search_min_phonetic_term_length:3
```

**Additional context**

Problem looks pretty similar to https://github.com/RediSearch/RediSearch/issues/4186, but it was fixed months ago in https://github.com/RediSearch/RediSearch/pull/4529 afaik.

Please let me know if something else required.

**Comment by meiravgri** [comment]
Hi @nantiferov,
Could you please clarify what you mean by "stuck?"
According to the logs, it seems that the rdb load process ended successfully.
On restart, we reindex all the data, i.e rebuilding HNSW index. This operation can be very long.

Let me know if i answered your question.

**Comment by nantiferov** [comment]
By "stuck" I mean redis replica stays in `sync` state for >2 hours without any messages in logs (with loglevel=notice), with output:
```log
$ redis-cli -p 6379 role
1) "slave"
2) "x.x.x.x"
3) (integer) 6378
4) "sync"
5) (integer) -1
```

And for this time other cluster nodes are spammed with messages about this node going to fail state and back, like:
```log
522:M 26 Sep 2024 10:40:22.574 * FAIL message received from 5a2242f967ed301d642e82c35bbc5e8e2acf79fb about c3d63d936648476c199f353f9295b1b3ac908494
522:M 26 Sep 2024 10:40:24.139 * Clear FAIL state for node c3d63d936648476c199f353f9295b1b3ac908494: replica is reachable again.
```

> On restart, we reindex all the data, i.e rebuilding HNSW index. This operation can be very long.

1. Does it mean that it's expected to rebuild index with 9Gb of data 2.5 hours?
It makes maintenance with Search module enabled pretty time consuming it seems.

2. Is it possible to track progress in output of `redis-cli info modules` or somehow else?

3. I think it would be great to have something printed in redis log with default `loglevel=notice` after `<search> creating vector index`, like `rebuilding HNSW index, it will take approximately Xminutes`, depending on size of data in bgsave dump.
Right now I only noticed some small memory used growth on OS level after hour or so and decided to give it a chance to see if after almost 3 hours replica synced.

**Comment by nantiferov** [comment]
Checked logs history and found answer for 2nd question. search_used_memory_indexes/search_used_memory_indexes_human from `redis-cli info modules` grows slowly in the process of rebuilding HNSW index, i.e.

```log
# restarted replica
search_used_memory_indexes:112814415
search_used_memory_indexes_human:107.58821105957031
search_total_indexing_time:894385.9375

# VS connected replica
search_used_memory_indexes:797191783
search_used_memory_indexes_human:760.2613525390625
search_total_indexing_time:16084202
```

So should be possible to track reindexing by comparing current search_used_memory_indexes with one before restart.

**Comment by nantiferov** [comment]
Another update: it seems we used lower cluster-node-timeout than default and it was causing these flapping FAIL statuses for replica while it was restarting. With default `cluster-node-timeout 15000` it's not repeating.

I'm talking about these
```log
522:M 26 Sep 2024 10:40:22.574 * FAIL message received from 5a2242f967ed301d642e82c35bbc5e8e2acf79fb about c3d63d936648476c199f353f9295b1b3ac908494
522:M 26 Sep 2024 10:40:24.139 * Clear FAIL state for node c3d63d936648476c199f353f9295b1b3ac908494: replica is reachable again.
```

**Comment by meiravgri** [comment]
As mentioned, considering the data size, 2 hours is a reasonable time to load the rdb.
The replica becomes available after the rdb load process has finished.
To enhance this process you can set `WORKERS` config with a value greater than zero (number of requested threads).
This will allow the module to use additional threads for operations such as rdb loading and for running queries from different clients in parallel.
If you want to additional resources (threads) only when executing operational processes (such as rdb load), leave `WORKERS=0` and set `MIN_OPERATION_WORKERS`.

Let me know if this solved your problem.
ץ``

**Comment by meiravgri** [comment]
Forgot to mention that the easiest way to build with this capability is to compile `master` branch.
Note when compiling `master` you don't need to specify `COORD=oss`, it will be compiled with the coordinator by default. a simple `make` will do the job :)

**Comment by nantiferov** [comment]
Thank you for update. That's definitely something I need to check.

> Forgot to mention that the easiest way to build with this capability is to compile master branch.

But why from master branch? It seems these options were added some time ago and should be available in 2.10.7,

**Comment by nantiferov** [comment]
Ah, I see, looks like not enabled, will try master now.

Log from 2.10.7:

```log
48468:M 30 Sep 2024 09:48:04.575 # <search> Invalid Configurations: No such configuration option `WORKERS`
48468:M 30 Sep 2024 09:48:04.575 # <search> Could not init search library...
48468:M 30 Sep 2024 09:48:04.575 # Module /var/lib/redis/modules/redisearch.so initialization failed. Module not loaded
48468:M 30 Sep 2024 09:48:04.575 # Can't load module from /var/lib/redis/modules/redisearch.so: server aborting
```

**Comment by nantiferov** [comment]
Tested with build from latest master, looks better with ~47min index creation instead of 2.5h with `WORKERS 2` on 4 core ec2. All cores usage close to 95%

```log
48963:M 30 Sep 2024 10:19:11.945 * <search> Redis version found by RedisSearch : 7.4.0 - oss
48963:M 30 Sep 2024 10:19:11.945 * <search> RediSearch version 99.99.99 (Git=master-45de454dd)
48963:M 30 Sep 2024 10:19:11.945 * <search> Low level api version 1 initialized successfully
48963:M 30 Sep 2024 10:19:11.945 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000,
48963:M 30 Sep 2024 10:19:11.946 * <search> Initialized thread pools!
48963:M 30 Sep 2024 10:19:11.946 * <search> Enabled workers threadpool of size 2
48963:M 30 Sep 2024 10:19:11.946 * <search> Enabled role change notification
48963:M 30 Sep 2024 10:19:11.946 * <search> Cluster configuration: AUTO partitions, type: 0, coordinator timeout: 0ms
48963:M 30 Sep 2024 10:19:11.946 * <search> Register write commands
48963:M 30 Sep 2024 10:19:11.946 * Module 'search' loaded from /var/lib/redis/modules/redisearch-dev.so
48963:M 30 Sep 2024 10:19:11.947 * <search> Acquired RedisJSON_V5 API
48963:S 30 Sep 2024 10:19:42.890 * <search> Loading event starts
...
48963:S 30 Sep 2024 10:19:42.890 * Loading RDB produced by version 7.4.0
48963:S 30 Sep 2024 10:19:42.890 * RDB age 26 seconds
48963:S 30 Sep 2024 10:19:42.890 * RDB memory usage when created 10744.69 Mb
48963:S 30 Sep 2024 10:19:42.891 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12882034328B
48963:S 30 Sep 2024 10:19:42.891 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12881979088B
48963:S 30 Sep 2024 10:19:42.891 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12881924952B
48963:S 30 Sep 2024 11:07:44.877 * Done loading RDB, keys loaded: 7910945, keys expired: 0.
48963:S 30 Sep 2024 11:07:45.878 * <search> Loading event ends
48963:S 30 Sep 2024 11:07:45.878 * MASTER <-> REPLICA sync: Finished with success
```
Results with `MIN_OPERATION_WORKERS 3` are same to `WORKERS 2` both in terms of time and cpu usage

`MIN_OPERATION_WORKERS 2` takes slightly longer (1h 7m), but all 4 cores utilised by 68%.
```log
49889:M 30 Sep 2024 12:32:09.138 * <search> Redis version found by RedisSearch : 7.4.0 - oss
49889:M 30 Sep 2024 12:32:09.138 * <search> RediSearch version 99.99.99 (Git=master-45de454dd)
49889:M 30 Sep 2024 12:32:09.138 * <search> Low level api version 1 initialized successfully
49889:M 30 Sep 2024 12:32:09.138 * <search> Acquired RedisJSON_V5 API
49889:M 30 Sep 2024 12:32:09.138 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000,
49889:M 30 Sep 2024 12:32:09.138 * <search> Initialized thread pools!
49889:M 30 Sep 2024 12:32:09.138 * <search> Disabled workers threadpool of size 0
49889:M 30 Sep 2024 12:32:09.138 * <search> Enabled role change notification
49889:M 30 Sep 2024 12:32:09.138 * <search> Cluster configuration: AUTO partitions, type: 0, coordinator timeout: 0ms
49889:M 30 Sep 2024 12:32:09.138 * <search> Register write commands
49889:M 30 Sep 2024 12:32:09.138 * Module 'search' loaded from /var/lib/redis/modules/redisearch-dev.so
49889:M 30 Sep 2024 12:32:09.139 * Server initialized
49889:M 30 Sep 2024 12:32:09.139 * <search> Loading event starts
49889:M 30 Sep 2024 12:32:09.139 * <search> Enabled workers threadpool of size 2
49889:M 30 Sep 2024 12:32:09.139 * <search> Enabled workers threadpool of size 2
49889:M 30 Sep 2024 12:32:09.139 * Loading RDB produced by version 7.4.0
49889:M 30 Sep 2024 12:32:09.139 * RDB age 1981 seconds
49889:M 30 Sep 2024 12:32:09.139 * RDB memory usage when created 10748.89 Mb
49889:M 30 Sep 2024 12:32:09.139 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12882333816B
49889:M 30 Sep 2024 12:32:09.139 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12882278576B
49889:M 30 Sep 2024 12:32:09.139 # <search> creating vector index. Server memory limit: 12884901888B, required memory: 20344B, available memory: 12882224456B
49889:M 30 Sep 2024 13:39:08.424 * Done loading RDB, keys loaded: 7914934, keys expired: 0.
49889:M 30 Sep 2024 13:39:08.424 * <search> Disabled workers threadpool of size 2
49889:M 30 Sep 2024 13:39:09.425 * <search> Loading event ends
```

From other good news - seems now redis with module enabled returns correctly metrics to redis_exporter, so it's possible to see memory growing and other metrics.

**Comment by meiravgri** [comment]
The performance with `WORKERS` configuration should be affected only if you are running queries.
I see that in the second attempt with `MIN_OPERATION_WORKERS 2` there are 4000 more keys. However, it doesn't explain a 20 min discrepancy.
It might result from the current load on the machine and how it decides to split its resources. 

I'm glad to hear that worked for you. Feel free to let me know if you have any more questions.

**Comment by nantiferov** [comment]
Thank you for help, with these options restart time becoming way better than before.

> Feel free to let me know if you have any more questions.

Just one more question: It's mentioned in this issue https://github.com/RediSearch/RediSearch/issues/4489#issuecomment-1966226779 that multi-threading options are available for Redis Enterprise only, so I guess by using build from master branch I'm doing something unsupported?
Or there are plans to enable it in OSS?
How safe it is to use dev build?

**Comment by meiravgri** [comment]
Future versions will allow multi-threaded also in the community version (loss).
You can safely compile master until it is available in an official release.

**Comment by nantiferov** [comment]
Cool, thank you for details.
Have a nice day.
