### ISSUE TITLE
Document count off

### ISSUE THREAD

**Issue by stockholmux** [RediSearch/RediSearch#506]
Using 1.4, I'm experiencing off-by-one count:
```
127.0.0.1:6379>  ft.search permits garage limit 0 0
1) (integer) 49488
127.0.0.1:6379> ft.search permits carport limit 0 0
1) (integer) 190
127.0.0.1:6379> ft.search permits "garage carport" limit 0 0
1) (integer) 133
127.0.0.1:6379> ft.search permits garage|carport limit 0 0
1) (integer) 49544

```

Now, these numbers don't quite add up.
49488 (garage) + 190 (carport) = 49678
49678 - 133 ("garage carport", to remove double counts for documents with both) = 49545 (not 49544 as garage|carport was reporting)

A few versions back "garage carport" was reporting 134, which was correct.

**Comment by MeirShpilraien** [comment]
@stockholmux can you send me an RDB so I can check it out?

**Comment by stockholmux** [comment]
@MeirShpilraien It's relatively large. I'll share with you privately.

**Comment by MeirShpilraien** [comment]
@stockholmux thanks, which redis version are you using?

**Comment by MeirShpilraien** [comment]
@stockholmux I will need to know how you created the RDB you sent me, any chance you have a script that created it?

**Comment by MeirShpilraien** [comment]
@stockholmux I just run you script and those are the results I am getting:
```
127.0.0.1:6379> ft.search permits garage limit 0 0
1) (integer) 49488
127.0.0.1:6379> ft.search permits carport limit 0 0
1) (integer) 190
127.0.0.1:6379> ft.search permits "garage carport" limit 0 0
1) (integer) 134
127.0.0.1:6379> ft.search permits garage|carport limit 0 0
1) (integer) 49544
```
It looks ok, is it reproduced easily each time? also on which version did it happened to you?
