### ISSUE TITLE
Documentation error: RedisSearch is not open source

### ISSUE THREAD

**Issue by ddevault** [RediSearch/RediSearch#518]
https://oss.redislabs.com/redisearch/

>RediSearch is a an open-source Full-Text and Secondary Index engine over Redis

The Apache 2.0 license modified with the Commons Clause is not an open-source license.

The wording in most of the documentation is outdated, such as this page which claims RedisML is AGPL:

https://oss.redislabs.com/redisml/

Or this page, which implies the projects listed there are all open source:

https://redislabs.com/community/oss-projects/

I assume you don't want me to spam a bunch of your bug trackers with these tickets, so I'll leave it to just this one for now.

**Comment by itamarhaber** [comment]
Hello @SirCmpwn 

Thanks for pointing out the errors and inaccuracies, there is indeed no need for additional issues to be opened for them.

We are reviewing these matters and will update with regards to respective developments. Keeping issue this open until then.

**Comment by SirCmpwn** [comment]
Bump.

**Comment by kfogel** [comment]
@SirCmpwn's point is pretty straightforward and, I hope, non-controversial.  Obviously it doesn't take much time to remove the words "open source" from some web pages, but possibly by "reviewing these matters" you meant that you're reviewing the licensing decisions themselves, rather than merely how to describe them.  Either way, I hope this issue hasn't been back-burnered.

**Comment by itamarhaber** [comment]
I can not confirm or deny any of the above, but I can say it hasn't been back-burnered :)

**Comment by SirCmpwn** [comment]
I understand that it may take time to complete your work on moving to the new license, deciding to stay there, or whatever else you have in mind. But I think you should prioritize removing dishonest statements from your marketing material and documentation. I don't think that dishonestly is a trait you would want to be known for.

**Comment by kfogel** [comment]
Glad to hear that, @itamarhaber :-).

**Comment by brennanfee** [comment]
This has got to be fixed in order to actually be open source.  The Redis modules site explicitly states, "Only modules under an OSI approved license are listed here."  Commons Clause **IS NOT OSI APPROVED**.

**Comment by SirCmpwn** [comment]
bump.

**Comment by julianfoad** [comment]
@itamarhaber Hello. Please could you let us know about any progress or hold-up?

The Redis modules site at https://redis.io/modules still has the error that @brennanfee pointed out.

**Comment by ddevault** [comment]
Here again for your regularly scheduled pissed-off-at-being-ignored bump. Enough of this bullshit, guys.

**Comment by felixrabe** [comment]
-   [X] https://oss.redislabs.com/redisearch/ now says
    > RediSearch is a source available Full-Text and Secondary Index engine over Redis	
-   [X] https://oss.redislabs.com/redisml/ now says
    > License
    > Redis Source Available License Agreement - see LICENSE
-   [ ] https://redislabs.com/community/oss-projects/ might have better wording (though still slightly misleading), but the URL is still clearly wrong and should redirect to something that does not mention "oss"; suggestion: "/community/projects".

**Comment by ddevault** [comment]
Why did you close this? This page is still very misleading:

https://redislabs.com/community/oss-projects/

The URL and text are both misleading.
