### ISSUE TITLE
[BUG] Crash on Fork GC

### ISSUE THREAD

**Issue by keithchew** [RediSearch/RediSearch#5188]
Encountered a crash on 2.8.16:
```
113230:52:C 10 Nov 2024 01:23:00.228 # Accessing address: 0x7f9a7b97
113230:52:C 10 Nov 2024 01:23:00.228 # Crashed running the instruction at: 0x7f9acac44754

------ STACK TRACE ------
EIP:
/opt/redis-stack/lib/redisearch.so(TrieMapIterator_Next+0xf4) [0x7f9acac44754]

Backtrace:
/lib/x86_64-linux-gnu/libpthread.so.0(+0x14420) [0x7f9adeac5420]
/opt/redis-stack/lib/redisearch.so(TrieMapIterator_Next+0xf4) [0x7f9acac44754]
/opt/redis-stack/lib/redisearch.so(+0x1982de) [0x7f9acac7c2de]
/opt/redis-stack/lib/redisearch.so(+0x19a2e5) [0x7f9acac7e2e5]
/opt/redis-stack/lib/redisearch.so(+0x15ca67) [0x7f9acac40a67]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x8609) [0x7f9adeab9609]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x43) [0x7f9ade9dc353]

```

Luckily, I have additional logs in my local copy and I can confirm that the above happens in the child process during a GC fork. Looking at fork_gc.c, FGC_childCollectTags is the only method calling TrieMapIterator_Next.

Unfortunately, I do not have a reproduction step and the crash is rare, first time hitting it after 12 months of relatively intensive usage 24/7. Will continue keeping at eye out and post any further updates here.

**Comment by kei-nan** [comment]
Hi @keithchew,

Thanks for reporting the crash.
Do you happen to have the redisearch.so library that crashed?
It will help us get a proper call stack of the crash line(with files, line numbers and so on).
