### ISSUE TITLE
Volatile results trying to get all document IDs - limit not reached

### ISSUE THREAD

**Issue by mahemoff** [RediSearch/RediSearch#520]
I'm trying to get all keys and the results are different each time.

e.g. I run "FT.search series * NOCONTENT LIMIT 0 100000" on an index with about 400,000 items and it returns different size lists each time e.g. 48 items, 19,698 items, 45,398 items. I did see it return the full amount (100,000 items) once. The amount usually ends with a number in high 40's or high 90's making me think it's iterating in 50's and terminating due to an incomplete result.

This is with RediSearch 1.4.0rc3 on Redis 4.9.106

**Comment by mnunberg** [comment]
You are probably reaching the query timeout. Set “TIMEOUT” to something higher in the loadmodule directive (when launching Redis). The value is in milliseconds.

**Comment by dvirsky** [comment]
Also, you should look into the using the cursor API

**Comment by mahemoff** [comment]
Timeout would make sense, but this doesn't seem timeout related. e.g. in some cases, the results are coming back in under a second on a replica, but very incomplete. Other times, there might be more results in e.g. 10 seconds. The common pattern is the amount usually end in 49, 99, or similar (the client typically queries in groups of 50 and maybe that's related.)

@dvirsky In this case, I'm just trying to get a complete list for a batch sync process, so a few seconds latency isn't an issue. I'm hoping it doesn't cause much problem to get e.g. a 100,000 IDs in one call, but will look at cursor API if needed.

**Comment by mnunberg** [comment]
I'm going to consider this fixed in 1.6, at least.
