### ISSUE TITLE
[BUG] [CRASH] crash running redisearch 2.10.5 (redis stack 7.4) on mac os arm with rdb created with 2.10.7

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#5408]
**Describe the bug**
I have an RDB file which was created in production with redis 7.4.1 and RS 2.10.7 (latest stable of both). This file crashes redis on startup when loaded with the latest version of redis-stack 7.4.0 which includes RS 2.10.5. 

**To Reproduce**
1. Install redis-stack 7.4.0 on mac os x arm
2. Copy RDB file created with 2.10.7 into appropriate directory
3. start redis-server

**Expected behavior**
Server starts.

**Screenshots**

**Crash report**

59985:C 23 Dec 2024 22:35:46.468 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
59985:C 23 Dec 2024 22:35:46.468 * Redis version=7.4.1, bits=64, commit=74b289a0, modified=0, pid=59985, just started
59985:C 23 Dec 2024 22:35:46.468 * Configuration loaded
59985:M 23 Dec 2024 22:35:46.469 * Increased maximum number of open files to 10032 (it was originally set to 256).
59985:M 23 Dec 2024 22:35:46.469 * monotonic clock: POSIX clock_gettime
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis Community Edition
  .-`` .-```.  ```\/    _.,_ ''-._     7.4.1 (74b289a0/0) 64 bit
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 59985
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           https://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

59985:M 23 Dec 2024 22:35:46.470 # WARNING: The TCP backlog setting of 511 cannot be enforced because kern.ipc.somaxconn is set to the lower value of 128.
59985:M 23 Dec 2024 22:35:46.471 * Module 'RedisCompat' loaded from /Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/lib/rediscompat.so
59985:M 23 Dec 2024 22:35:46.476 * <search> Redis version found by RedisSearch : 7.4.1 - oss
59985:M 23 Dec 2024 22:35:46.477 * <search> RediSearch version 2.10.5 (Git=2.10-e2f28a9)
59985:M 23 Dec 2024 22:35:46.477 * <search> Low level api version 1 initialized successfully
59985:M 23 Dec 2024 22:35:46.477 * <search> gc: ON, prefix min length: 2, min word length to stem: 4, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, max number of search results:  1000000,
59985:M 23 Dec 2024 22:35:46.477 * <search> Initialized thread pools!
59985:M 23 Dec 2024 22:35:46.478 * <search> Enabled role change notification
59985:M 23 Dec 2024 22:35:46.478 * Module 'search' loaded from /Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/lib/redisearch.so
59985:M 23 Dec 2024 22:35:46.478 * Server initialized
59985:M 23 Dec 2024 22:35:46.479 * <search> Loading event starts
59985:M 23 Dec 2024 22:35:46.479 * Loading RDB produced by version 7.4.1
59985:M 23 Dec 2024 22:35:46.479 * RDB age 26546 seconds
59985:M 23 Dec 2024 22:35:46.479 * RDB memory usage when created 4306.16 Mb

=== REDIS BUG REPORT START: Cut & paste starting from here ===
59985:M 23 Dec 2024 22:35:46.479 # Redis 7.4.1 crashed by signal: 11, si_code: 2
59985:M 23 Dec 2024 22:35:46.479 # Accessing address: 0x4
59985:M 23 Dec 2024 22:35:46.479 # Crashed running the instruction at: 0x10210b9e8

------ STACK TRACE ------
EIP:
0   redis-server                        0x000000010210b9e8 decrRefCount + 28

Backtrace:
0   libsystem_platform.dylib            0x0000000194b82584 _sigtramp + 56
1   redis-server                        0x00000001021c8f3c RM_FreeString + 28
2   redis-server                        0x00000001021c8f3c RM_FreeString + 28
3   redisearch.so                       0x0000000103745404 IndexError_Clear + 100
4   redisearch.so                       0x0000000103776998 IndexSpec_Free + 108
5   redisearch.so                       0x000000010378ec6c StrongRef_Release + 108
6   redisearch.so                       0x000000010377858c IndexSpec_CreateFromRdb + 812
7   redisearch.so                       0x000000010377985c Indexes_RdbLoad + 164
8   redis-server                        0x0000000102131d2c rdbLoadRioWithLoadingCtx + 1528
9   redis-server                        0x0000000102133008 rdbLoad + 428
10  redis-server                        0x00000001020f2eb4 main + 19576
11  dyld                                0x00000001947c7154 start + 2476

------ STACK TRACE DONE ------

------ REGISTERS ------
59985:M 23 Dec 2024 22:35:46.483 #
x0:0000000000000000 x1:0000000000000000 x2:0000000000000001 x3:000000016dd6a91f
x4:0000000000000005 x5:0000000025800000 x6:0000000000000002 x7:0000000000000000
x8:00000001021c8f20 x9:00006000008e8b10 x10:0000000000000001 x11:00000000fffffffd
x12:0000010000000000 x13:0000000000000000 x14:0000000000000000 x15:0000000000000000
x16:0000000194b117d4 x17:00000002070a23e0 x18:0000000000000000 x19:0000000000000000
x20:0000000000000000 x21:0000000103aa3ab0 x22:0000000103a23564 x23:fffffffffffffc18
x24:0000000103aa4138 x25:0000000103a2a2df x26:0000000000000000 x27:000000012a032ed0
x28:0000000103a1a496 fp:000000016dd6a8c0 lr:00000001021c8f3c
sp:000000016dd6a880 pc:000000010210b9e8 cpsr:80001000

59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88f) -> 0000000103aa3ab0
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88e) -> 0000000000000001
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88d) -> 0000000103745404
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88c) -> 000000016dd6a910
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88b) -> 000000016dd6a920
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a88a) -> 0000000103aa4000
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a889) -> 00000001021c8f3c
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a888) -> 000000016dd6a8e0
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a887) -> 00006000024cf800
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a886) -> 0000000000000000
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a885) -> 0000000103aa3ab0
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a884) -> 0000000103a23564
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a883) -> fffffffffffffc18
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a882) -> 0000000103aa4138
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a881) -> 0000000103a2a2df
59985:M 23 Dec 2024 22:35:46.483 # (000000016dd6a880) -> 0000000000000000

------ INFO OUTPUT ------
# Server
redis_version:7.4.1
redis_git_sha1:74b289a0
redis_git_dirty:0
redis_build_id:73417084e296cefa
redis_mode:standalone
os:Darwin 23.6.0 arm64
arch_bits:64
monotonic_clock:POSIX clock_gettime
multiplexing_api:kqueue
atomicvar_api:c11-builtin
gcc_version:4.2.1
process_id:59985
process_supervised:no
run_id:6b2713c31c1f4972b4af41976201d7ef9cf9e450
tcp_port:6379
server_time_usec:1735022146479752
uptime_in_seconds:0
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:6968898
executable:/Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/bin/redis-server
config_file:/Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/etc/redis-stack-service.conf
io_threads_active:0
listener0:name=tcp,bind=*,bind=-::*,port=6379

# Clients
connected_clients:0
cluster_connections:0
maxclients:10000
client_recent_max_input_buffer:0
client_recent_max_output_buffer:0
blocked_clients:0
tracking_clients:0
pubsub_clients:0
watching_clients:0
clients_in_timeout_table:0
total_watched_keys:0
total_blocking_keys:0
total_blocking_keys_on_nokey:0

# Memory
used_memory:1288368
used_memory_human:1.23M
used_memory_rss:0
used_memory_rss_human:0B
used_memory_peak:1288368
used_memory_peak_human:1.23M
used_memory_peak_perc:108.37%
used_memory_overhead:1245372
used_memory_startup:1245152
used_memory_dataset:42996
used_memory_dataset_perc:99.49%
allocator_allocated:0
allocator_active:0
allocator_resident:0
allocator_muzzy:0
total_system_memory:25769803776
total_system_memory_human:24.00G
used_memory_lua:31744
used_memory_vm_eval:31744
used_memory_lua_human:31.00K
used_memory_scripts_eval:0
number_of_cached_scripts:0
number_of_functions:0
number_of_libraries:0
used_memory_vm_functions:32768
used_memory_vm_total:64512
used_memory_vm_total_human:63.00K
used_memory_functions:216
used_memory_scripts:216
used_memory_scripts_human:216B
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:nan
allocator_frag_bytes:0
allocator_rss_ratio:nan
allocator_rss_bytes:0
rss_overhead_ratio:nan
rss_overhead_bytes:0
mem_fragmentation_ratio:nan
mem_fragmentation_bytes:0
mem_not_counted_for_evict:0
mem_replication_backlog:4
mem_total_replication_buffers:0
mem_clients_slaves:0
mem_clients_normal:0
mem_cluster_links:0
mem_aof_buffer:0
mem_allocator:libc
mem_overhead_db_hashtable_rehashing:0
active_defrag_running:0
lazyfree_pending_objects:0
lazyfreed_objects:0

# Persistence
loading:1
async_loading:0
current_cow_peak:0
current_cow_size:0
current_cow_size_age:0
current_fork_perc:0.00
current_save_keys_processed:0
current_save_keys_total:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1735022146
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_saves:0
rdb_last_cow_size:0
rdb_last_load_keys_expired:0
rdb_last_load_keys_loaded:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_rewrites:0
aof_rewrites_consecutive_failures:0
aof_last_write_status:ok
aof_last_cow_size:0
module_fork_in_progress:0
module_fork_last_cow_size:0
loading_start_time:1735022146
loading_total_bytes:1540526836
loading_rdb_used_mem:4515339968
loading_loaded_bytes:0
loading_loaded_perc:0.00
loading_eta_seconds:1

# Stats
total_connections_received:0
total_commands_processed:1
instantaneous_ops_per_sec:0
total_net_input_bytes:0
total_net_output_bytes:0
total_net_repl_input_bytes:0
total_net_repl_output_bytes:0
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
instantaneous_input_repl_kbps:0.00
instantaneous_output_repl_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_subkeys:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
expire_cycle_cpu_milliseconds:0
evicted_keys:0
evicted_clients:0
evicted_scripts:0
total_eviction_exceeded_time:0
current_eviction_exceeded_time:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
pubsubshard_channels:0
latest_fork_usec:0
total_forks:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0
total_active_defrag_time:0
current_active_defrag_time:0
tracking_total_keys:0
tracking_total_items:0
tracking_total_prefixes:0
unexpected_error_replies:0
total_error_replies:0
dump_payload_sanitizations:0
total_reads_processed:0
total_writes_processed:0
io_threaded_reads_processed:0
io_threaded_writes_processed:0
client_query_buffer_limit_disconnections:0
client_output_buffer_limit_disconnections:0
reply_buffer_shrinks:0
reply_buffer_expands:0
eventloop_cycles:0
eventloop_duration_sum:0
eventloop_duration_cmd_sum:0
instantaneous_eventloop_cycles_per_sec:0
instantaneous_eventloop_duration_usec:0
acl_access_denied_auth:0
acl_access_denied_cmd:0
acl_access_denied_key:0
acl_access_denied_channel:0

# Replication
role:master
connected_slaves:0
master_failover_state:no-failover
master_replid:02657e14669efd84fb8e61ca5be3421188c2e126
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:1
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.014201
used_cpu_user:0.009801
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Modules
module:name=search,ver=21005,api=1,filters=0,usedby=[],using=[],options=[handle-io-errors]
module:name=RedisCompat,ver=1,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_info:calls=1,usec=72,usec_per_call=72.00,rejected_calls=0,failed_calls=0

# Errorstats

# Latencystats
latency_percentiles_usec_info:p50=72.191,p99=72.191,p99.9=72.191

# Cluster
cluster_enabled:0

# Keyspace

------ CLIENT LIST OUTPUT ------

------ MODULES INFO OUTPUT ------
# search_version
search_version:2.10.5
search_redis_version:7.4.1 - oss

# search_index
search_number_of_indexes:0

# search_fields_statistics

# search_memory
search_used_memory_indexes:0
search_used_memory_indexes_human:0
search_total_indexing_time:0

# search_cursors
search_global_idle:0
search_global_total:0

# search_gc
search_bytes_collected:0
search_total_cycles:0
search_total_ms_run:0

# search_dialect_statistics
search_dialect_1:0
search_dialect_2:0
search_dialect_3:0
search_dialect_4:0

# search_runtime_configurations
search_enableGC:ON
search_minimal_term_prefix:2
search_minimal_stem_length:4
search_maximal_prefix_expansions:200
search_query_timeout_ms:500
search_timeout_policy:return
search_cursor_read_size:1000
search_cursor_max_idle_time:300000
search_max_doc_table_size:1000000
search_max_search_results:1000000
search_max_aggregate_results:-1
search_gc_scan_size:100
search_min_phonetic_term_length:3

------ CONFIG DEBUG OUTPUT ------
lazyfree-lazy-user-del no
lazyfree-lazy-expire no
io-threads 1
repl-diskless-load disabled
lazyfree-lazy-server-del no
activedefrag no
lazyfree-lazy-user-flush no
repl-diskless-sync yes
slave-read-only yes
sanitize-dump-payload no
replica-read-only yes
client-query-buffer-limit 1gb
list-compress-depth 0
io-threads-do-reads no
lazyfree-lazy-eviction no
proto-max-bulk-len 512mb

------ DUMPING CODE AROUND EIP ------
Symbol: decrRefCount (base: 0x10210b9cc)
Module: /Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/bin/redis-server (base 0x102094000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x10210b9cc -D -b binary -m i386:x86-64 /tmp/dump.bin
------
59985:M 23 Dec 2024 22:35:46.484 # dump of function (hexdump of 156 bytes):
fa67bba9f85f01a9f65702a9f44f03a9fd7b04a9fd030191f30300aa090440b92805007141030054680240b9090d40923f190071e8210054ea0800d04a912f91cb0000104c6969386b090c8b780d00f01823179160011fd61f0d1c72a11a0054680640f9681a00b409f15f38290900123f110071481d00540a0900904a813e91495969f81401098bc40000143f0100714d1e00540a00b0123f010a6b
Function at 0x1ec64ba26 is _ZN3AGX20AppleCompressionGen210CompressorILNS0_11PixelFormatE15ELj1ELh0ELNS0_13SubblockOrderE1EL19AGXTextureFootprint0EE16compressSubblockEPhRhPKhmhh30eAGXTextureFormatComponentType

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

**Environment (please complete the following information):**
 - OS: mac os x
 - Apple M2
 - Version/branch redis stack 7.4.0

**Additional context**

I downloaded redis-stack from here:
https://redis.io/downloads/#redis-stack-downloads 

1. Mac OS: 14.6.1 (23G93)
2. Run redis-server with the following config file:

port 6379
daemonize no
loadmodule /Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/lib/rediscompat.so
loadmodule /Users/michaelmasouras/src/redis-stack-server-7.4.0-v1.monterey.arm64/lib/redisearch.so
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ./

Originally reported https://github.com/redis/redis/issues/13700

**Comment by meiravgri** [comment]
Hi, thanks for reporting
This is a known issue that was already fices in https://github.com/RediSearch/RediSearch/pull/5007
The fix will be available in the next redis-stack release.

**Comment by mmasouras** [comment]
Thank you. Any rough timeline for the next redis-stack release? You can close this ticket if you wish.

**Comment by meiravgri** [comment]
Mid January :)
