### ISSUE TITLE
Add support for 64bit integers

### ISSUE THREAD

**Issue by gkorland** [RediSearch/RediSearch#557]

**Comment by jameycai** [comment]
Thank you!   I usually convert the time to 13 bit milliseconds for storage.

I am using java UUID.randomUUID().getLeastSignificantBits() to generate a long numeric ID.

**Comment by jameycai** [comment]
In the next release, is this feature added?

**Comment by jameycai** [comment]
@gkorland @mnunberg  In the next release, is this feature added?

**Comment by jameycai** [comment]
@gkorland @mnunberg  Can you add this feature in the next version?

**Comment by jameycai** [comment]
@mnunberg  Can you add this feature in the next version?

**Comment by gkorland** [comment]
Duplicate #1080
