### ISSUE TITLE
Limitations total indexes

### ISSUE THREAD

**Issue by vlradstake** [RediSearch/RediSearch#592]
Hi, we are updating a application with 1 index, but we need +- 700 text fields.  Because there are only 128 text fields supported/recommended. We are exploring other options. Is it possible and recommended to create 700 indexes with 10 text fields? Thanks

**Comment by mnunberg** [comment]
Is it possible to restructure your application to split the fields over multiple documents? I am curious what the use case for 700 fields is!

**Comment by vlradstake** [comment]
So i will try to explain how the applications works:
- add 90.000 (items) hashes to redis with SADD
- add 90.000 (items) documents to redisearch index with FT.ADDHASH
- each item can add multiple fields to the index, 200 in the current index
- the index is used to filter the items
- we use FT.AGGREGATE to get and count the possibilities
- now we want to add more filter options (700+) because the items have a lot of different filter options. 

So not all the items use all filter possibilities but a few in the current structure it is possible to categorize the items.
- Lets say, 2000 items in a category with 10 filter options

**Comment by mnunberg** [comment]
In general each new index (currently) opens a thread for indexing, unless `SAFEMODE` is enabled. `SAFEMODE` shouldn't have much of a negative performance impact.
