### ISSUE TITLE
Allow FT.DEBUG to return the list of indexes already created

### ISSUE THREAD

**Issue by luistrigueiros** [RediSearch/RediSearch#622]
Hi,

I have been looking at the documentation for [RedisSearch module](https://oss.redislabs.com/redisearch/Commands.html#ftconfig) and I have not found a way to introspect the redis instance for a list of already created indexes.
Should this not be possible by issuing the FT.CONIFG may without any args ?

**Comment by luistrigueiros** [comment]
Sorry I just realized that I can use the : 

scan 0 match ft*

To achieve this

**Comment by MeirShpilraien** [comment]
We will add it using the FT.DEBUG command (changing the topic).

**Comment by luistrigueiros** [comment]
Hi @MeirShpilraien,

Thank you for thanking input onboard.
Additionaly I think that it would be handy to have command to dump and a given index creation schema.
This would dump out the one existing index schema for inspection.

Kindly
  Luis Oscar Trigueiros

**Comment by MeirShpilraien** [comment]
You can do it using FT.INFO <index name>

**Comment by kkmuffme** [comment]
This is available as FT._LIST in redisearch 2.0 now

**Comment by ashtul** [comment]
fixed by #1337
