### ISSUE TITLE
[enhancement] Log cause of query syntax error

### ISSUE THREAD

**Issue by mahemoff** [RediSearch/RediSearch#645]
Query syntax errors show up in logs as:

> <ft> Error parsing query: Syntax error at offset 9 near 'abc'

Would it be possible to also log the fully query that triggered it?

**Comment by gkorland** [comment]
We'll add more details in Debug level

**Comment by mnunberg** [comment]
The master branch won't log query failure details at all. This is something which should be handled at the application level. @mahemoff is the query failure showing up in the logs a useful feature for you?

**Comment by playerfm** [comment]
Don't know about others, but it's very useful to me as there are some boundary cases that can cause issues like this and it's hard to capture them on clients unless distributed logging is setup on all of them. Without the query logged, it means having to track down which client/app made the call and update it.

**Comment by mahemoff** [comment]
Don't know about others, but it's very useful to me as there are some boundary cases that can cause issues like this and it's hard to capture them on clients unless distributed logging is setup on all of them. Without the query logged, it means having to track down which client/app made the call and update it.
