### ISSUE TITLE
Use more specific error message when unknown FT.ALTER subcommand provided

### ISSUE THREAD

**Issue by jruaux** [RediSearch/RediSearch#649]
I'm using the latest from master branch. From redis-cli I cannot issue the FT.ALTER command:

```
127.0.0.1:6379> FT.ALTER beers newField NUMERIC SORTABLE
(error) Unknown command
```

**Comment by jruaux** [comment]
My bad, I was missing the SCHEMA ADD portion:
```
FT.ALTER beers SCHEMA ADD newField NUMERIC SORTABLE
```

**Comment by jruaux** [comment]
Could the error message be changed to something more specific?

**Comment by mnunberg** [comment]
Yes, let’s rename this bug
