### ISSUE TITLE
Cherry pick to master

### ISSUE THREAD

**Issue by MeirShpilraien** [RediSearch/RediSearch#657]
* [x] #656 
* [x] #659
* [x] #660
* [x] #677 
* [x] #683 
* [x] #696

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/65

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/659

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/660

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/677

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/683

**Comment by MeirShpilraien** [comment]
https://github.com/RedisLabsModules/RediSearch/pull/696

**Comment by mnunberg** [comment]
All issues have been reviewed and the relevant cherry-pick PRs have been made
