### ISSUE TITLE
how to update the document only if the doc exists

### ISSUE THREAD

**Issue by angrySmeagol** [RediSearch/RediSearch#658]
I used ft.add with REPLACE and optionally PARTIAL. But, when the document does not exists.
No mater what condition I set,  the document will add to the index.
Is there any way to update document only when the document exists?

**Comment by MeirShpilraien** [comment]
Currently its not possible, added to version 1.5.

**Comment by mnunberg** [comment]
I think we will implement this using the `NOCREATE` option. If present, REPLACE will not create the document if it does not already exist, but return an error
