### ISSUE TITLE
Remove the use of moduleRegisterApi

### ISSUE THREAD

**Issue by MeirShpilraien** [RediSearch/RediSearch#672]
Instead use the register api which was introduce in redis 5.0.4.
If the api does not exist continue without it.

**Comment by codegrau** [comment]
Would that solve issue https://github.com/RedisLabsModules/RediSearch/issues/671 regarding redisearch.so not loadable on FreeBSD (Undefined symbol "moduleRegisterApi") neither in Redis 4.0.14 nor 5.0.4?

**Comment by MeirShpilraien** [comment]
Yes it will probably solve it, till then you can try using v1.4.7 instead of master.
