### ISSUE TITLE
Add support for Geo Polygon query

### ISSUE THREAD

**Issue by gkorland** [RediSearch/RediSearch#680]

**Comment by gitcatrat** [comment]
Would be super nice to have. This is the only missing feature that blocks me from using RediSearch.

**Comment by ashtul** [comment]
@gitcatrat We don't have an exact timeline for releasing polygon support, but it is on our agenda.
It would be helpful if you could share your valuable thoughts, wishes, or suggestions on this feature.

**Comment by raiusa** [comment]
I am also evaluating RediSearch to use on enterprise level and need Geo Polygon capability to solve one of my use case. Do you have specific timeline for releasing polygon support ?

**Comment by alexander-schranz** [comment]
I'm little bit confused if this is implemented or not based on https://redis.io/docs/latest/develop/interact/search-and-query/query/geo-spatial/

I have documents with `GEO` type so LAT and LON where I have 2 queries the first one by distance which works. But the second one by a rectangle box which I tried to use Polygon but it seems like Polygon only part of `GEOSHAPE` but not `GEO` is that correct?

**Comment by oshadmi** [comment]
@alexander-schranz 
`GEOSHAPE` was introduced with [v2.8.4](https://github.com/RediSearch/RediSearch/releases/tag/v2.8.4)
And was slightly enhanced in [v2.10.5](https://github.com/RediSearch/RediSearch/releases/tag/v2.10.5)

You should use `GEOSHAPE` index field type, e.g.
```
... $['location'] AS location GEOSHAPE FLAT
```

And in the JSON document you should use `POINT` or `POLYGON`, e.g.,
```
JSON.SET <key> $.location '"POINT(48.8566 2.3522)"'
```

And then the `WITHIN` query would retrieve results.

**Comment by alexander-schranz** [comment]
@oshadmi Thx for the response, the Problem is GEOSHAPE can not be used for Distance query which is the other Filter I want to support on the same field.

**Comment by oshadmi** [comment]
@alexander-schranz Which distance function are you interested with? There are few options for distance between Polygons and Points

**Comment by oshadmi** [comment]
@adrianoamaral Please notice this enhancement request ☝🏼

**Comment by alexander-schranz** [comment]
We use the GEO field to store lng lat and support Radius search by lat lng distance and Bounding Box.

Radius seems supported by GEO field but not by GEOSHAPE, BoundingBox/Polygon only by GEOSHAPE. Would it not be possible to support Polygon for GEO field also as you can handle it like a GEOSHAPE point?
