### ISSUE TITLE
Make FORK_GC_RUN_INTERVAL settable by FT.CONFIG

### ISSUE THREAD

**Issue by tw-bert** [RediSearch/RediSearch#687]
_This is a spinoff from [here](https://github.com/RedisLabsModules/RediSearch/issues/684#issuecomment-489035424)._

**Feature request:**

It will help us tremendously if `FORK_GC_RUN_INTERVAL` can be set at runtime with [`FT.CONFIG`](https://oss.redislabs.com/redisearch/Commands.html#ftconfig).

_Context:_ Restarting a master is no small feat in a 24/7 multi-tier Redis environment. Even with proper H/A in place, stale data can't be prevented if dozens of GB's need to be (re-)distributed.

**Comment by MeirShpilraien** [comment]
@mnunberg I think we can add it to 1.6.0, what do you think?

**Comment by MeirShpilraien** [comment]
This one is less trivial then originally thought, it is possible to change this value at runtime but the new value will only take effect after the next GC run.
@tw-bert do you think it will be good enough?

**Comment by tw-bert** [comment]
@MeirShpilraien It would be a bit counter-intuitive IMHO, but it would be good enough for us. Thanks for looking into this.

**Comment by tw-bert** [comment]
Great
