### ISSUE TITLE
Crash on FT.SEARCH and FT.EXPLAIN

### ISSUE THREAD

**Issue by dinhha** [RediSearch/RediSearch#691]
I tried to search indexes with this query, but Redis server crashed. 
Redis Server version 5.0.4, 
RediSearch version 1.4.8
`FT.SEARCH events_indexes "((@title:Acting)|(@title:Architecture)|(@title:Arts)|(@title:Sports)|(@title:Drawing)|(@title:computer)) @endTime:[1557209247449 +inf]"`
But when I try to replace these words, it work pretty well:
- **Architecture** -> **Architect**
- **Sports** -> **Sport**
- **Arts** -> **Art**
<img width="1118" alt="Screen Shot 2019-05-07 at 1 55 38 PM" src="https://user-images.githubusercontent.com/4687651/57278083-d07e7380-70cf-11e9-8c60-0148947021db.png">
<img width="1128" alt="Screen Shot 2019-05-07 at 2 00 25 PM" src="https://user-images.githubusercontent.com/4687651/57278377-7f22b400-70d0-11e9-948d-9fd9102c0c53.png">

Same on FT.EXPLAIN and FT.EXPLAINCLI

This is log:
<pre><code>
=== REDIS BUG REPORT START: Cut & paste starting from here ===
49584:M 07 May 2019 13:58:55.343 # Redis 5.0.4 crashed by signal: 11
49584:M 07 May 2019 13:58:55.343 # Crashed running the instruction at: 0x10ba77f08
49584:M 07 May 2019 13:58:55.343 # Accessing address: 0x8
49584:M 07 May 2019 13:58:55.344 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
0   redisearch.so                       0x000000010ba77f08 UI_TesterFree + 40

Backtrace:
0   redis-server                        0x000000010b8921a0 logStackTrace + 110
1   redis-server                        0x000000010b892527 sigsegvHandler + 236
2   libsystem_platform.dylib            0x00007fff70054b5d _sigtramp + 29
3   ???                                 0x0000000000000000 0x0 + 0
4   redisearch.so                       0x000000010ba75c25 NewUnionIterator + 549
5   redisearch.so                       0x000000010ba84ff7 Query_EvalNode + 1191
6   redisearch.so                       0x000000010ba85480 QAST_Iterate + 64
7   redisearch.so                       0x000000010ba4047e AREQ_ApplyContext + 782
8   redisearch.so                       0x000000010ba3c8ed buildRequest + 301
9   redisearch.so                       0x000000010ba3c68d execCommandCommon + 109
10  redis-server                        0x000000010b8b6f41 RedisModuleCommandDispatcher + 91
11  redis-server                        0x000000010b854857 call + 223
12  redis-server                        0x000000010b8550dc processCommand + 1537
13  redis-server                        0x000000010b8617e1 processInputBuffer + 285
14  redis-server                        0x000000010b84ddff aeProcessEvents + 550
15  redis-server                        0x000000010b84e0ee aeMain + 43
16  redis-server                        0x000000010b857f6d main + 1377
17  libdyld.dylib                       0x00007fff6fe6f3d5 start + 1

------ INFO OUTPUT ------
# Server
redis_version:5.0.4
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:d4ba11298acbb366
redis_mode:standalone
os:Darwin 18.5.0 x86_64
arch_bits:64
multiplexing_api:kqueue
atomicvar_api:atomic-builtin
gcc_version:4.2.1
process_id:49584
run_id:3d1b151ea1059e329741861991bb2915665c13c3
tcp_port:6379
uptime_in_seconds:457
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:13708463
executable:/usr/local/opt/redis/bin/redis-server
config_file:/usr/local/etc/redis.conf

# Clients
connected_clients:1
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:5356832
used_memory_human:5.11M
used_memory_rss:5402624
used_memory_rss_human:5.15M
used_memory_peak:5356832
used_memory_peak_human:5.11M
used_memory_peak_perc:100.66%
used_memory_overhead:1283126
used_memory_startup:987824
used_memory_dataset:4073706
used_memory_dataset_perc:93.24%
allocator_allocated:5304672
allocator_active:5364736
allocator_resident:5364736
total_system_memory:8589934592
total_system_memory_human:8.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.01
allocator_frag_bytes:60064
allocator_rss_ratio:1.00
allocator_rss_bytes:0
rss_overhead_ratio:1.01
rss_overhead_bytes:37888
mem_fragmentation_ratio:1.02
mem_fragmentation_bytes:97952
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:49694
mem_aof_buffer:0
mem_allocator:libc
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:0
rdb_bgsave_in_progress:0
rdb_last_save_time:1557211878
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:-1
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:0
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:1
total_commands_processed:11
instantaneous_ops_per_sec:0
total_net_input_bytes:376
total_net_output_bytes:13447
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:46124
keyspace_misses:26
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:0
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:fba0ac0207ae7c77d81deb3dc14128f6f0a592e9
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.485660
used_cpu_user:1.698688
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats
cmdstat_command:calls=1,usec=1119,usec_per_call=1119.00
cmdstat_FT.SEARCH:calls=1,usec=40918,usec_per_call=40918.00
cmdstat_info:calls=3,usec=491,usec_per_call=163.67
cmdstat_hgetall:calls=6,usec=8,usec_per_call=1.33

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=4501,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=6965 addr=127.0.0.1:63149 fd=7 name= age=223 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=182 qbuf-free=32586 obl=0 oll=0 omem=0 events=r cmd=FT.SEARCH

------ CURRENT CLIENT INFO ------
id=6965 addr=127.0.0.1:63149 fd=7 name= age=223 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=182 qbuf-free=32586 obl=0 oll=0 omem=0 events=r cmd=FT.SEARCH
argv[0]: 'FT.SEARCH'
argv[1]: 'events_indexes'
argv[2]: '((@title:Acting)|(@title:Architecture)|(@title:Arts)|(@title:Sports)|(@title:Drawing)|(@title:computer)) @endTime:[1557209247449 +inf]'

------ REGISTERS ------
49584:M 07 May 2019 13:58:55.350 # 
RAX:00007f8b22d947a0 RBX:0000000000000000
RCX:00007f8b22d947a0 RDX:0000000000000946
RDI:0000000000000000 RSI:00007f8b22d947a0
RBP:00007ffee43b5860 RSP:00007ffee43b5850
R8 :00007f8b22d00000 R9 :0000000000000006
R10:0000000000000002 R11:000000000000001a
R12:000000010ba764c0 R13:00007f8b22d94690
R14:00007f8b22d94780 R15:0000000000000003
RIP:000000010ba77f08 EFL:0000000000010246
CS :000000000000002b FS:0000000000000000  GS:0000000000000000
49584:M 07 May 2019 13:58:55.350 # (00007ffee43b585f) -> 00007fff7001ca60
49584:M 07 May 2019 13:58:55.350 # (00007ffee43b585e) -> 00007ffee43b5920
49584:M 07 May 2019 13:58:55.351 # (00007ffee43b585d) -> 00007fff6feba129
49584:M 07 May 2019 13:58:55.351 # (00007ffee43b585c) -> 00007ffee43b5970
49584:M 07 May 2019 13:58:55.351 # (00007ffee43b585b) -> 000000010ba84ff7
49584:M 07 May 2019 13:58:55.351 # (00007ffee43b585a) -> 00007ffee43b5940
49584:M 07 May 2019 13:58:55.352 # (00007ffee43b5859) -> 00007f8b22d923f0
49584:M 07 May 2019 13:58:55.352 # (00007ffee43b5858) -> 00007f8b22d9234c
49584:M 07 May 2019 13:58:55.353 # (00007ffee43b5857) -> 00007ffee43b5958
49584:M 07 May 2019 13:58:55.354 # (00007ffee43b5856) -> 00007f8b22d922c0
49584:M 07 May 2019 13:58:55.355 # (00007ffee43b5855) -> 0000000000000000
49584:M 07 May 2019 13:58:55.355 # (00007ffee43b5854) -> 3ff0000000000000
49584:M 07 May 2019 13:58:55.356 # (00007ffee43b5853) -> 000000010ba75c25
49584:M 07 May 2019 13:58:55.357 # (00007ffee43b5852) -> 00007ffee43b58a0
49584:M 07 May 2019 13:58:55.357 # (00007ffee43b5851) -> 00007f8b22d92030
49584:M 07 May 2019 13:58:55.358 # (00007ffee43b5850) -> 0000000000000000

------ DUMPING CODE AROUND EIP ------
Symbol: UI_TesterFree (base: 0x10ba77ee0)
Module: /Users/apple/redisearch.so (base 0x10ba3a000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x10ba77ee0 -D -b binary -m i386:x86-64 /tmp/dump.bin
------
49584:M 07 May 2019 13:58:55.358 # dump of function (hexdump of 168 bytes):
554889e54156534989fe837f18007e2731db662e0f1f8400000000000f1f4000498b4610488b3cd8ff570848ffc3496346184839c37ce9498b7e10488d1dbe601900ff134c89f74889d85b415e5dff20554889e54157415653504989f64989ff31db662e0f1f8400000000000f1f4000498b4710b9000000004885c074038b48f489c94839cb7314488b3cd84c89f6ff1748ffc385c075d831c0eb05b8010000004883c4085b415e

=== REDIS BUG REPORT END. Make sure to include from START to END. ===
</code></pre>

**Comment by MeirShpilraien** [comment]
@dinhha are you sure you are using 1.4.8? I suspect you are using master.

**Comment by dinhha** [comment]
> @dinhha are you sure you are using 1.4.8? I suspect you are using master.

I tried using master already, same issue. Actually this issue only happen on my Mac OS, not Ubuntu

**Comment by MeirShpilraien** [comment]
@dinhha so its happened on master and not on 1.4.8? Cause I tried to reproduce in 1.4.8 and I couldn't.

**Comment by MeirShpilraien** [comment]
Ohh only on MAC, ok will try reproduce on MAC.

**Comment by itamarhaber** [comment]
Hello @dinhha 

It looks like we need more information, e.g. the schema and some of the data, to reproduce. On High Sierra, Redis 5.0.4 & RediSearch 1.4.8 this is what I get:

```
127.0.0.1:6379> FT.CREATE events_indexes SCHEMA title TEXT endTime NUMERIC
OK
127.0.0.1:6379> FT.ADD events_indexes 1 1 FIELDS title "computing" endTime 1557209247449
OK
127.0.0.1:6379> FT.ADD events_indexes 2 1 FIELDS title "hoarding" endTime 1557209247449
OK
127.0.0.1:6379> FT.SEARCH events_indexes "((@title:Acting)|(@title:Architecture)|(@title:Arts)|(@title:Sports)|(@title:Drawing)|(@title:computer)) @endTime:[1557209247449 +inf]"
1) (integer) 1
2) "1"
3) 1) "title"
   2) "computing"
   3) "endTime"
   4) "1557209247449"
```

**Comment by dinhha** [comment]
I've just try again on master, it didn't happen. Let's me watch then give more detail later. We can close this issue now
