### ISSUE TITLE
FT.AGGREGATE query crashed the docker container

### ISSUE THREAD

**Issue by elizabetht** [RediSearch/RediSearch#694]
Following were the commands issued to create index and add documents to a stand-alone redis container
```
127.0.0.1:6379> FT.CREATE myIndex SCHEMA fileName TEXT SORTABLE content TEXT SORTABLE docId TAG SORTABLE NOINDEX
OK
127.0.0.1:6379> FT.ADD myIndex doc1 1.0 FIELDS fileName file1 content "lorem ipsum" docId doc1
OK
127.0.0.1:6379> FT.ADD myIndex doc2 1.0 FIELDS fileName file2 content "lorem ipsum lorem ipsum" docId doc2
OK
127.0.0.1:6379> FT.ADD myIndex doc3 1.0 FIELDS fileName file3 content "lorem ipsum lorem ipsum lorem ipsum" docId doc3
OK
```
In an attempt to get the frequency of the search term, on issuing the following command (which could be possibly wrong), the redis container crashed. Even if a wrong command was issued, the container should not have crashed is the expectation.
FT.AGGREGATE command issued:
```
FT.AGGREGATE myIndex "lorem" GROUPBY 1 @content REDUCE COUNT_DISTINCT 1 @content as frequency SORTBY 2 @frequency DESC APPLY matched_terms() as count
```

Redis container crashed with the following logs:
```

=== REDIS BUG REPORT START: Cut & paste starting from here ===
1:M 08 May 2019 03:05:40.416 # Redis 5.0.4 crashed by signal: 11
1:M 08 May 2019 03:05:40.416 # Crashed running the instruction at: 0x7f8c0aac625b
1:M 08 May 2019 03:05:40.416 # Accessing address: (nil)
1:M 08 May 2019 03:05:40.416 # Failed assertion: <no assertion failed> (<no file>:0)
```

**Comment by MeirShpilraien** [comment]
@elizabetht what is the redisearch version?

**Comment by MeirShpilraien** [comment]
fixed on : https://github.com/RedisLabsModules/RediSearch/pull/696

**Comment by MeirShpilraien** [comment]
@elizabetht the fix is included in 1.4.9. Can I close this issue?

**Comment by elizabetht** [comment]
@MeirShpilraien I see that the container no longer crashes but I see no results come back for `count` in my query. Is that the expected behavior with `matched_terms`?

**Comment by MeirShpilraien** [comment]
This is because you apply the matched_terms after performing long aggregation pipe, the original record is no longer exists. We will document better how and where the APPLY function should be used.
