### ISSUE TITLE
Compilation [ 99%] Linking CXX executable apibench /bin/ld: cannot find -lredismock ../../libapi_stubs.a(api_stubs.c.o): In function `siphash':

### ISSUE THREAD

**Issue by sbilello** [RediSearch/RediSearch#695]
uname -a
`4.16.13-1.el7.elrepo.x86_64 #1 SMP Wed May 30 14:31:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux`

cmake version 3.14.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

g++ --version
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)

**Comment by mnunberg** [comment]
Hi, did you pull the latest master?

**Comment by sbilello** [comment]
Now it compiles! But the module does not work


Scanning dependencies of target test_args
>
> [100%] Building C object src/rmutil/CMakeFiles/test_args.dir/test_args.c.o
>
> [100%] Linking C executable test_args
>
> [100%] Built target test_args
>
> [root@qa-sergio-search-exporter-dos2-exporter-01 build]# redis-server
>> --loadmodule ./redisearch.so
>
>
>> *** FATAL CONFIG FILE ERROR ***
>
> Reading the configuration file, at line 2
>
> >>> 'loadmodule "./redisearch.so"'
>
> Bad directive or wrong number of arguments
>
> [root@qa-sergio-search-exporter-dos2-exporter-01 build]# ls
>
> CMakeCache.txt  CMakeFiles  cmake_install.cmake  libapi_stubs.a
>> libredisearchS.a  Makefile  redisearch.so  rmtest.config.default  src
>
> [root@qa-sergio-search-exporter-dos2-exporter-01 build]#
>
>

**Comment by mnunberg** [comment]
You need to remove the `--`  from the configuration directive if it’s in a file

**Comment by sbilello** [comment]
[root@qa-sergio-search-exporter-dos2-exporter-01 build]# redis-server
loadmodule redisearch.so
6524:C 09 May 19:13:37.574 # Fatal error, can't open config file
'loadmodule'
[root@qa-sergio-search-exporter-dos2-exporter-01 build]# redis-server
loadmodule ./redisearch.so

The -- it is reported in the official doc
https://oss.redislabs.com/redisearch/Quick_Start.html

**Comment by sbilello** [comment]
I tried with and withou ./ before redisearch

**Comment by sbilello** [comment]
[root@qa-sergio-search-exporter-dos2-exporter-01 build]# redis-server
--version
Redis server v=3.2.12 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64
build=7897e7d0e13773f
[root@qa-sergio-search-exporter-dos2-exporter-01 build]#

**Comment by mnunberg** [comment]
Ahh, your version of Redis does not support modules. You need version 4 or higher; I'd recommend at least 4.0.10

**Comment by sbilello** [comment]
Now it works
I followed this guide to install latest redis 5
https://computingforgeeks.com/how-to-install-latest-redis-on-centos-7/
However if I place in redis.conf
# Redis configuration file example.
#
# Note that in order to read the configuration file, Redis must be
# started with the file path as first argument:
#
# ./redis-server /path/to/redis.conf
loadmodule redisearch.so

and in
[root@qa-sergio-search-exporter-dos2-exporter-01 modules]# pwd
/usr/lib64/redis/modules
[root@qa-sergio-search-exporter-dos2-exporter-01 modules]# ls -lat
total 6312
drwxr-x---. 2 redis redis      27 May  9 19:25 .
drwxr-x---. 3 redis redis      21 May  9 19:19 ..
-rwxrwxrwx. 1 root  root  6460288 May  9 19:05 redisearch.so
[root@qa-sergio-search-exporter-dos2-exporter-01 modules]#

I add the module it does not work.
● redis.service - Redis persistent key-value database
   Loaded: loaded (/usr/lib/systemd/system/redis.service; enabled; vendor
preset: disabled)
  Drop-In: /etc/systemd/system/redis.service.d
           └─limit.conf
   Active: failed (Result: exit-code) since Thu 2019-05-09 19:28:04 UTC; 4s
ago
  Process: 8441 ExecStop=/usr/libexec/redis-shutdown (code=exited,
status=1/FAILURE)
  Process: 8436 ExecStart=/usr/bin/redis-server /etc/redis.conf
--supervised systemd (code=exited, status=1/FAILURE)
 Main PID: 8436 (code=exited, status=1/FAILURE)

May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]:
Starting Redis persistent key-value database...
May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]:
Started Redis persistent key-value database.
May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]:
redis.service: main process exited, code=exited, status=1/FAILURE
May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]:
redis.service: control process exited, code=exited status=1
May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]: Unit
redis.service entered failed state.
May 09 19:28:04 qa-sergio-search-exporter-dos2-exporter-01 systemd[1]:
redis.service failed.
[root@qa-sergio-search-exporter-dos2-exporter-01 modules]#

It works only with
[root@qa-sergio-search-exporter-dos2-exporter-01 build]# redis-server
--loadmodule /usr/lib64/redis/modules/redisearch.so
8697:C 09 May 2019 19:30:00.803 # oO0OoO0OoO0Oo Redis is starting
oO0OoO0OoO0Oo
8697:C 09 May 2019 19:30:00.803 # Redis version=5.0.4, bits=64,
commit=00000000, modified=0, pid=8697, just started
8697:C 09 May 2019 19:30:00.803 # Configuration loaded
8697:M 09 May 2019 19:30:00.804 * Increased maximum number of open files to
10032 (it was originally set to 1024).
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 8697
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

8697:M 09 May 2019 19:30:00.804 # WARNING: The TCP backlog setting of 511
cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower
value of 128.
8697:M 09 May 2019 19:30:00.804 # Server initialized
8697:M 09 May 2019 19:30:00.804 # WARNING overcommit_memory is set to 0!
Background save may fail under low memory condition. To fix this issue add
'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the
command 'sysctl vm.overcommit_memory=1' for this to take effect.
8697:M 09 May 2019 19:30:00.805 * <ft> Low level api version 1 initialized
successfully
8697:M 09 May 2019 19:30:00.805 * <ft> RediSearch version 1.99.1
(Git=v1.4.2-345-ga1e7550)
8697:M 09 May 2019 19:30:00.805 * <ft> concurrency: ON, gc: ON, prefix min
length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout
policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max
doctable size: 1000000, search pool size: 20, index pool size: 8,
8697:M 09 May 2019 19:30:00.808 * <ft> Initialized thread pool!
8697:M 09 May 2019 19:30:00.808 * Module 'ft' loaded from
/usr/lib64/redis/modules/redisearch.so
8697:M 09 May 2019 19:30:00.808 * Ready to accept connections

**Comment by mnunberg** [comment]
You need to provide an absolute path for the module

**Comment by sbilello** [comment]
I gave an absolute path and full permissions
[root@qa-sergio-search-exporter-dos2-exporter-01 sergio.bilello]# ls -lat
/srv/exporter/redisearch.so
-rwxrwxrwx. 1 root root 6460288 May  9 19:05 /srv/exporter/redisearch.so
[root@qa-sergio-search-exporter-dos2-exporter-01 sergio.bilello]#
and I got this
13557:M 09 May 2019 20:07:23.880 # WARNING: The TCP backlog setting of 511
cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower
value of 128.
13557:M 09 May 2019 20:07:23.880 # Server initialized
13557:M 09 May 2019 20:07:23.881 # WARNING overcommit_memory is set to 0!
Background save may fail under low memory condition. To fix this issue add
'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the
command 'sysctl vm.overcommit_memory=1' for this to take effect.
13557:M 09 May 2019 20:07:23.881 # Module /srv/exporter/redisearch.so
failed to load: /srv/exporter/redisearch.so: cannot open shared object
file: Permission denied
13557:M 09 May 2019 20:07:23.881 # Can't load module from
/srv/exporter/redisearch.so: server aborting

**Comment by mnunberg** [comment]
If you run with loadmodule on the commandline, does it work? It’s possible srv is mounted with the noexec option

**Comment by sbilello** [comment]
Yes it works from the command line.
I tried to load it from the same path that I load from the command line.

**Comment by sbilello** [comment]
It does not work from systemctl start redis.
However I am working for an hackaton project so I am letting it work with a
dirty redis-server --loadmode /mypath/redisearch.so & and it works
I am curious how it works the persistence of this thing if I set a key and
get it and restart the server I lost the key saved. I issued the command
from the redis-cli
Thanks for your help and the fix on the compilation saved my hack prototype

**Comment by mnunberg** [comment]
With persistence in Redis, you have two options; you can either use rdb persistence in which your data is manually or periodically saved, or you can use aof persistence. RDB lets you do snapshots, while AOF allows more periodic saves. There’s plenty of material on google regarding how to use redis with persistence, and the pros and cons of rdb and aof.

**Comment by mnunberg** [comment]
I'm closing this issue, please open a new issue or write to our mailing list for more questions :)
