### ISSUE TITLE
Free gc (and possibly other) internals asynchronously

### ISSUE THREAD

**Issue by mnunberg** [RediSearch/RediSearch#700]
If we drop the index while being in middle of a gc sweep, we risk having the gc free itself. When the gc resumes, it will be accessing uninitialized memory.

**Comment by MeirShpilraien** [comment]
- [ ] add this fix to 1.4

**Comment by MeirShpilraien** [comment]
this already fixed on 1.4.3-tip branch, make sure its also fixed on master.

**Comment by gkorland** [comment]
@MeirShpilraien fixed in 1.6?

**Comment by MeirShpilraien** [comment]
yes
