### ISSUE TITLE
Not able to get equal value of field.

### ISSUE THREAD

**Issue by Hvishal88** [RediSearch/RediSearch#703]
I am not able to get the exact number of documents while doing FT.SEARCH.

is there any way to get it?

For e.g;
consider I have a schema with EmpName as text.
And having values like.

Vishal
Vishal Patel
Bob
Charls

out of them, I want exact match of "Vishal" and the result count should be 1 only.
I have tried 

**FT.SEARCH MyIdx @EmpName:"Vishal"**
But it's giving 2 records. (records which contain a word "Vishal")

Can anybody provide the solution for that?

**Comment by MeirShpilraien** [comment]
You should consider using TAGS instead of TEXT. TAGS are not tokenized which means that if you have two value `Vishal` and `Vishal Patel` and you search for `Vishal` you will not get `Vishal Patel`.

Hope I understood you question correctly.

**Comment by Hvishal88** [comment]
> 
> 
> You should consider using TAGS instead of TEXT. TAGS are not tokenized which means that if you have two value `Vishal` and `Vishal Patel` and you search for `Vishal` you will not get `Vishal Patel`.
> 
> Hope I understood you question correctly.

Hi MeirShailraien 
It is working as per requirement using TAG. Thanks for your comments.

**Comment by mstaack** [comment]
@MeirShpilraien given i have a record with `name` and i want it to be fully searchable (type text) and also have the possibility to have an exact match (type tag) do i have to duplicate the attribute?
so adding a TAG and a TEXT attribute?

or is there something better?

thanks

**Comment by MeirShpilraien** [comment]
Currently I do not see any other way. We might add in the future the ability to do exact match of TEXT but currently its not possible (notice that even if we do it, it will probably be much less efficient then using tags).

**Comment by mnunberg** [comment]
I am guessing that _maybe_ (and just _maybe_) it could be possible with a filter expression using aggregation. It would be very slow of course, but might work for a one-off.

**Comment by mstaack** [comment]
thanks for your info!
so if you want sql like `where name = "foobar"`   name needs to be a TAG field.
