### ISSUE TITLE
return arbitrary fields from documents

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#704]
(see discussion: https://groups.google.com/forum/#!topic/redisearch/gDcuiVrQICo)

I am asking RS to return specific fields from my documents, but I get this error back:

127.0.0.1:6379> "FT.SEARCH" "il1" "@tags:{w\\:couchride}" "LIMIT" "0" "1" "RETURN" "1" "did"
(error) Property 'did' not loaded or in schema

If I ommit the RETURN clause, I get the entire document back:
127.0.0.1:6379> "FT.SEARCH" "il1" "@tags:{w\\:couchride}" "LIMIT" "0" "1"

1) (integer) 124197
2) "p:513944"
3)  1) ctitle
    2) "2005 Kawasaki Ninja ZX 6R"
    ....
   15) did
   16) "cf:d:420"
etc....

It would be helpful if RS could return any field that exists in the document, whether it's indexed or not.

**Comment by MeirShpilraien** [comment]
@mmasouras which redisearch version are you using?

I just tried it on 1.4.9 and its looks like it working:
```
127.0.0.1:6379> FT.CREATE idx SCHEMA test TEXT SORTABLE test1 TEXT NOINDEX
OK
127.0.0.1:6379> ft.add idx doc1 1.0 FIELDS test foo test1 bar
OK
127.0.0.1:6379> FT.SEARCH idx doo
1) (integer) 0
127.0.0.1:6379> FT.SEARCH idx foo
1) (integer) 1
2) "doc1"
3) 1) "test"
   2) "foo"
   3) "test1"
   4) "bar"
127.0.0.1:6379> FT.SEARCH idx foo RETURN 1 test1
1) (integer) 1
2) "doc1"
3) 1) "test1"
   2) "bar"
```

I also tried it without even declaring test1 in the schema and it works.

**Comment by mnunberg** [comment]
Meir, it doesn’t work in master; this is by design, but we might need to change this. In theory we shouldn’t be required to return fields not known to RS.

**Comment by mmasouras** [comment]
Can you clarify what is the functionality after this change?
1. Can I retrieve a field that is not declared in the schema
2. What happens if I omit the RETURN clause, do I get the whole hash as is the current behavior?

Thank you!

Also maybe add these clarifications here:
https://oss.redislabs.com/redisearch/Commands.html#ftsearch

**Comment by mnunberg** [comment]
1. Yes
2. Yes
