### ISSUE TITLE
INFIELDS keyword with FT.AGGREGATE

### ISSUE THREAD

**Issue by Nomafin** [RediSearch/RediSearch#723]
Is it possible to run an FT.AGGREGATE query so that the search only applies to certain fields like you can with FT.SEARCH and INFIELDS keyword? I have a usecase where I run FT.SEARCH into several fields and display the results to end user, and also would like to show the total number of results by content type which I've achieved by doing another query with FT.AGGREGATE. In some cases that would yield wrong results because the search targets all fields then, not only the ones I want to.

**Comment by mnunberg** [comment]
INFIELDS is the old way to search for items in specific fields. You can use the query mini-language, e.g. @(field1|field2|field3):”hello world”

**Comment by Nomafin** [comment]
So how would a full query go then?

```FT.SEARCH my_index "@(title|content):"foo bar" @another_field:something"```

is a syntax error.

**Comment by Nomafin** [comment]
I can't actually get it to work with pretty much any variation I can think of. Very simple

```FT.SEARCH my_index "@(title|content):foobar"``` gives a syntax error as well. I'm running RediSearch 1.4.10.

**Comment by mnunberg** [comment]
Huh, I don't know where I got that syntax from! The magic syntax is:

```
@title|content:(foobar)
```

**Comment by mnunberg** [comment]
In any event, the upcoming 1.6 version should allow you to use `INFIELDS` in `FT.AGGREGATE`
