### ISSUE TITLE
Add ALIAS change move alias from index to another index

### ISSUE THREAD

**Issue by gkorland** [RediSearch/RediSearch#724]
Current behavior should be changed:
```
127.0.0.1:6379>  FT.ALTER myIdx ALIAS ADD bb
OK
127.0.0.1:6379>  FT.CREATE myIdx1 SCHEMA title TEXT WEIGHT 5.0 body TEXT url TEXT
OK
127.0.0.1:6379>  FT.ALTER myIdx1 ALIAS ADD bb
(error) Alias already exists
```

**Comment by mnunberg** [comment]
You need to use `ALIAS DEL` and then `ALIAS ADD` in such a scenario.

**Comment by mnunberg** [comment]
Another thing we can do is add another command such as `ALIAS SWAP` or `ALIAS MOVE` or whatever.

**Comment by gkorland** [comment]
FT.ALIASADD bb myIdx1
FT.ALIASDEL bb 
FT.ALIASUPDATE bb myIdx2

FT.ALIASDUMP
FT.ALIASGET bb
