### ISSUE TITLE
search on specific field return 0

### ISSUE THREAD

**Issue by trimbilrepo** [RediSearch/RediSearch#725]
I create index 
```
127.0.0.1:6379> FT.CREATE products SCHEMA name TEXT price NUMERIC
OK
```

add 2 item
```
127.0.0.1:6379> FT.ADD products prod1 1.0 FIELDS name "it just regular product 1 with some price tag" price 5000
OK
127.0.0.1:6379> FT.ADD products prod2 1.0 FIELDS name "name of product 2" price 75000
OK
```
tried to search with keyword "some"
```
FT.SEARCH products some
1) (integer) 1
2) "prod1"
3) 1) name
   2) "it just regular product 1 with some price tag"
   3) price
   4) "5000"
```
it success. But if I tried to search item with price 5000
```
127.0.0.1:6379> FT.SEARCH products @price:5000
1) (integer) 0

127.0.0.1:6379> FT.SEARCH products "@price:5000"
1) (integer) 0
```
it return 0. I tried also using INFIELDS
```
127.0.0.1:6379> FT.SEARCH products 5000 INFIELDS 1 price
1) (integer) 0
```
could somebody help me, how to search based on field properly

thanks

**Comment by mnunberg** [comment]
For a numeric search you need to specify a range:

@price:[5000 5000]

**Comment by trimbilrepo** [comment]
Thank you.
`127.0.0.1:6379> FT.SEARCH products "@price:[5000 75000]"
1) (integer) 2
2) "prod2"
3) 1) name
   2) "name of product 2"
   3) price
   4) "75000"
4) "prod1"
5) 1) name
   2) "it just regular product 1 with some price tag"
   3) price
   4) "5000"`

**Comment by Ankit7991** [comment]
I am having this issue on above example. (Error: **(error) elem.map is not a function**)

> 127.0.0.1:6379> FT.CREATE products SCHEMA name TEXT price NUMERIC
OK

> 127.0.0.1:6379> FT.ADD products prod1 1.0 FIELDS name "it just regular product 1 with some price tag" price 5000
OK

> 127.0.0.1:6379> FT.ADD products prod2 1.0 FIELDS name "name of product 2" price 75000
OK

> 127.0.0.1:6379> FT.SEARCH products "@price:[5000 75000]"
**(error) elem.map is not a function**

> 127.0.0.1:6379> FT._LIST
1 ) products


I am using docker to run redis-stack. And using form there. (https://redis.io/docs/stack/get-started/install/docker/)
- Checked with both docker instancec  (1. redis/redis-stack-server, 2. redis/redis-stack). **Same issue there as well**
