### ISSUE TITLE
Allow FT.SEARCH ... SORTBY to accept multiple fields

### ISSUE THREAD

**Issue by hzdx200** [RediSearch/RediSearch#733]
i use the docker images in github page. the version is 1.4.10
docker run -p 6379:6379 redislabs/redisearch:latest
then, do these commands;
 1. FT.CREATE user_test3 SCHEMA username TEXT SORTABLE  age NUMERIC SORTABLE height NUMERIC SORTABLE 

2. FT.ADD user_test3 doc 1.0 FIELDS username "lilei" age 27 height 1.3
    FT.ADD user_test3 doc1 1.0 FIELDS username "lilei" age 27 height 1.4
    FT.ADD user_test3 doc2 1.0 FIELDS username "lilei" age 28 height 1.3
3. FT.SEARCH user_test3 "lilei" SORTBY height ASC  SORTBY age DESC
1) (integer) 3
2) "doc2"
3) 1) age
   2) "28"
   3) username
   4) "lilei"
   5) height
   6) "1.3"
4) "doc1"
5) 1) age
   2) "27"
   3) username
   4) "lilei"
   5) height
   6) "1.4"   <----  
6) "doc"
7) 1) age
   2) "27"
   3) username
   4) "lilei"
   5) height
   6) "1.3"        <----

**Comment by hzdx200** [comment]
so, the height doesn't work as “ASC”, it seems that "SORTBY height ASC" doesn't work.

**Comment by mnunberg** [comment]
You need to use FT.AGGREGATE instead, which allows for multiple SORTBY fields. We may allow more than 1 field in future versions for FT.SEARCH

**Comment by btzsoft** [comment]
Hi, Any plans on adding this feature for `FT.SEARCH` ? Thx.

**Comment by ashtul** [comment]
related #1615
