### ISSUE TITLE
Module crashes with a long query

### ISSUE THREAD

**Issue by shkediy** [RediSearch/RediSearch#738]
When running a request that contains a long query, the server crashes.
This is the stack trace:
=== REDIS BUG REPORT START: Cut & paste starting from here ===
5718:M 25 Jun 2019 14:04:16.488 # Redis 5.0.5 crashed by signal: 11
5718:M 25 Jun 2019 14:04:16.488 # Crashed running the instruction at: 0x7fd388a2ecdf
5718:M 25 Jun 2019 14:04:16.488 # Accessing address: 0xfffffffffffffff4
5718:M 25 Jun 2019 14:04:16.488 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
../../modules/RediSearch-1.6.0/build/redisearch.so(+0x67cdf)[0x7fd388a2ecdf]

Backtrace:
./redis-server *:6379(logStackTrace+0x45)[0x473ed5]
./redis-server *:6379(sigsegvHandler+0xb9)[0x474699]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x11390)[0x7fd38b20e390]
../../modules/RediSearch-1.6.0/build/redisearch.so(+0x67cdf)[0x7fd388a2ecdf]
../../modules/RediSearch-1.6.0/build/redisearch.so(NewUnionIterator+0x1a6)[0x7fd388a2fd66]
../../modules/RediSearch-1.6.0/build/redisearch.so(Query_EvalNode+0x3b4)[0x7fd388a377c4]
../../modules/RediSearch-1.6.0/build/redisearch.so(Query_EvalNode+0x432)[0x7fd388a37842]
../../modules/RediSearch-1.6.0/build/redisearch.so(QAST_Iterate+0x58)[0x7fd388a37e38]
../../modules/RediSearch-1.6.0/build/redisearch.so(AREQ_ApplyContext+0x331)[0x7fd388a3e901]
../../modules/RediSearch-1.6.0/build/redisearch.so(+0x71a58)[0x7fd388a38a58]
../../modules/RediSearch-1.6.0/build/redisearch.so(+0x723a7)[0x7fd388a393a7]
./redis-server *:6379(RedisModuleCommandDispatcher+0x56)[0x4a0426]
./redis-server *:6379(call+0xaf)[0x43004f]
./redis-server *:6379(processCommand+0x377)[0x430717]
./redis-server *:6379(processInputBuffer+0x175)[0x440b55]
./redis-server *:6379(aeProcessEvents+0x36d)[0x429cdd]
./redis-server *:6379(aeMain+0x2b)[0x429f0b]
./redis-server *:6379(main+0x4ae)[0x426abe]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fd38ae53830]
./redis-server *:6379(_start+0x29)[0x426d29]

To reproduce:

- Extract the attached zip file to the server.

- Run ./create_sales.sh localhost 6379

- Run the following query:

```
FT.SEARCH sales "@CUSTOMERNAME:('Royale Belge'|'Bavarian Collectables Imports, Co.'|'Australian Collectables, Ltd'|'Rovelli Gifts'|'Norway Gifts By Mail, Co.'|'Mini Caravy'|'Iberia Gift Imports, Corp.'|'Heintze Collectables'|'AV Stores, Co.'|'CAF Imports'|'Clover Collections, Co.'|'Suominen Souveniers'|'Blauer See Auto, Co.'|'L'ordine Souveniers'|'Vida Sport, Ltd'|'Toms Spezialitten, Ltd'|'Marseille Mini Autos'|'Cruz & Sons Co.'|'Handji Gifts& Co'|'Mini Auto Werke'|'La Corne D'abondance, Co.'|'Oulu Toy Supplies, Inc.'|'giftsbymail.co.uk'|'Royal Canadian Collectables, Ltd.'|'Petit Auto'|'Enaco Distributors'|'Double Decker Gift Stores, Ltd'|'Alpha Cognac'|'Stylish Desk Decors, Co.'|'Danish Wholesale Imports'|'Atelier graphique'|'Osaka Souveniers Co.'|'Quebec Home Shopping Network'|'Anna's Decorations, Ltd'|'Auto Assoc. & Cie.'|'Scandinavian Gift Ideas'|'Amica Models & Co.'|'Tokyo Collectables, Ltd'|'Canadian Gift Exchange Network'|'Saveley & Henriot, Co.'|'Australian Gift Network, Co'|'Dragon Souveniers, Ltd.'|'Corrida Auto Replicas, Ltd'|'Volvo Model Replicas, Co'|'Euro Shopping Channel'|'UK Collectables, Ltd.'|'Souveniers And Things Co.'|'Salzburg Collectables'|'Baane Mini Imports'|'Toys of Finland, Co.'|'La Rochelle Gifts'|'Australian Collectors, Co.'|'Auto Canal Petit'|'Herkku Gifts'|'Daedalus Designs Imports'|'Lyon Souveniers'|'Reims Collectables')" RETURN 2 ORDERNUMBER CUSTOMERNAME
```
[sales_data.zip](https://github.com/RediSearch/RediSearch/files/3325654/sales_data.zip)

**Comment by dme-development** [comment]
We are having the exact same issue with the version form master branch. If needed, I can also provide our full stack trace.

**Comment by mnunberg** [comment]
@dme-development I've just pushed a fix for this issue.

**Comment by jsp123** [comment]
l
