### ISSUE TITLE
Exact search giving wrong results

### ISSUE THREAD

**Issue by dme-development** [RediSearch/RediSearch#742]
We are having some inconsitent results when performing exact searches. This behavior is seen on v1.4.8 & v1.4.11. I was not able to test on master/v1.6

Example:
```
FT.SEARCH "idxCachedAuctionItem" "@CleanModel:\"C4\"" RETURN 1 CleanModel LIMIT 0 99

56) "CAI:3519935"
 57) 1) "CleanModel"
     2) "C4"
 58) "CAI:3519644"
 59) 1) "CleanModel"
     2) "C4"
 60) "CAI:3538001"
 61) 1) "CleanModel"
     2) "Picasso"
 62) "CAI:3534279"
 63) 1) "CleanModel"
     2) "Picasso"
 64) "CAI:3529819"
 65) 1) "CleanModel"
     2) "Picasso"
 66) "CAI:3529816"
 67) 1) "CleanModel"
     2) "Picasso"
```

"Picasso" should not be in the results when searching for "C4".

Same when searching some other values:
```
FT.SEARCH "idxCachedAuctionItem" "@CleanModel:(\"2 Series\")" RETURN 1 CleanModel LIMIT 0 99
192) "CAI:3520137"
193) 1) "CleanModel"
     2) "2 Series"
194) "CAI:3526340"
195) 1) "CleanModel"
     2) "2 Series"
196) "CAI:3532200"
197) 1) "CleanModel"
     2) "3 Series"
```

- "3 Series" should not be in the results when searching for "2 Series".
- We have 273 "3 Series" in Redis so it is strange that this command would return 1.
- Also when searching exact for "3 Series", no wrong results are returned.

Another issue - might not be related to the two above - is the following example:

```
FT.SEARCH "idxCachedAuctionItem" "@CleanModel:\"C\"" RETURN 1 CleanModel LIMIT 0 99

16) "CAI:3534522"
 17) 1) "CleanModel"
     2) "C"
 18) "CAI:3534516"
 19) 1) "CleanModel"
     2) "C-max"
 20) "CAI:3534530"
 21) 1) "CleanModel"
     2) "C"
```

We do not want model "C-max" showing up in the results when searching exact for model "C"

**Comment by mnunberg** [comment]
Was the document somehow modified outside of RediSearch?

**Comment by dme-development** [comment]
No, that is impossible. I believe the documents we are querying now didn't have any updates. And else, we update our document always through the RediSearch commands.

**Comment by mnunberg** [comment]
One more thing.. the quoting here looks a bit off

**Comment by dme-development** [comment]
Yes, the quotes for the exact search are escaped when I execute them, but I guess they got transformed by pasting it here. I don't think that is the issue.

**Comment by mnunberg** [comment]
I edited your post so that it appears in code blocks (i.e. triple-backtick). As far as C-max is concerned, RediSearch considers the `-` to be a word separator, and thus when you index the term `C-max`, it is actually indexed as two terms; `C` and `max`. You can avoid this by escaping the term when indexing (i.e. `C\-max`); however a known limitation is that the `\\` now remains in your document (it is not "ignored" by search).

**Comment by dme-development** [comment]
Ok, for the C-max, I can escape the values on index and on query. I will give it a try on Monday.

For the index, we use StackEchange.Redis lib to create the index and the only flag we provide is DisableStopWords. This results in STOPWORDS 0. Could this be related? For the rest, it should use the default values. Is there any command so I can verify the existing index and list the options/parameters? I don't see it in the FT.INFO command.

I guess you can use our previous rdb to debug or let me know if you want me to send a new one.

**Comment by MeirShpilraien** [comment]
@dme-development if you can send an rdb that reproduce this issue it will be great, thanks.

**Comment by dme-development** [comment]
@mnunberg @MeirShpilraien it should be in your mailbox now.

**Comment by MeirShpilraien** [comment]
@dme-development any chance you know how to reproduce the rdb? If you repopulate the data is it still the end result?

**Comment by MeirShpilraien** [comment]
@dme-development I think @mnunberg is right. I check the inverted index and it do not contains the `Index_StoreFieldFlags`, which means that it does not contains information about in which field in the document the terms appear. So when you search for C4 it will return documents that contains C4 in any field (and not only the specified field).

**Comment by dme-development** [comment]
Thanks for investigating @MeirShpilraien. 

I did a little research in the code of StackExchange.Redis & NRediSearch and it seems that by passing the DisableStopWords flag, the default values are not used and thus the NOFIELDS parameter is set. I will try passing the KeepFieldFlags explicitly and rebuild & repopulate the index. I will let you know this afternoon.

**Comment by dme-development** [comment]
@MeirShpilraien @mnunberg your suggestion seems to be correct. I recreated the index with the correct flags and results are fine now. Thanks for helping us out. Don't think I would ever have found this on my own. 
Closing this ticket...
