### ISSUE TITLE
Problem using FT.CREATE command with PHP whereas works in CMD

### ISSUE THREAD

**Issue by ashish200025** [RediSearch/RediSearch#784]
Below is my command which works correct in CMD:
FT.CREATE paras SCHEMA name TEXT SORTABLE age NUMERIC SORTABLE myTag TAG SORTABLE

but when i try to do it with PHP like below:
$redis->rawCommand( 'FT.CREATE', "INDEXNAME SCHEMA name TEXT SORTABLE age NUMERIC SORTABLE myTag TAG SORTABLE");

then it always returns false. where as FT.INFO works correctly in PHP like below:
$redis->rawCommand('FT.INFO', 'INDEXNAME'); // here INDEXNAME added using CMD that's why we can use it in PHP.

also, when i put any example command( e.g. 'Tester') then it does not give error in PHP where as CMD gives error for it that command does not exists.

**Comment by mnunberg** [comment]
according to the [documentation](https://github.com/phpredis/phpredis#example-106) `rawCommand` takes a variadic list of arguments. It looks like you are sending `INDEXNAME SCHEMA name TEXT`... etc. as a single argument.
