### ISSUE TITLE
Incorrect result when searching for fields containing special char using '|' for union 

### ISSUE THREAD

**Issue by manoj-jayaraman** [RediSearch/RediSearch#812]
I am trying to perform search for multiple words using '|' on a field . When I tried to perform the search I am getting incorrect result.  Find below the statements executed.  Getting proper result only if the value for the field doesn't contain "--" (result of 1st search command).
If I replace the "--" with "*" to perform wild card search, I am getting result only for the last search text provided the in the query .

```
FT.CREATE idx SCHEMA title TEXT SORTABLE NOSTEM bookid NUMERIC SORTABLE version NUMERIC SORTABLE price NUMERIC SORTABLE 
FT.ADD idx doc1 1.0 FIELDS title "book--1" bookid 100 version 0 price 1000
FT.ADD idx doc2 1.0 FIELDS title "book--1" bookid 100 version 1 price 1001
FT.ADD idx doc3 1.0 FIELDS title "book--1" bookid 100 version 2 price 1002
FT.ADD idx doc4 1.0 FIELDS title "book--2" bookid 200 version 0 price 2000
FT.ADD idx doc5 1.0 FIELDS title "book--2" bookid 200 version 1 price 2001
FT.ADD idx doc6 1.0 FIELDS title "book--3" bookid 300 version 1 price 3002
FT.ADD idx doc7 1.0 FIELDS title "book--3" bookid 300 version 2 price 3003
FT.ADD idx doc8 1.0 FIELDS title "book1" bookid 100 version 10 price 10010
FT.ADD idx doc9 1.0 FIELDS title "book3" bookid 300 version 1 price 30031

**127.0.0.1:6379> FT.SEARCH "idx" "@title:'book1'|'book3'"**
1) (integer) 2
2) "doc9"
3) 1) title
   2) "book1"
   3) bookid
   4) "100"
   5) version
   6) "10"
   7) price
   8) "10010"
4) "doc8"
5) 1) title
   2) "book3"
   3) bookid
   4) "300"
   5) version
   6) "1"
   7) price
   8) "30031"

```
added extra space between " * " to avoid formatting in the below command

```
**127.0.0.1:6379> FT.SEARCH "idx" "@title:(book * 1|book * 3)"**
1) (integer) 2
2) "doc7"
3) 1) title
   2) "book--3"
   3) bookid
   4) "300"
   5) version
   6) "2"
   7) price
   8) "3003"
4) "doc6"
5) 1) title
   2) "book--3"
   3) bookid
   4) "300"
   5) version
   6) "1"
   7) price
   8) "3002"
**127.0.0.1:6379> FT.SEARCH "idx" "@title:('book--1'|'book--3')"**
1) (integer) 0
```

**Comment by gkorland** [comment]
@manoj-jayaraman thanks for reporting the issue, can you please mark the version you're using?

**Comment by manoj-jayaraman** [comment]
> @manoj-jayaraman thanks for reporting the issue, can you please mark the version you're using?
@gkorland find below the version details

127.0.0.1:6379> MODULE LIST
1) 1) "name"
   2) "ft"
   3) "ver"
   4) (integer) 10600

**Comment by mnunberg** [comment]
@manoj-jayaraman I'll look at this later; but I would suggest you look (and maybe paste) the output of `FT.EXPLAIN` (or `FT.EXPLAINCLI`) of your query. This will show you how your query is actually parsed.

**Comment by manoj-jayaraman** [comment]
@mnunberg Find below the explain plan for all the 3 commands. 

127.0.0.1:6379> FT.EXPLAINCLI "idx" "@title:'book1'|'book3'"
 1) @title:UNION {
 2)   @title:UNION {
 3)     @title:book1
 4)     @title:+book1(expanded)
 5)   }
 6)   @title:UNION {
 7)     @title:book3
 8)     @title:+book3(expanded)
 9)   }
10) }
11)
127.0.0.1:6379> FT.EXPLAINCLI "idx" "@title:(book * 1|book * 3)"
 1) @title:INTERSECT {
 2)   @title:PREFIX{book * }
 3)   @title:UNION {
 4)     @title:UNION {
 5)       @title:1
 6)       @title:+1(expanded)
 7)     }
 8)     @title:PREFIX{book * }
 9)   }
10)   @title:UNION {
11)     @title:3
12)     @title:+3(expanded)
13)   }
14) }
15)
127.0.0.1:6379> FT.EXPLAINCLI "idx" "@title:('book--1'|'book--3')"
 1) @title:INTERSECT {
 2)   @title:UNION {
 3)     @title:book
 4)     @title:+book(expanded)
 5)   }
 6)   @title:NOT{
 7)     @title:UNION {
 8)       @title:-1
 9)       @title:book
10)     }
11)   }
12)   @title:NOT{
13)     @title:-3
14)   }
15) }
16)

**Comment by manoj-jayaraman** [comment]
Tried using the FILTER clause to select the title with "--" in FT.AGGREGATE and it resulted in the correct result. Find below the execution details
127.0.0.1:6379> FT.AGGREGATE "idx" "@title:book*" GROUPBY 2 @title @bookid REDUCE MAX 1 @price FILTER "@title == 'book--1' || @title=='book--3'"
1) (integer) 5
2) 1) title
   2) "book--3"
   3) bookid
   4) "300"
   5) _g0_maxprice
   6) "3003"
3) 1) title
   2) "book--1"
   3) bookid
   4) "100"
   5) _g0_maxprice
   6) "1002"
127.0.0.1:6379> FT.EXPLAINCLI "idx" "@title:book*" GROUPBY 2 @title @bookid REDUCE MAX 1 @price FILTER "@title == 'book--1' || @title=='book--3'"
1) @title:PREFIX{book*}
2)

**Comment by mnunberg** [comment]
So if you see the explain output from before, the `book*1` or `book*3` doesn't do what you think it does.

Maybe it will work if, while indexing, you do `book\-\-1`, otherwise it will tokenize as `book`, `1`, and likewise do `book\-\-1` in `FT.SEARCH`. Note that when using redis-cli, you will need to double-escape; e.g. `book\\-\\-1`

**Comment by mnunberg** [comment]
Closing, as this seems to be a usage error; I'll still respond on here, but re-open if we've found an actual bug.
