### ISSUE TITLE
Potential dangling pointer in RediSearch_CreateField

### ISSUE THREAD

**Issue by mnunberg** [RediSearch/RediSearch#823]
When creating two fields in succession, e.g.

```c
f1 = RediSearch_CreateField(...);
f2 = RediSearch_CreateField(...);
```

The second creation of the field may cause `f1` to be a dangling pointer; meaning that if you try to set any kind of option on it, it may crash or otherwise corrupt memory. The only solution is to change the API to return an array index into the internal field list, and have all field-manipulation or access functions require the passing of the index itself.

**Comment by MeirShpilraien** [comment]
@swilly22 @ashtul FYI

**Comment by MeirShpilraien** [comment]
@mnunberg maybe we can change the struct to hold a pointer to the spec and the field index and then the api will stay the same right?

**Comment by mnunberg** [comment]
And when will it be freed?
