### ISSUE TITLE
Crash when using SORTBY on fields created with FT.ALTER

### ISSUE THREAD

**Issue by dsnowberger** [RediSearch/RediSearch#848]
I added some new sortable text fields, and SORTBY on those fields causes a core dump - unless INFIELDS has been set to match the sorted fields.

Command:
`ft.search index query sortby new_field`

Error:
```redis-server: /RSBUILD/src/value.c:444: RSValue_Cmp: Assertion `v1' failed.```

Redisearch version is 1.4.12. No other data shows up in the debug log.

**Comment by mnunberg** [comment]
(note) This seems to affect 1.4 series only. Should not be an issue on master

**Comment by dsnowberger** [comment]
Is this something that will be fixed then for 1.4.14, @mnunberg? Or will it be an issue until 1.5?

**Comment by MeirShpilraien** [comment]
@dsnowberger Thanks for reporting, will fix that for 1.4.16.

**Comment by ashton-ellis** [comment]
@MeirShpilraien Does 1.4.16 have a release date that you can share?

**Comment by MeirShpilraien** [comment]
Should be released this week
