### ISSUE TITLE
FT crash on restart

### ISSUE THREAD

**Issue by djbokkeman** [RediSearch/RediSearch#866]
On start/restart of the server we get "The RDB file contains module data for the module '
                                                                                     ' that is not terminated by the proper module value EOF marker"

Within the single quotes '' there is a lot of whitespace. 

I'm not sure how to use gdb on startup with redis-server.

Database is about 200mb.

Our database somehow get's corrupted over time but we are not sure when. We constantly update the database with queries like 'FT.ADDHASH', 'products' 'product:x', '1', 'REPLACE', 'LANGUAGE dutch' and running multiple indexes (300+)

Only on restart we know if the database is corrupted. Any tips on how to further debug? Or someone interested in looking into the rdb?

Same results on:
redis-server v5.0.4 and Redis-server v4.0.11
RediSearch v1.4.11 and RediSearch v1.4.14

**Comment by MeirShpilraien** [comment]
@djbokkeman Can you send us the corrupted RDB?

**Comment by djbokkeman** [comment]
Hi @MeirShpilraien, 

Thank you so much!

Please follow link and I will approve access immediately.

correct: https://drive.google.com/file/d/1aZDa3DO2tUY-ELxra1Tw7Wmsq0N82wYb/view?usp=sharing
corrupt: https://drive.google.com/file/d/1FNfi0VGdGWyvcghIoFz5plNSNyKsr1kn/view?usp=sharing

**Comment by MeirShpilraien** [comment]
@djbokkeman I currently suspect at something, can you check it you see such log message in you redis log file?
`Trie: saving %zd nodes actually iterated only %zd nodes`

**Comment by djbokkeman** [comment]
@MeirShpilraien, yes I got those in the lot:

334:M 26 Aug 16:15:55.709 * 10000 changes in 60 seconds. Saving...
2334:M 26 Aug 16:15:55.795 * Background saving started by pid 14346
14346:C 26 Aug 16:15:57.307 # <ft> Trie: saving 17382 nodes actually iterated only 17383 nodes

**Comment by MeirShpilraien** [comment]
@djbokkeman So my assumption is correct. Redisearch wrote to the RDB that the number of terms in the trie is 17382, but it actually wrote 17383 terms. When RediSearch reads this RDB it reads only 17382 terms, the last term is not read by RediSearch and cause a corruption when redis continues to read the RDB.
The Trie in the RDB tells me that you are also using the suggestion api (SUGADD, SUGGET,... ). If so, can you send a sample of the code that use it. I am trying to understand how the trie iterator returns more elements then the total number of elements in the trie. If I will understand the usage pattern it might help me to reproduce the issue...

**Comment by djbokkeman** [comment]
Hi @MeirShpilraien,

That's great! I added 2 docs. First how we add the suggestions and second some queries. I Hope it's helpful. Please let me know if you need more info.

code for adding: https://drive.google.com/file/d/1la0udWZPL5d9HBkY9iDw7HDvO0AmeByQ/view?usp=sharing
few seconds of live queries: https://drive.google.com/file/d/1HGcJDvKVE5PnekStRgG1pC9d8xJzVO3J/view?usp=sharing

**Comment by MeirShpilraien** [comment]
@djbokkeman I finally was able to reproduce it!
```
127.0.0.1:6379> FT.sugadd sug test123 1
(integer) 1
127.0.0.1:6379> FT.sugadd sug test456 1
(integer) 2
127.0.0.1:6379> FT.sugdel sug test
(integer) 1
127.0.0.1:6379> FT.suglen sug
(integer) 1
127.0.0.1:6379> FT.sugget sug "" MAX 17343
1) "test123"
2) "test456"
127.0.0.1:6379> debug reload
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>
```
```
27644:M 27 Aug 2019 13:40:43.631 * DB saved on disk
27644:M 27 Aug 2019 13:40:43.631 # The RDB file contains module data for the module '����U' that is not terminated by the proper module value EOF marker
```

It is a bug in the trie that allows to delete a none existing nodes, this cause the trie node counter to be reduced by one while no node was actually deleted, eventually it cause a corruption.

The fix is pretty easy and we will add it to 1.4.15 (probably will be release this week).

The only question left is whether or not you need the data on the corrupted RDB. If you need the data I might be able to load it and resave it properly. Let me know if its important or not.

Thank you for reporting!!

**Comment by djbokkeman** [comment]
Hi @MeirShpilraien,

That's just awesome news and we really appreciate the swift response. thanks! 

Also thank you for the kind offer but we don't really need to recover the corrupted data. We can rebuild it from a working version within an acceptable timeframe.
 
It might not be related to this restart bug, but we also experience (virtual)memory increasing in time. At 70gb of virtual memory we restart the redis server to prevent further problems. That's how we ended up in this thread. Should I report this in a new ticket or is this a symptom of the trie bug above?

**Comment by MeirShpilraien** [comment]
Lets open a different issue for the memory. We have a big PR that solves many memory issues: https://github.com/RediSearch/RediSearch/pull/857. I hope to merge it soon. I you don't want to wait until we merge it you can try take this branch and see if it solve those memory leaks...

**Comment by djbokkeman** [comment]
@MeirShpilraien I will test #857, 1.4 on our dev server and let you know.

**Comment by MeirShpilraien** [comment]
Great, let me know how it goes, if it will not help then we will deep dive to your specific use-case and try to identify the leak...
