### ISSUE TITLE
Server breaks on Mac OS after indexing ~14k documents 

### ISSUE THREAD

**Issue by pablodiguerero** [RediSearch/RediSearch#881]
`redis-server(28036,0x7000111f7000) malloc: *** error for object 0x7f80640d8cb0: pointer being realloc'd was not allocated
redis-server(28036,0x7000111f7000) malloc: *** set a breakpoint in malloc_error_break to debug
Assertion failed: (size == sizeof(long long)), function FGC_sendLongLong, file /usr/local/opt/RediSearch/src/fork_gc.c, line 67.
Abort trap: 6`

**Comment by mnunberg** [comment]
@pablodiguerero Did you intend to close this?
