### ISSUE TITLE
Optional Query weight attribute doesn't work if apply on same field.

### ISSUE THREAD

**Issue by mohsintahir** [RediSearch/RediSearch#884]
Right now, when I try to search a keyword and use an optional query with weight on the same field to boost result, it doesn't seem doing anything.

I have tried redisearch 1.4.0 and 1.4.15

I have indexed document with different TEXT fields of variable sizes and while indexing I have given them different document_score based on my app internal logic. Now I want my users to search for a document by making a query but I want to boost those results that exactly match the query to be at the top.

I have seen scoring algorithm(TF-IDF) sample code provided by redis but none of them seem to do anything with the $weight we provide to a subquery. All of the talks about field weights, document_score and query term frequencies. None of the talks about $weight in a query and how it will effect the end result.

Lets say I have 4 document with different text fields. One of them is `title` field which is also TEXT. The entries of `title` fields of each 4 documents are as follows

"mohsin conversation with the mohsin"
"conversation the conversation - a drama about conversation, the science of conversation."
"Fareham Civilization Church - Sermons and conversations mohsin conversation the"
"mohsin conversation the conversation tahir"
When I generate the following query to redisearch

```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```
I expect the documents with exact `conversation the conversation` to be at top and all other results (having slop distance > 0) after them.

But the output is totally different. i.e.

"Fareham Civilization Church - Sermons and conversations mohsin conversation the"
 "mohsin conversation with the mohsin"
 "conversation the conversation - a drama about conversation, the science of conversation."
 "mohsin conversation the conversation tahir"

Some Internal info: 
I am using following query to create index:
"FT.create {index_name} STOPWORDS 0 SCHEMA title text weight 50 subtitle text weight 10 author text weight 10 description text weight 20" 

and query to fetch result is as follows:
```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```

Note: I do see optional query works well if apply on other fields but doesn't seem to work as intended if apply to same field e.g. 

Same field example is as follows but doesn't work:
```@title:(conversation the conversation*) (~@title:"conversation the conversation"=>{$weight: 10;})```

But different field example like  

```@title:(conversation the conversation*) (~@description:"conversation the conversation"=>{$weight: 10;})```

works well

**Comment by mnunberg** [comment]
Can you try with the latest master? There are known issues with optional queries on 1.4.x

**Comment by mohsintahir** [comment]
I am using docker for development. isn't redislabs/redisearch:stable points to latest master ?

**Comment by mnunberg** [comment]
`:stable` should be pointing to the latest official release, which isn't master. `:edge` points to master.

**Comment by mohsintahir** [comment]
I have tested with `:edge` but still same result.

**Comment by mnunberg** [comment]
Can you provide a list of commands that I can use to reproduce?

**Comment by mohsintahir** [comment]
# Create `shows`

FT.CREATE shows STOPWORDS 0 SCHEMA title text weight 50

# Add documents

1. FT.ADD shows 1 0.025 NOSAVE REPLACE FIELDS title "fareham civil church sermon and convers mohsin convers the" 

2. FT.ADD shows 2 0.05 NOSAVE REPLACE FIELDS title "mohsin convers with the mohsin"

3. FT.ADD shows 3 0.0251 NOSAVE REPLACE FIELDS title "convers the convers a drama about convers the scienc of convers"

4. FT.ADD shows 4 0.023 NOSAVE REPLACE FIELDS title "mohsin convers the convers tahir"


# search documents

FT.SEARCH shows @title:(convers the convers) (~@title:\"convers the convers\"=>{$weight: 10;}) LIMIT 0 50"

**Comment by MeirShpilraien** [comment]
@mohsintahir there is a bug in redisearch which I will describe bellow but regardless your query is not complete, you need to also specify the 'inorder' and 'slop' attributes so it will tell redisearch you actually want exact match for 'conversation the conversation'.

Now to the bug, the problem happens even before the optional iterator, look at the following query (with the index and data from you example):
```
127.0.0.1:6379> FT.SEARCH idx "(@title:(conversation the conversation))=>{$inorder: true;$slop: 0}"
1) (integer) 2
2) "doc2"
3) 1) "title"
   2) "conversation the conversation - a drama about conversation, the science of conversation."
4) "doc4"
5) 1) "title"
   2) "mohsin conversation the conversation tahir"
```
This query tells redisearch to search for those words ("conversation the conversation") in this order, with no other words between them. And it returns the correct result.

Now look at this query:
```
127.0.0.1:6379> FT.SEARCH idx "@title:conversation (@title:(conversation the conversation))=>{$inorder: true;$slop: 0}"
1) (integer) 4
2) "doc3"
3) 1) "title"
   2) "Fareham Civilization Church - Sermons and conversations mohsin conversation the"
4) "doc2"
5) 1) "title"
   2) "conversation the conversation - a drama about conversation, the science of conversation."
6) "doc4"
7) 1) "title"
   2) "mohsin conversation the conversation tahir"
8) "doc1"
9) 1) "title"
   2) "mohsin conversation with the mohsin"
```
Basically this query takes the previous query and add another 'and' attribute that tells it to return only results that contains the word 'conversation' in them. And you can see that the results set is greater then the previous query (which does not make sense cause we expect a subset of the previous query).

The problem is with the Intersect Iterator which does not take into account the 'inorder' and 'slop' attributes at some cases. After fixing it you can see that I am getting a correct results:
```
127.0.0.1:6379> FT.SEARCH idx "@title:(conversation) (@title:(conversation the conversation))=>{$inorder: true;$slop: 0}"
1) (integer) 2
2) "doc2"
3) 1) "title"
   2) "conversation the conversation - a drama about conversation, the science of conversation."
4) "doc4"
5) 1) "title"
   2) "mohsin conversation the conversation tahir"
```

Also when running your query (with the fix of 'inorder' and 'slop') I am also getting the expected results
```
127.0.0.1:6379> ft.search idx "@title:(conversation the conversation) ~(@title:(conversation the conversation)=>{$weight: 10;$inorder: true;$slop: 0})"
1) (integer) 4
2) "doc2"
3) 1) "title"
   2) "conversation the conversation - a drama about conversation, the science of conversation."
4) "doc4"
5) 1) "title"
   2) "mohsin conversation the conversation tahir"
6) "doc3"
7) 1) "title"
   2) "Fareham Civilization Church - Sermons and conversations mohsin conversation the"
8) "doc1"
9) 1) "title"
   2) "mohsin conversation with the mohsin"
```

I will include the fix in the next 1.4 version.
@mnunberg we need to make sure to cherry pick it to master.

**Comment by mohsintahir** [comment]
@MeirShpilraien Thank you so much for helping me understand what's going on, it really helped me alot understanding things. I didn't incorporate $slop and $inorder because In documents it is mentioned that $slop defaults to 0 and I was using quotes to wrap the text, so I thought $inorder is not needed.


Anyhow a big thanks!.

Can you kindly release the next version as I think this bug is itself a big improvement and can be released earlier ?

**Comment by MeirShpilraien** [comment]
@mohsintahir Sorry its my mistake, you are right, the 'slop' and 'inorder' is not needed. After the fix your query works just fine:
```
127.0.0.1:6379> FT.SEARCH idx '@title:(conversation the conversation) (~@title:"conversation the conversation"=>{$weight: 10;})' LIMIT 0 50
1) (integer) 4
2) "doc2"
3) 1) title
   2) "conversation the conversation - a drama about conversation, the science of conversation."
4) "doc4"
5) 1) title
   2) "mohsin conversation the conversation tahir"
6) "doc3"
7) 1) title
   2) "Fareham Civilization Church - Sermons and conversations mohsin conversation the"
8) "doc1"
9) 1) title
   2) "mohsin conversation with the mohsin"
```

There is a pending PR for the fix: https://github.com/RediSearch/RediSearch/pull/885
we will release soon
