### ISSUE TITLE
Unexpected behaviour when searching in traditional chinese

### ISSUE THREAD

**Issue by ericfengchao** [RediSearch/RediSearch#887]
im recently experimenting with chinese support for redisearch and I found an odd situation with it. I have indexed two documents with same one word(旋转), just that one in simplified chinese(旋转) while the other in traditional(旋轉). The command logs are as follows.
```
1567530713.182716 [0 172.17.0.1:54328] "FT.CREATE" "myIndex" "SCHEMA" "title" "TEXT"
1567530713.183409 [0 172.17.0.1:54328] "FT.ADD" "myIndex" "doc1" "1" "LANGUAGE" "chinese" "REPLACE" "FIELDS" "title" "\xe6\x97\x8b\xe8\xbd\xac"
1567530713.183664 [0 172.17.0.1:54328] "FT.ADD" "myIndex" "doc2" "1" "LANGUAGE" "chinese" "REPLACE" "FIELDS" "title" "\xe6\x97\x8b\xe8\xbd\x89"
```

Then, when i try to search the documents with simplified(旋转), i get both docs return. 
```
→ redis-cli -p 6378 "FT.SEARCH" "myIndex" "旋转" LANGUAGE chinese  WITHPAYLOADS WITHSCORES LIMIT 0 10
1) (integer) 2
2) "doc2"
3) "1"
4) (nil)
5) 1) "title"
   2) "\xe6\x97\x8b\xe8\xbd\x89"
6) "doc1"
7) "1"
8) (nil)
9) 1) "title"
   2) "\xe6\x97\x8b\xe8\xbd\xac"
```

However, when i search with traditional(旋轉), no docs returned. 
```
→ redis-cli -p 6378 "FT.SEARCH" "myIndex" "旋轉" LANGUAGE chinese  WITHPAYLOADS WITHSCORES LIMIT 0 10
1) (integer) 0
```

I then found out that both documents are tokenised into the simplified version of the word. 
```
→ redis-cli -p 6378 keys "*"
1) "doc2"
2) "idx:myIndex"
3) "ft:myIndex/\xe6\x97\x8b\xe8\xbd\xac"
4) "doc1"
```

a handy tool for decoding utf-8 chars if anyone wants to verify the above testing case https://www.browserling.com/tools/utf8-decode

i have tried a few other documents with more than 1 word and pure traditional chinese characters. The behaviour is similar. Simplified chinese queries work as expected always while traditional chinese queries fail to retrieve expected documents most of the time.

was it a bug that simplifying chinese characters was missing in **query**?

**Comment by MeirShpilraien** [comment]
@ericfengchao Can you specify the redisearch version you are using?

**Comment by gkorland** [comment]
I managed to recreate it with 1.4.15, we'll check it out

**Comment by ericfengchao** [comment]
i am using the latest redisearch docker image which i suppose is version `1.4.15`.

**Comment by mnunberg** [comment]
We use friso internally, which *should* run the same code paths for both query and tokenization
