### ISSUE TITLE
Compile Error on armv7l

### ISSUE THREAD

**Issue by psheltz** [RediSearch/RediSearch#901]
I am trying to compile the current version of RedisSearch on a Raspberry Pi 3 with armv7l. I get the following compile error:
```
/home/software/RediSearch/src/numeric_index.c: In function ‘NumericIndexType_Register’:
/home/software/RediSearch/src/numeric_index.c:514:45: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types]
                                .mem_usage = NumericIndexType_MemUsage};
```
Has anyone else tried to build on a non-x86 system? Is there a minimum gcc that RediSearch requires? My OS is Ubuntu16.04 and gcc is v5.4.0.

**Comment by rafie** [comment]
This is a genuine error, happening on arm7l and not on aarch64. It's a warning turned into error, so we can try suppressing it for sake of testing.

**Comment by psheltz** [comment]
Is there a modification I should make to a config file and recompile?

**Comment by mnunberg** [comment]
https://github.com/RediSearch/RediSearch/blob/master/cmake/redisearch_cflags.cmake#L19

**Comment by mnunberg** [comment]
@psheltz is there more context on the types expected vs received?

**Comment by psheltz** [comment]
@mnunberg I tried compiling on another RPI system that has more up to date gcc (8.3.0) and I get the same error but better debug output:
```
/home/pi/software/RediSearch/src/numeric_index.c: In function ‘NumericIndexType_Register’:
/home/pi/software/RediSearch/src/numeric_index.c:514:45: error: initialization of ‘size_t (*)(const void *)’ {aka ‘unsigned int (*)(const void *)’} from incompatible pointer type ‘long unsigned int (*)(const void *)’ [-Werror=incompatible-pointer-types]
                                .mem_usage = NumericIndexType_MemUsage};
```

**Comment by mnunberg** [comment]
No, it should be fine

**Comment by mnunberg** [comment]
You could even modify the function to return a `size_t` instead of `unsigned long` and thereby avoid the warning altogether (and this also seems to be the correct solution; and is indeed more related to x32)

**Comment by psheltz** [comment]
I added `SET(HAVE_W_INCOMPATIBLE_POINTER_TYPES OFF)` to the cmake file and it compiles fine. For the long term, I may modify the source code as you suggested. Thanks!
