### ISSUE TITLE
FT.ADD with incorrect index gives wrong error

### ISSUE THREAD

**Issue by ashtul** [RediSearch/RediSearch#944]
```
127.0.0.1:6379> FLUSHALL
OK
127.0.0.1:6379> ft.add idx doc1 1.0
(error) No field list found
```
Should return `Unknown index name`

Error returns from parseDocumentOptions() which is called before.

**Comment by mnunberg** [comment]
Should it? The provided arguments are incorrect. Logically, arguments should be parsed for correctness prior to actually accessing any resources.
