### ISSUE TITLE
Newest edge build floods logs

### ISSUE THREAD

**Issue by Nomafin** [RediSearch/RediSearch#951]
The newest Docker edge build (as of Oct 16th) floods gigabytes of logs in a matter of minutes when it's normally working otherwise. All the log rows are: 

```{"log":"warning: got a bad length when writing to pipe.\r\n","stream":"stdout","time":"2019-10-16T19:26:22.912825727Z"}```

**Comment by mnunberg** [comment]
Does the log correlate with anything else? This shouldn't happen generally..

**Comment by Nomafin** [comment]
Is it possible to turn the logging of completely? RediSearch takes lots of resources right now and I think it's just because of the logs. The latest 1.6 RC doesn't do the same (but can't be used because of the bug that produces wrong search results that is fixed in the edge version).

**Comment by mnunberg** [comment]
Unfortunately this specific line is a `printf()` statement so it doesn't go through the normal Redis logging mechanism. My best suggestion as a temporary fix is to comment out the line and rebuild, until this issue is fixed in the next release.

**Comment by Nomafin** [comment]
Found a workaround: I overrid the container starting command with

```redis-server --loadmodule /usr/lib/redis/modules/redisearch.so --logfile /dev/null```

which did the trick. Docker writes all stdouts to the log as well so this works as a workaround until you release the real fix for the problem.

**Comment by mnunberg** [comment]
@Nomafin Please try the latest master version; the underlying issue should be fixed there.
