### ISSUE TITLE
FT.SEARCH with RETURN changes the format of NUMERIC field

### ISSUE THREAD

**Issue by guykorlandredis** [RediSearch/RediSearch#954]
The output of Numeric Field is changed when returned with a RETURN clause in a FT.SEARCH query. This only happens when the number is 12 digits or longer.

However, the same number is returned in a standard numeric format when FT.SEARCH is run without any RETURN clause or if it queried using FT.GET

```
ft.search numTest "@age:[50 +inf]" return 2 age timestamp
 1) (integer) 9
 2) "thirdDoc"
 3) 1) "age"
    2) "999999999"
    3) "timestamp"
    4) "2.01911100905e+13"
 4) "G8"
 5) 1) "age"
    2) "1.23456789101e+12"
    3) "timestamp"
    4) "1.56991283902e+12"
 6) "G7"
 7) 1) "age"
    2) "123456789101"
    3) "timestamp"
    4) "1.56991283902e+12"
```

Same query when run without the RETURN clause. See how the output of the “age” column changed.

```
ft.search numTest "@age:[50 +inf]"
 1) (integer) 9
 2) "thirdDoc"
 3) 1) "name"
    2) "indana"
    3) "age"
    4) "999999999"
    5) "timestamp"
    6) "20191110090500"
 4) "G8"
 5) 1) "name"
    2) "checkbug?"
    3) "age"
    4) "1234567891011"
    5) "timestamp"
    6) "1569912839016"
 6) "G7"
 7) 1) "name"
    2) "checkbug?"
    3) "age"
    4) "123456789101"
    5) "timestamp"
    6) "1569912839016"
```

**Comment by mnunberg** [comment]
@gkorland are the fields sortable by any chance? Also, what version does this happen on?

**Comment by mnunberg** [comment]
This does not appear to be an issue with 1.6 in this particular case, but overall there remains the issue of the data in our "sortable" not being of the same format as what is stored in Redis. The proper way to solve this is by adding an actual long integer field type..

**Comment by mnunberg** [comment]
This should be fixed in current master, since we now return all data from the document, and not the sortables array
