### ISSUE TITLE
Crash with Garbage Collection Enabled

### ISSUE THREAD

**Issue by dwedwick** [RediSearch/RediSearch#967]
When I enable garbage collection (i.e. do not turn it off), Redis crashes periodically throughout the day.  When I indicate NOGC, RediSearch and Redis work without fail.

This is similar in symptoms to the other issue "Redis 5.0.5 crashed by signal: 11 - using RediSearch #905"

Partial log is below.  The full log and example dump.rdb file is here (kindly let me know when I can remove it after it's been downloaded.

https://drive.google.com/open?id=19Iys0Ex9EYhcB7RgoapMRhE9ACWjm1HW

Thanks

11276:M 23 Oct 2019 11:42:02.060 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
11276:M 23 Oct 2019 11:42:02.060 # Server initialized
11276:M 23 Oct 2019 11:42:02.060 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/
sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
11276:M 23 Oct 2019 11:42:02.061 * <ft> RediSearch version 99.99.99 (Git=v1.6.0-338-gde2b2bd)
11276:M 23 Oct 2019 11:42:02.061 * <ft> Low level api version 1 initialized successfully
11276:M 23 Oct 2019 11:42:02.061 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 10
00, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8, 
11276:M 23 Oct 2019 11:42:02.062 * <ft> Initialized thread pool!
11276:M 23 Oct 2019 11:42:02.062 * Module 'ft' loaded from /var/lib/redis/redisearch.so
11276:M 23 Oct 2019 11:42:12.410 * DB loaded from disk: 10.348 seconds
11276:M 23 Oct 2019 11:42:12.410 * Ready to accept connections
11276:M 23 Oct 2019 12:20:01.969 * Background saving started by pid 12751
12751:C 23 Oct 2019 12:20:19.181 * DB saved on disk
12751:C 23 Oct 2019 12:20:19.192 * RDB: 108 MB of memory used by copy-on-write
11276:M 23 Oct 2019 12:20:19.288 * Background saving terminated with success

=== REDIS BUG REPORT START: Cut & paste starting from here ===
13444:C 23 Oct 2019 12:44:10.468 # Redis 5.0.5 crashed by signal: 11
13444:C 23 Oct 2019 12:44:10.469 # Crashed running the instruction at: 0x5485ec
13444:C 23 Oct 2019 12:44:10.469 # Accessing address: (nil)
13444:C 23 Oct 2019 12:44:10.469 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------

**Comment by mnunberg** [comment]
The stack trace is needed..

**Comment by dwedwick** [comment]
I put it in the tarball on the Google drive - can you get it from the dump file?

**Comment by dwedwick** [comment]
Sorry to not be clear - the file on Google Drive has the dump file as well as the redis log file that shows the error.

No failures in 48 hours after turning off garbage collection.

=== REDIS BUG REPORT START: Cut & paste starting from here ===
13444:C 23 Oct 2019 12:44:10.468 # Redis 5.0.5 crashed by signal: 11
13444:C 23 Oct 2019 12:44:10.469 # Crashed running the instruction at: 0x5485ec
13444:C 23 Oct 2019 12:44:10.469 # Accessing address: (nil)
13444:C 23 Oct 2019 12:44:10.469 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/usr/local/bin/redis-server 192.168.99.118:6379(je_tcache_bin_flush_small+0x29c)[0x5485ec]

Backtrace:
/usr/local/bin/redis-server 192.168.99.118:6379(logStackTrace+0x43)[0x4824be]
/usr/local/bin/redis-server 192.168.99.118:6379(sigsegvHandler+0x102)[0x482bfe]
/lib64/libpthread.so.0(+0xf5d0)[0x7f691f8595d0]
/usr/local/bin/redis-server 192.168.99.118:6379(je_tcache_bin_flush_small+0x29c)[0x5485ec]
/usr/local/bin/redis-server 192.168.99.118:6379(je_tcache_event_hard+0x48)[0x549b38]
/usr/local/bin/redis-server 192.168.99.118:6379(zfree+0x61)[0x43bd42]
/usr/local/bin/redis-server 192.168.99.118:6379(decrRefCount+0xcb)[0x449adc]
/usr/local/bin/redis-server 192.168.99.118:6379(RM_CloseKey+0x5a)[0x4b5353]
/var/lib/redis/redisearch.so(+0x7dbb3)[0x7f691ca41bb3]
/var/lib/redis/redisearch.so(+0x7fa7f)[0x7f691ca43a7f]
/var/lib/redis/redisearch.so(+0xaecd2)[0x7f691ca72cd2]
/lib64/libpthread.so.0(+0x7dd5)[0x7f691f851dd5]
/lib64/libc.so.6(clone+0x6d)[0x7f691f57b02d]

------ INFO OUTPUT ------
# Server
redis_version:5.0.5
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:df2db5feee29f6b2
redis_mode:standalone
os:Linux 2.6.32-042stab113.21 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:13444
run_id:aeead001af68e88589af5ffe6f1c048af4d49676
tcp_port:6379
uptime_in_seconds:3728
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:11578762
executable:/usr/local/bin/redis-server
config_file:/etc/redis.conf

# Clients
connected_clients:1
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:474018672
used_memory_human:452.06M
used_memory_rss:526348288
used_memory_rss_human:501.96M
used_memory_peak:510015936
used_memory_peak_human:486.39M
used_memory_peak_perc:92.94%
used_memory_overhead:55066610
used_memory_startup:791400
used_memory_dataset:418952062
used_memory_dataset_perc:88.53%
allocator_allocated:477139992
allocator_active:524447744
allocator_resident:538251264
total_system_memory:8589934592
total_system_memory_human:8.00G
used_memory_lua:37888
used_memory_lua_human:37.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.10
allocator_frag_bytes:47307752
allocator_rss_ratio:1.03
allocator_rss_bytes:13803520
rss_overhead_ratio:0.98
rss_overhead_bytes:-11902976
mem_fragmentation_ratio:1.11
mem_fragmentation_bytes:52359000
mem_not_counted_for_evict:0
mem_replication_backlog:0
mem_clients_slaves:0
mem_clients_normal:16922
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:2129
rdb_bgsave_in_progress:0
rdb_last_save_time:1571858419
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:18
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:113954816
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:5842
total_commands_processed:14593
instantaneous_ops_per_sec:33
total_net_input_bytes:6466831
total_net_output_bytes:3975792
instantaneous_input_kbps:15.01
instantaneous_output_kbps:16.25
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:0
keyspace_misses:0
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:17846
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:0
master_replid:4cc5492d56d3e53c5b46e1e86ee0cf75b3e0e9d3
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:0
second_repl_offset:-1
repl_backlog_active:0
repl_backlog_size:1048576
repl_backlog_first_byte_offset:0
repl_backlog_histlen:0

# CPU
used_cpu_sys:0.016997
used_cpu_user:0.022996
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats
cmdstat_bgsave:calls=1,usec=17977,usec_per_call=17977.00
cmdstat_select:calls=5834,usec=9277,usec_per_call=1.59
cmdstat_set:calls=2910,usec=33903,usec_per_call=11.65
cmdstat_FT.ADD:calls=2911,usec=360446,usec_per_call=123.82
cmdstat_auth:calls=2924,usec=3707,usec_per_call=1.27
cmdstat_monitor:calls=1,usec=2,usec_per_call=2.00
cmdstat_ping:calls=12,usec=16,usec_per_call=1.33

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=990987,expires=0,avg_ttl=0
db1:keys=129539,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=4752 addr=127.0.0.1:57541 fd=8 name= age=2041 idle=0 flags=O db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=monitor

------ REGISTERS ------
13444:C 23 Oct 2019 12:44:10.470 # 
RAX:fffffffffffffff8 RBX:0000000000000000
RCX:0000000000000005 RDX:0000000000000000
RDI:00007f68dc205c68 RSI:00007f68f1a3dd60
RBP:00007f68eb1f9490 RSP:00007f68eb1f9250
R8 :ffffffffffffffe0 R9 :0000000000000002
R10:00007f68eb1f9250 R11:00000000044c7004
R12:fffffffffffffff0 R13:00007f68dc200900
R14:00007f68eb1f9258 R15:00007f68eb1fa248
RIP:00000000005485ec EFL:0000000000010246
CSGSFS:0000000000000033
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925f) -> 00007f68dc205cb0
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925e) -> ffffffffffffffe0
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925d) -> 00007f68dc200900
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925c) -> 0000000000005368
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925b) -> 0000000000000001
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f925a) -> fffffffffffffff8
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9259) -> 0000000000000002
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9258) -> 00007f68eb1f9250
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9257) -> 0000000000000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9256) -> 0000000300000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9255) -> 0000000000000013
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9254) -> 0000000000000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9253) -> 0000000000000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9252) -> 0000000000000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9251) -> 0000000000000000
13444:C 23 Oct 2019 12:44:10.470 # (00007f68eb1f9250) -> 00007f68dc20d2c0

------ FAST MEMORY TEST ------
*** Preparing to test memory region 7ab000 (2252800 bytes)
*** Preparing to test memory region 22c4000 (135168 bytes)
*** Preparing to test memory region 7f68d3800000 (4194304 bytes)
*** Preparing to test memory region 7f68d3d80000 (73924608 bytes)
*** Preparing to test memory region 7f68d8580000 (86507520 bytes)
*** Preparing to test memory region 7f68dd9f8000 (100663296 bytes)
*** Preparing to test memory region 7f68e39f9000 (10485760 bytes)
*** Preparing to test memory region 7f68e43fa000 (10485760 bytes)
*** Preparing to test memory region 7f68e4dfa000 (83886080 bytes)
*** Preparing to test memory region 7f68e9dfb000 (10485760 bytes)
*** Preparing to test memory region 7f68ea7fc000 (10485760 bytes)
*** Preparing to test memory region 7f68eb1fc000 (67108864 bytes)
*** Preparing to test memory region 7f68ef1fd000 (10485760 bytes)
*** Preparing to test memory region 7f68efbfe000 (10485760 bytes)
*** Preparing to test memory region 7f68f05fe000 (58720256 bytes)
*** Preparing to test memory region 7f68f3dff000 (10485760 bytes)
*** Preparing to test memory region 7f68f4800000 (10485760 bytes)
*** Preparing to test memory region 7f68f5200000 (161480704 bytes)
*** Preparing to test memory region 7f68fed9e000 (46137344 bytes)
*** Preparing to test memory region 7f690199f000 (10485760 bytes)
*** Preparing to test memory region 7f69023a0000 (10485760 bytes)
*** Preparing to test memory region 7f6902da0000 (54525952 bytes)
*** Preparing to test memory region 7f69061a1000 (10485760 bytes)
*** Preparing to test memory region 7f6906ba2000 (10485760 bytes)
*** Preparing to test memory region 7f69075a3000 (10485760 bytes)
*** Preparing to test memory region 7f6907fa4000 (10485760 bytes)
*** Preparing to test memory region 7f69089a5000 (10485760 bytes)
*** Preparing to test memory region 7f69093a6000 (10485760 bytes)
*** Preparing to test memory region 7f6909da7000 (10485760 bytes)
*** Preparing to test memory region 7f690a7a8000 (10485760 bytes)
*** Preparing to test memory region 7f690b1a9000 (10485760 bytes)
*** Preparing to test memory region 7f690bbaa000 (10485760 bytes)
*** Preparing to test memory region 7f690c5ab000 (10485760 bytes)
*** Preparing to test memory region 7f690cfac000 (10485760 bytes)
*** Preparing to test memory region 7f690d9ad000 (10485760 bytes)
*** Preparing to test memory region 7f690e3ae000 (10485760 bytes)
*** Preparing to test memory region 7f690edaf000 (10485760 bytes)
*** Preparing to test memory region 7f690f7b0000 (10485760 bytes)
*** Preparing to test memory region 7f69101b1000 (10485760 bytes)
*** Preparing to test memory region 7f6910bb2000 (10485760 bytes)
*** Preparing to test memory region 7f69115b3000 (10485760 bytes)
*** Preparing to test memory region 7f6911fb4000 (10485760 bytes)
*** Preparing to test memory region 7f69129b5000 (10485760 bytes)
*** Preparing to test memory region 7f69133b6000 (10485760 bytes)
*** Preparing to test memory region 7f6913db7000 (10485760 bytes)
*** Preparing to test memory region 7f69147b8000 (10485760 bytes)
*** Preparing to test memory region 7f69151b9000 (10485760 bytes)
*** Preparing to test memory region 7f6915bba000 (10485760 bytes)
*** Preparing to test memory region 7f69165bb000 (10485760 bytes)
*** Preparing to test memory region 7f6916fbc000 (10485760 bytes)
*** Preparing to test memory region 7f69179bd000 (10485760 bytes)
*** Preparing to test memory region 7f69183be000 (10485760 bytes)
*** Preparing to test memory region 7f6918dbf000 (10485760 bytes)
*** Preparing to test memory region 7f69197c0000 (10485760 bytes)
*** Preparing to test memory region 7f691a1c1000 (10485760 bytes)
*** Preparing to test memory region 7f691abc2000 (10485760 bytes)
*** Preparing to test memory region 7f691b5c3000 (10485760 bytes)
*** Preparing to test memory region 7f691bfc4000 (10485760 bytes)
*** Preparing to test memory region 7f691cdfa000 (12288 bytes)
*** Preparing to test memory region 7f691cdfe000 (10485760 bytes)
*** Preparing to test memory region 7f691d7ff000 (10485760 bytes)
*** Preparing to test memory region 7f691e200000 (10485760 bytes)
*** Preparing to test memory region 7f691ec00000 (8388608 bytes)
*** Preparing to test memory region 7f691f845000 (20480 bytes)
*** Preparing to test memory region 7f691fa62000 (16384 bytes)
*** Preparing to test memory region 7f6920386000 (20480 bytes)
*** Preparing to test memory region 7f6920393000 (4096 bytes)
*** Preparing to test memory region 7f6920394000 (4096 bytes)
*** Preparing to test memory region 7f6920397000 (4096 bytes)

**Comment by MeirShpilraien** [comment]
@dwedwick can you also share you redisearch.so binary?
thanks.

**Comment by mnunberg** [comment]
How are you building redisearch?

**Comment by dwedwick** [comment]
I put the binary and the output of the build process in this file:

https://drive.google.com/open?id=1DL7xMQvIkCGg3M5iLx7KtrMX1Wr_GjCH

For building, I'm just running make inside the top directory.

**Comment by mnunberg** [comment]
@dwedwick Are you familiar at all with CMake? can you build it without optimizations?

**Comment by mnunberg** [comment]
Also, does this crash your server? from what I can tell, this should only happen in the child gc process, so your server should remain in tact.

**Comment by dwedwick** [comment]
I think the server stays running.  

I'm not familiar with using cmake.  I just did:
`cd build
cmake .. -DCMAKE_BUILD_TYPE=DEBUG
make `

If I should do something different, please let me know.

**Comment by MeirShpilraien** [comment]
@dwedwick I just was able to reproduce a crash with GC enable. The issue was that at some cases we leave the last block unhanded and point to illegal memory. Funny think, this PR (https://github.com/RediSearch/RediSearch/commit/f15adc32134a1b758782945fd9924beb1a4d5bff) which fix a data lost on GC also fixes this illegal memory issue. If you can test the current master and see if it solves the crashes it will be great.

**Comment by dwedwick** [comment]
All is working perfect - no crashes in the last 12 hours.  I was seeing a crash at least once every two hours or so.

Thanks for resolving the issue.
