### ISSUE TITLE
get STOPWORDS for a specific index

### ISSUE THREAD

**Issue by filipecosta90** [RediSearch/RediSearch#970]
RediSearch has a pre-defined default list of stop-words and we can alter or completely disable them. After going over the current documentation, I believe there is no reference on how to get the STOPWORDS for a specific index. 
This is pertinent information to be able to keep track of since it influences the way we respond to both ingestion and querying.

**Comment by ashtul** [comment]
What would be the best way to expose this?
How about FT.INFO?
