### ISSUE TITLE
RediSearch Crashes

### ISSUE THREAD

**Issue by ashokgit** [RediSearch/RediSearch#973]
Hello all, 
My redisearch gets crashed giving the following log below. any help would be very helpful.
....
.O.O.O.O.O.O.23584:M 31 Oct 2019 10:32:50.077 # Background saving terminated by signal 9
23584:M 31 Oct 2019 10:32:50.081 * Starting BGSAVE for SYNC with target: replicas sockets
23584:M 31 Oct 2019 10:32:50.107 * Background RDB transfer started by pid 26701
26701:C 31 Oct 2019 10:32:53.982 # Out Of Memory allocating 72056490214465023 bytes!

=== REDIS BUG REPORT START: Cut & paste starting from here ===
26701:C 31 Oct 2019 10:32:53.982 # ------------------------------------------------
26701:C 31 Oct 2019 10:32:53.982 # !!! Software Failure. Press left mouse button to continue
26701:C 31 Oct 2019 10:32:53.982 # Guru Meditation: Redis aborting for OUT OF MEMORY #server.c:3888
26701:C 31 Oct 2019 10:32:53.982 # (forcing SIGSEGV in order to print the stack trace)
26701:C 31 Oct 2019 10:32:53.982 # ------------------------------------------------
26701:C 31 Oct 2019 10:32:53.982 # Redis 5.0.3 crashed by signal: 11
26701:C 31 Oct 2019 10:32:53.982 # Crashed running the instruction at: 0x55f51fc6e7f4
26701:C 31 Oct 2019 10:32:53.982 # Accessing address: 0xffffffffffffffff
26701:C 31 Oct 2019 10:32:53.982 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
redis-rdb-to-slaves *:6379(_serverPanic+0x144)[0x55f51fc6e7f4]

Backtrace:
redis-rdb-to-slaves *:6379(logStackTrace+0x45)[0x55f51fc709d5]
redis-rdb-to-slaves *:6379(sigsegvHandler+0xb1)[0x55f51fc71171]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x13f40)[0x7fb4a62eff40]
redis-rdb-to-slaves *:6379(_serverPanic+0x144)[0x55f51fc6e7f4]
redis-rdb-to-slaves *:6379(redisOutOfMemoryHandler+0x34)[0x55f51fc27a24]
redis-rdb-to-slaves *:6379(zmalloc+0x49)[0x55f51fc31799]
redis-rdb-to-slaves *:6379(+0x4e91d)[0x55f51fc4991d]
redis-rdb-to-slaves *:6379(rdbSaveRawString+0x18d)[0x55f51fc49d3d]
redis-rdb-to-slaves *:6379(RM_SaveStringBuffer+0x44)[0x55f51fc9bd84]
/etc/redis/modules/redisearch.so(InvertedIndex_RdbSave+0xa8)[0x7fb4a37fead8]
redis-rdb-to-slaves *:6379(rdbSaveObject+0xbe)[0x55f51fc4aebe]
redis-rdb-to-slaves *:6379(rdbSaveKeyValuePair+0x14e)[0x55f51fc4b87e]
redis-rdb-to-slaves *:6379(rdbSaveRio+0x29d)[0x55f51fc4bfed]
redis-rdb-to-slaves *:6379(rdbSaveRioWithEOFMark+0x1c8)[0x55f51fc4c428]
redis-rdb-to-slaves *:6379(rdbSaveToSlavesSockets+0x282)[0x55f51fc4f162]
redis-rdb-to-slaves *:6379(startBgsaveForReplication+0x5c)[0x55f51fc4795c]
redis-rdb-to-slaves *:6379(updateSlavesWaitingBgsave+0x24f)[0x55f51fc480df]
redis-rdb-to-slaves *:6379(serverCron+0x81f)[0x55f51fc2b77f]
redis-rdb-to-slaves *:6379(aeProcessEvents+0x43a)[0x55f51fc23d9a]
redis-rdb-to-slaves *:6379(aeMain+0x2b)[0x55f51fc23ecb]
redis-rdb-to-slaves *:6379(main+0x4c9)[0x55f51fc1e3f9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xeb)[0x7fb4a6117b6b]
redis-rdb-to-slaves *:6379(_start+0x2a)[0x55f51fc1e64a]

------ INFO OUTPUT ------
# Server
redis_version:5.0.3
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:23238c6957772153
redis_mode:standalone
os:Linux 5.0.0-31-generic x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:8.3.0
process_id:26701
run_id:986c67a7812aaf54080adc264b681981478565f4
tcp_port:6379
uptime_in_seconds:23106
uptime_in_days:0
hz:10
configured_hz:10
lru_clock:12236882
executable:/usr/bin/redis-server
config_file:/etc/redis/redis.conf

# Clients
connected_clients:0
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:848789960
used_memory_human:809.47M
used_memory_rss:1303478272
used_memory_rss_human:1.21G
used_memory_peak:6097002240
used_memory_peak_human:5.68G
used_memory_peak_perc:13.92%
used_memory_overhead:34728482
used_memory_startup:795944
used_memory_dataset:814061478
used_memory_dataset_perc:96.00%
allocator_allocated:848371384
allocator_active:1227255808
allocator_resident:1314103296
total_system_memory:8361447424
total_system_memory_human:7.79G
used_memory_lua:41984
used_memory_lua_human:41.00K
used_memory_scripts:0
used_memory_scripts_human:0B
number_of_cached_scripts:0
maxmemory:0
maxmemory_human:0B
maxmemory_policy:allkeys-lru
allocator_frag_ratio:1.45
allocator_frag_bytes:378884424
allocator_rss_ratio:1.07
allocator_rss_bytes:86847488
rss_overhead_ratio:0.99
rss_overhead_bytes:-10625024
mem_fragmentation_ratio:1.54
mem_fragmentation_bytes:456524424
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:16922
mem_clients_normal:0
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:4145
rdb_bgsave_in_progress:0
rdb_last_save_time:1572501518
rdb_last_bgsave_status:err
rdb_last_bgsave_time_sec:24
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:96210944
aof_enabled:1
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0
aof_current_size:4090514181
aof_base_size:3861191016
aof_pending_rewrite:0
aof_buffer_length:0
aof_rewrite_buffer_length:0
aof_pending_bio_fsync:0
aof_delayed_fsync:0

# Stats
total_connections_received:1264
total_commands_processed:117553
instantaneous_ops_per_sec:0
total_net_input_bytes:230313013
total_net_output_bytes:457952730
instantaneous_input_kbps:0.00
instantaneous_output_kbps:0.00
rejected_connections:0
sync_full:183
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:20116
keyspace_misses:9
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:23962
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:master
connected_slaves:1
slave0:ip=159.89.88.224,port=6379,state=wait_bgsave,offset=0,lag=0
master_replid:37e6ec59c45a4472026d6677a5bf6b7864f7aa2f
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:229355334
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:228306759
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:0.671839
used_cpu_user:3.199284
used_cpu_sys_children:0.000000
used_cpu_user_children:0.000000

# Commandstats
cmdstat_auth:calls=1363,usec=4070,usec_per_call=2.99
cmdstat_FT.SEARCH:calls=9,usec=95691,usec_per_call=10632.33
cmdstat_FT.DEL:calls=10,usec=768,usec_per_call=76.80
cmdstat_select:calls=1001,usec=2081,usec_per_call=2.08
cmdstat_psync:calls=183,usec=25001,usec_per_call=136.62
cmdstat_FT.GET:calls=9787,usec=6934995,usec_per_call=708.59
cmdstat_FT.ADD:calls=9664,usec=12050653,usec_per_call=1246.96
cmdstat_replconf:calls=13691,usec=150501,usec_per_call=10.99
cmdstat_FT.INFO:calls=1000,usec=2471665,usec_per_call=2471.67
cmdstat_hgetall:calls=9807,usec=904469,usec_per_call=92.23
cmdstat_config:calls=1,usec=16,usec_per_call=16.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=611960,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=21305 addr=159.89.88.224:54816 fd=374 name= age=24 idle=24 flags=S db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=psync

------ REGISTERS ------
26701:C 31 Oct 2019 10:32:53.994 # 
RAX:0000000000000000 RBX:00007ffe8c4051b0
RCX:00007fb4a64f5040 RDX:0000000000000011
RDI:00007fb4a5a05318 RSI:00007fb4a65076ac
RBP:000055f51fcb0dc4 RSP:00007ffe8c405190
R8 :0000000000000008 R9 :00007fb4a5eed8d8
R10:00007fb4a5c008c0 R11:0000000000000033
R12:0000000000000f30 R13:00007ffe8c4058c0
R14:fefefe9e02010000 R15:0000000000000005
RIP:000055f51fc6e7f4 EFL:0000000000010206
CSGSFS:002b000000000033
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519f) -> 00007fb4a648997e
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519e) -> 00000000000000cc
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519d) -> 0000000000000040
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519c) -> 00007ffe8c40526f
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519b) -> 00007ffe8c4052d7
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c40519a) -> 00007fb4a5c00980
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405199) -> 0100000000000000
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405198) -> 0000000000000000
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405197) -> 59524f4d454d2046
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405196) -> 4f2054554f20726f
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405195) -> 6620676e6974726f
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405194) -> 6261207369646552
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405193) -> 00007ffe8c4052c0
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405192) -> 00007ffe8c405390
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405191) -> 0000003000000018
26701:C 31 Oct 2019 10:32:53.994 # (00007ffe8c405190) -> 00007ffe8c405270

**Comment by mnunberg** [comment]
@ashokgit what version are you working with? (should be the first few lines redisearch prints to the logs at startup)

**Comment by ashokgit** [comment]
27209:M 31 Oct 2019 13:01:12.599 # Server initialized
27209:M 31 Oct 2019 13:01:12.604 * <ft> RediSearch version 99.99.99 (Git=v1.6.0-307-g2a57a9aa)
27209:M 31 Oct 2019 13:01:12.604 # <ft> Upgrade redis-server to use Redis Search's C API
27209:M 31 Oct 2019 13:01:12.604 # <ft> Could not initialize low level api
27209:M 31 Oct 2019 13:01:12.604 * <ft> concurrency: ON, gc: ON, prefix min length: 2, prefix max expansions: 200, query timeout (ms): 500, timeout policy: return, cursor read size: 1000, cursor max idle (ms): 300000, max doctable size: 1000000, search pool size: 20, index pool size: 8, 
27209:M 31 Oct 2019 13:01:12.605 * <ft> Initialized thread pool!
27209:M 31 Oct 2019 13:01:12.605 * Module 'ft' loaded from /etc/redis/modules/redisearch.so

**Comment by mnunberg** [comment]
I believe we fixed this last week; please try a fresh checkout from master and see if this fixes your issue!

The version you're using is 2 weeks old.
