### ISSUE TITLE
optional operator with field does not restrict the result to that field only

### ISSUE THREAD

**Issue by mohsintahir** [RediSearch/RediSearch#981]
I have an index named `shows` with 2 fields `title` and `description` and I have indexed 2 documents as follows:

document 1: title => 'the foo', description => 'the boo'
document 2: title => 'foo', description => 'the boo'

when I try to search for document with query 
`FT.SEARCH shows (@title:the*) ~(@title:the=>{$weight:10;$slop:0;$inorder:true;})  LIMIT 0 50`

It returns document 1 and document 2, whereas it should return document 1 only as `the` is only in the `title`  of document 1.

Whereas If I remove optional query part like 
`FT.SEARCH shows (@title:the*)  LIMIT 0 50`
it returns document 1 only which is correct behavior so my understanding is `~` optional checks other fields too. Can you kindly help me in making the `title` optional only and if it is not present in `title` then don't search in other fields.

Your help would highly be appreciated.

**Comment by MeirShpilraien** [comment]
Which redisearch version are you using? How did you created the index?

**Comment by mohsintahir** [comment]
@MeirShpilraien I am using Redisearch version 1.6.3 and I had created index using following command:

"FT.CREATE shows STOPWORDS 0 SCHEMA title text weight 50 description text weight 20"

**Comment by mohsintahir** [comment]
Hi @MeirShpilraien, can you kindly guide me ? it has been 6 days since I receive a reply from you people ?

Thanks!

**Comment by MeirShpilraien** [comment]
Sorry @mohsintahir I just was not able to check it yet, it does look like a bug that we will need to fix. Is it also happened on 1.4.17?

**Comment by mohsintahir** [comment]
I haven't checked on 1.4.17 but previously I was using 1.4.13 and it was not happening in that version. I switched to redisearch 1.6.3 in order to have utilize this fix https://github.com/RediSearch/RediSearch/issues/884

**Comment by MeirShpilraien** [comment]
@mohsintahir this fix is included in 1.4.16 and above ..

**Comment by mohsintahir** [comment]
Yes you are right but I am unable to recall the proper reason of using 1.6.3. I had to use 1.6.3 due to some specific reason which I don't remember at the moment. Any chances to fix https://github.com/RediSearch/RediSearch/issues/981#issue-521644293 and have in 1.6.x ?

**Comment by MeirShpilraien** [comment]
@mohsintahir sure we will fix it, but knowing whether or not its reproducible on 1.4.16/17 might help to identify the problem quicker. I will check it myself, just thought you might already checked and I do not need to.
Will update as soon as I will have the fix.

**Comment by mohsintahir** [comment]
@MeirShpilraien I have checked by myself and it is not reproducible on versions 1.4.16/17.

**Comment by mohsintahir** [comment]
@MeirShpilraien any update regarding this bug ? Thanks!

**Comment by MeirShpilraien** [comment]
@mohsintahir not yet, will update us soon as we fix it.

**Comment by mnunberg** [comment]
I'm wondering if "the" is actually a stopword, and therefore ignored..

**Comment by mnunberg** [comment]
```
127.0.0.1:6379> FT.CREATE shows STOPWORDS 0 SCHEMA title text weight 50 description text weight 20
OK
127.0.0.1:6379> ft.add shows doc1 1.0 fields title "the foo" description "the boo"
OK
127.0.0.1:6379> ft.add shows doc2 1.0 fields title "foo" description "the boo"
OK
127.0.0.1:6379> FT.SEARCH shows "(@title:the*) ~(@title:the=>{$weight:10;$slop:0;$inorder:true;})" LIMIT 0 50
1) (integer) 1
2) "doc1"
3) 1) "title"
   2) "the foo"
   3) "description"
   4) "the boo"
```

**Comment by mnunberg** [comment]
This should have been fixed in some prior commit. You should upgrade to a newer version of 1.6
