### ISSUE TITLE
Tag parser returns error when searching for a tag with a value of "a"

### ISSUE THREAD

**Issue by ethanhann** [RediSearch/RediSearch#984]
This error is occuring on the latest RediSearch docker image (RediSearch 1.4.17 / Redis 5.0.6).

Steps to reproduce...

1. Create an index with a tag field `foo`:
```bash
FT.CREATE MyIndex SCHEMA foo TAG
```

2. Search tag `foo` with value "a" (fails with a syntax error):

```bash
FT.SEARCH MyIndex "@foo:{a}"

(error) Syntax error at offset 6 near "a"
```

3. Search tag `foo` with value "b" (works as expected):

```bash
FT.SEARCH MyIndex "@foo:{b}"

1) (integer) 0
```

**Comment by mnunberg** [comment]
This happens on 1.6 as well. Interesting.

**Comment by ashtul** [comment]
in lexer.c line 609: `RSQuery_Parse(pParser, STOPWORD, tok, q);` is reached.
