### ISSUE TITLE
crash - maybe related to numeric indexing

### ISSUE THREAD

**Issue by mmasouras** [RediSearch/RediSearch#987]
=== REDIS BUG REPORT START: Cut & paste starting from here ===
10443:S 18 Nov 2019 03:17:51.134 # Redis 5.0.6 crashed by signal: 11
10443:S 18 Nov 2019 03:17:51.134 # Crashed running the instruction at: 0x7f8336699705
10443:S 18 Nov 2019 03:17:51.134 # Accessing address: 0x28
10443:S 18 Nov 2019 03:17:51.134 # Failed assertion: <no assertion failed> (<no file>:0)

------ STACK TRACE ------
EIP:
/home/redis/redisearch.so(FGC_parentHandleFromChild+0x5d5)[0x7f8336699705]

Backtrace:
/usr/local/bin/redis-server *:6379(logStackTrace+0x5a)[0x55fa0232c73a]
/usr/local/bin/redis-server *:6379(sigsegvHandler+0xb1)[0x55fa0232cef1]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890)[0x7f8339011890]
/home/redis/redisearch.so(FGC_parentHandleFromChild+0x5d5)[0x7f8336699705]
/home/redis/redisearch.so(+0x4ef73)[0x7f8336699f73]
/home/redis/redisearch.so(+0x5116d)[0x7f833669c16d]
/home/redis/redisearch.so(+0xb4f30)[0x7f83366fff30]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76db)[0x7f83390066db]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x3f)[0x7f8338d2f88f]

------ INFO OUTPUT ------
# Server
redis_version:5.0.6
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:b4e632f35d8fd57f
redis_mode:standalone
os:Linux 5.0.0-1020-gcp x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:7.4.0
process_id:10443
run_id:5010ee97e75662a4afc03781abc8f849773a1a5c
tcp_port:6379
uptime_in_seconds:444927
uptime_in_days:5
hz:10
configured_hz:10
lru_clock:13765983
executable:/usr/local/bin/redis-server
config_file:/home/redis/redis.conf

# Clients
connected_clients:13
client_recent_max_input_buffer:2
client_recent_max_output_buffer:0
blocked_clients:0

# Memory
used_memory:6210152008
used_memory_human:5.78G
used_memory_rss:6384775168
used_memory_rss_human:5.95G
used_memory_peak:6255035424
used_memory_peak_human:5.83G
used_memory_peak_perc:99.28%
used_memory_overhead:277037706
used_memory_startup:791904
used_memory_dataset:5933114302
used_memory_dataset_perc:95.55%
allocator_allocated:6211927584
allocator_active:6257524736
allocator_resident:6413230080
total_system_memory:13646721024
total_system_memory_human:12.71G
used_memory_lua:43008
used_memory_lua_human:42.00K
used_memory_scripts:368
used_memory_scripts_human:368B
number_of_cached_scripts:2
maxmemory:0
maxmemory_human:0B
maxmemory_policy:noeviction
allocator_frag_ratio:1.01
allocator_frag_bytes:45597152
allocator_rss_ratio:1.02
allocator_rss_bytes:155705344
rss_overhead_ratio:1.00
rss_overhead_bytes:-28454912
mem_fragmentation_ratio:1.03
mem_fragmentation_bytes:174756304
mem_not_counted_for_evict:0
mem_replication_backlog:1048576
mem_clients_slaves:0
mem_clients_normal:219986
mem_aof_buffer:0
mem_allocator:jemalloc-5.1.0
active_defrag_running:0
lazyfree_pending_objects:0

# Persistence
loading:0
rdb_changes_since_last_save:927
rdb_bgsave_in_progress:0
rdb_last_save_time:1574047044
rdb_last_bgsave_status:ok
rdb_last_bgsave_time_sec:48
rdb_current_bgsave_time_sec:-1
rdb_last_cow_size:52457472
aof_enabled:0
aof_rewrite_in_progress:0
aof_rewrite_scheduled:0
aof_last_rewrite_time_sec:-1
aof_current_rewrite_time_sec:-1
aof_last_bgrewrite_status:ok
aof_last_write_status:ok
aof_last_cow_size:0

# Stats
total_connections_received:7249
total_commands_processed:35584397
instantaneous_ops_per_sec:12
total_net_input_bytes:5120574665
total_net_output_bytes:12142675464
instantaneous_input_kbps:1.51
instantaneous_output_kbps:5.76
rejected_connections:0
sync_full:0
sync_partial_ok:0
sync_partial_err:0
expired_keys:0
expired_stale_perc:0.00
expired_time_cap_reached_count:0
evicted_keys:0
keyspace_hits:54226955
keyspace_misses:81862
pubsub_channels:0
pubsub_patterns:0
latest_fork_usec:206013
migrate_cached_sockets:0
slave_expires_tracked_keys:0
active_defrag_hits:0
active_defrag_misses:0
active_defrag_key_hits:0
active_defrag_key_misses:0

# Replication
role:slave
master_host:104.197.164.251
master_port:6379
master_link_status:up
master_last_io_seconds_ago:1
master_sync_in_progress:0
slave_repl_offset:954137260
slave_priority:100
slave_read_only:1
connected_slaves:0
master_replid:05169a1b731fb49b3dd238eceb617e49b56ab120
master_replid2:0000000000000000000000000000000000000000
master_repl_offset:954137260
second_repl_offset:-1
repl_backlog_active:1
repl_backlog_size:1048576
repl_backlog_first_byte_offset:953088685
repl_backlog_histlen:1048576

# CPU
used_cpu_sys:1329.051673
used_cpu_user:3529.871367
used_cpu_sys_children:623.878536
used_cpu_user_children:4419.867715

# Commandstats
cmdstat_ping:calls=43772,usec=27231,usec_per_call=0.62
cmdstat_zremrangebyrank:calls=348964,usec=12637853,usec_per_call=36.22
cmdstat_get:calls=45695,usec=478979,usec_per_call=10.48
cmdstat_sadd:calls=1,usec=12,usec_per_call=12.00
cmdstat_smembers:calls=25930,usec=3137548,usec_per_call=121.00
cmdstat_FT.SAFEADDHASH:calls=354153,usec=334020027,usec_per_call=943.15
cmdstat_hget:calls=554345,usec=10185489,usec_per_call=18.37
cmdstat_select:calls=1,usec=2,usec_per_call=2.00
cmdstat_zadd:calls=818306,usec=34073361,usec_per_call=41.64
cmdstat_hgetall:calls=6771239,usec=129428114,usec_per_call=19.11
cmdstat_hset:calls=802759,usec=18909836,usec_per_call=23.56
cmdstat_zrem:calls=357160,usec=13851084,usec_per_call=38.78
cmdstat_FT.DEL:calls=34832,usec=4065297,usec_per_call=116.71
cmdstat_set:calls=679232,usec=18909623,usec_per_call=27.84
cmdstat_geoadd:calls=323105,usec=11855079,usec_per_call=36.69
cmdstat_auth:calls=7179,usec=20709,usec_per_call=2.88
cmdstat_hdel:calls=115341,usec=2220459,usec_per_call=19.25
cmdstat_incr:calls=11804,usec=95988,usec_per_call=8.13
cmdstat_hmset:calls=380076,usec=19022363,usec_per_call=50.05
cmdstat_expire:calls=11383,usec=77980,usec_per_call=6.85
cmdstat_exec:calls=388985,usec=340090743,usec_per_call=874.30
cmdstat_info:calls=44493,usec=7112401,usec_per_call=159.85
cmdstat_srem:calls=1,usec=28,usec_per_call=28.00
cmdstat_FT.SEARCH:calls=22962359,usec=1571662716,usec_per_call=68.45
cmdstat_del:calls=114297,usec=3644615,usec_per_call=31.89
cmdstat_multi:calls=388985,usec=168262,usec_per_call=0.43

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=3766098,expires=2384337,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=143 addr=104.197.164.251:6379 fd=8 name= age=444778 idle=1 flags=M db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=zadd
id=6005408 addr=127.0.0.1:33002 fd=12 name= age=606 idle=606 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=smembers
id=6005409 addr=127.0.0.1:33004 fd=14 name= age=606 idle=606 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=6003253 addr=127.0.0.1:60868 fd=13 name= age=1070 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hget
id=6003254 addr=127.0.0.1:60872 fd=16 name= age=1070 idle=14 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=6003255 addr=127.0.0.1:60874 fd=17 name= age=1070 idle=2 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hget
id=6003272 addr=127.0.0.1:60896 fd=20 name= age=1066 idle=1066 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=smembers
id=6003273 addr=127.0.0.1:60898 fd=21 name= age=1066 idle=1066 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=6003268 addr=127.0.0.1:60888 fd=18 name= age=1067 idle=1067 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=smembers
id=6007466 addr=127.0.0.1:33292 fd=10 name= age=156 idle=7 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=6007467 addr=127.0.0.1:33294 fd=11 name= age=156 idle=156 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=smembers
id=6003269 addr=127.0.0.1:60890 fd=19 name= age=1067 idle=1067 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=hgetall
id=130 addr=34.70.28.133:42044 fd=9 name= age=444811 idle=1 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=info

------ REGISTERS ------
10443:S 18 Nov 2019 03:17:51.194 #
RAX:0000000000000000 RBX:00007f82304e32c0
RCX:000055fa024210a0 RDX:00007f82317fa470
RDI:00007f828af8cd00 RSI:00007f82317fa448
RBP:00007f82317fa430 RSP:00007f82317fa380
R8 :000000000000000a R9 :0000000000000018
R10:00007f82317fafb8 R11:0000000000000002
R12:00007f828aeb35c0 R13:00007f82d8d95a70
R14:0000000000000000 R15:00007f828af8cd00
RIP:00007f8336699705 EFL:0000000000010246
CSGSFS:002b000000000033
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38f) -> 000000000000001b
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38e) -> 00007f822262cc20
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38d) -> 0000000000000003
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38c) -> 00007f8233007008
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38b) -> ffffffffffffffe8
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa38a) -> 000000000000000f
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa389) -> 00007f82317fa400
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa388) -> 00007f82b8899dc0
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa387) -> 00007f822071a78c
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa386) -> 00007f8200000001
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa385) -> 00007f82317fa400
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa384) -> 00007f82317fa3e8
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa383) -> 00007f82317fa3f8
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa382) -> 00007f82317fa470
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa381) -> 00007f82317fa3f0
10443:S 18 Nov 2019 03:17:51.194 # (00007f82317fa380) -> 00007f8233405850

------ FAST MEMORY TEST ------
10443:S 18 Nov 2019 03:17:51.194 # Bio thread for job type #0 terminated
10443:S 18 Nov 2019 03:17:51.195 # Bio thread for job type #1 terminated
10443:S 18 Nov 2019 03:17:51.195 # Bio thread for job type #2 terminated
*** Preparing to test memory region 55fa02662000 (2252800 bytes)
*** Preparing to test memory region 55fa02adf000 (135168 bytes)
*** Preparing to test memory region 55fa02b00000 (8331264 bytes)
*** Preparing to test memory region 7f8160000000 (135168 bytes)
*** Preparing to test memory region 7f8166c00000 (1109393408 bytes)
*** Preparing to test memory region 7f81a8f80000 (1795821568 bytes)
*** Preparing to test memory region 7f8218000000 (135168 bytes)
*** Preparing to test memory region 7f821c000000 (135168 bytes)
*** Preparing to test memory region 7f8220000000 (37748736 bytes)
*** Preparing to test memory region 7f82224fe000 (11534336 bytes)
*** Preparing to test memory region 7f8222fff000 (8388608 bytes)
*** Preparing to test memory region 7f8223800000 (8388608 bytes)
*** Preparing to test memory region 7f8224000000 (135168 bytes)
*** Preparing to test memory region 7f8228000000 (135168 bytes)
*** Preparing to test memory region 7f822c000000 (135168 bytes)
*** Preparing to test memory region 7f823017b000 (6815744 bytes)
*** Preparing to test memory region 7f82307fc000 (8388608 bytes)
*** Preparing to test memory region 7f8230ffd000 (8388608 bytes)
*** Preparing to test memory region 7f82317fe000 (8388608 bytes)
*** Preparing to test memory region 7f8231fff000 (8388608 bytes)
*** Preparing to test memory region 7f8232800000 (8388608 bytes)
*** Preparing to test memory region 7f8233000000 (27262976 bytes)
*** Preparing to test memory region 7f8234bfd000 (8388608 bytes)
*** Preparing to test memory region 7f82353fe000 (8388608 bytes)
*** Preparing to test memory region 7f8235bff000 (8388608 bytes)
*** Preparing to test memory region 7f8236580000 (23592960 bytes)
*** Preparing to test memory region 7f8237dfc000 (671088640 bytes)
*** Preparing to test memory region 7f825fdfd000 (8388608 bytes)
*** Preparing to test memory region 7f8260dfe000 (536870912 bytes)
*** Preparing to test memory region 7f8280dff000 (8388608 bytes)
*** Preparing to test memory region 7f8281800000 (20971520 bytes)
*** Preparing to test memory region 7f8282dfe000 (872415232 bytes)
*** Preparing to test memory region 7f82b6dff000 (8388608 bytes)
*** Preparing to test memory region 7f82b7e00000 (12582912 bytes)
*** Preparing to test memory region 7f82b8bfe000 (335544320 bytes)
*** Preparing to test memory region 7f82ccbff000 (8388608 bytes)
*** Preparing to test memory region 7f82cdc00000 (278921216 bytes)
*** Preparing to test memory region 7f82de7fe000 (436207616 bytes)
*** Preparing to test memory region 7f82f87ff000 (8388608 bytes)
*** Preparing to test memory region 7f82f9080000 (441974784 bytes)
*** Preparing to test memory region 7f8313635000 (402653184 bytes)
*** Preparing to test memory region 7f832b636000 (8388608 bytes)
*** Preparing to test memory region 7f832be37000 (8388608 bytes)
*** Preparing to test memory region 7f832c638000 (8388608 bytes)
*** Preparing to test memory region 7f832ce39000 (8388608 bytes)
*** Preparing to test memory region 7f832d63a000 (8388608 bytes)
*** Preparing to test memory region 7f832de3b000 (8388608 bytes)
*** Preparing to test memory region 7f832e63c000 (8388608 bytes)
*** Preparing to test memory region 7f832ee3d000 (8388608 bytes)
*** Preparing to test memory region 7f832f63e000 (8388608 bytes)
*** Preparing to test memory region 7f832fe3f000 (8388608 bytes)
*** Preparing to test memory region 7f8330640000 (8388608 bytes)
*** Preparing to test memory region 7f8330e41000 (8388608 bytes)
*** Preparing to test memory region 7f8331642000 (8388608 bytes)
*** Preparing to test memory region 7f8331e43000 (8388608 bytes)
*** Preparing to test memory region 7f8332644000 (8388608 bytes)
*** Preparing to test memory region 7f8332e45000 (8388608 bytes)
*** Preparing to test memory region 7f8333646000 (8388608 bytes)
*** Preparing to test memory region 7f8333e47000 (8388608 bytes)
*** Preparing to test memory region 7f8334648000 (8388608 bytes)
*** Preparing to test memory region 7f8334e49000 (8388608 bytes)
*** Preparing to test memory region 7f833564a000 (8388608 bytes)
*** Preparing to test memory region 7f8335e4b000 (8388608 bytes)
*** Preparing to test memory region 7f8336a87000 (12288 bytes)
*** Preparing to test memory region 7f8336a8b000 (8388608 bytes)
*** Preparing to test memory region 7f833728c000 (8388608 bytes)
*** Preparing to test memory region 7f8337a8d000 (8388608 bytes)
*** Preparing to test memory region 7f8338400000 (8388608 bytes)
*** Preparing to test memory region 7f8338ffb000 (16384 bytes)
*** Preparing to test memory region 7f833921a000 (16384 bytes)
*** Preparing to test memory region 7f8339be0000 (32768 bytes)
*** Preparing to test memory region 7f8339bf1000 (4096 bytes)

**Comment by mmasouras** [comment]
10535:S 18 Nov 2019 16:35:55.969 * <ft> RediSearch version 99.99.99 (Git=v1.6.0-346-g3995dfcc)

**Comment by mnunberg** [comment]
This seems to have already been fixed in 422f627f79da928f14bebb9298b8f2f993c90821. I do not know how I missed this!

**Comment by mmasouras** [comment]
There have been a lot of fixes related to crashes recently. What is the best release to grab and test to achieve this?
https://github.com/RediSearch/RediSearch/releases

 Are all these fixes in 1.4.18? 

In another thread I am asked to: "Can you pls check with v1.6.4 to verify that the crash has been fixed?" 

I can't find 1.6.4 in the releases page either.

**Comment by gkorland** [comment]
>Are all these fixes in 1.4.18?
Yes.

>I can't find 1.6.4 in the releases page either.
https://github.com/RediSearch/RediSearch/releases/tag/v1.6.4
