### ISSUE TITLE
Forkgc do not updates the unique sum on numeric nodes

### ISSUE THREAD

**Issue by MeirShpilraien** [RediSearch/RediSearch#997]
Cause bad split values and corruption in the numeric tree.

**Comment by mnunberg** [comment]
This seems to be an overall issue in numeric gc; not only in fork gc. Should we fix in default 'legacy' mode?

**Comment by mnunberg** [comment]
also i'm not sure how this causes corruption. the split value only helps to make a balanced tree; once the tree is created, the unique_sum value is no longer touched.
