### ISSUE TITLE
Sortable allocating too much memory

### ISSUE THREAD

**Issue by MeirShpilraien** [RediSearch/RediSearch#998]
The sortable array is allocating more memory then it needs:
sortable.c: 16 (1.4 branch)
current code : `RSSortingVector *ret = rm_calloc(1, sizeof(RSSortingVector) + len * (sizeof(RSValue)));`
Should be : `RSSortingVector *ret = rm_calloc(1, sizeof(RSSortingVector) + len * (sizeof(RSValue*)));`

**Comment by mnunberg** [comment]
needs to be picked to 1.6 as well..
